export type TabType =
  | 'NONE'
  | 'ADMIN_ORGANIZATION_REQUEST'
  | 'ADMIN_COMPANY_REQUEST'
  | 'EXP_EXPENSE_REQUEST'
  | 'EXP_PAYMENT_REQUEST'
  | 'ACC_SETTLEMENT_REQUEST'
  | 'ACC_ARRANGEMENT_REQUEST'
  | 'ACC_CONFIRMATION_REQUEST';

const tabType: {
  [key: string]: TabType;
} = {
  NONE: 'NONE',
  ADMIN_ORGANIZATION_REQUEST: 'ADMIN_ORGANIZATION_REQUEST',
  ADMIN_COMPANY_REQUEST: 'ADMIN_COMPANY_REQUEST',
  EXP_EXPENSE_REQUEST: 'EXP_EXPENSE_REQUEST',
  EXP_PAYMENT_REQUEST: 'EXP_PAYMENT_REQUEST',
  ACC_SETTLEMENT_REQUEST: 'ACC_SETTLEMENT_REQUEST',
  ACC_ARRANGEMENT_REQUEST: 'ACC_ARRANGEMENT_REQUEST',
  ACC_CONFIRMATION_REQUEST: 'ACC_CONFIRMATION_REQUEST',
};

export default tabType;
