import { ConfigList, ConfigListMap } from '../../utils/ConfigUtil';

import displayType from '../displayType';
import fieldType from '../fieldType';

const { DISPLAY_LIST, DISPLAY_DETAIL } = displayType;

const { FIELD_HIDDEN, FIELD_TEXTAREA } = fieldType;

const base: ConfigList = [
  {
    key: 'companyId',
    type: FIELD_HIDDEN,
  },
  {
    key: 'moduleType',
    type: FIELD_HIDDEN,
  },
  {
    section: 'ExpReportHeader',
    msgkey: 'Admin_Lbl_ExpReportHeader',
    isExpandable: true,
    configList: [
      {
        key: 'reportHeaderAccountingPeriod',
        msgkey: 'Exp_Clbl_AccountingPeriod',
        type: FIELD_TEXTAREA,
        display: DISPLAY_LIST,
      },
      {
        key: 'reportHeaderAccountingPeriod_L0',
        msgkey: 'Exp_Clbl_AccountingPeriod',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyExpense',
      },
      {
        key: 'reportHeaderAccountingPeriod_L1',
        msgkey: 'Exp_Clbl_AccountingPeriod',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyExpense',
      },
      {
        key: 'reportHeaderAccountingPeriod_L2',
        msgkey: 'Exp_Clbl_AccountingPeriod',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyExpense',
      },
      {
        key: 'reportHeaderRecordDate',
        msgkey: 'Exp_Clbl_RecordDate',
        type: FIELD_TEXTAREA,
        display: DISPLAY_LIST,
      },
      {
        key: 'reportHeaderRecordDate_L0',
        msgkey: 'Exp_Clbl_RecordDate',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyExpense',
      },
      {
        key: 'reportHeaderRecordDate_L1',
        msgkey: 'Exp_Clbl_RecordDate',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyExpense',
      },
      {
        key: 'reportHeaderRecordDate_L2',
        msgkey: 'Exp_Clbl_RecordDate',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyExpense',
      },
      {
        key: 'reportHeaderScheduledDate',
        msgkey: 'Exp_Clbl_ScheduledDate',
        type: FIELD_TEXTAREA,
        display: DISPLAY_LIST,
      },
      {
        key: 'reportHeaderScheduledDate_L0',
        msgkey: 'Exp_Clbl_ScheduledDate',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyRequest',
      },
      {
        key: 'reportHeaderScheduledDate_L1',
        msgkey: 'Exp_Clbl_ScheduledDate',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyRequest',
      },
      {
        key: 'reportHeaderScheduledDate_L2',
        msgkey: 'Exp_Clbl_ScheduledDate',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyRequest',
      },
      {
        key: 'reportHeaderReportType',
        msgkey: 'Exp_Clbl_ReportType',
        type: FIELD_TEXTAREA,
        display: DISPLAY_LIST,
      },
      {
        key: 'reportHeaderReportType_L0',
        msgkey: 'Exp_Clbl_ReportType',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'reportHeaderReportType_L1',
        msgkey: 'Exp_Clbl_ReportType',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'reportHeaderReportType_L2',
        msgkey: 'Exp_Clbl_ReportType',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'reportHeaderJob',
        msgkey: 'Exp_Lbl_Job',
        type: FIELD_TEXTAREA,
        display: DISPLAY_LIST,
      },
      {
        key: 'reportHeaderJob_L0',
        msgkey: 'Exp_Lbl_Job',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'reportHeaderJob_L1',
        msgkey: 'Exp_Lbl_Job',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'reportHeaderJob_L2',
        msgkey: 'Exp_Lbl_Job',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'reportHeaderCostCenter',
        msgkey: 'Exp_Clbl_CostCenterHeader',
        type: FIELD_TEXTAREA,
        display: DISPLAY_LIST,
      },
      {
        key: 'reportHeaderCostCenter_L0',
        msgkey: 'Exp_Clbl_CostCenterHeader',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'reportHeaderCostCenter_L1',
        msgkey: 'Exp_Clbl_CostCenterHeader',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'reportHeaderCostCenter_L2',
        msgkey: 'Exp_Clbl_CostCenterHeader',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'reportHeaderVendor',
        msgkey: 'Exp_Clbl_Vendor',
        type: FIELD_TEXTAREA,
        display: DISPLAY_LIST,
      },
      {
        key: 'reportHeaderVendor_L0',
        msgkey: 'Exp_Clbl_Vendor',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'reportHeaderVendor_L1',
        msgkey: 'Exp_Clbl_Vendor',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'reportHeaderVendor_L2',
        msgkey: 'Exp_Clbl_Vendor',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'reportHeaderRemarks',
        msgkey: 'Exp_Clbl_ReportRemarks',
        type: FIELD_TEXTAREA,
        display: DISPLAY_LIST,
      },
      {
        key: 'reportHeaderRemarks_L0',
        msgkey: 'Exp_Clbl_ReportRemarks',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyExpense',
      },
      {
        key: 'reportHeaderRemarks_L1',
        msgkey: 'Exp_Clbl_ReportRemarks',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyExpense',
      },
      {
        key: 'reportHeaderRemarks_L2',
        msgkey: 'Exp_Clbl_ReportRemarks',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyExpense',
      },
      {
        key: 'reportHeaderPurpose',
        msgkey: 'Exp_Clbl_Purpose',
        type: FIELD_TEXTAREA,
        display: DISPLAY_LIST,
      },
      {
        key: 'reportHeaderPurpose_L0',
        msgkey: 'Exp_Clbl_Purpose',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyRequest',
      },
      {
        key: 'reportHeaderPurpose_L1',
        msgkey: 'Exp_Clbl_Purpose',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyRequest',
      },
      {
        key: 'reportHeaderPurpose_L2',
        msgkey: 'Exp_Clbl_Purpose',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyRequest',
      },
      {
        key: 'reportHeaderCARequestAmount_L0',
        msgkey: 'Exp_Clbl_CashAdvanceRequestAmount',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyRequest',
      },
      {
        key: 'reportHeaderCARequestAmount_L1',
        msgkey: 'Exp_Clbl_CashAdvanceRequestAmount',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyRequest',
      },
      {
        key: 'reportHeaderCARequestAmount_L2',
        msgkey: 'Exp_Clbl_CashAdvanceRequestAmount',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyRequest',
      },
      {
        key: 'reportHeaderCARequestDate_L0',
        msgkey: 'Exp_Clbl_CashAdvanceRequestDate',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyRequest',
      },
      {
        key: 'reportHeaderCARequestDate_L1',
        msgkey: 'Exp_Clbl_CashAdvanceRequestDate',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyRequest',
      },
      {
        key: 'reportHeaderCARequestDate_L2',
        msgkey: 'Exp_Clbl_CashAdvanceRequestDate',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyRequest',
      },
      {
        key: 'reportHeaderCAPurpose_L0',
        msgkey: 'Exp_Clbl_CashAdvanceRequestPurpose',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyRequest',
      },
      {
        key: 'reportHeaderCAPurpose_L1',
        msgkey: 'Exp_Clbl_CashAdvanceRequestPurpose',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyRequest',
      },
      {
        key: 'reportHeaderCAPurpose_L2',
        msgkey: 'Exp_Clbl_CashAdvanceRequestPurpose',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyRequest',
      },
      {
        key: 'reportHeaderCAAmount_L0',
        msgkey: 'Exp_Clbl_CashAdvanceAmount',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'reportHeaderCAAmount_L1',
        msgkey: 'Exp_Clbl_CashAdvanceAmount',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'reportHeaderCAAmount_L2',
        msgkey: 'Exp_Clbl_CashAdvanceAmount',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'reportHeaderCADate_L0',
        msgkey: 'Exp_Clbl_CashAdvanceDate',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'reportHeaderCADate_L1',
        msgkey: 'Exp_Clbl_CashAdvanceDate',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'reportHeaderCADate_L2',
        msgkey: 'Exp_Clbl_CashAdvanceDate',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'reportHeaderCASettlementAmount_L0',
        msgkey: 'Exp_Clbl_SettlementAmount',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'reportHeaderCASettlementAmount_L1',
        msgkey: 'Exp_Clbl_SettlementAmount',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'reportHeaderCASettlementAmount_L2',
        msgkey: 'Exp_Clbl_SettlementAmount',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
    ],
  },
  {
    section: 'ExpRecord',
    msgkey: 'Admin_Lbl_ExpRecord',
    isExpandable: true,
    configList: [
      {
        key: 'recordDate',
        msgkey: 'Exp_Clbl_Date',
        type: FIELD_TEXTAREA,
        display: DISPLAY_LIST,
      },
      {
        key: 'recordDate_L0',
        msgkey: 'Exp_Clbl_Date',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyExpense',
      },
      {
        key: 'recordDate_L1',
        msgkey: 'Exp_Clbl_Date',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyExpense',
      },
      {
        key: 'recordDate_L2',
        msgkey: 'Exp_Clbl_Date',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyExpense',
      },
      {
        key: 'requestRecordDate',
        msgkey: 'Exp_Clbl_Date',
        type: FIELD_TEXTAREA,
        display: DISPLAY_LIST,
      },
      {
        key: 'requestRecordDate_L0',
        msgkey: 'Exp_Clbl_Date',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyRequest',
      },
      {
        key: 'requestRecordDate_L1',
        msgkey: 'Exp_Clbl_Date',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyRequest',
      },
      {
        key: 'requestRecordDate_L2',
        msgkey: 'Exp_Clbl_Date',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyRequest',
      },
      {
        key: 'recordExpenseType',
        msgkey: 'Exp_Clbl_ExpenseType',
        type: FIELD_TEXTAREA,
        display: DISPLAY_LIST,
      },
      {
        key: 'recordExpenseType_L0',
        msgkey: 'Exp_Clbl_ExpenseType',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordExpenseType_L1',
        msgkey: 'Exp_Clbl_ExpenseType',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordExpenseType_L2',
        msgkey: 'Exp_Clbl_ExpenseType',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordPaymentMethod_L0',
        msgkey: 'Exp_Lbl_PaymentMethod',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordPaymentMethod_L1',
        msgkey: 'Exp_Lbl_PaymentMethod',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordPaymentMethod_L2',
        msgkey: 'Exp_Lbl_PaymentMethod',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordLocalAmount_L0',
        msgkey: 'Exp_Clbl_LocalAmount',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordLocalAmount_L1',
        msgkey: 'Exp_Clbl_LocalAmount',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordLocalAmount_L2',
        msgkey: 'Exp_Clbl_LocalAmount',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordCurrency_L0',
        msgkey: 'Exp_Clbl_Currency',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordCurrency_L1',
        msgkey: 'Exp_Clbl_Currency',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordCurrency_L2',
        msgkey: 'Exp_Clbl_Currency',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordExchangeRate_L0',
        msgkey: 'Exp_Clbl_ExchangeRate',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordExchangeRate_L1',
        msgkey: 'Exp_Clbl_ExchangeRate',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordExchangeRate_L2',
        msgkey: 'Exp_Clbl_ExchangeRate',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordIncludeTax_L0',
        msgkey: 'Exp_Clbl_IncludeTax',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordIncludeTax_L1',
        msgkey: 'Exp_Clbl_IncludeTax',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordIncludeTax_L2',
        msgkey: 'Exp_Clbl_IncludeTax',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordWithoutTax_L0',
        msgkey: 'Exp_Clbl_WithoutTax',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordWithoutTax_L1',
        msgkey: 'Exp_Clbl_WithoutTax',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordWithoutTax_L2',
        msgkey: 'Exp_Clbl_WithoutTax',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordGstAmount_L0',
        msgkey: 'Exp_Clbl_GstAmount',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordGstAmount_L1',
        msgkey: 'Exp_Clbl_GstAmount',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordGstAmount_L2',
        msgkey: 'Exp_Clbl_GstAmount',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordWithholdingTaxAmount',
        msgkey: 'Exp_Clbl_WithholdingTaxAmount',
        type: FIELD_TEXTAREA,
        display: DISPLAY_LIST,
      },
      {
        key: 'recordWithholdingTaxAmount_L0',
        msgkey: 'Exp_Clbl_WithholdingTaxAmount',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordWithholdingTaxAmount_L1',
        msgkey: 'Exp_Clbl_WithholdingTaxAmount',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordWithholdingTaxAmount_L2',
        msgkey: 'Exp_Clbl_WithholdingTaxAmount',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordInvoice',
        msgkey: 'Exp_Clbl_Invoice',
        type: FIELD_TEXTAREA,
        display: DISPLAY_LIST,
      },
      {
        key: 'recordInvoice_L0',
        msgkey: 'Exp_Clbl_Invoice',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordInvoice_L1',
        msgkey: 'Exp_Clbl_Invoice',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordInvoice_L2',
        msgkey: 'Exp_Clbl_Invoice',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordReceipt',
        msgkey: 'Exp_Lbl_Receipt',
        type: FIELD_TEXTAREA,
        display: DISPLAY_LIST,
      },
      {
        key: 'recordReceipt_L0',
        msgkey: 'Exp_Lbl_Receipt',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyExpense',
      },
      {
        key: 'recordReceipt_L1',
        msgkey: 'Exp_Lbl_Receipt',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyExpense',
      },
      {
        key: 'recordReceipt_L2',
        msgkey: 'Exp_Lbl_Receipt',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyExpense',
      },
      {
        key: 'recordQuotation',
        msgkey: 'Exp_Lbl_Quotation',
        type: FIELD_TEXTAREA,
        display: DISPLAY_LIST,
      },
      {
        key: 'recordQuotation_L0',
        msgkey: 'Exp_Lbl_Quotation',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyRequest',
      },
      {
        key: 'recordQuotation_L1',
        msgkey: 'Exp_Lbl_Quotation',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyRequest',
      },
      {
        key: 'recordQuotation_L2',
        msgkey: 'Exp_Lbl_Quotation',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
        help: 'Admin_Help_OnlyRequest',
      },
      {
        key: 'recordJob',
        msgkey: 'Exp_Lbl_Job',
        type: FIELD_TEXTAREA,
        display: DISPLAY_LIST,
      },
      {
        key: 'recordJob_L0',
        msgkey: 'Exp_Lbl_Job',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordJob_L1',
        msgkey: 'Exp_Lbl_Job',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordJob_L2',
        msgkey: 'Exp_Lbl_Job',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordCostCenter',
        msgkey: 'Exp_Clbl_CostCenter',
        type: FIELD_TEXTAREA,
        display: DISPLAY_LIST,
      },
      {
        key: 'recordCostCenter_L0',
        msgkey: 'Exp_Clbl_CostCenter',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordCostCenter_L1',
        msgkey: 'Exp_Clbl_CostCenter',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordCostCenter_L2',
        msgkey: 'Exp_Clbl_CostCenter',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordSummary',
        msgkey: 'Exp_Clbl_Summary',
        type: FIELD_TEXTAREA,
        display: DISPLAY_LIST,
      },
      {
        key: 'recordSummary_L0',
        msgkey: 'Exp_Clbl_Summary',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordSummary_L1',
        msgkey: 'Exp_Clbl_Summary',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
      {
        key: 'recordSummary_L2',
        msgkey: 'Exp_Clbl_Summary',
        type: FIELD_TEXTAREA,
        display: DISPLAY_DETAIL,
      },
    ],
  },
];

const configList: ConfigListMap = { base };

export default configList;
