import mapValues from 'lodash/mapValues';

export type IconSetType =
  | 'add'
  | 'adduser'
  | 'announcement-copy'
  | 'answer'
  | 'apex-copy'
  | 'approval-copy'
  | 'approved'
  | 'apps-copy'
  | 'alert'
  | 'arrowdown'
  | 'arrowup'
  | 'attach'
  | 'back-copy'
  | 'ban'
  | 'block'
  | 'bold'
  | 'bookmark'
  | 'breadcrumbs'
  | 'broadcast'
  | 'brush'
  | 'bucket'
  | 'builder'
  | 'call-copy'
  | 'capslock'
  | 'cases'
  | 'center_align_text'
  | 'change_owner-copy'
  | 'change_record_type-copy'
  | 'chart'
  | 'chat'
  | 'check-copy'
  | 'checkin'
  | 'chevrondown'
  | 'chevronleft'
  | 'chevronright'
  | 'chevronup'
  | 'clear'
  | 'clock'
  | 'close-copy'
  | 'comments'
  | 'company'
  | 'connected_apps-copy'
  | 'contract_alt'
  | 'contract-copy'
  | 'copy'
  | 'crossfilter'
  | 'custom_apps'
  | 'cut'
  | 'dash'
  | 'database'
  | 'datadotcom'
  | 'dayview'
  | 'delete-copy'
  | 'deprecate'
  | 'description-copy'
  | 'desktop'
  | 'dislike'
  | 'dock_panel'
  | 'down'
  | 'download-copy'
  | 'edit_form'
  | 'edit-copy'
  | 'email-copy'
  | 'emoji'
  | 'end_call'
  | 'erect_window'
  | 'error'
  | 'event-copy'
  | 'expand_alt'
  | 'expand'
  | 'fallback-copy'
  | 'favorite'
  | 'feed-copy'
  | 'file-copy'
  | 'filter-copy'
  | 'filterList'
  | 'flow-copy'
  | 'forward'
  | 'frozen'
  | 'full_width_view'
  | 'groups-copy'
  | 'help'
  | 'home-copy'
  | 'identity'
  | 'image'
  | 'inbox'
  | 'info_alt'
  | 'info-copy'
  | 'insert_tag_field'
  | 'insert_template'
  | 'italic'
  | 'jump_to_bottom'
  | 'jump_to_top'
  | 'justify_text'
  | 'kanban'
  | 'keyboard_dismiss'
  | 'knowledge_base'
  | 'layers'
  | 'layout'
  | 'left_align_text'
  | 'left'
  | 'level_up'
  | 'like'
  | 'link-copy'
  | 'location'
  | 'lock'
  | 'log_a_call-copy'
  | 'logout'
  | 'magicwand'
  | 'mark_all_as_read'
  | 'matrix'
  | 'merge-copy'
  | 'metrics-copy'
  | 'minimize_window'
  | 'moneybag'
  | 'monthlyview'
  | 'move'
  | 'muted'
  | 'new_window'
  | 'new-copy'
  | 'news-copy'
  | 'note-copy'
  | 'notebook'
  | 'notification'
  | 'office365'
  | 'offline_cached'
  | 'offline'
  | 'open_folder'
  | 'open'
  | 'opened_folder'
  | 'overflow'
  | 'package_org_beta'
  | 'package_org'
  | 'package'
  | 'page-1'
  | 'page'
  | 'palette'
  | 'paste'
  | 'people-copy'
  | 'phone_landscape'
  | 'phone_portrait'
  | 'photo-copy'
  | 'picklist'
  | 'plus'
  | 'power'
  | 'preview-copy'
  | 'priority-copy'
  | 'process-copy'
  | 'push'
  | 'puzzle'
  | 'question'
  | 'questions_and_answers'
  | 'quotation_marks'
  | 'ratio'
  | 'record_create'
  | 'record-copy'
  | 'redo'
  | 'refresh-copy'
  | 'relate'
  | 'remove_formatting'
  | 'remove_link'
  | 'replace'
  | 'reply_all'
  | 'reply'
  | 'reset_password-copy'
  | 'resource_absence'
  | 'resource_capacity'
  | 'resource_territory'
  | 'retweet'
  | 'richtextbulletedlist'
  | 'richtextindent'
  | 'richtextnumberedlist'
  | 'richtextoutdent'
  | 'right_align_text'
  | 'right'
  | 'rotate'
  | 'rows'
  | 'salesforce1'
  | 'search'
  | 'settings'
  | 'setup_assistant_guide'
  | 'setup'
  | 'share_mobile'
  | 'share_post-copy'
  | 'share-copy'
  | 'shield'
  | 'side_list'
  | 'signpost'
  | 'sms'
  | 'snippet'
  | 'socialshare'
  | 'sort-copy'
  | 'spinner'
  | 'standard_objects'
  | 'status_approved'
  | 'status_pending_reapply'
  | 'status_pending'
  | 'status_rejected_reapply'
  | 'status_rejected'
  | 'stop'
  | 'strikethrough'
  | 'success'
  | 'summary'
  | 'summarydetail'
  | 'switch'
  | 'sync'
  | 'system-error'
  | 'table'
  | 'tablet_landscape'
  | 'tablet_portrait'
  | 'tabset'
  | 'task-copy'
  | 'text_background_color'
  | 'text_color'
  | 'threedots_vertical'
  | 'threedots'
  | 'thunder'
  | 'tile_card_list'
  | 'topic-copy'
  | 'touch_action'
  | 'trail'
  | 'turn_off_notifications'
  | 'undelete'
  | 'undeprecate'
  | 'underline'
  | 'undo'
  | 'unlock'
  | 'unmuted'
  | 'up'
  | 'upload-copy'
  | 'user_role'
  | 'user-copy'
  | 'video'
  | 'volume_high'
  | 'volume_low'
  | 'volume_off'
  | 'warning'
  | 'warning-reverse'
  | 'weeklyview'
  | 'wifi'
  | 'work_order_type'
  | 'world'
  | 'yubi_key'
  | 'zoomin'
  | 'zoomout';

const _iconSet = {
  /* eslint-disable global-require */
  ratio: require('../../../images/icons/ratio.svg'),
  add: require('../../../images/icons/add.svg'),
  adduser: require('../../../images/icons/adduser.svg'),
  alert: require('../../../images/icons/alert.svg'),
  'announcement-copy': require('../../../images/icons/announcement-copy.svg'),
  answer: require('../../../images/icons/answer.svg'),
  'apex-copy': require('../../../images/icons/apex-copy.svg'),
  'approval-copy': require('../../../images/icons/approval-copy.svg'),
  approved: require('../../../images/icons/approved.svg'),
  'apps-copy': require('../../../images/icons/apps-copy.svg'),
  arrowdown: require('../../../images/icons/arrowdown.svg'),
  arrowup: require('../../../images/icons/arrowup.svg'),
  attach: require('../../../images/icons/attach.svg'),
  'back-copy': require('../../../images/icons/back-copy.svg'),
  ban: require('../../../images/icons/ban.svg'),
  block: require('../../../images/icons/icon_error.svg'),
  bold: require('../../../images/icons/bold.svg'),
  bookmark: require('../../../images/icons/bookmark.svg'),
  breadcrumbs: require('../../../images/icons/breadcrumbs.svg'),
  broadcast: require('../../../images/icons/broadcast.svg'),
  brush: require('../../../images/icons/brush.svg'),
  bucket: require('../../../images/icons/bucket.svg'),
  builder: require('../../../images/icons/builder.svg'),
  'call-copy': require('../../../images/icons/call-copy.svg'),
  capslock: require('../../../images/icons/capslock.svg'),
  cases: require('../../../images/icons/cases.svg'),
  center_align_text: require('../../../images/icons/center_align_text.svg'),
  'change_owner-copy': require('../../../images/icons/change_owner-copy.svg'),
  'change_record_type-copy': require('../../../images/icons/change_record_type-copy.svg'),
  chart: require('../../../images/icons/chart.svg'),
  chat: require('../../../images/icons/chat.svg'),
  'check-copy': require('../../../images/icons/check-copy.svg'),
  checkin: require('../../../images/icons/checkin.svg'),
  chevrondown: require('../../../images/icons/chevrondown.svg'),
  chevronleft: require('../../../images/icons/chevronleft.svg'),
  chevronright: require('../../../images/icons/chevronright.svg'),
  chevronup: require('../../../images/icons/chevronup.svg'),
  clear: require('../../../images/icons/clear.svg'),
  clock: require('../../../images/icons/clock.svg'),
  'close-copy': require('../../../images/icons/close-copy.svg'),
  comments: require('../../../images/icons/comments.svg'),
  company: require('../../../images/icons/company.svg'),
  'connected_apps-copy': require('../../../images/icons/connected_apps-copy.svg'),
  contract_alt: require('../../../images/icons/contract_alt.svg'),
  'contract-copy': require('../../../images/icons/contract-copy.svg'),
  copy: require('../../../images/icons/copy.svg'),
  crossfilter: require('../../../images/icons/crossfilter.svg'),
  custom_apps: require('../../../images/icons/custom_apps.svg'),
  cut: require('../../../images/icons/cut.svg'),
  dash: require('../../../images/icons/dash.svg'),
  database: require('../../../images/icons/database.svg'),
  datadotcom: require('../../../images/icons/datadotcom.svg'),
  dayview: require('../../../images/icons/dayview.svg'),
  'delete-copy': require('../../../images/icons/delete-copy.svg'),
  deprecate: require('../../../images/icons/deprecate.svg'),
  'description-copy': require('../../../images/icons/description-copy.svg'),
  desktop: require('../../../images/icons/desktop.svg'),
  dislike: require('../../../images/icons/dislike.svg'),
  dock_panel: require('../../../images/icons/dock_panel.svg'),
  down: require('../../../images/icons/down.svg'),
  'download-copy': require('../../../images/icons/download-copy.svg'),
  edit_form: require('../../../images/icons/edit_form.svg'),
  'edit-copy': require('../../../images/icons/edit-copy.svg'),
  'email-copy': require('../../../images/icons/email-copy.svg'),
  emoji: require('../../../images/icons/emoji.svg'),
  end_call: require('../../../images/icons/end_call.svg'),
  erect_window: require('../../../images/icons/erect_window.svg'),
  error: require('../../../images/icons/error.svg'),
  'event-copy': require('../../../images/icons/event-copy.svg'),
  expand_alt: require('../../../images/icons/expand_alt.svg'),
  expand: require('../../../images/icons/expand.svg'),
  'fallback-copy': require('../../../images/icons/fallback-copy.svg'),
  favorite: require('../../../images/icons/favorite.svg'),
  'feed-copy': require('../../../images/icons/feed-copy.svg'),
  'file-copy': require('../../../images/icons/file-copy.svg'),
  'filter-copy': require('../../../images/icons/filter-copy.svg'),
  filterList: require('../../../images/icons/filterList.svg'),
  'flow-copy': require('../../../images/icons/flow-copy.svg'),
  forward: require('../../../images/icons/forward.svg'),
  frozen: require('../../../images/icons/frozen.svg'),
  full_width_view: require('../../../images/icons/full_width_view.svg'),
  'groups-copy': require('../../../images/icons/groups-copy.svg'),
  help: require('../../../images/icons/help.svg'),
  'home-copy': require('../../../images/icons/home-copy.svg'),
  identity: require('../../../images/icons/identity.svg'),
  image: require('../../../images/icons/image.svg'),
  inbox: require('../../../images/icons/inbox.svg'),
  info_alt: require('../../../images/icons/info_alt.svg'),
  'info-copy': require('../../../images/icons/info-copy.svg'),
  insert_tag_field: require('../../../images/icons/insert_tag_field.svg'),
  insert_template: require('../../../images/icons/insert_template.svg'),
  italic: require('../../../images/icons/italic.svg'),
  jump_to_bottom: require('../../../images/icons/jump_to_bottom.svg'),
  jump_to_top: require('../../../images/icons/jump_to_top.svg'),
  justify_text: require('../../../images/icons/justify_text.svg'),
  kanban: require('../../../images/icons/kanban.svg'),
  keyboard_dismiss: require('../../../images/icons/keyboard_dismiss.svg'),
  knowledge_base: require('../../../images/icons/knowledge_base.svg'),
  layers: require('../../../images/icons/layers.svg'),
  layout: require('../../../images/icons/layout.svg'),
  left_align_text: require('../../../images/icons/left_align_text.svg'),
  left: require('../../../images/icons/left.svg'),
  level_up: require('../../../images/icons/level_up.svg'),
  like: require('../../../images/icons/like.svg'),
  'link-copy': require('../../../images/icons/link-copy.svg'),
  location: require('../../../images/icons/location.svg'),
  lock: require('../../../images/icons/lock.svg'),
  'log_a_call-copy': require('../../../images/icons/log_a_call-copy.svg'),
  logout: require('../../../images/icons/logout.svg'),
  magicwand: require('../../../images/icons/magicwand.svg'),
  mark_all_as_read: require('../../../images/icons/mark_all_as_read.svg'),
  matrix: require('../../../images/icons/matrix.svg'),
  'merge-copy': require('../../../images/icons/merge-copy.svg'),
  'metrics-copy': require('../../../images/icons/metrics-copy.svg'),
  minimize_window: require('../../../images/icons/minimize_window.svg'),
  moneybag: require('../../../images/icons/moneybag.svg'),
  monthlyview: require('../../../images/icons/monthlyview.svg'),
  move: require('../../../images/icons/move.svg'),
  muted: require('../../../images/icons/muted.svg'),
  new_window: require('../../../images/icons/new_window.svg'),
  'new-copy': require('../../../images/icons/new-copy.svg'),
  'news-copy': require('../../../images/icons/news-copy.svg'),
  'note-copy': require('../../../images/icons/note-copy.svg'),
  notebook: require('../../../images/icons/notebook.svg'),
  notification: require('../../../images/icons/notification.svg'),
  office365: require('../../../images/icons/office365.svg'),
  offline_cached: require('../../../images/icons/offline_cached.svg'),
  offline: require('../../../images/icons/offline.svg'),
  open_folder: require('../../../images/icons/open_folder.svg'),
  open: require('../../../images/icons/open.svg'),
  opened_folder: require('../../../images/icons/opened_folder.svg'),
  overflow: require('../../../images/icons/overflow.svg'),
  package_org_beta: require('../../../images/icons/package_org_beta.svg'),
  package_org: require('../../../images/icons/package_org.svg'),
  package: require('../../../images/icons/package.svg'),
  'page-1': require('../../../images/icons/page-1.svg'),
  page: require('../../../images/icons/page.svg'),
  palette: require('../../../images/icons/palette.svg'),
  paste: require('../../../images/icons/paste.svg'),
  'people-copy': require('../../../images/icons/people-copy.svg'),
  phone_landscape: require('../../../images/icons/phone_landscape.svg'),
  phone_portrait: require('../../../images/icons/phone_portrait.svg'),
  'photo-copy': require('../../../images/icons/photo-copy.svg'),
  picklist: require('../../../images/icons/picklist.svg'),
  plus: require('../../../images/icons/plus.svg'),
  power: require('../../../images/icons/power.svg'),
  'preview-copy': require('../../../images/icons/preview-copy.svg'),
  'priority-copy': require('../../../images/icons/priority-copy.svg'),
  'process-copy': require('../../../images/icons/process-copy.svg'),
  push: require('../../../images/icons/push.svg'),
  puzzle: require('../../../images/icons/puzzle.svg'),
  question: require('../../../images/icons/question.svg'),
  questions_and_answers: require('../../../images/icons/questions_and_answers.svg'),
  quotation_marks: require('../../../images/icons/quotation_marks.svg'),
  record_create: require('../../../images/icons/record_create.svg'),
  'record-copy': require('../../../images/icons/record-copy.svg'),
  redo: require('../../../images/icons/redo.svg'),
  'refresh-copy': require('../../../images/icons/refresh-copy.svg'),
  relate: require('../../../images/icons/relate.svg'),
  remove_formatting: require('../../../images/icons/remove_formatting.svg'),
  remove_link: require('../../../images/icons/remove_link.svg'),
  replace: require('../../../images/icons/replace.svg'),
  reply_all: require('../../../images/icons/reply_all.svg'),
  reply: require('../../../images/icons/reply.svg'),
  'reset_password-copy': require('../../../images/icons/reset_password-copy.svg'),
  resource_absence: require('../../../images/icons/resource_absence.svg'),
  resource_capacity: require('../../../images/icons/resource_capacity.svg'),
  resource_territory: require('../../../images/icons/resource_territory.svg'),
  retweet: require('../../../images/icons/retweet.svg'),
  richtextbulletedlist: require('../../../images/icons/richtextbulletedlist.svg'),
  richtextindent: require('../../../images/icons/richtextindent.svg'),
  richtextnumberedlist: require('../../../images/icons/richtextnumberedlist.svg'),
  richtextoutdent: require('../../../images/icons/richtextoutdent.svg'),
  right_align_text: require('../../../images/icons/right_align_text.svg'),
  right: require('../../../images/icons/right.svg'),
  rotate: require('../../../images/icons/rotate.svg'),
  rows: require('../../../images/icons/rows.svg'),
  salesforce1: require('../../../images/icons/salesforce1.svg'),
  search: require('../../../images/icons/search.svg'),
  settings: require('../../../images/icons/settings.svg'),
  setup_assistant_guide: require('../../../images/icons/setup_assistant_guide.svg'),
  setup: require('../../../images/icons/setup.svg'),
  share_mobile: require('../../../images/icons/share_mobile.svg'),
  'share_post-copy': require('../../../images/icons/share_post-copy.svg'),
  'share-copy': require('../../../images/icons/share-copy.svg'),
  shield: require('../../../images/icons/shield.svg'),
  side_list: require('../../../images/icons/side_list.svg'),
  signpost: require('../../../images/icons/signpost.svg'),
  sms: require('../../../images/icons/sms.svg'),
  snippet: require('../../../images/icons/snippet.svg'),
  socialshare: require('../../../images/icons/socialshare.svg'),
  'sort-copy': require('../../../images/icons/sort-copy.svg'),
  spinner: require('../../../images/icons/spinner.svg'),
  standard_objects: require('../../../images/icons/standard_objects.svg'),
  status_approved: require('../../../images/status/approved.svg'),
  status_pending_reapply: require('../../../images/status/pending_reapply.svg'),
  status_pending: require('../../../images/status/pending.svg'),
  status_rejected_reapply: require('../../../images/status/rejected_reapply.svg'),
  status_rejected: require('../../../images/status/rejected.svg'),
  stop: require('../../../images/icons/stop.svg'),
  strikethrough: require('../../../images/icons/strikethrough.svg'),
  success: require('../../../images/icons/success.svg'),
  summary: require('../../../images/icons/summary.svg'),
  summarydetail: require('../../../images/icons/summarydetail.svg'),
  switch: require('../../../images/icons/switch.svg'),
  sync: require('../../../images/icons/sync.svg'),
  'system-error': require('../../../images/icons/system-error.svg'),
  table: require('../../../images/icons/table.svg'),
  tablet_landscape: require('../../../images/icons/tablet_landscape.svg'),
  tablet_portrait: require('../../../images/icons/tablet_portrait.svg'),
  tabset: require('../../../images/icons/tabset.svg'),
  'task-copy': require('../../../images/icons/task-copy.svg'),
  text_background_color: require('../../../images/icons/text_background_color.svg'),
  text_color: require('../../../images/icons/text_color.svg'),
  threedots_vertical: require('../../../images/icons/threedots_vertical.svg'),
  threedots: require('../../../images/icons/threedots.svg'),
  thunder: require('../../../images/icons/thunder.svg'),
  tile_card_list: require('../../../images/icons/tile_card_list.svg'),
  'topic-copy': require('../../../images/icons/topic-copy.svg'),
  touch_action: require('../../../images/icons/touch_action.svg'),
  trail: require('../../../images/icons/trail.svg'),
  turn_off_notifications: require('../../../images/icons/turn_off_notifications.svg'),
  undelete: require('../../../images/icons/undelete.svg'),
  undeprecate: require('../../../images/icons/undeprecate.svg'),
  underline: require('../../../images/icons/underline.svg'),
  undo: require('../../../images/icons/undo.svg'),
  unlock: require('../../../images/icons/unlock.svg'),
  unmuted: require('../../../images/icons/unmuted.svg'),
  up: require('../../../images/icons/up.svg'),
  'upload-copy': require('../../../images/icons/upload-copy.svg'),
  user_role: require('../../../images/icons/user_role.svg'),
  'user-copy': require('../../../images/icons/user-copy.svg'),
  video: require('../../../images/icons/video.svg'),
  volume_high: require('../../../images/icons/volume_high.svg'),
  volume_low: require('../../../images/icons/volume_low.svg'),
  volume_off: require('../../../images/icons/volume_off.svg'),
  warning: require('../../../images/icons/warning.svg'),
  'warning-reverse': require('../../../images/icons/warning-reverse.svg'),
  weeklyview: require('../../../images/icons/weeklyview.svg'),
  wifi: require('../../../images/icons/wifi.svg'),
  work_order_type: require('../../../images/icons/work_order_type.svg'),
  world: require('../../../images/icons/world.svg'),
  yubi_key: require('../../../images/icons/yubi_key.svg'),
  zoomin: require('../../../images/icons/zoomin.svg'),
  zoomout: require('../../../images/icons/zoomout.svg'),
  pencil: require('../../../images/icons/pencil.svg'),
  /* eslint-enable global-require */
};

// Hack
// flowの機能としてpngやsvgなどよくあるassetsをデフォルトでstringとして扱う機能がある。
// このデフォルトの型は module.name_mapper.extension オプションで別の型に設定することが
// 出来るはずなのだが、どういうわけか常にstringになってしまう。
// そこで、一旦anyにキャストしてから正しい型に再キャストしている。
const iconSet = mapValues(_iconSet, (mod) => mod.default);

export default iconSet;
