if(typeof(teasp) == 'object' && !teasp.resolved['7705'] && teasp.view && teasp.view.EmpWorks){
teasp.view.EmpWorks.prototype.openExpApply=function(){for(var e=this.pouch.getJobApply(),t=null,a=teasp.util.date.getDateList(e.startDate,e.endDate),o=[],s={},i=0;i<a.length;i++){var n=a[i],r=this.pouch.getEmpMonthByDate(n);
if(!s[r.yearMonth]&&(s[r.yearMonth]=1,(r.config.useDailyApply&&r.config.checkWorkingTime||r.config.checkWorkingTimeMonthly)&&!teasp.constant.STATUS_FIX.contains(r.apply.status))){var l=Math.floor(r.yearMonth/100),p=r.yearMonth%100,d=r.subNo;o.push(teasp.util.date.formatMonth("zv00000020",l,p,d))}}var c="";if(o.length>0){if(!this.checkPreApplyMonthly(a))return;c='<br/><span style="font-size:90%;">（'+teasp.util.date.formatDate(e.startDate,"M/d")+"～"+teasp.util.date.formatDate(e.endDate,"M/d")+" の勤怠は更新できなくなります。ご注意ください）</span>";
}var m=this.pouch.getWorks()||[];if(m.length||confirm(teasp.message.getLabel("tf10008160",this.pouch.isUseJobWorkFlow()?teasp.message.getLabel("applyx_btn_title"):teasp.message.getLabel("fix_btn_title")))){var h={title:teasp.message.getLabel("tm40001060"),buttonType:this.pouch.isUseJobWorkFlow()?0:1,descript:"",applyKey:teasp.constant.APPLY_KEY_JOBAPPLY,warning:t};this.pouch.isUseJobWorkFlow()?h.descript=teasp.message.getLabel("tm40001070",this.pouch.getJobYearMonthJp()):h.descript=teasp.message.getLabel("tm40001080",this.pouch.getJobYearMonthJp()),
h.descript+=c,teasp.manager.dialogOpen("ApplyComment",h,this.pouch,this,function(e){teasp.manager.request("submitJobApply",{empId:this.pouch.getEmpId(),month:this.pouch.getJobYearMonth(),startDate:this.pouch.getJobStartDate(),comment:e.comment},this.pouch,{hideBusy:!1},this,function(){this.refreshMonthly()},function(e){teasp.message.alertError(e)})})}};
teasp.view.EmpWorks.prototype.checkPreApplyMonthly=function(e){console.log("EmpWorks checkPreApplyMonthly()");for(var t=teasp.message.getLabel("tm10001060"),a=this.pouch.dataObj,o=this.pouch.getWorks(),s={},i={},n=[],r=[],l=[],p=[],d=0;d<e.length;d++){var c=e[d],m=a.days[c];s[c]={time:0,works:[],timeFixTime:0};for(var h=s[c],u=0;u<o.length;u++){var y=o[u];if(y.date==c&&(y.time>0||y.volume>0||""!=(y.taskNote||"")||""!=(y.progress||"")||""!=(y.extraItem1||"")||""!=(y.extraItem2||""))){
h.works.push(y),h.time+=y.time,y.timeFix&&(h.timeFixTime+=y.time);var g=y.process?y.process:"",f=y.jobId+":"+g,v=i[f];v||(v=i[f]={jobName:y.job.name,time:0,process:y.process,jobLeaderId:y.job.jobLeaderId}),v.time+=y.time}}var b=m.rack.validApplys&&m.rack.validApplys.waiting||[];b.length&&n.push(c);for(var _=m.rack.validApplys||{},T=_.reviseTime||[],u=0;u<T.length;u++){var j=T[u];teasp.constant.STATUS_APPROVES.indexOf(j.status)>=0&&!j.entered&&r.push(c);
}var E=_.kyushtu&&_.kyushtu.length?_.kyushtu[0]:null,L="number"==typeof m.startTime&&"number"==typeof m.endTime,k=a.workNotes[c]?a.workNotes[c].workNetTime||0:0;m.dayType?m.dayType&&!E&&h.time>0&&p.push(c):m.rack.holidayJoin&&3==m.rack.holidayJoin.flag||m.plannedHoliday&&!E?h.time>0&&p.push(c):L||m.dbDayType?h.time!=k&&p.push(c):l.push(c)}var D=[];return n.length&&D.push(teasp.message.getLabel("tm10001080").replace(/^\n/,"")+"\n("+teasp.view.EmpWorks.sliceDates(n)+")"),
r.length&&D.push("勤怠時刻修正申請が反映されていません（勤務表を開くと反映されます）。\n("+teasp.view.EmpWorks.sliceDates(r)+")"),l.length&&D.push("勤怠が入力されていない日があります。\n("+teasp.view.EmpWorks.sliceDates(l)+")"),p.length&&D.push("工数の合計と実労働時間が合いません。\n("+teasp.view.EmpWorks.sliceDates(p)+")"),D.length?(alert(t+"\n"+D.join("\n")),!1):!0};
teasp.view.EmpWorks.sliceDates=function(e){var t=(e||[]).length;return t>5&&e.splice(5,e.length),e.join(", ").replace(/-/g,"/")+(t>5?", ..":"");};
teasp.dialog.InputTime.prototype.isReadOnly=function(){return this.pouch.isJobMonthFixedByDate(this.args.date)?!0:this.pouch.isEmpMonthReadOnly()||this.dayWrap.isDailyFix()||this.readOnly||!this.pouch.isUpdater()};
teasp.dialog.EditTime.prototype.isReadOnly=function(){return this.pouch.isJobMonthFixedByDate(this.args.date)?!0:this.pouch.isEmpMonthReadOnly()||!this.dayWrap.isInputTime()||this.dayWrap.isDailyFix()};
teasp.dialog.EmpApply.prototype.isReadOnly=function(e){return this.pouch.isJobMonthFixedByDate(this.args.date)?!0:this.monthFix||this.dayFix||this.pouch.isReadOnly()||!e&&!this.applyable};
}
