/*
 * CONSTANS
 */
export const APPROVE_SUCCESS = 'MODULES/UI/ATT/REQUEST/APPROVE_SUCCESS';
export const REJECT_SUCCESS = 'MODULES/UI/ATT/REQUEST/REJECT_SUCCESS';
export const EDIT_COMMENT = 'MODULES/UI/ATT/REQUEST/EDIT_COMMENT';
