import { State } from '../../absenceRequest';

const absenceRequest: State = {
  request: {
    id: '',
    requestTypeCode: 'Absence',
    requestTypeName: '欠勤',
    status: 'NotRequested',
    startDate: '2020-02-07',
    endDate: '2020-02-07',
    startTime: null,
    endTime: null,
    remarks: '',
    reason: '',
    leaveName: '',
    leaveCode: '',
    leaveType: null,
    leaveRange: null,
    leaveDetailCode: null,
    leaveDetailName: null,
    substituteLeaveType: null,
    substituteDate: '',
    originalRequestId: '',
    isForReapply: false,
    directApplyRestTimes: [],
    patternCode: null,
    patternName: null,
    patternRestTimes: [],
    requireReason: false,
    approver01Name: '',
    type: 'Absence',
    personalReason: false,
    useManagePersonalReason: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    requestDayType: null,
    requestableDayType: 'Holiday',
    canDirectInputTimeRequest: false,
    isDirectInputTimeRequest: false,
    useLateArrivalReason: false,
    useEarlyLeaveReason: false,
    reasonId: '',
    reasonCode: '',
    reasonName: '',
  },
  hasRange: false,
};

export default absenceRequest;
