import { State } from '../../directRequest';

const directRequest: State = {
  request: {
    id: '',
    requestTypeCode: 'Direct',
    requestTypeName: '直行直帰',
    status: 'NotRequested',
    startDate: '2020-04-06',
    endDate: '2020-04-06',
    startTime: null,
    endTime: null,
    remarks: '',
    reason: '',
    leaveName: '',
    leaveCode: '',
    leaveType: null,
    leaveRange: null,
    leaveDetailCode: null,
    leaveDetailName: null,
    substituteLeaveType: null,
    substituteDate: '',
    originalRequestId: '',
    isForReapply: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    directApplyRestTimes: [
      {
        startTime: null,
        endTime: null,
        restReason: null,
      },
      {
        startTime: null,
        endTime: null,
        restReason: null,
      },
      {
        startTime: null,
        endTime: null,
        restReason: null,
      },
    ],
    patternCode: null,
    patternName: null,
    patternRestTimes: [],
    requireReason: false,
    approver01Name: '',
    type: 'Direct',
    personalReason: false,
    useManagePersonalReason: false,
    requestDayType: null,
    requestableDayType: 'Holiday',
    canDirectInputTimeRequest: false,
    isDirectInputTimeRequest: false,
    useLateArrivalReason: false,
    useEarlyLeaveReason: false,
    reasonId: '',
    reasonName: '',
    reasonCode: '',
  },
  hasRange: false,
};

export default directRequest;
