import { DIRECT_INPUT } from '@attendance/domain/models/AttPattern';

import { State } from '../../holidayWorkRequest';

export const defaultValue: State = {
  request: {
    id: '',
    requestTypeCode: 'HolidayWork',
    requestTypeName: '休日出勤',
    status: 'NotRequested',
    startDate: '2020-04-05',
    endDate: '',
    startTime: 540,
    endTime: 1080,
    remarks: '',
    reason: '',
    leaveName: '',
    leaveCode: '',
    leaveType: null,
    leaveRange: null,
    leaveDetailCode: null,
    leaveDetailName: null,
    substituteLeaveType: 'None',
    substituteLeaveTypes: ['None', 'CompensatoryStocked', 'Substitute'],
    substituteDate: '',
    originalRequestId: '',
    isForReapply: false,
    directApplyRestTimes: [],
    patternCode: null,
    patternName: null,
    patternRestTimes: [],
    requireReason: false,
    approver01Name: '',
    type: 'HolidayWork',
    personalReason: false,
    useManagePersonalReason: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    requestDayType: null,
    requestableDayType: 'Holiday',
    canDirectInputTimeRequest: false,
    isDirectInputTimeRequest: false,
    useLateArrivalReason: false,
    useEarlyLeaveReason: false,
    reasonId: '',
    reasonCode: '',
    reasonName: '',
    patterns: [],
    enabledPatternApply: false,
  },
  selectedAttPattern: null,
};

export const patterns: State['request']['patterns'] = [
  {
    name: 'Direct input',
    code: DIRECT_INPUT,
    startTime: null,
    endTime: null,
    restTimes: [],
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
  },
  {
    name: 'pattern1',
    code: 'pattern1',
    startTime: 300,
    endTime: 1320,
    restTimes: [
      {
        startTime: 420,
        endTime: 480,
        restReason: {
          id: 'a0A2800000FmMQCEA1',
          name: 'お昼休み',
          code: '001',
        },
      },
      {
        startTime: 600,
        endTime: 660,
        restReason: {
          id: 'a0A2800000FmMQCEA1',
          name: 'お昼休み',
          code: '001',
        },
      },
      {
        startTime: 780,
        endTime: 900,
        restReason: {
          id: 'a0A2800000FmMQCEA1',
          name: 'お昼休み',
          code: '001',
        },
      },
      {
        startTime: 1020,
        endTime: 1080,
        restReason: {
          id: 'a0A2800000FmMQCEA1',
          name: 'お昼休み',
          code: '001',
        },
      },
      {
        startTime: 1200,
        endTime: 1260,
        restReason: {
          id: 'a0A2800000FmMQCEA1',
          name: 'お昼休み',
          code: '001',
        },
      },
    ],
    workSystem: 'JP:Modified',
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
  },
  {
    name: 'pattern2',
    code: 'pattern2',
    startTime: 600,
    endTime: 1140,
    restTimes: [
      {
        startTime: 720,
        endTime: 780,
        restReason: {
          id: 'a0A2800000FmMQCEA1',
          name: 'お昼休み',
          code: '001',
        },
      },
    ],
    workSystem: 'JP:Modified',
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
  },
];
