import { State } from '../../lateArrivalRequest';

const lateArrivalRequest: State = {
  request: {
    id: '',
    requestTypeCode: 'LateArrival',
    requestTypeName: '遅刻',
    status: 'NotRequested',
    startDate: '2020-04-07',
    endDate: '',
    startTime: 540,
    endTime: null,
    remarks: '',
    reason: '',
    leaveName: '',
    leaveCode: '',
    leaveType: null,
    leaveRange: null,
    leaveDetailCode: null,
    leaveDetailName: null,
    substituteLeaveType: null,
    substituteDate: '',
    originalRequestId: '',
    isForReapply: false,
    directApplyRestTimes: [],
    patternCode: null,
    patternName: null,
    patternRestTimes: [],
    requireReason: false,
    approver01Name: '',
    type: 'LateArrival',
    personalReason: false,
    useManagePersonalReason: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    requestDayType: null,
    requestableDayType: 'Holiday',
    canDirectInputTimeRequest: false,
    isDirectInputTimeRequest: false,
    useLateArrivalReason: false,
    useEarlyLeaveReason: false,
    reasonId: null,
    reasonName: null,
    reasonCode: null,
  },
  lateArrivalReasonList: [],
  useLateArrivalReason: false,
};

export default lateArrivalRequest;
