import configureStore from '../../../store/configureStore';

export default configureStore({
  commons: {
    app: {
      loadingDepth: 0,
      error: null,
      unexpectedError: null,
      confirmDialog: null,
    },
    accessControl: {
      permission: {
        viewAttTimeSheetByDelegate: false,
        editAttTimeSheetByDelegate: false,
        submitAttDailyRequestByDelegate: false,
        cancelAttDailyRequestByDelegate: false,
        approveAttDailyRequestByDelegate: false,
        cancelAttDailyApprovalByEmployee: false,
        cancelAttDailyApprovalByDelegate: false,
        submitAttRequestByDelegate: false,
        cancelAttRequestByDelegate: false,
        approveAttRequestByDelegate: false,
        cancelAttApprovalByEmployee: false,
        cancelAttApprovalByDelegate: false,
        manageOverallSetting: false,
        switchCompany: false,
        manageDepartment: false,
        manageEmployee: false,
        manageCalendar: false,
        manageJobType: false,
        manageJob: false,
        manageMobileSetting: false,
        managePermission: false,
        managePlannerSetting: false,
        manageAttLeave: false,
        manageAttShortTimeWorkSetting: false,
        manageAttLeaveOfAbsence: false,
        manageAttWorkingType: false,
        manageAttAgreementAlertSetting: false,
        manageAttLeaveGrant: false,
        manageAttShortTimeWorkSettingApply: false,
        manageAttLeaveOfAbsenceApply: false,
        manageTimeSetting: false,
        manageTimeWorkCategory: false,
      },
    },
    standaloneMode: {
      enabled: false,
    },
  },
  userSetting: {
    userName: 'yokoyama.shodai+wsp+dev@teamspirit.com',
    useExpenseRequest: false,
    useExpense: true,
    photoUrl: 'https://c.ap4.content.force.com/profilephoto/005/T',
    name: 'Shodai Yokoyama',
    managerName: '横山 翔大',
    language: 'ja',
    id: '0056F000009E298QAC',
    employeeName: '横山 翔大',
    employeeId: 'a0O6F00000s3K4IUAU',
    departmentName: 'ながーーーーーーーーーーーーーーーーーーーい部署',
    departmentId: 'a0M6F00000PfcE3UAJ',
    currencySymbol: '￥',
    currencyName: '日本円',
    currencyId: 'a0q6F00000Oymx7QAB',
    currencyDecimalPlaces: 0,
    currencyCode: 'JPY',
    costCenterName: 'DEFAULT',
    costCenterHistoryId: 'a126F00000DbMHuQAN',
    companyName: '<WSP>TeamSpirit',
    companyId: 'a0J6F000013GckRUAS',
    approver01Name: '横山 翔大',
    allowToChangeApproverSelf: true,
  },
  attendance: {
    dailyRequest: {
      entities: {
        availableRequests: [
          {
            id: '',
            requestTypeCode: 'Leave',
            requestTypeName: '休暇',
            status: 'NotRequested',
            startDate: '',
            endDate: '',
            startTime: 0,
            endTime: 0,
            remarks: '',
            reason: '',
            leaveName: '',
            leaveType: null,
            leaveRange: null,
            substituteLeaveType: null,
            substituteDate: '',
            originalRequestId: '',
            isForReapply: false,
            directApplyRestTimes: [],
            approver01Name: '',
            targetDate: '',
          },
          {
            id: '',
            requestTypeCode: 'OvertimeWork',
            requestTypeName: '残業',
            status: 'NotRequested',
            startDate: '',
            endDate: '',
            startTime: 0,
            endTime: 0,
            remarks: '',
            reason: '',
            leaveName: '',
            leaveType: null,
            leaveRange: null,
            substituteLeaveType: null,
            substituteDate: '',
            originalRequestId: '',
            isForReapply: false,
            directApplyRestTimes: [],
            approver01Name: '',
            targetDate: '',
          },
          {
            id: '',
            requestTypeCode: 'EarlyStartWork',
            requestTypeName: '早朝勤務',
            status: 'NotRequested',
            startDate: '',
            endDate: '',
            startTime: 0,
            endTime: 0,
            remarks: '',
            reason: '',
            leaveName: '',
            leaveType: null,
            leaveRange: null,
            substituteLeaveType: null,
            substituteDate: '',
            originalRequestId: '',
            isForReapply: false,
            directApplyRestTimes: [],
            approver01Name: '',
            targetDate: '',
          },
          {
            id: '',
            requestTypeCode: 'Direct',
            requestTypeName: '直行直帰',
            status: 'NotRequested',
            startDate: '',
            endDate: '',
            startTime: 0,
            endTime: 0,
            remarks: '',
            reason: '',
            leaveName: '',
            leaveType: null,
            leaveRange: null,
            substituteLeaveType: null,
            substituteDate: '',
            originalRequestId: '',
            isForReapply: false,
            directApplyRestTimes: [],
            approver01Name: '',
            targetDate: '',
          },
          {
            id: '',
            requestTypeCode: 'Absence',
            requestTypeName: '欠勤',
            status: 'NotRequested',
            startDate: '',
            endDate: '',
            startTime: 0,
            endTime: 0,
            remarks: '',
            reason: '',
            leaveName: '',
            leaveType: null,
            leaveRange: null,
            substituteLeaveType: null,
            substituteDate: '',
            originalRequestId: '',
            isForReapply: false,
            directApplyRestTimes: [],
            approver01Name: '',
            targetDate: '',
          },
        ],
        latestRequests: [],
      },
      ui: {
        detail: {
          isEditing: true,
          target: {
            id: '',
            requestTypeCode: 'None',
            requestTypeName: 'Request type name',
            status: 'NotRequested',
            startDate: '',
            endDate: '',
            startTime: 0,
            endTime: 0,
            remarks: '',
            reason: '',
            leaveName: '',
            leaveType: null,
            leaveRange: null,
            substituteLeaveType: null,
            substituteDate: '',
            originalRequestId: '',
            isForReapply: false,
            directApplyRestTimes: [],
            approver01Name: '',
            targetDate: '',
          },
          editAction: 'Create',
          disableAction: 'None',
        },
      },
    },
    timesheet: {
      ui: {
        daily: {
          paging: {
            current: '2019-01-03',
            prev: '2019-01-02',
            next: '2019-01-04',
          },
          editing: {
            id: 'a0A6F0000118JosUAE',
            targetDate: '2019-01-03',
            startTime: null,
            endTime: null,
            restTimes: [
              {
                startTime: null,
                endTime: null,
              },
            ],
            restHours: null,
            remarks: '',
            canEdit: true,
            hasOtherRestTime: false,
          },
        },
        monthly: {
          paging: {
            current: '',
            prev: '',
            next: '',
            pages: [],
          },
        },
      },
      entities: {
        id: 'a0E6F000027l0eBUAQ',
        recordAllRecordDates: [
          '2019-01-01',
          '2019-01-02',
          '2019-01-03',
          '2019-01-04',
          '2019-01-05',
          '2019-01-06',
          '2019-01-07',
          '2019-01-08',
          '2019-01-09',
          '2019-01-10',
          '2019-01-11',
          '2019-01-12',
          '2019-01-13',
          '2019-01-14',
          '2019-01-15',
          '2019-01-16',
          '2019-01-17',
          '2019-01-18',
          '2019-01-19',
          '2019-01-20',
          '2019-01-21',
          '2019-01-22',
          '2019-01-23',
          '2019-01-24',
          '2019-01-25',
          '2019-01-26',
          '2019-01-27',
          '2019-01-28',
          '2019-01-29',
          '2019-01-30',
          '2019-01-31',
        ],
        recordsByRecordDate: {
          '2019-01-01': {
            id: 'a0A6F0000118JoqUAE',
            recordDate: '2019-01-01',
            dayType: 'Holiday',
            startTime: null,
            endTime: null,
            startStampTime: null,
            endStampTime: null,
            restTimes: [
              {
                startTime: null,
                endTime: null,
              },
            ],
            requestTypeCodes: ['HolidayWork'],
            requestIds: [],
            contractedDetail: {
              workSystem: null,
              startTime: null,
              rest5StartTime: null,
              rest5EndTime: null,
              rest4StartTime: null,
              rest4EndTime: null,
              rest3StartTime: null,
              rest3EndTime: null,
              rest2StartTime: null,
              rest2EndTime: null,
              rest1StartTime: null,
              rest1EndTime: null,
              requireOvertimeWorkApplyAfter: null,
              requireEarlyStartWorkApplyBefore: null,
              holidayWorkConfig: null,
              flexStartTime: null,
              flexEndTime: null,
              endTime: null,
              directApplyStartTime: null,
              directApplyRest5StartTime: null,
              directApplyRest5EndTime: null,
              directApplyRest4StartTime: null,
              directApplyRest4EndTime: null,
              directApplyRest3StartTime: null,
              directApplyRest3EndTime: null,
              directApplyRest2StartTime: null,
              directApplyRest2EndTime: null,
              directApplyRest1StartTime: null,
              directApplyRest1EndTime: null,
              directApplyEndTime: null,
              allowToChangeApproverSelf: null,
            },
            ciliTimePeriods: [],
            ciloTimePeriods: [],
            coliTimePeriods: [],
            coloTimePeriods: [],
            remarks: '',
            isLeaveOfAbsence: false,
            insufficientRestTime: 0,
            restHours: null,
            outStartTime: null,
            outEndTime: null,
            approver01Name: '横山 翔大',
            shouldInput: false,
            canEdit: false,
            effectualLeaveRequests: [],
            hasAbsenceRequest: false,
          },
          '2019-01-02': {
            id: 'a0A6F0000118JorUAE',
            recordDate: '2019-01-02',
            dayType: 'Workday',
            startTime: null,
            endTime: null,
            startStampTime: null,
            endStampTime: null,
            restTimes: [
              {
                startTime: null,
                endTime: null,
              },
            ],
            requestTypeCodes: [
              'Leave',
              'OvertimeWork',
              'EarlyStartWork',
              'Absence',
              'Direct',
            ],
            requestIds: [],
            contractedDetail: {
              workSystem: null,
              startTime: 660,
              rest5StartTime: null,
              rest5EndTime: null,
              rest4StartTime: null,
              rest4EndTime: null,
              rest3StartTime: null,
              rest3EndTime: null,
              rest2StartTime: null,
              rest2EndTime: null,
              rest1StartTime: null,
              rest1EndTime: null,
              requireOvertimeWorkApplyAfter: null,
              requireEarlyStartWorkApplyBefore: null,
              holidayWorkConfig: null,
              flexStartTime: null,
              flexEndTime: null,
              endTime: 960,
              directApplyStartTime: null,
              directApplyRest5StartTime: null,
              directApplyRest5EndTime: null,
              directApplyRest4StartTime: null,
              directApplyRest4EndTime: null,
              directApplyRest3StartTime: null,
              directApplyRest3EndTime: null,
              directApplyRest2StartTime: null,
              directApplyRest2EndTime: null,
              directApplyRest1StartTime: null,
              directApplyRest1EndTime: null,
              directApplyEndTime: null,
              allowToChangeApproverSelf: null,
            },
            ciliTimePeriods: [],
            ciloTimePeriods: [],
            coliTimePeriods: [],
            coloTimePeriods: [],
            remarks: '',
            isLeaveOfAbsence: false,
            insufficientRestTime: 0,
            restHours: null,
            outStartTime: null,
            outEndTime: null,
            approver01Name: '横山 翔大',
            shouldInput: true,
            canEdit: true,
            effectualLeaveRequests: [],
            hasAbsenceRequest: false,
          },
          '2019-01-03': {
            id: 'a0A6F0000118JosUAE',
            recordDate: '2019-01-03',
            dayType: 'Workday',
            startTime: null,
            endTime: null,
            startStampTime: null,
            endStampTime: null,
            restTimes: [
              {
                startTime: null,
                endTime: null,
              },
            ],
            requestTypeCodes: [
              'Leave',
              'OvertimeWork',
              'EarlyStartWork',
              'Absence',
              'Direct',
            ],
            requestIds: [],
            contractedDetail: {
              workSystem: null,
              startTime: 660,
              rest5StartTime: null,
              rest5EndTime: null,
              rest4StartTime: null,
              rest4EndTime: null,
              rest3StartTime: null,
              rest3EndTime: null,
              rest2StartTime: null,
              rest2EndTime: null,
              rest1StartTime: null,
              rest1EndTime: null,
              requireOvertimeWorkApplyAfter: null,
              requireEarlyStartWorkApplyBefore: null,
              holidayWorkConfig: null,
              flexStartTime: null,
              flexEndTime: null,
              endTime: 960,
              directApplyStartTime: null,
              directApplyRest5StartTime: null,
              directApplyRest5EndTime: null,
              directApplyRest4StartTime: null,
              directApplyRest4EndTime: null,
              directApplyRest3StartTime: null,
              directApplyRest3EndTime: null,
              directApplyRest2StartTime: null,
              directApplyRest2EndTime: null,
              directApplyRest1StartTime: null,
              directApplyRest1EndTime: null,
              directApplyEndTime: null,
              allowToChangeApproverSelf: null,
            },
            ciliTimePeriods: [],
            ciloTimePeriods: [],
            coliTimePeriods: [],
            coloTimePeriods: [],
            remarks: '',
            isLeaveOfAbsence: false,
            insufficientRestTime: 0,
            restHours: null,
            outStartTime: null,
            outEndTime: null,
            approver01Name: '横山 翔大',
            shouldInput: true,
            canEdit: true,
            effectualLeaveRequests: [],
            hasAbsenceRequest: false,
          },
          '2019-01-04': {
            id: 'a0A6F0000118JotUAE',
            recordDate: '2019-01-04',
            dayType: 'Workday',
            startTime: null,
            endTime: null,
            startStampTime: null,
            endStampTime: null,
            restTimes: [
              {
                startTime: null,
                endTime: null,
              },
            ],
            requestTypeCodes: [
              'Leave',
              'OvertimeWork',
              'EarlyStartWork',
              'Absence',
              'Direct',
            ],
            requestIds: [],
            contractedDetail: {
              workSystem: null,
              startTime: 660,
              rest5StartTime: null,
              rest5EndTime: null,
              rest4StartTime: null,
              rest4EndTime: null,
              rest3StartTime: null,
              rest3EndTime: null,
              rest2StartTime: null,
              rest2EndTime: null,
              rest1StartTime: null,
              rest1EndTime: null,
              requireOvertimeWorkApplyAfter: null,
              requireEarlyStartWorkApplyBefore: null,
              holidayWorkConfig: null,
              flexStartTime: null,
              flexEndTime: null,
              endTime: 960,
              directApplyStartTime: null,
              directApplyRest5StartTime: null,
              directApplyRest5EndTime: null,
              directApplyRest4StartTime: null,
              directApplyRest4EndTime: null,
              directApplyRest3StartTime: null,
              directApplyRest3EndTime: null,
              directApplyRest2StartTime: null,
              directApplyRest2EndTime: null,
              directApplyRest1StartTime: null,
              directApplyRest1EndTime: null,
              directApplyEndTime: null,
              allowToChangeApproverSelf: null,
            },
            ciliTimePeriods: [],
            ciloTimePeriods: [],
            coliTimePeriods: [],
            coloTimePeriods: [],
            remarks: '',
            isLeaveOfAbsence: false,
            insufficientRestTime: 0,
            restHours: null,
            outStartTime: null,
            outEndTime: null,
            approver01Name: '横山 翔大',
            shouldInput: true,
            canEdit: true,
            effectualLeaveRequests: [],
            hasAbsenceRequest: false,
          },
          '2019-01-05': {
            id: 'a0A6F0000118JouUAE',
            recordDate: '2019-01-05',
            dayType: 'Holiday',
            startTime: null,
            endTime: null,
            startStampTime: null,
            endStampTime: null,
            restTimes: [
              {
                startTime: null,
                endTime: null,
              },
            ],
            requestTypeCodes: ['HolidayWork'],
            requestIds: [],
            contractedDetail: {
              workSystem: null,
              startTime: null,
              rest5StartTime: null,
              rest5EndTime: null,
              rest4StartTime: null,
              rest4EndTime: null,
              rest3StartTime: null,
              rest3EndTime: null,
              rest2StartTime: null,
              rest2EndTime: null,
              rest1StartTime: null,
              rest1EndTime: null,
              requireOvertimeWorkApplyAfter: null,
              requireEarlyStartWorkApplyBefore: null,
              holidayWorkConfig: null,
              flexStartTime: null,
              flexEndTime: null,
              endTime: null,
              directApplyStartTime: null,
              directApplyRest5StartTime: null,
              directApplyRest5EndTime: null,
              directApplyRest4StartTime: null,
              directApplyRest4EndTime: null,
              directApplyRest3StartTime: null,
              directApplyRest3EndTime: null,
              directApplyRest2StartTime: null,
              directApplyRest2EndTime: null,
              directApplyRest1StartTime: null,
              directApplyRest1EndTime: null,
              directApplyEndTime: null,
              allowToChangeApproverSelf: null,
            },
            ciliTimePeriods: [],
            ciloTimePeriods: [],
            coliTimePeriods: [],
            coloTimePeriods: [],
            remarks: '',
            isLeaveOfAbsence: false,
            insufficientRestTime: 0,
            restHours: null,
            outStartTime: null,
            outEndTime: null,
            approver01Name: '横山 翔大',
            shouldInput: false,
            canEdit: false,
            effectualLeaveRequests: [],
            hasAbsenceRequest: false,
          },
          '2019-01-06': {
            id: 'a0A6F0000118JovUAE',
            recordDate: '2019-01-06',
            dayType: 'LegalHoliday',
            startTime: null,
            endTime: null,
            startStampTime: null,
            endStampTime: null,
            restTimes: [
              {
                startTime: null,
                endTime: null,
              },
            ],
            requestTypeCodes: ['HolidayWork'],
            requestIds: [],
            contractedDetail: {
              workSystem: null,
              startTime: null,
              rest5StartTime: null,
              rest5EndTime: null,
              rest4StartTime: null,
              rest4EndTime: null,
              rest3StartTime: null,
              rest3EndTime: null,
              rest2StartTime: null,
              rest2EndTime: null,
              rest1StartTime: null,
              rest1EndTime: null,
              requireOvertimeWorkApplyAfter: null,
              requireEarlyStartWorkApplyBefore: null,
              holidayWorkConfig: null,
              flexStartTime: null,
              flexEndTime: null,
              endTime: null,
              directApplyStartTime: null,
              directApplyRest5StartTime: null,
              directApplyRest5EndTime: null,
              directApplyRest4StartTime: null,
              directApplyRest4EndTime: null,
              directApplyRest3StartTime: null,
              directApplyRest3EndTime: null,
              directApplyRest2StartTime: null,
              directApplyRest2EndTime: null,
              directApplyRest1StartTime: null,
              directApplyRest1EndTime: null,
              directApplyEndTime: null,
              allowToChangeApproverSelf: null,
            },
            ciliTimePeriods: [],
            ciloTimePeriods: [],
            coliTimePeriods: [],
            coloTimePeriods: [],
            remarks: '',
            isLeaveOfAbsence: false,
            insufficientRestTime: 0,
            restHours: null,
            outStartTime: null,
            outEndTime: null,
            approver01Name: '横山 翔大',
            shouldInput: false,
            canEdit: false,
            effectualLeaveRequests: [],
            hasAbsenceRequest: false,
          },
          '2019-01-07': {
            id: 'a0A6F0000118JowUAE',
            recordDate: '2019-01-07',
            dayType: 'Workday',
            startTime: null,
            endTime: null,
            startStampTime: null,
            endStampTime: null,
            restTimes: [
              {
                startTime: null,
                endTime: null,
              },
            ],
            requestTypeCodes: [
              'Leave',
              'OvertimeWork',
              'EarlyStartWork',
              'Absence',
              'Direct',
            ],
            requestIds: [],
            contractedDetail: {
              workSystem: null,
              startTime: 660,
              rest5StartTime: null,
              rest5EndTime: null,
              rest4StartTime: null,
              rest4EndTime: null,
              rest3StartTime: null,
              rest3EndTime: null,
              rest2StartTime: null,
              rest2EndTime: null,
              rest1StartTime: null,
              rest1EndTime: null,
              requireOvertimeWorkApplyAfter: null,
              requireEarlyStartWorkApplyBefore: null,
              holidayWorkConfig: null,
              flexStartTime: null,
              flexEndTime: null,
              endTime: 960,
              directApplyStartTime: null,
              directApplyRest5StartTime: null,
              directApplyRest5EndTime: null,
              directApplyRest4StartTime: null,
              directApplyRest4EndTime: null,
              directApplyRest3StartTime: null,
              directApplyRest3EndTime: null,
              directApplyRest2StartTime: null,
              directApplyRest2EndTime: null,
              directApplyRest1StartTime: null,
              directApplyRest1EndTime: null,
              directApplyEndTime: null,
              allowToChangeApproverSelf: null,
            },
            ciliTimePeriods: [],
            ciloTimePeriods: [],
            coliTimePeriods: [],
            coloTimePeriods: [],
            remarks: '',
            isLeaveOfAbsence: false,
            insufficientRestTime: 0,
            restHours: null,
            outStartTime: null,
            outEndTime: null,
            approver01Name: '横山 翔大',
            shouldInput: true,
            canEdit: true,
            effectualLeaveRequests: [],
            hasAbsenceRequest: false,
          },
          '2019-01-08': {
            id: 'a0A6F0000118JoxUAE',
            recordDate: '2019-01-08',
            dayType: 'Workday',
            startTime: null,
            endTime: null,
            startStampTime: null,
            endStampTime: null,
            restTimes: [
              {
                startTime: null,
                endTime: null,
              },
            ],
            requestTypeCodes: [
              'Leave',
              'OvertimeWork',
              'EarlyStartWork',
              'Absence',
              'Direct',
            ],
            requestIds: [],
            contractedDetail: {
              workSystem: null,
              startTime: 660,
              rest5StartTime: null,
              rest5EndTime: null,
              rest4StartTime: null,
              rest4EndTime: null,
              rest3StartTime: null,
              rest3EndTime: null,
              rest2StartTime: null,
              rest2EndTime: null,
              rest1StartTime: null,
              rest1EndTime: null,
              requireOvertimeWorkApplyAfter: null,
              requireEarlyStartWorkApplyBefore: null,
              holidayWorkConfig: null,
              flexStartTime: null,
              flexEndTime: null,
              endTime: 960,
              directApplyStartTime: null,
              directApplyRest5StartTime: null,
              directApplyRest5EndTime: null,
              directApplyRest4StartTime: null,
              directApplyRest4EndTime: null,
              directApplyRest3StartTime: null,
              directApplyRest3EndTime: null,
              directApplyRest2StartTime: null,
              directApplyRest2EndTime: null,
              directApplyRest1StartTime: null,
              directApplyRest1EndTime: null,
              directApplyEndTime: null,
              allowToChangeApproverSelf: null,
            },
            ciliTimePeriods: [],
            ciloTimePeriods: [],
            coliTimePeriods: [],
            coloTimePeriods: [],
            remarks: '',
            isLeaveOfAbsence: false,
            insufficientRestTime: 0,
            restHours: null,
            outStartTime: null,
            outEndTime: null,
            approver01Name: '横山 翔大',
            shouldInput: true,
            canEdit: true,
            effectualLeaveRequests: [],
            hasAbsenceRequest: false,
          },
          '2019-01-09': {
            id: 'a0A6F0000118JoyUAE',
            recordDate: '2019-01-09',
            dayType: 'Workday',
            startTime: null,
            endTime: null,
            startStampTime: null,
            endStampTime: null,
            restTimes: [
              {
                startTime: null,
                endTime: null,
              },
            ],
            requestTypeCodes: [
              'Leave',
              'OvertimeWork',
              'EarlyStartWork',
              'Absence',
              'Direct',
            ],
            requestIds: [],
            contractedDetail: {
              workSystem: null,
              startTime: 660,
              rest5StartTime: null,
              rest5EndTime: null,
              rest4StartTime: null,
              rest4EndTime: null,
              rest3StartTime: null,
              rest3EndTime: null,
              rest2StartTime: null,
              rest2EndTime: null,
              rest1StartTime: null,
              rest1EndTime: null,
              requireOvertimeWorkApplyAfter: null,
              requireEarlyStartWorkApplyBefore: null,
              holidayWorkConfig: null,
              flexStartTime: null,
              flexEndTime: null,
              endTime: 960,
              directApplyStartTime: null,
              directApplyRest5StartTime: null,
              directApplyRest5EndTime: null,
              directApplyRest4StartTime: null,
              directApplyRest4EndTime: null,
              directApplyRest3StartTime: null,
              directApplyRest3EndTime: null,
              directApplyRest2StartTime: null,
              directApplyRest2EndTime: null,
              directApplyRest1StartTime: null,
              directApplyRest1EndTime: null,
              directApplyEndTime: null,
              allowToChangeApproverSelf: null,
            },
            ciliTimePeriods: [],
            ciloTimePeriods: [],
            coliTimePeriods: [],
            coloTimePeriods: [],
            remarks: '',
            isLeaveOfAbsence: false,
            insufficientRestTime: 0,
            restHours: null,
            outStartTime: null,
            outEndTime: null,
            approver01Name: '横山 翔大',
            shouldInput: true,
            canEdit: true,
            effectualLeaveRequests: [],
            hasAbsenceRequest: false,
          },
          '2019-01-10': {
            id: 'a0A6F0000118JozUAE',
            recordDate: '2019-01-10',
            dayType: 'Workday',
            startTime: null,
            endTime: null,
            startStampTime: null,
            endStampTime: null,
            restTimes: [
              {
                startTime: null,
                endTime: null,
              },
            ],
            requestTypeCodes: [
              'Leave',
              'OvertimeWork',
              'EarlyStartWork',
              'Absence',
              'Direct',
            ],
            requestIds: [],
            contractedDetail: {
              workSystem: null,
              startTime: 660,
              rest5StartTime: null,
              rest5EndTime: null,
              rest4StartTime: null,
              rest4EndTime: null,
              rest3StartTime: null,
              rest3EndTime: null,
              rest2StartTime: null,
              rest2EndTime: null,
              rest1StartTime: null,
              rest1EndTime: null,
              requireOvertimeWorkApplyAfter: null,
              requireEarlyStartWorkApplyBefore: null,
              holidayWorkConfig: null,
              flexStartTime: null,
              flexEndTime: null,
              endTime: 960,
              directApplyStartTime: null,
              directApplyRest5StartTime: null,
              directApplyRest5EndTime: null,
              directApplyRest4StartTime: null,
              directApplyRest4EndTime: null,
              directApplyRest3StartTime: null,
              directApplyRest3EndTime: null,
              directApplyRest2StartTime: null,
              directApplyRest2EndTime: null,
              directApplyRest1StartTime: null,
              directApplyRest1EndTime: null,
              directApplyEndTime: null,
              allowToChangeApproverSelf: null,
            },
            ciliTimePeriods: [],
            ciloTimePeriods: [],
            coliTimePeriods: [],
            coloTimePeriods: [],
            remarks: '',
            isLeaveOfAbsence: false,
            insufficientRestTime: 0,
            restHours: null,
            outStartTime: null,
            outEndTime: null,
            approver01Name: '横山 翔大',
            shouldInput: true,
            canEdit: true,
            effectualLeaveRequests: [],
            hasAbsenceRequest: false,
          },
          '2019-01-11': {
            id: 'a0A6F0000118Jp0UAE',
            recordDate: '2019-01-11',
            dayType: 'Workday',
            startTime: null,
            endTime: null,
            startStampTime: null,
            endStampTime: null,
            restTimes: [
              {
                startTime: null,
                endTime: null,
              },
            ],
            requestTypeCodes: [
              'Leave',
              'OvertimeWork',
              'EarlyStartWork',
              'Absence',
              'Direct',
            ],
            requestIds: [],
            contractedDetail: {
              workSystem: null,
              startTime: 660,
              rest5StartTime: null,
              rest5EndTime: null,
              rest4StartTime: null,
              rest4EndTime: null,
              rest3StartTime: null,
              rest3EndTime: null,
              rest2StartTime: null,
              rest2EndTime: null,
              rest1StartTime: null,
              rest1EndTime: null,
              requireOvertimeWorkApplyAfter: null,
              requireEarlyStartWorkApplyBefore: null,
              holidayWorkConfig: null,
              flexStartTime: null,
              flexEndTime: null,
              endTime: 960,
              directApplyStartTime: null,
              directApplyRest5StartTime: null,
              directApplyRest5EndTime: null,
              directApplyRest4StartTime: null,
              directApplyRest4EndTime: null,
              directApplyRest3StartTime: null,
              directApplyRest3EndTime: null,
              directApplyRest2StartTime: null,
              directApplyRest2EndTime: null,
              directApplyRest1StartTime: null,
              directApplyRest1EndTime: null,
              directApplyEndTime: null,
              allowToChangeApproverSelf: null,
            },
            ciliTimePeriods: [],
            ciloTimePeriods: [],
            coliTimePeriods: [],
            coloTimePeriods: [],
            remarks: '',
            isLeaveOfAbsence: false,
            insufficientRestTime: 0,
            restHours: null,
            outStartTime: null,
            outEndTime: null,
            approver01Name: '横山 翔大',
            shouldInput: true,
            canEdit: true,
            effectualLeaveRequests: [],
            hasAbsenceRequest: false,
          },
          '2019-01-12': {
            id: 'a0A6F0000118Jp1UAE',
            recordDate: '2019-01-12',
            dayType: 'Holiday',
            startTime: null,
            endTime: null,
            startStampTime: null,
            endStampTime: null,
            restTimes: [
              {
                startTime: null,
                endTime: null,
              },
            ],
            requestTypeCodes: ['HolidayWork'],
            requestIds: [],
            contractedDetail: {
              workSystem: null,
              startTime: null,
              rest5StartTime: null,
              rest5EndTime: null,
              rest4StartTime: null,
              rest4EndTime: null,
              rest3StartTime: null,
              rest3EndTime: null,
              rest2StartTime: null,
              rest2EndTime: null,
              rest1StartTime: null,
              rest1EndTime: null,
              requireOvertimeWorkApplyAfter: null,
              requireEarlyStartWorkApplyBefore: null,
              holidayWorkConfig: null,
              flexStartTime: null,
              flexEndTime: null,
              endTime: null,
              directApplyStartTime: null,
              directApplyRest5StartTime: null,
              directApplyRest5EndTime: null,
              directApplyRest4StartTime: null,
              directApplyRest4EndTime: null,
              directApplyRest3StartTime: null,
              directApplyRest3EndTime: null,
              directApplyRest2StartTime: null,
              directApplyRest2EndTime: null,
              directApplyRest1StartTime: null,
              directApplyRest1EndTime: null,
              directApplyEndTime: null,
              allowToChangeApproverSelf: null,
            },
            ciliTimePeriods: [],
            ciloTimePeriods: [],
            coliTimePeriods: [],
            coloTimePeriods: [],
            remarks: '',
            isLeaveOfAbsence: false,
            insufficientRestTime: 0,
            restHours: null,
            outStartTime: null,
            outEndTime: null,
            approver01Name: '横山 翔大',
            shouldInput: false,
            canEdit: false,
            effectualLeaveRequests: [],
            hasAbsenceRequest: false,
          },
          '2019-01-13': {
            id: 'a0A6F0000118Jp2UAE',
            recordDate: '2019-01-13',
            dayType: 'LegalHoliday',
            startTime: null,
            endTime: null,
            startStampTime: null,
            endStampTime: null,
            restTimes: [
              {
                startTime: null,
                endTime: null,
              },
            ],
            requestTypeCodes: ['HolidayWork'],
            requestIds: [],
            contractedDetail: {
              workSystem: null,
              startTime: null,
              rest5StartTime: null,
              rest5EndTime: null,
              rest4StartTime: null,
              rest4EndTime: null,
              rest3StartTime: null,
              rest3EndTime: null,
              rest2StartTime: null,
              rest2EndTime: null,
              rest1StartTime: null,
              rest1EndTime: null,
              requireOvertimeWorkApplyAfter: null,
              requireEarlyStartWorkApplyBefore: null,
              holidayWorkConfig: null,
              flexStartTime: null,
              flexEndTime: null,
              endTime: null,
              directApplyStartTime: null,
              directApplyRest5StartTime: null,
              directApplyRest5EndTime: null,
              directApplyRest4StartTime: null,
              directApplyRest4EndTime: null,
              directApplyRest3StartTime: null,
              directApplyRest3EndTime: null,
              directApplyRest2StartTime: null,
              directApplyRest2EndTime: null,
              directApplyRest1StartTime: null,
              directApplyRest1EndTime: null,
              directApplyEndTime: null,
              allowToChangeApproverSelf: null,
            },
            ciliTimePeriods: [],
            ciloTimePeriods: [],
            coliTimePeriods: [],
            coloTimePeriods: [],
            remarks: '',
            isLeaveOfAbsence: false,
            insufficientRestTime: 0,
            restHours: null,
            outStartTime: null,
            outEndTime: null,
            approver01Name: '横山 翔大',
            shouldInput: false,
            canEdit: false,
            effectualLeaveRequests: [],
            hasAbsenceRequest: false,
          },
          '2019-01-14': {
            id: 'a0A6F0000118Jp3UAE',
            recordDate: '2019-01-14',
            dayType: 'Holiday',
            startTime: null,
            endTime: null,
            startStampTime: null,
            endStampTime: null,
            restTimes: [
              {
                startTime: null,
                endTime: null,
              },
            ],
            requestTypeCodes: ['HolidayWork'],
            requestIds: [],
            contractedDetail: {
              workSystem: null,
              startTime: null,
              rest5StartTime: null,
              rest5EndTime: null,
              rest4StartTime: null,
              rest4EndTime: null,
              rest3StartTime: null,
              rest3EndTime: null,
              rest2StartTime: null,
              rest2EndTime: null,
              rest1StartTime: null,
              rest1EndTime: null,
              requireOvertimeWorkApplyAfter: null,
              requireEarlyStartWorkApplyBefore: null,
              holidayWorkConfig: null,
              flexStartTime: null,
              flexEndTime: null,
              endTime: null,
              directApplyStartTime: null,
              directApplyRest5StartTime: null,
              directApplyRest5EndTime: null,
              directApplyRest4StartTime: null,
              directApplyRest4EndTime: null,
              directApplyRest3StartTime: null,
              directApplyRest3EndTime: null,
              directApplyRest2StartTime: null,
              directApplyRest2EndTime: null,
              directApplyRest1StartTime: null,
              directApplyRest1EndTime: null,
              directApplyEndTime: null,
              allowToChangeApproverSelf: null,
            },
            ciliTimePeriods: [],
            ciloTimePeriods: [],
            coliTimePeriods: [],
            coloTimePeriods: [],
            remarks: '',
            isLeaveOfAbsence: false,
            insufficientRestTime: 0,
            restHours: null,
            outStartTime: null,
            outEndTime: null,
            approver01Name: '横山 翔大',
            shouldInput: false,
            canEdit: false,
            effectualLeaveRequests: [],
            hasAbsenceRequest: false,
          },
          '2019-01-15': {
            id: 'a0A6F0000118Jp4UAE',
            recordDate: '2019-01-15',
            dayType: 'Workday',
            startTime: null,
            endTime: null,
            startStampTime: null,
            endStampTime: null,
            restTimes: [
              {
                startTime: null,
                endTime: null,
              },
            ],
            requestTypeCodes: [
              'Leave',
              'OvertimeWork',
              'EarlyStartWork',
              'Absence',
              'Direct',
            ],
            requestIds: [],
            contractedDetail: {
              workSystem: null,
              startTime: 660,
              rest5StartTime: null,
              rest5EndTime: null,
              rest4StartTime: null,
              rest4EndTime: null,
              rest3StartTime: null,
              rest3EndTime: null,
              rest2StartTime: null,
              rest2EndTime: null,
              rest1StartTime: null,
              rest1EndTime: null,
              requireOvertimeWorkApplyAfter: null,
              requireEarlyStartWorkApplyBefore: null,
              holidayWorkConfig: null,
              flexStartTime: null,
              flexEndTime: null,
              endTime: 960,
              directApplyStartTime: null,
              directApplyRest5StartTime: null,
              directApplyRest5EndTime: null,
              directApplyRest4StartTime: null,
              directApplyRest4EndTime: null,
              directApplyRest3StartTime: null,
              directApplyRest3EndTime: null,
              directApplyRest2StartTime: null,
              directApplyRest2EndTime: null,
              directApplyRest1StartTime: null,
              directApplyRest1EndTime: null,
              directApplyEndTime: null,
              allowToChangeApproverSelf: null,
            },
            ciliTimePeriods: [],
            ciloTimePeriods: [],
            coliTimePeriods: [],
            coloTimePeriods: [],
            remarks: '',
            isLeaveOfAbsence: false,
            insufficientRestTime: 0,
            restHours: null,
            outStartTime: null,
            outEndTime: null,
            approver01Name: '横山 翔大',
            shouldInput: true,
            canEdit: true,
            effectualLeaveRequests: [],
            hasAbsenceRequest: false,
          },
          '2019-01-16': {
            id: 'a0A6F0000118Jp5UAE',
            recordDate: '2019-01-16',
            dayType: 'Workday',
            startTime: null,
            endTime: null,
            startStampTime: null,
            endStampTime: null,
            restTimes: [
              {
                startTime: null,
                endTime: null,
              },
            ],
            requestTypeCodes: [
              'Leave',
              'OvertimeWork',
              'EarlyStartWork',
              'Absence',
              'Direct',
            ],
            requestIds: [],
            contractedDetail: {
              workSystem: null,
              startTime: 660,
              rest5StartTime: null,
              rest5EndTime: null,
              rest4StartTime: null,
              rest4EndTime: null,
              rest3StartTime: null,
              rest3EndTime: null,
              rest2StartTime: null,
              rest2EndTime: null,
              rest1StartTime: null,
              rest1EndTime: null,
              requireOvertimeWorkApplyAfter: null,
              requireEarlyStartWorkApplyBefore: null,
              holidayWorkConfig: null,
              flexStartTime: null,
              flexEndTime: null,
              endTime: 960,
              directApplyStartTime: null,
              directApplyRest5StartTime: null,
              directApplyRest5EndTime: null,
              directApplyRest4StartTime: null,
              directApplyRest4EndTime: null,
              directApplyRest3StartTime: null,
              directApplyRest3EndTime: null,
              directApplyRest2StartTime: null,
              directApplyRest2EndTime: null,
              directApplyRest1StartTime: null,
              directApplyRest1EndTime: null,
              directApplyEndTime: null,
              allowToChangeApproverSelf: null,
            },
            ciliTimePeriods: [],
            ciloTimePeriods: [],
            coliTimePeriods: [],
            coloTimePeriods: [],
            remarks: '',
            isLeaveOfAbsence: false,
            insufficientRestTime: 0,
            restHours: null,
            outStartTime: null,
            outEndTime: null,
            approver01Name: '横山 翔大',
            shouldInput: true,
            canEdit: true,
            effectualLeaveRequests: [],
            hasAbsenceRequest: false,
          },
          '2019-01-17': {
            id: 'a0A6F0000118Jp6UAE',
            recordDate: '2019-01-17',
            dayType: 'Workday',
            startTime: null,
            endTime: null,
            startStampTime: null,
            endStampTime: null,
            restTimes: [
              {
                startTime: null,
                endTime: null,
              },
            ],
            requestTypeCodes: [
              'Leave',
              'OvertimeWork',
              'EarlyStartWork',
              'Absence',
              'Direct',
            ],
            requestIds: [],
            contractedDetail: {
              workSystem: null,
              startTime: 660,
              rest5StartTime: null,
              rest5EndTime: null,
              rest4StartTime: null,
              rest4EndTime: null,
              rest3StartTime: null,
              rest3EndTime: null,
              rest2StartTime: null,
              rest2EndTime: null,
              rest1StartTime: null,
              rest1EndTime: null,
              requireOvertimeWorkApplyAfter: null,
              requireEarlyStartWorkApplyBefore: null,
              holidayWorkConfig: null,
              flexStartTime: null,
              flexEndTime: null,
              endTime: 960,
              directApplyStartTime: null,
              directApplyRest5StartTime: null,
              directApplyRest5EndTime: null,
              directApplyRest4StartTime: null,
              directApplyRest4EndTime: null,
              directApplyRest3StartTime: null,
              directApplyRest3EndTime: null,
              directApplyRest2StartTime: null,
              directApplyRest2EndTime: null,
              directApplyRest1StartTime: null,
              directApplyRest1EndTime: null,
              directApplyEndTime: null,
              allowToChangeApproverSelf: null,
            },
            ciliTimePeriods: [],
            ciloTimePeriods: [],
            coliTimePeriods: [],
            coloTimePeriods: [],
            remarks: '',
            isLeaveOfAbsence: false,
            insufficientRestTime: 0,
            restHours: null,
            outStartTime: null,
            outEndTime: null,
            approver01Name: '横山 翔大',
            shouldInput: true,
            canEdit: true,
            effectualLeaveRequests: [],
            hasAbsenceRequest: false,
          },
          '2019-01-18': {
            id: 'a0A6F0000118Jp7UAE',
            recordDate: '2019-01-18',
            dayType: 'Workday',
            startTime: null,
            endTime: null,
            startStampTime: null,
            endStampTime: null,
            restTimes: [
              {
                startTime: null,
                endTime: null,
              },
            ],
            requestTypeCodes: [
              'Leave',
              'OvertimeWork',
              'EarlyStartWork',
              'Absence',
              'Direct',
            ],
            requestIds: [],
            contractedDetail: {
              workSystem: null,
              startTime: 660,
              rest5StartTime: null,
              rest5EndTime: null,
              rest4StartTime: null,
              rest4EndTime: null,
              rest3StartTime: null,
              rest3EndTime: null,
              rest2StartTime: null,
              rest2EndTime: null,
              rest1StartTime: null,
              rest1EndTime: null,
              requireOvertimeWorkApplyAfter: null,
              requireEarlyStartWorkApplyBefore: null,
              holidayWorkConfig: null,
              flexStartTime: null,
              flexEndTime: null,
              endTime: 960,
              directApplyStartTime: null,
              directApplyRest5StartTime: null,
              directApplyRest5EndTime: null,
              directApplyRest4StartTime: null,
              directApplyRest4EndTime: null,
              directApplyRest3StartTime: null,
              directApplyRest3EndTime: null,
              directApplyRest2StartTime: null,
              directApplyRest2EndTime: null,
              directApplyRest1StartTime: null,
              directApplyRest1EndTime: null,
              directApplyEndTime: null,
              allowToChangeApproverSelf: null,
            },
            ciliTimePeriods: [],
            ciloTimePeriods: [],
            coliTimePeriods: [],
            coloTimePeriods: [],
            remarks: '',
            isLeaveOfAbsence: false,
            insufficientRestTime: 0,
            restHours: null,
            outStartTime: null,
            outEndTime: null,
            approver01Name: '横山 翔大',
            shouldInput: true,
            canEdit: true,
            effectualLeaveRequests: [],
            hasAbsenceRequest: false,
          },
          '2019-01-19': {
            id: 'a0A6F0000118Jp8UAE',
            recordDate: '2019-01-19',
            dayType: 'Holiday',
            startTime: null,
            endTime: null,
            startStampTime: null,
            endStampTime: null,
            restTimes: [
              {
                startTime: null,
                endTime: null,
              },
            ],
            requestTypeCodes: ['HolidayWork'],
            requestIds: [],
            contractedDetail: {
              workSystem: null,
              startTime: null,
              rest5StartTime: null,
              rest5EndTime: null,
              rest4StartTime: null,
              rest4EndTime: null,
              rest3StartTime: null,
              rest3EndTime: null,
              rest2StartTime: null,
              rest2EndTime: null,
              rest1StartTime: null,
              rest1EndTime: null,
              requireOvertimeWorkApplyAfter: null,
              requireEarlyStartWorkApplyBefore: null,
              holidayWorkConfig: null,
              flexStartTime: null,
              flexEndTime: null,
              endTime: null,
              directApplyStartTime: null,
              directApplyRest5StartTime: null,
              directApplyRest5EndTime: null,
              directApplyRest4StartTime: null,
              directApplyRest4EndTime: null,
              directApplyRest3StartTime: null,
              directApplyRest3EndTime: null,
              directApplyRest2StartTime: null,
              directApplyRest2EndTime: null,
              directApplyRest1StartTime: null,
              directApplyRest1EndTime: null,
              directApplyEndTime: null,
              allowToChangeApproverSelf: null,
            },
            ciliTimePeriods: [],
            ciloTimePeriods: [],
            coliTimePeriods: [],
            coloTimePeriods: [],
            remarks: '',
            isLeaveOfAbsence: false,
            insufficientRestTime: 0,
            restHours: null,
            outStartTime: null,
            outEndTime: null,
            approver01Name: '横山 翔大',
            shouldInput: false,
            canEdit: false,
            effectualLeaveRequests: [],
            hasAbsenceRequest: false,
          },
          '2019-01-20': {
            id: 'a0A6F0000118Jp9UAE',
            recordDate: '2019-01-20',
            dayType: 'LegalHoliday',
            startTime: null,
            endTime: null,
            startStampTime: null,
            endStampTime: null,
            restTimes: [
              {
                startTime: null,
                endTime: null,
              },
            ],
            requestTypeCodes: ['HolidayWork'],
            requestIds: [],
            contractedDetail: {
              workSystem: null,
              startTime: null,
              rest5StartTime: null,
              rest5EndTime: null,
              rest4StartTime: null,
              rest4EndTime: null,
              rest3StartTime: null,
              rest3EndTime: null,
              rest2StartTime: null,
              rest2EndTime: null,
              rest1StartTime: null,
              rest1EndTime: null,
              requireOvertimeWorkApplyAfter: null,
              requireEarlyStartWorkApplyBefore: null,
              holidayWorkConfig: null,
              flexStartTime: null,
              flexEndTime: null,
              endTime: null,
              directApplyStartTime: null,
              directApplyRest5StartTime: null,
              directApplyRest5EndTime: null,
              directApplyRest4StartTime: null,
              directApplyRest4EndTime: null,
              directApplyRest3StartTime: null,
              directApplyRest3EndTime: null,
              directApplyRest2StartTime: null,
              directApplyRest2EndTime: null,
              directApplyRest1StartTime: null,
              directApplyRest1EndTime: null,
              directApplyEndTime: null,
              allowToChangeApproverSelf: null,
            },
            ciliTimePeriods: [],
            ciloTimePeriods: [],
            coliTimePeriods: [],
            coloTimePeriods: [],
            remarks: '',
            isLeaveOfAbsence: false,
            insufficientRestTime: 0,
            restHours: null,
            outStartTime: null,
            outEndTime: null,
            approver01Name: '横山 翔大',
            shouldInput: false,
            canEdit: false,
            effectualLeaveRequests: [],
            hasAbsenceRequest: false,
          },
          '2019-01-21': {
            id: 'a0A6F0000118JpAUAU',
            recordDate: '2019-01-21',
            dayType: 'Workday',
            startTime: null,
            endTime: null,
            startStampTime: null,
            endStampTime: null,
            restTimes: [
              {
                startTime: null,
                endTime: null,
              },
            ],
            requestTypeCodes: [
              'Leave',
              'OvertimeWork',
              'EarlyStartWork',
              'Absence',
              'Direct',
            ],
            requestIds: [],
            contractedDetail: {
              workSystem: null,
              startTime: 660,
              rest5StartTime: null,
              rest5EndTime: null,
              rest4StartTime: null,
              rest4EndTime: null,
              rest3StartTime: null,
              rest3EndTime: null,
              rest2StartTime: null,
              rest2EndTime: null,
              rest1StartTime: null,
              rest1EndTime: null,
              requireOvertimeWorkApplyAfter: null,
              requireEarlyStartWorkApplyBefore: null,
              holidayWorkConfig: null,
              flexStartTime: null,
              flexEndTime: null,
              endTime: 960,
              directApplyStartTime: null,
              directApplyRest5StartTime: null,
              directApplyRest5EndTime: null,
              directApplyRest4StartTime: null,
              directApplyRest4EndTime: null,
              directApplyRest3StartTime: null,
              directApplyRest3EndTime: null,
              directApplyRest2StartTime: null,
              directApplyRest2EndTime: null,
              directApplyRest1StartTime: null,
              directApplyRest1EndTime: null,
              directApplyEndTime: null,
              allowToChangeApproverSelf: null,
            },
            ciliTimePeriods: [],
            ciloTimePeriods: [],
            coliTimePeriods: [],
            coloTimePeriods: [],
            remarks: '',
            isLeaveOfAbsence: false,
            insufficientRestTime: 0,
            restHours: null,
            outStartTime: null,
            outEndTime: null,
            approver01Name: '横山 翔大',
            shouldInput: true,
            canEdit: true,
            effectualLeaveRequests: [],
            hasAbsenceRequest: false,
          },
          '2019-01-22': {
            id: 'a0A6F0000118JpBUAU',
            recordDate: '2019-01-22',
            dayType: 'Workday',
            startTime: null,
            endTime: null,
            startStampTime: null,
            endStampTime: null,
            restTimes: [
              {
                startTime: null,
                endTime: null,
              },
            ],
            requestTypeCodes: [
              'Leave',
              'OvertimeWork',
              'EarlyStartWork',
              'Absence',
              'Direct',
            ],
            requestIds: [],
            contractedDetail: {
              workSystem: null,
              startTime: 660,
              rest5StartTime: null,
              rest5EndTime: null,
              rest4StartTime: null,
              rest4EndTime: null,
              rest3StartTime: null,
              rest3EndTime: null,
              rest2StartTime: null,
              rest2EndTime: null,
              rest1StartTime: null,
              rest1EndTime: null,
              requireOvertimeWorkApplyAfter: null,
              requireEarlyStartWorkApplyBefore: null,
              holidayWorkConfig: null,
              flexStartTime: null,
              flexEndTime: null,
              endTime: 960,
              directApplyStartTime: null,
              directApplyRest5StartTime: null,
              directApplyRest5EndTime: null,
              directApplyRest4StartTime: null,
              directApplyRest4EndTime: null,
              directApplyRest3StartTime: null,
              directApplyRest3EndTime: null,
              directApplyRest2StartTime: null,
              directApplyRest2EndTime: null,
              directApplyRest1StartTime: null,
              directApplyRest1EndTime: null,
              directApplyEndTime: null,
              allowToChangeApproverSelf: null,
            },
            ciliTimePeriods: [],
            ciloTimePeriods: [],
            coliTimePeriods: [],
            coloTimePeriods: [],
            remarks: '',
            isLeaveOfAbsence: false,
            insufficientRestTime: 0,
            restHours: null,
            outStartTime: null,
            outEndTime: null,
            approver01Name: '横山 翔大',
            shouldInput: true,
            canEdit: true,
            effectualLeaveRequests: [],
            hasAbsenceRequest: false,
          },
          '2019-01-23': {
            id: 'a0A6F0000118JpCUAU',
            recordDate: '2019-01-23',
            dayType: 'Workday',
            startTime: null,
            endTime: null,
            startStampTime: null,
            endStampTime: null,
            restTimes: [
              {
                startTime: null,
                endTime: null,
              },
            ],
            requestTypeCodes: [
              'Leave',
              'OvertimeWork',
              'EarlyStartWork',
              'Absence',
              'Direct',
            ],
            requestIds: [],
            contractedDetail: {
              workSystem: null,
              startTime: 660,
              rest5StartTime: null,
              rest5EndTime: null,
              rest4StartTime: null,
              rest4EndTime: null,
              rest3StartTime: null,
              rest3EndTime: null,
              rest2StartTime: null,
              rest2EndTime: null,
              rest1StartTime: null,
              rest1EndTime: null,
              requireOvertimeWorkApplyAfter: null,
              requireEarlyStartWorkApplyBefore: null,
              holidayWorkConfig: null,
              flexStartTime: null,
              flexEndTime: null,
              endTime: 960,
              directApplyStartTime: null,
              directApplyRest5StartTime: null,
              directApplyRest5EndTime: null,
              directApplyRest4StartTime: null,
              directApplyRest4EndTime: null,
              directApplyRest3StartTime: null,
              directApplyRest3EndTime: null,
              directApplyRest2StartTime: null,
              directApplyRest2EndTime: null,
              directApplyRest1StartTime: null,
              directApplyRest1EndTime: null,
              directApplyEndTime: null,
              allowToChangeApproverSelf: null,
            },
            ciliTimePeriods: [],
            ciloTimePeriods: [],
            coliTimePeriods: [],
            coloTimePeriods: [],
            remarks: '',
            isLeaveOfAbsence: false,
            insufficientRestTime: 0,
            restHours: null,
            outStartTime: null,
            outEndTime: null,
            approver01Name: '横山 翔大',
            shouldInput: true,
            canEdit: true,
            effectualLeaveRequests: [],
            hasAbsenceRequest: false,
          },
          '2019-01-24': {
            id: 'a0A6F0000118JpDUAU',
            recordDate: '2019-01-24',
            dayType: 'Workday',
            startTime: null,
            endTime: null,
            startStampTime: null,
            endStampTime: null,
            restTimes: [
              {
                startTime: null,
                endTime: null,
              },
            ],
            requestTypeCodes: [
              'Leave',
              'OvertimeWork',
              'EarlyStartWork',
              'Absence',
              'Direct',
            ],
            requestIds: [],
            contractedDetail: {
              workSystem: null,
              startTime: 660,
              rest5StartTime: null,
              rest5EndTime: null,
              rest4StartTime: null,
              rest4EndTime: null,
              rest3StartTime: null,
              rest3EndTime: null,
              rest2StartTime: null,
              rest2EndTime: null,
              rest1StartTime: null,
              rest1EndTime: null,
              requireOvertimeWorkApplyAfter: null,
              requireEarlyStartWorkApplyBefore: null,
              holidayWorkConfig: null,
              flexStartTime: null,
              flexEndTime: null,
              endTime: 960,
              directApplyStartTime: null,
              directApplyRest5StartTime: null,
              directApplyRest5EndTime: null,
              directApplyRest4StartTime: null,
              directApplyRest4EndTime: null,
              directApplyRest3StartTime: null,
              directApplyRest3EndTime: null,
              directApplyRest2StartTime: null,
              directApplyRest2EndTime: null,
              directApplyRest1StartTime: null,
              directApplyRest1EndTime: null,
              directApplyEndTime: null,
              allowToChangeApproverSelf: null,
            },
            ciliTimePeriods: [],
            ciloTimePeriods: [],
            coliTimePeriods: [],
            coloTimePeriods: [],
            remarks: '',
            isLeaveOfAbsence: false,
            insufficientRestTime: 0,
            restHours: null,
            outStartTime: null,
            outEndTime: null,
            approver01Name: '横山 翔大',
            shouldInput: true,
            canEdit: true,
            effectualLeaveRequests: [],
            hasAbsenceRequest: false,
          },
          '2019-01-25': {
            id: 'a0A6F0000118JpEUAU',
            recordDate: '2019-01-25',
            dayType: 'Workday',
            startTime: null,
            endTime: null,
            startStampTime: null,
            endStampTime: null,
            restTimes: [
              {
                startTime: null,
                endTime: null,
              },
            ],
            requestTypeCodes: [
              'Leave',
              'OvertimeWork',
              'EarlyStartWork',
              'Absence',
              'Direct',
            ],
            requestIds: [],
            contractedDetail: {
              workSystem: null,
              startTime: 660,
              rest5StartTime: null,
              rest5EndTime: null,
              rest4StartTime: null,
              rest4EndTime: null,
              rest3StartTime: null,
              rest3EndTime: null,
              rest2StartTime: null,
              rest2EndTime: null,
              rest1StartTime: null,
              rest1EndTime: null,
              requireOvertimeWorkApplyAfter: null,
              requireEarlyStartWorkApplyBefore: null,
              holidayWorkConfig: null,
              flexStartTime: null,
              flexEndTime: null,
              endTime: 960,
              directApplyStartTime: null,
              directApplyRest5StartTime: null,
              directApplyRest5EndTime: null,
              directApplyRest4StartTime: null,
              directApplyRest4EndTime: null,
              directApplyRest3StartTime: null,
              directApplyRest3EndTime: null,
              directApplyRest2StartTime: null,
              directApplyRest2EndTime: null,
              directApplyRest1StartTime: null,
              directApplyRest1EndTime: null,
              directApplyEndTime: null,
              allowToChangeApproverSelf: null,
            },
            ciliTimePeriods: [],
            ciloTimePeriods: [],
            coliTimePeriods: [],
            coloTimePeriods: [],
            remarks: '',
            isLeaveOfAbsence: false,
            insufficientRestTime: 0,
            restHours: null,
            outStartTime: null,
            outEndTime: null,
            approver01Name: '横山 翔大',
            shouldInput: true,
            canEdit: true,
            effectualLeaveRequests: [],
            hasAbsenceRequest: false,
          },
          '2019-01-26': {
            id: 'a0A6F0000118JpFUAU',
            recordDate: '2019-01-26',
            dayType: 'Holiday',
            startTime: null,
            endTime: null,
            startStampTime: null,
            endStampTime: null,
            restTimes: [
              {
                startTime: null,
                endTime: null,
              },
            ],
            requestTypeCodes: ['HolidayWork'],
            requestIds: [],
            contractedDetail: {
              workSystem: null,
              startTime: null,
              rest5StartTime: null,
              rest5EndTime: null,
              rest4StartTime: null,
              rest4EndTime: null,
              rest3StartTime: null,
              rest3EndTime: null,
              rest2StartTime: null,
              rest2EndTime: null,
              rest1StartTime: null,
              rest1EndTime: null,
              requireOvertimeWorkApplyAfter: null,
              requireEarlyStartWorkApplyBefore: null,
              holidayWorkConfig: null,
              flexStartTime: null,
              flexEndTime: null,
              endTime: null,
              directApplyStartTime: null,
              directApplyRest5StartTime: null,
              directApplyRest5EndTime: null,
              directApplyRest4StartTime: null,
              directApplyRest4EndTime: null,
              directApplyRest3StartTime: null,
              directApplyRest3EndTime: null,
              directApplyRest2StartTime: null,
              directApplyRest2EndTime: null,
              directApplyRest1StartTime: null,
              directApplyRest1EndTime: null,
              directApplyEndTime: null,
              allowToChangeApproverSelf: null,
            },
            ciliTimePeriods: [],
            ciloTimePeriods: [],
            coliTimePeriods: [],
            coloTimePeriods: [],
            remarks: '',
            isLeaveOfAbsence: false,
            insufficientRestTime: 0,
            restHours: null,
            outStartTime: null,
            outEndTime: null,
            approver01Name: '横山 翔大',
            shouldInput: false,
            canEdit: false,
            effectualLeaveRequests: [],
            hasAbsenceRequest: false,
          },
          '2019-01-27': {
            id: 'a0A6F0000118JpGUAU',
            recordDate: '2019-01-27',
            dayType: 'LegalHoliday',
            startTime: null,
            endTime: null,
            startStampTime: null,
            endStampTime: null,
            restTimes: [
              {
                startTime: null,
                endTime: null,
              },
            ],
            requestTypeCodes: ['HolidayWork'],
            requestIds: [],
            contractedDetail: {
              workSystem: null,
              startTime: null,
              rest5StartTime: null,
              rest5EndTime: null,
              rest4StartTime: null,
              rest4EndTime: null,
              rest3StartTime: null,
              rest3EndTime: null,
              rest2StartTime: null,
              rest2EndTime: null,
              rest1StartTime: null,
              rest1EndTime: null,
              requireOvertimeWorkApplyAfter: null,
              requireEarlyStartWorkApplyBefore: null,
              holidayWorkConfig: null,
              flexStartTime: null,
              flexEndTime: null,
              endTime: null,
              directApplyStartTime: null,
              directApplyRest5StartTime: null,
              directApplyRest5EndTime: null,
              directApplyRest4StartTime: null,
              directApplyRest4EndTime: null,
              directApplyRest3StartTime: null,
              directApplyRest3EndTime: null,
              directApplyRest2StartTime: null,
              directApplyRest2EndTime: null,
              directApplyRest1StartTime: null,
              directApplyRest1EndTime: null,
              directApplyEndTime: null,
              allowToChangeApproverSelf: null,
            },
            ciliTimePeriods: [],
            ciloTimePeriods: [],
            coliTimePeriods: [],
            coloTimePeriods: [],
            remarks: '',
            isLeaveOfAbsence: false,
            insufficientRestTime: 0,
            restHours: null,
            outStartTime: null,
            outEndTime: null,
            approver01Name: '横山 翔大',
            shouldInput: false,
            canEdit: false,
            effectualLeaveRequests: [],
            hasAbsenceRequest: false,
          },
          '2019-01-28': {
            id: 'a0A6F0000118JpHUAU',
            recordDate: '2019-01-28',
            dayType: 'Workday',
            startTime: null,
            endTime: null,
            startStampTime: null,
            endStampTime: null,
            restTimes: [
              {
                startTime: null,
                endTime: null,
              },
            ],
            requestTypeCodes: [
              'Leave',
              'OvertimeWork',
              'EarlyStartWork',
              'Absence',
              'Direct',
            ],
            requestIds: [],
            contractedDetail: {
              workSystem: null,
              startTime: 660,
              rest5StartTime: null,
              rest5EndTime: null,
              rest4StartTime: null,
              rest4EndTime: null,
              rest3StartTime: null,
              rest3EndTime: null,
              rest2StartTime: null,
              rest2EndTime: null,
              rest1StartTime: null,
              rest1EndTime: null,
              requireOvertimeWorkApplyAfter: null,
              requireEarlyStartWorkApplyBefore: null,
              holidayWorkConfig: null,
              flexStartTime: null,
              flexEndTime: null,
              endTime: 960,
              directApplyStartTime: null,
              directApplyRest5StartTime: null,
              directApplyRest5EndTime: null,
              directApplyRest4StartTime: null,
              directApplyRest4EndTime: null,
              directApplyRest3StartTime: null,
              directApplyRest3EndTime: null,
              directApplyRest2StartTime: null,
              directApplyRest2EndTime: null,
              directApplyRest1StartTime: null,
              directApplyRest1EndTime: null,
              directApplyEndTime: null,
              allowToChangeApproverSelf: null,
            },
            ciliTimePeriods: [],
            ciloTimePeriods: [],
            coliTimePeriods: [],
            coloTimePeriods: [],
            remarks: '',
            isLeaveOfAbsence: false,
            insufficientRestTime: 0,
            restHours: null,
            outStartTime: null,
            outEndTime: null,
            approver01Name: '横山 翔大',
            shouldInput: true,
            canEdit: true,
            effectualLeaveRequests: [],
            hasAbsenceRequest: false,
          },
          '2019-01-29': {
            id: 'a0A6F0000118JpIUAU',
            recordDate: '2019-01-29',
            dayType: 'Workday',
            startTime: null,
            endTime: null,
            startStampTime: null,
            endStampTime: null,
            restTimes: [
              {
                startTime: null,
                endTime: null,
              },
            ],
            requestTypeCodes: [
              'Leave',
              'OvertimeWork',
              'EarlyStartWork',
              'Absence',
              'Direct',
            ],
            requestIds: [],
            contractedDetail: {
              workSystem: null,
              startTime: 660,
              rest5StartTime: null,
              rest5EndTime: null,
              rest4StartTime: null,
              rest4EndTime: null,
              rest3StartTime: null,
              rest3EndTime: null,
              rest2StartTime: null,
              rest2EndTime: null,
              rest1StartTime: null,
              rest1EndTime: null,
              requireOvertimeWorkApplyAfter: null,
              requireEarlyStartWorkApplyBefore: null,
              holidayWorkConfig: null,
              flexStartTime: null,
              flexEndTime: null,
              endTime: 960,
              directApplyStartTime: null,
              directApplyRest5StartTime: null,
              directApplyRest5EndTime: null,
              directApplyRest4StartTime: null,
              directApplyRest4EndTime: null,
              directApplyRest3StartTime: null,
              directApplyRest3EndTime: null,
              directApplyRest2StartTime: null,
              directApplyRest2EndTime: null,
              directApplyRest1StartTime: null,
              directApplyRest1EndTime: null,
              directApplyEndTime: null,
              allowToChangeApproverSelf: null,
            },
            ciliTimePeriods: [],
            ciloTimePeriods: [],
            coliTimePeriods: [],
            coloTimePeriods: [],
            remarks: '',
            isLeaveOfAbsence: false,
            insufficientRestTime: 0,
            restHours: null,
            outStartTime: null,
            outEndTime: null,
            approver01Name: '横山 翔大',
            shouldInput: true,
            canEdit: true,
            effectualLeaveRequests: [],
            hasAbsenceRequest: false,
          },
          '2019-01-30': {
            id: 'a0A6F0000118JpJUAU',
            recordDate: '2019-01-30',
            dayType: 'Workday',
            startTime: null,
            endTime: null,
            startStampTime: null,
            endStampTime: null,
            restTimes: [
              {
                startTime: null,
                endTime: null,
              },
            ],
            requestTypeCodes: [
              'Leave',
              'OvertimeWork',
              'EarlyStartWork',
              'Absence',
              'Direct',
            ],
            requestIds: [],
            contractedDetail: {
              workSystem: null,
              startTime: 660,
              rest5StartTime: null,
              rest5EndTime: null,
              rest4StartTime: null,
              rest4EndTime: null,
              rest3StartTime: null,
              rest3EndTime: null,
              rest2StartTime: null,
              rest2EndTime: null,
              rest1StartTime: null,
              rest1EndTime: null,
              requireOvertimeWorkApplyAfter: null,
              requireEarlyStartWorkApplyBefore: null,
              holidayWorkConfig: null,
              flexStartTime: null,
              flexEndTime: null,
              endTime: 960,
              directApplyStartTime: null,
              directApplyRest5StartTime: null,
              directApplyRest5EndTime: null,
              directApplyRest4StartTime: null,
              directApplyRest4EndTime: null,
              directApplyRest3StartTime: null,
              directApplyRest3EndTime: null,
              directApplyRest2StartTime: null,
              directApplyRest2EndTime: null,
              directApplyRest1StartTime: null,
              directApplyRest1EndTime: null,
              directApplyEndTime: null,
              allowToChangeApproverSelf: null,
            },
            ciliTimePeriods: [],
            ciloTimePeriods: [],
            coliTimePeriods: [],
            coloTimePeriods: [],
            remarks: '',
            isLeaveOfAbsence: false,
            insufficientRestTime: 0,
            restHours: null,
            outStartTime: null,
            outEndTime: null,
            approver01Name: '横山 翔大',
            shouldInput: true,
            canEdit: true,
            effectualLeaveRequests: [],
            hasAbsenceRequest: false,
          },
          '2019-01-31': {
            id: 'a0A6F0000118JpKUAU',
            recordDate: '2019-01-31',
            dayType: 'Workday',
            startTime: null,
            endTime: null,
            startStampTime: null,
            endStampTime: null,
            restTimes: [
              {
                startTime: null,
                endTime: null,
              },
            ],
            requestTypeCodes: [
              'Leave',
              'OvertimeWork',
              'EarlyStartWork',
              'Absence',
              'Direct',
            ],
            requestIds: [],
            contractedDetail: {
              workSystem: null,
              startTime: 660,
              rest5StartTime: null,
              rest5EndTime: null,
              rest4StartTime: null,
              rest4EndTime: null,
              rest3StartTime: null,
              rest3EndTime: null,
              rest2StartTime: null,
              rest2EndTime: null,
              rest1StartTime: null,
              rest1EndTime: null,
              requireOvertimeWorkApplyAfter: null,
              requireEarlyStartWorkApplyBefore: null,
              holidayWorkConfig: null,
              flexStartTime: null,
              flexEndTime: null,
              endTime: 960,
              directApplyStartTime: null,
              directApplyRest5StartTime: null,
              directApplyRest5EndTime: null,
              directApplyRest4StartTime: null,
              directApplyRest4EndTime: null,
              directApplyRest3StartTime: null,
              directApplyRest3EndTime: null,
              directApplyRest2StartTime: null,
              directApplyRest2EndTime: null,
              directApplyRest1StartTime: null,
              directApplyRest1EndTime: null,
              directApplyEndTime: null,
              allowToChangeApproverSelf: null,
            },
            ciliTimePeriods: [],
            ciloTimePeriods: [],
            coliTimePeriods: [],
            coloTimePeriods: [],
            remarks: '',
            isLeaveOfAbsence: false,
            insufficientRestTime: 0,
            restHours: null,
            outStartTime: null,
            outEndTime: null,
            approver01Name: '横山 翔大',
            shouldInput: true,
            canEdit: true,
            effectualLeaveRequests: [],
            hasAbsenceRequest: false,
          },
        },
        periods: [
          {
            startDate: '2019-03-01',
            name: '2019年03月',
            endDate: '2019-03-31',
          },
          {
            startDate: '2019-02-01',
            name: '2019年02月',
            endDate: '2019-02-28',
          },
          {
            startDate: '2019-01-01',
            name: '2019年01月',
            endDate: '2019-01-31',
          },
          {
            startDate: '2018-12-01',
            name: '2018年12月',
            endDate: '2018-12-31',
          },
          {
            startDate: '2018-11-01',
            name: '2018年11月',
            endDate: '2018-11-30',
          },
          {
            startDate: '2018-10-01',
            name: '2018年10月',
            endDate: '2018-10-31',
          },
          {
            startDate: '2018-09-01',
            name: '2018年09月',
            endDate: '2018-09-30',
          },
          {
            startDate: '2018-08-01',
            name: '2018年08月',
            endDate: '2018-08-31',
          },
          {
            startDate: '2018-07-01',
            name: '2018年07月',
            endDate: '2018-07-31',
          },
          {
            startDate: '2018-06-18',
            name: '2018年06月',
            endDate: '2018-06-30',
          },
        ],
        requestTypes: {
          Direct: {
            name: '直行直帰',
            code: 'Direct',
          },
          Absence: {
            name: '欠勤',
            code: 'Absence',
          },
          OvertimeWork: {
            name: '残業',
            code: 'OvertimeWork',
          },
          EarlyStartWork: {
            name: '早朝勤務',
            code: 'EarlyStartWork',
          },
          HolidayWork: {
            name: '休日出勤',
            code: 'HolidayWork',
          },
          Leave: {
            name: '休暇',
            code: 'Leave',
          },
        },
        requestAllIds: [],
        requestsById: {},
        employeeName: '横山 翔大',
        departmentName: 'ながーーーーーーーーーーーーーーーーーーーい部署',
        workingTypeName: '動作確認用',
        startDate: '2019-01-01',
        endDate: '2019-01-31',
        requestId: null,
        status: 'NotRequested',
        approver01Name: null,
        isLocked: false,
        workingType: {
          workSystem: 'JP:Flex',
          startTime: 660,
          rest5StartTime: null,
          rest5EndTime: null,
          rest4StartTime: null,
          rest4EndTime: null,
          rest3StartTime: null,
          rest3EndTime: null,
          rest2StartTime: null,
          rest2EndTime: null,
          rest1StartTime: null,
          rest1EndTime: null,
          requireOvertimeWorkApplyAfter: null,
          requireEarlyStartWorkApplyBefore: null,
          holidayWorkConfig: {
            substituteLeaveTypeList: ['Substitute'],
          },
          flexStartTime: 420,
          flexEndTime: 1320,
          endTime: 960,
          directApplyStartTime: 540,
          directApplyRest5StartTime: null,
          directApplyRest5EndTime: null,
          directApplyRest4StartTime: null,
          directApplyRest4EndTime: null,
          directApplyRest3StartTime: null,
          directApplyRest3EndTime: null,
          directApplyRest2StartTime: null,
          directApplyRest2EndTime: null,
          directApplyRest1StartTime: 720,
          directApplyRest1EndTime: 780,
          directApplyEndTime: 1140,
          allowToChangeApproverSelf: true,
        },
        isAllAbsent: false,
      },
    },
    timeStamp: {
      entities: {
        dailyStampTime: {
          isEnableStartStamp: true,
          isEnableEndStamp: true,
          isEnableRestartStamp: false,
          defaultAction: 'in',
        },
        location: {
          latitude: null,
          longitude: null,
          accuracy: null,
          fetchTime: null,
          fetchStatus: 'None',
          watchPositionID: null,
        },
      },
      ui: {
        willSendLocation: false,
        message: '',
      },
    },
  },
  approval: {
    entities: {
      list: [],
      expense: {
        report: null,
      },
    },
  },
  expense: {
    entities: {
      reportList: [],
      taxType: [],
      expenseTypeList: [],
      recordList: [],
      recordItem: null,
      routeResults: {
        route: {
          routeNumber: 0,
          routeList: [],
        },
        commuter: {
          routeNumber: 0,
          routeList: [],
        },
      },
      report: {
        subject: '',
        accountingDate: '2019-01-10',
        accountingPeriodId: null,
        totalAmount: 0,
        jobId: null,
        jobName: '',
        costCenterHistoryId: null,
        costCenterName: '',
        remarks: '',
        records: [],
        expReportTypeId: null,
        extendedItemText01Id: null,
        extendedItemText01Value: null,
        extendedItemText01Info: null,
        extendedItemText02Id: null,
        extendedItemText02Value: null,
        extendedItemText02Info: null,
        extendedItemText03Id: null,
        extendedItemText03Value: null,
        extendedItemText03Info: null,
        extendedItemText04Id: null,
        extendedItemText04Value: null,
        extendedItemText04Info: null,
        extendedItemText05Id: null,
        extendedItemText05Value: null,
        extendedItemText05Info: null,
        extendedItemText06Id: null,
        extendedItemText06Value: null,
        extendedItemText06Info: null,
        extendedItemText07Id: null,
        extendedItemText07Value: null,
        extendedItemText07Info: null,
        extendedItemText08Id: null,
        extendedItemText08Value: null,
        extendedItemText08Info: null,
        extendedItemText09Id: null,
        extendedItemText09Value: null,
        extendedItemText09Info: null,
        extendedItemText10Id: null,
        extendedItemText10Value: null,
        extendedItemText10Info: null,
        extendedItemPicklist01Id: null,
        extendedItemPicklist01Value: null,
        extendedItemPicklist01Info: null,
        extendedItemPicklist02Id: null,
        extendedItemPicklist02Value: null,
        extendedItemPicklist02Info: null,
        extendedItemPicklist03Id: null,
        extendedItemPicklist03Value: null,
        extendedItemPicklist03Info: null,
        extendedItemPicklist04Id: null,
        extendedItemPicklist04Value: null,
        extendedItemPicklist04Info: null,
        extendedItemPicklist05Id: null,
        extendedItemPicklist05Value: null,
        extendedItemPicklist05Info: null,
        extendedItemPicklist06Id: null,
        extendedItemPicklist06Value: null,
        extendedItemPicklist06Info: null,
        extendedItemPicklist07Id: null,
        extendedItemPicklist07Value: null,
        extendedItemPicklist07Info: null,
        extendedItemPicklist08Id: null,
        extendedItemPicklist08Value: null,
        extendedItemPicklist08Info: null,
        extendedItemPicklist09Id: null,
        extendedItemPicklist09Value: null,
        extendedItemPicklist09Info: null,
        extendedItemPicklist10Id: null,
        extendedItemPicklist10Value: null,
        extendedItemPicklist10Info: null,
      },
      accountingPeriod: [],
      costCenterList: [],
      costCenterAllList: [],
      expReportType: [],
      job: [],
      jobAll: [],
    },
    ui: {
      general: {
        formValues: {},
        rate: 0,
        isShowDialog: false,
        readOnly: true,
      },
      report: {
        formValues: {},
      },
      record: {
        list: {
          select: {
            selectedIds: [],
            flagsById: {},
          },
        },
      },
    },
    pages: {
      routeFormPage: {},
      defaultRouteOptions: {
        jorudanAreaPreference: null,
        jorudanChargedExpressDistance: null,
        jorudanCommuterPass: null,
        jorudanFareType: '0',
        jorudanHighwayBus: '0',
        jorudanRouteSort: '0',
        jorudanSeatPreference: '0',
        jorudanUseChargedExpress: '0',
      },
    },
  },
  mobileCommons: {
    error: {},
    loading: {},
  },
  tracking: {
    entity: {
      dailyTask: {
        targetDate: '',
        status: 'NotRequested',
        note: null,
        output: null,
        realWorkTime: null,
        isTemporaryWorkTime: false,
        taskList: [],
      },
      job: [],
    },
    ui: {
      dailyTask: {
        isEditing: false,
        dailyTask: null,
      },
      dailyTaskJob: {
        jobId: null,
        workCategoryId: null,
        taskTime: '00:00',
      },
    },
  },
  personalSetting: {
    plannerDefaultView: 'Weekly',
  },
});
