export default {
  common: {
    app: {
      loadingDepth: 0,
      error: null,
      unexpectedError: null,
      confirmDialog: null,
    },
    accessControl: {
      permission: {
        approveAttDailyRequestByDelegate: true,
        approveAttRequestByDelegate: true,
        approveSelfAttDailyRequestByEmployee: true,
        approveSelfAttRequestByEmployee: true,
        cancelAttApprovalByDelegate: true,
        cancelAttApprovalByEmployee: true,
        cancelAttDailyApprovalByDelegate: true,
        cancelAttDailyApprovalByEmployee: true,
        cancelAttDailyRequestByDelegate: true,
        cancelAttRequestByDelegate: true,
        editAttTimeSheetByDelegate: true,
        manageAttAgreementAlertSetting: true,
        manageAttLeave: true,
        manageAttLeaveGrant: true,
        manageAttLeaveOfAbsence: true,
        manageAttLeaveOfAbsenceApply: true,
        manageAttPattern: true,
        manageAttPatternApply: true,
        manageAttShortTimeWorkSetting: true,
        manageAttShortTimeWorkSettingApply: true,
        manageAttWorkingType: true,
        manageCalendar: true,
        manageDepartment: true,
        manageEmployee: true,
        manageJob: true,
        manageJobType: true,
        manageMobileSetting: true,
        manageOverallSetting: true,
        managePermission: true,
        managePlannerSetting: true,
        manageTimeSetting: true,
        manageTimeWorkCategory: true,
        submitAttDailyRequestByDelegate: true,
        submitAttRequestByDelegate: true,
        switchCompany: true,
        viewAttTimeSheetByDelegate: true,
        viewTimeTrackByDelegate: true,
        manageExpTypeGroup: true,
        manageExpenseType: true,
        manageTaxType: true,
        manageExpSetting: true,
        manageExchangeRate: true,
        manageAccountingPeriod: true,
        manageReportType: true,
        manageCostCenter: true,
        manageVendor: true,
        manageExtendedItem: true,
        manageEmployeeGroup: true,
        manageExpCreditCard: true,
        manageExpCustomHint: true,
      },
    },
    dialog: {
      show: false,
    },
    delegateApprovalDialog: {
      isNewAssignment: false,
    },
    empInfo: {
      isFetching: false,
      didInvalidate: false,
      record: {},
      startDayOfTheWeek: 0,
    },
    proxyEmployeeInfo: {
      isProxyMode: false,
      id: '',
      employeeCode: '',
      employeeName: '',
      employeePhotoUrl: '',
      departmentCode: '',
      departmentName: '',
      title: '',
      managerName: '',
    },
    targetEmpId: '',
    approverEmployeeSetting: {
      entities: {
        id: '',
        employeeName: '',
      },
      ui: {
        dialog: {
          isOpen: false,
          type: '',
        },
        status: {
          isReadOnly: true,
          targetDate: '',
        },
      },
    },
    approverEmployeeSearch: {
      ui: {
        dialog: {
          isOpen: false,
          type: '',
        },
        operation: {
          searchStrategy: 1,
          isSearchByQueriesExecuted: false,
          departmentCode: '',
          departmentName: '',
          employeeCode: '',
          employeeName: '',
          title: '',
          targetDate: '',
          selectedEmployeeId: '',
        },
      },
      entities: {
        allIds: [],
        byId: {},
      },
    },
    approvalHistoryList: [],
    jobList: [],
    expTypeList: [],
    expTaxTypeList: [],
    costCenterList: [],
    selectedTab: 'NONE',
    currencyList: [],
    suggestInput: {
      origin: {
        selectSuggestion: {},
        suggestions: [],
        status: 'INITIAL',
        value: '',
      },
      arrival: {
        selectSuggestion: {},
        suggestions: [],
        status: 'INITIAL',
        value: '',
      },
      via1: {
        selectSuggestion: {},
        suggestions: [],
        status: 'INITIAL',
        value: '',
      },
      via2: {
        selectSuggestion: {},
        suggestions: [],
        status: 'INITIAL',
        value: '',
      },
      via3: {
        selectSuggestion: {},
        suggestions: [],
        status: 'INITIAL',
        value: '',
      },
      via4: {
        selectSuggestion: {},
        suggestions: [],
        status: 'INITIAL',
        value: '',
      },
    },
    searchedRoute: {},
    standaloneMode: {
      enabled: false,
    },
    stationHistoryList: [],
    userSetting: {
      useWorkTime: true,
      userName: 'yokoyama.shodai+wsp+e2e@teamspirit.com',
      usePlanner: true,
      useExpenseRequest: true,
      useExpense: true,
      useAttendance: true,
      photoUrl:
        'https://yokoyama-e2e-dev-ed--c.documentforce.com/profilephoto/7292v000000kcjz/T',
      name: '横山 翔大',
      managerName:
        'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
      language: 'ja',
      id: '0052v00000WEgZvAAL',
      employeeName:
        'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
      employeeId: 'a0W2v000015RnJtEAK',
      employeeCode: '1',
      departmentName: null,
      departmentId: null,
      departmentCode: null,
      currencySymbol: '',
      currencyName: null,
      currencyId: null,
      currencyDecimalPlaces: null,
      currencyCode: null,
      costCenterName: null,
      costCenterHistoryId: null,
      costCenterCode: null,
      companyName: 'Company 1',
      companyId: 'a0N2v00000Y3UcOEAV',
      approver01Name:
        'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
      allowToChangeApproverSelf: true,
      allowTaxAmountChange: null,
    },
    personalSetting: {
      searchConditionList: [],
      plannerDefaultView: 'Weekly',
    },
    personalSettingDialog: {
      isVisible: false,
      selectedGroup: 'TIME_TRACKING',
      newPersonalSetting: {
        plannerDefaultView: 'Weekly',
      },
    },
    jobSelectDialog: {
      isVisible: false,
    },
    stampWidget: {
      isEnableStartStamp: true,
      isEnableEndStamp: true,
      isEnableRestartStamp: false,
      mode: 'CLOCK_IN',
      message: '',
    },
    toast: {
      isShow: false,
      message: '',
    },
  },
  entities: {
    dailyTimeTrack: {
      '2019-08-01': {
        status: 'Disabled',
        recordDate: '2019-08-01',
        output: null,
        note: null,
        dailyRecordItemList: [],
        targetDate: '2019-08-01',
        time: null,
        realWorkTime: null,
        totalTaskTime: null,
      },
      '2019-08-02': {
        status: 'Disabled',
        recordDate: '2019-08-02',
        output: null,
        note: null,
        dailyRecordItemList: [],
        targetDate: '2019-08-02',
        time: null,
        realWorkTime: null,
        totalTaskTime: null,
      },
      '2019-08-03': {
        status: 'Disabled',
        recordDate: '2019-08-03',
        output: null,
        note: null,
        dailyRecordItemList: [],
        targetDate: '2019-08-03',
        time: null,
        realWorkTime: null,
        totalTaskTime: null,
      },
      '2019-08-04': {
        status: 'Disabled',
        recordDate: '2019-08-04',
        output: null,
        note: null,
        dailyRecordItemList: [],
        targetDate: '2019-08-04',
        time: null,
        realWorkTime: null,
        totalTaskTime: null,
      },
      '2019-08-05': {
        status: 'Disabled',
        recordDate: '2019-08-05',
        output: null,
        note: null,
        dailyRecordItemList: [
          {
            workCategoryName: '',
            workCategoryId: null,
            workCategoryCode: null,
            taskTime: 0,
            taskNote: null,
            ratio: 100,
            jobName: 'とっくりセーターを半分だけかぶるモデルの仕事',
            jobId: 'a0h2v00000XB8oWAAT',
            jobCode: '6',
          },
          {
            workCategoryName: '',
            workCategoryId: null,
            workCategoryCode: null,
            taskTime: 9900,
            taskNote: null,
            ratio: null,
            jobName: '自宅の警備の仕事',
            jobId: 'a0h2v00000XB8oCAAT',
            jobCode: '3',
          },
        ],
        targetDate: '2019-08-05',
        time: 9900,
        realWorkTime: 2819,
        totalTaskTime: 9900,
      },
      '2019-08-06': {
        status: 'Disabled',
        recordDate: '2019-08-06',
        output: null,
        note: null,
        dailyRecordItemList: [],
        targetDate: '2019-08-06',
        time: null,
        realWorkTime: null,
        totalTaskTime: null,
      },
      '2019-08-07': {
        status: 'Disabled',
        recordDate: '2019-08-07',
        output: null,
        note: null,
        dailyRecordItemList: [],
        targetDate: '2019-08-07',
        time: null,
        realWorkTime: null,
        totalTaskTime: null,
      },
      '2019-08-08': {
        status: 'Disabled',
        recordDate: '2019-08-08',
        output: null,
        note: null,
        dailyRecordItemList: [],
        targetDate: '2019-08-08',
        time: null,
        realWorkTime: null,
        totalTaskTime: null,
      },
      '2019-08-09': {
        status: 'Disabled',
        recordDate: '2019-08-09',
        output: null,
        note: null,
        dailyRecordItemList: [
          {
            workCategoryName: '',
            workCategoryId: null,
            workCategoryCode: null,
            taskTime: 280,
            taskNote: null,
            ratio: null,
            jobName: '自宅の警備の仕事',
            jobId: 'a0h2v00000XB8oCAAT',
            jobCode: '3',
          },
          {
            workCategoryName: '',
            workCategoryId: null,
            workCategoryCode: null,
            taskTime: 560,
            taskNote: null,
            ratio: 100,
            jobName: 'そうめんに2～3本だけ黄色や赤色や緑色の麺を混ぜる仕事',
            jobId: 'a0h2v00000XB8o7AAD',
            jobCode: '2',
          },
        ],
        targetDate: '2019-08-09',
        time: 840,
        realWorkTime: 840,
        totalTaskTime: 840,
      },
      '2019-08-10': {
        status: 'Disabled',
        recordDate: '2019-08-10',
        output: null,
        note: null,
        dailyRecordItemList: [],
        targetDate: '2019-08-10',
        time: null,
        realWorkTime: null,
        totalTaskTime: null,
      },
      '2019-08-11': {
        status: 'Disabled',
        recordDate: '2019-08-11',
        output: null,
        note: null,
        dailyRecordItemList: [],
        targetDate: '2019-08-11',
        time: null,
        realWorkTime: null,
        totalTaskTime: null,
      },
      '2019-08-12': {
        status: 'Disabled',
        recordDate: '2019-08-12',
        output: null,
        note: null,
        dailyRecordItemList: [],
        targetDate: '2019-08-12',
        time: null,
        realWorkTime: null,
        totalTaskTime: null,
      },
      '2019-08-13': {
        status: 'Disabled',
        recordDate: '2019-08-13',
        output: null,
        note: null,
        dailyRecordItemList: [
          {
            workCategoryName: '',
            workCategoryId: null,
            workCategoryCode: null,
            taskTime: 270,
            taskNote: null,
            ratio: 0,
            jobName: '自宅の警備の仕事',
            jobId: 'a0h2v00000XB8oCAAT',
            jobCode: '3',
          },
          {
            workCategoryName: '',
            workCategoryId: null,
            workCategoryCode: null,
            taskTime: 0,
            taskNote: null,
            ratio: 100,
            jobName: '7',
            jobId: 'a0h2v00000Xa3gRAAR',
            jobCode: '7',
          },
          {
            workCategoryName: '7',
            workCategoryId: 'a1F2v00000CwZRHEA3',
            workCategoryCode: '7',
            taskTime: 120,
            taskNote: null,
            ratio: 0,
            jobName: '9',
            jobId: 'a0h2v00000Xa3gtAAB',
            jobCode: '9',
          },
          {
            workCategoryName: '7',
            workCategoryId: 'a1F2v00000CwZRHEA3',
            workCategoryCode: '7',
            taskTime: 300,
            taskNote: null,
            ratio: 0,
            jobName: '10',
            jobId: 'a0h2v00000Xa3h3AAB',
            jobCode: '10',
          },
        ],
        targetDate: '2019-08-13',
        time: 690,
        realWorkTime: 397,
        totalTaskTime: 690,
      },
      '2019-08-14': {
        status: 'Disabled',
        recordDate: '2019-08-14',
        output: null,
        note: null,
        dailyRecordItemList: [],
        targetDate: '2019-08-14',
        time: null,
        realWorkTime: null,
        totalTaskTime: null,
      },
      '2019-08-15': {
        status: 'Disabled',
        recordDate: '2019-08-15',
        output: null,
        note: null,
        dailyRecordItemList: [
          {
            workCategoryName: '',
            workCategoryId: null,
            workCategoryCode: null,
            taskTime: 540,
            taskNote: null,
            ratio: 100,
            jobName: 'そうめんに2～3本だけ黄色や赤色や緑色の麺を混ぜる仕事',
            jobId: 'a0h2v00000XB8o7AAD',
            jobCode: '2',
          },
        ],
        targetDate: '2019-08-15',
        time: 540,
        realWorkTime: 540,
        totalTaskTime: 540,
      },
      '2019-08-16': {
        status: 'Disabled',
        recordDate: '2019-08-16',
        output: null,
        note: null,
        dailyRecordItemList: [
          {
            workCategoryName: '',
            workCategoryId: null,
            workCategoryCode: null,
            taskTime: 0,
            taskNote: null,
            ratio: 100,
            jobName: 'そうめんに2～3本だけ黄色や赤色や緑色の麺を混ぜる仕事',
            jobId: 'a0h2v00000XB8o7AAD',
            jobCode: '2',
          },
          {
            workCategoryName: '11',
            workCategoryId: 'a1F2v00000CwZRbEAN',
            workCategoryCode: '11',
            taskTime: 250,
            taskNote: null,
            ratio: null,
            jobName: 'そうめんに2～3本だけ黄色や赤色や緑色の麺を混ぜる仕事',
            jobId: 'a0h2v00000XB8o7AAD',
            jobCode: '2',
          },
          {
            workCategoryName: '▲刺身の上にタンポポを乗せる',
            workCategoryId: 'a1F2v00000CwPQ4EAN',
            workCategoryCode: '2',
            taskTime: 250,
            taskNote: null,
            ratio: null,
            jobName: '自宅の警備の仕事',
            jobId: 'a0h2v00000XB8oCAAT',
            jobCode: '3',
          },
          {
            workCategoryName: 'ピザの上にペパロニを載せる',
            workCategoryId: 'a1F2v00000CwPPzEAN',
            workCategoryCode: '1',
            taskTime: 250,
            taskNote: null,
            ratio: null,
            jobName: 'そうめんに2～3本だけ黄色や赤色や緑色の麺を混ぜる仕事',
            jobId: 'a0h2v00000XB8o7AAD',
            jobCode: '2',
          },
          {
            workCategoryName: '',
            workCategoryId: null,
            workCategoryCode: null,
            taskTime: 395,
            taskNote: null,
            ratio: null,
            jobName: '7',
            jobId: 'a0h2v00000Xa3gRAAR',
            jobCode: '7',
          },
        ],
        targetDate: '2019-08-16',
        time: 1145,
        realWorkTime: null,
        totalTaskTime: 1145,
      },
      '2019-08-17': {
        status: 'Disabled',
        recordDate: '2019-08-17',
        output: null,
        note: null,
        dailyRecordItemList: [],
        targetDate: '2019-08-17',
        time: null,
        realWorkTime: null,
        totalTaskTime: null,
      },
      '2019-08-18': {
        status: 'Disabled',
        recordDate: '2019-08-18',
        output: null,
        note: null,
        dailyRecordItemList: [],
        targetDate: '2019-08-18',
        time: null,
        realWorkTime: null,
        totalTaskTime: null,
      },
      '2019-08-19': {
        status: 'Disabled',
        recordDate: '2019-08-19',
        output: null,
        note: null,
        dailyRecordItemList: [],
        targetDate: '2019-08-19',
        time: null,
        realWorkTime: null,
        totalTaskTime: null,
      },
      '2019-08-20': {
        status: 'Disabled',
        recordDate: '2019-08-20',
        output: null,
        note: '報告〜！',
        dailyRecordItemList: [
          {
            workCategoryName: '',
            workCategoryId: null,
            workCategoryCode: null,
            taskTime: 0,
            taskNote: null,
            ratio: 100,
            jobName: 'とっくりセーターを半分だけかぶるモデルの仕事',
            jobId: 'a0h2v00000XB8oWAAT',
            jobCode: '6',
          },
        ],
        targetDate: '2019-08-20',
        time: 0,
        realWorkTime: null,
        totalTaskTime: 0,
      },
      '2019-08-21': {
        status: 'Disabled',
        recordDate: '2019-08-21',
        output: null,
        note: null,
        dailyRecordItemList: [],
        targetDate: '2019-08-21',
        time: null,
        realWorkTime: null,
        totalTaskTime: null,
      },
      '2019-08-22': {
        status: 'Disabled',
        recordDate: '2019-08-22',
        output: null,
        note: null,
        dailyRecordItemList: [],
        targetDate: '2019-08-22',
        time: null,
        realWorkTime: null,
        totalTaskTime: null,
      },
      '2019-08-23': {
        status: 'Disabled',
        recordDate: '2019-08-23',
        output: null,
        note: null,
        dailyRecordItemList: [],
        targetDate: '2019-08-23',
        time: null,
        realWorkTime: null,
        totalTaskTime: null,
      },
      '2019-08-24': {
        status: 'Disabled',
        recordDate: '2019-08-24',
        output: null,
        note: null,
        dailyRecordItemList: [],
        targetDate: '2019-08-24',
        time: null,
        realWorkTime: null,
        totalTaskTime: null,
      },
      '2019-08-25': {
        status: 'Disabled',
        recordDate: '2019-08-25',
        output: null,
        note: null,
        dailyRecordItemList: [],
        targetDate: '2019-08-25',
        time: null,
        realWorkTime: null,
        totalTaskTime: null,
      },
      '2019-08-26': {
        status: 'Disabled',
        recordDate: '2019-08-26',
        output: null,
        note: null,
        dailyRecordItemList: [],
        targetDate: '2019-08-26',
        time: null,
        realWorkTime: null,
        totalTaskTime: null,
      },
      '2019-08-27': {
        status: 'Disabled',
        recordDate: '2019-08-27',
        output: null,
        note: null,
        dailyRecordItemList: [
          {
            workCategoryName:
              '吾輩は猫である。名前はまだ無い。どこで生れたかとんと見当がつかぬ。 何でも薄暗いじめじめした所でニャ',
            workCategoryId: 'a1F2v00000CwPQJEA3',
            workCategoryCode: '4',
            taskTime: 120,
            taskNote: null,
            ratio: null,
            jobName: '7',
            jobId: 'a0h2v00000Xa3gRAAR',
            jobCode: '7',
          },
          {
            workCategoryName: '',
            workCategoryId: null,
            workCategoryCode: null,
            taskTime: 234,
            taskNote: null,
            ratio: 100,
            jobName: '7',
            jobId: 'a0h2v00000Xa3gRAAR',
            jobCode: '7',
          },
        ],
        targetDate: '2019-08-27',
        time: 354,
        realWorkTime: 354,
        totalTaskTime: 354,
      },
      '2019-08-28': {
        status: 'Disabled',
        recordDate: '2019-08-28',
        output: null,
        note: null,
        dailyRecordItemList: [],
        targetDate: '2019-08-28',
        time: null,
        realWorkTime: null,
        totalTaskTime: null,
      },
      '2019-08-29': {
        status: 'Disabled',
        recordDate: '2019-08-29',
        output: null,
        note: null,
        dailyRecordItemList: [],
        targetDate: '2019-08-29',
        time: null,
        realWorkTime: null,
        totalTaskTime: null,
      },
      '2019-08-30': {
        status: 'Disabled',
        recordDate: '2019-08-30',
        output: null,
        note: null,
        dailyRecordItemList: [],
        targetDate: '2019-08-30',
        time: null,
        realWorkTime: null,
        totalTaskTime: null,
      },
      '2019-08-31': {
        status: 'Disabled',
        recordDate: '2019-08-31',
        output: null,
        note: null,
        dailyRecordItemList: [],
        targetDate: '2019-08-31',
        time: null,
        realWorkTime: null,
        totalTaskTime: null,
      },
    },
    timesheet: {
      employee: {
        employeeName:
          'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
        departmentName: null,
        workingTypeName: 'デフォルト (フレックス)',
      },
      attWorkingType: {
        startTime: 660,
        endTime: 960,
        holidayWorkConfig: {
          substituteLeaveTypeList: [],
        },
        workSystem: 'JP:Flex',
        flexStartTime: 420,
        flexEndTime: 1320,
        requireEarlyStartWorkApplyBefore: null,
        requireOvertimeWorkApplyAfter: null,
        directApplyStartTime: null,
        directApplyEndTime: null,
        directApplyRest1StartTime: null,
        directApplyRest1EndTime: null,
        directApplyRest2StartTime: null,
        directApplyRest2EndTime: null,
        directApplyRest3StartTime: null,
        directApplyRest3EndTime: null,
        directApplyRest4StartTime: null,
        directApplyRest4EndTime: null,
        directApplyRest5StartTime: null,
        directApplyRest5EndTime: null,
      },
      summaryPeriodList: [
        {
          startDate: '2019-10-01',
          name: '2019年10月',
          endDate: '2019-10-31',
        },
        {
          startDate: '2019-09-01',
          name: '2019年09月',
          endDate: '2019-09-30',
        },
        {
          startDate: '2019-08-01',
          name: '2019年08月',
          endDate: '2019-08-31',
        },
        {
          startDate: '2019-07-01',
          name: '2019年07月',
          endDate: '2019-07-31',
        },
        {
          startDate: '2019-06-01',
          name: '2019年06月',
          endDate: '2019-06-30',
        },
        {
          startDate: '2019-05-16',
          name: '2019年05月',
          endDate: '2019-05-31',
        },
      ],
      attDailyRequestTypeMap: {
        Pattern: {
          name: '勤務時間変更',
          code: 'Pattern',
        },
        Direct: {
          name: '直行直帰',
          code: 'Direct',
        },
        Absence: {
          name: '欠勤',
          code: 'Absence',
        },
        OvertimeWork: {
          name: '残業',
          code: 'OvertimeWork',
        },
        EarlyStartWork: {
          name: '早朝勤務',
          code: 'EarlyStartWork',
        },
        HolidayWork: {
          name: '休日出勤',
          code: 'HolidayWork',
        },
        Leave: {
          name: '休暇',
          code: 'Leave',
        },
      },
      attDailyRequestMap: {},
      attRecordList: [
        {
          id: 'a0D2v000018UKrhEAG',
          recordDate: '2019-08-01',
          dayType: 'Workday',
          startTime: null,
          endTime: null,
          startStampTime: null,
          endStampTime: null,
          outStartTime: null,
          outEndTime: null,
          rest1StartTime: null,
          rest1EndTime: null,
          rest2StartTime: null,
          rest2EndTime: null,
          rest3StartTime: null,
          rest3EndTime: null,
          rest4StartTime: null,
          rest4EndTime: null,
          rest5StartTime: null,
          rest5EndTime: null,
          restHours: null,
          remarks: null,
          requestTypeCodes: [],
          requestIds: [],
          contractedDetail: {
            workSystem: null,
            startTime: 660,
            rest5StartTime: null,
            rest5EndTime: null,
            rest4StartTime: null,
            rest4EndTime: null,
            rest3StartTime: null,
            rest3EndTime: null,
            rest2StartTime: null,
            rest2EndTime: null,
            rest1StartTime: null,
            rest1EndTime: null,
            requireOvertimeWorkApplyAfter: null,
            requireEarlyStartWorkApplyBefore: null,
            holidayWorkConfig: null,
            flexStartTime: null,
            flexEndTime: null,
            endTime: 960,
            directApplyStartTime: null,
            directApplyRest5StartTime: null,
            directApplyRest5EndTime: null,
            directApplyRest4StartTime: null,
            directApplyRest4EndTime: null,
            directApplyRest3StartTime: null,
            directApplyRest3EndTime: null,
            directApplyRest2StartTime: null,
            directApplyRest2EndTime: null,
            directApplyRest1StartTime: null,
            directApplyRest1EndTime: null,
            directApplyEndTime: null,
            allowToChangeApproverSelf: null,
          },
          ciliTimePeriods: [],
          ciloTimePeriods: [],
          coliTimePeriods: [],
          coloTimePeriods: [],
          approver01Name:
            'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
          isSummaryLocked: false,
          isLeaveOfAbsence: false,
          insufficientRestTime: 0,
        },
        {
          id: 'a0D2v000018UKriEAG',
          recordDate: '2019-08-02',
          dayType: 'Workday',
          startTime: null,
          endTime: null,
          startStampTime: null,
          endStampTime: null,
          outStartTime: null,
          outEndTime: null,
          rest1StartTime: null,
          rest1EndTime: null,
          rest2StartTime: null,
          rest2EndTime: null,
          rest3StartTime: null,
          rest3EndTime: null,
          rest4StartTime: null,
          rest4EndTime: null,
          rest5StartTime: null,
          rest5EndTime: null,
          restHours: null,
          remarks: null,
          requestTypeCodes: [],
          requestIds: [],
          contractedDetail: {
            workSystem: null,
            startTime: 660,
            rest5StartTime: null,
            rest5EndTime: null,
            rest4StartTime: null,
            rest4EndTime: null,
            rest3StartTime: null,
            rest3EndTime: null,
            rest2StartTime: null,
            rest2EndTime: null,
            rest1StartTime: null,
            rest1EndTime: null,
            requireOvertimeWorkApplyAfter: null,
            requireEarlyStartWorkApplyBefore: null,
            holidayWorkConfig: null,
            flexStartTime: null,
            flexEndTime: null,
            endTime: 960,
            directApplyStartTime: null,
            directApplyRest5StartTime: null,
            directApplyRest5EndTime: null,
            directApplyRest4StartTime: null,
            directApplyRest4EndTime: null,
            directApplyRest3StartTime: null,
            directApplyRest3EndTime: null,
            directApplyRest2StartTime: null,
            directApplyRest2EndTime: null,
            directApplyRest1StartTime: null,
            directApplyRest1EndTime: null,
            directApplyEndTime: null,
            allowToChangeApproverSelf: null,
          },
          ciliTimePeriods: [],
          ciloTimePeriods: [],
          coliTimePeriods: [],
          coloTimePeriods: [],
          approver01Name:
            'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
          isSummaryLocked: false,
          isLeaveOfAbsence: false,
          insufficientRestTime: 0,
        },
        {
          id: 'a0D2v000018UKrjEAG',
          recordDate: '2019-08-03',
          dayType: 'Holiday',
          startTime: null,
          endTime: null,
          startStampTime: null,
          endStampTime: null,
          outStartTime: null,
          outEndTime: null,
          rest1StartTime: null,
          rest1EndTime: null,
          rest2StartTime: null,
          rest2EndTime: null,
          rest3StartTime: null,
          rest3EndTime: null,
          rest4StartTime: null,
          rest4EndTime: null,
          rest5StartTime: null,
          rest5EndTime: null,
          restHours: null,
          remarks: null,
          requestTypeCodes: ['HolidayWork'],
          requestIds: [],
          contractedDetail: {
            workSystem: null,
            startTime: null,
            rest5StartTime: null,
            rest5EndTime: null,
            rest4StartTime: null,
            rest4EndTime: null,
            rest3StartTime: null,
            rest3EndTime: null,
            rest2StartTime: null,
            rest2EndTime: null,
            rest1StartTime: null,
            rest1EndTime: null,
            requireOvertimeWorkApplyAfter: null,
            requireEarlyStartWorkApplyBefore: null,
            holidayWorkConfig: null,
            flexStartTime: null,
            flexEndTime: null,
            endTime: null,
            directApplyStartTime: null,
            directApplyRest5StartTime: null,
            directApplyRest5EndTime: null,
            directApplyRest4StartTime: null,
            directApplyRest4EndTime: null,
            directApplyRest3StartTime: null,
            directApplyRest3EndTime: null,
            directApplyRest2StartTime: null,
            directApplyRest2EndTime: null,
            directApplyRest1StartTime: null,
            directApplyRest1EndTime: null,
            directApplyEndTime: null,
            allowToChangeApproverSelf: null,
          },
          ciliTimePeriods: [],
          ciloTimePeriods: [],
          coliTimePeriods: [],
          coloTimePeriods: [],
          approver01Name:
            'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
          isSummaryLocked: false,
          isLeaveOfAbsence: false,
          insufficientRestTime: 0,
        },
        {
          id: 'a0D2v000018UKrkEAG',
          recordDate: '2019-08-04',
          dayType: 'LegalHoliday',
          startTime: null,
          endTime: null,
          startStampTime: null,
          endStampTime: null,
          outStartTime: null,
          outEndTime: null,
          rest1StartTime: null,
          rest1EndTime: null,
          rest2StartTime: null,
          rest2EndTime: null,
          rest3StartTime: null,
          rest3EndTime: null,
          rest4StartTime: null,
          rest4EndTime: null,
          rest5StartTime: null,
          rest5EndTime: null,
          restHours: null,
          remarks: null,
          requestTypeCodes: ['HolidayWork'],
          requestIds: [],
          contractedDetail: {
            workSystem: null,
            startTime: null,
            rest5StartTime: null,
            rest5EndTime: null,
            rest4StartTime: null,
            rest4EndTime: null,
            rest3StartTime: null,
            rest3EndTime: null,
            rest2StartTime: null,
            rest2EndTime: null,
            rest1StartTime: null,
            rest1EndTime: null,
            requireOvertimeWorkApplyAfter: null,
            requireEarlyStartWorkApplyBefore: null,
            holidayWorkConfig: null,
            flexStartTime: null,
            flexEndTime: null,
            endTime: null,
            directApplyStartTime: null,
            directApplyRest5StartTime: null,
            directApplyRest5EndTime: null,
            directApplyRest4StartTime: null,
            directApplyRest4EndTime: null,
            directApplyRest3StartTime: null,
            directApplyRest3EndTime: null,
            directApplyRest2StartTime: null,
            directApplyRest2EndTime: null,
            directApplyRest1StartTime: null,
            directApplyRest1EndTime: null,
            directApplyEndTime: null,
            allowToChangeApproverSelf: null,
          },
          ciliTimePeriods: [],
          ciloTimePeriods: [],
          coliTimePeriods: [],
          coloTimePeriods: [],
          approver01Name:
            'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
          isSummaryLocked: false,
          isLeaveOfAbsence: false,
          insufficientRestTime: 0,
        },
        {
          id: 'a0D2v000018UKrlEAG',
          recordDate: '2019-08-05',
          dayType: 'Workday',
          startTime: 0,
          endTime: 2879,
          startStampTime: null,
          endStampTime: null,
          outStartTime: 0,
          outEndTime: 2879,
          rest1StartTime: null,
          rest1EndTime: null,
          rest2StartTime: null,
          rest2EndTime: null,
          rest3StartTime: null,
          rest3EndTime: null,
          rest4StartTime: null,
          rest4EndTime: null,
          rest5StartTime: null,
          rest5EndTime: null,
          restHours: 60,
          remarks: null,
          requestTypeCodes: [],
          requestIds: [],
          contractedDetail: {
            workSystem: null,
            startTime: 660,
            rest5StartTime: null,
            rest5EndTime: null,
            rest4StartTime: null,
            rest4EndTime: null,
            rest3StartTime: null,
            rest3EndTime: null,
            rest2StartTime: null,
            rest2EndTime: null,
            rest1StartTime: null,
            rest1EndTime: null,
            requireOvertimeWorkApplyAfter: null,
            requireEarlyStartWorkApplyBefore: null,
            holidayWorkConfig: null,
            flexStartTime: null,
            flexEndTime: null,
            endTime: 960,
            directApplyStartTime: null,
            directApplyRest5StartTime: null,
            directApplyRest5EndTime: null,
            directApplyRest4StartTime: null,
            directApplyRest4EndTime: null,
            directApplyRest3StartTime: null,
            directApplyRest3EndTime: null,
            directApplyRest2StartTime: null,
            directApplyRest2EndTime: null,
            directApplyRest1StartTime: null,
            directApplyRest1EndTime: null,
            directApplyEndTime: null,
            allowToChangeApproverSelf: null,
          },
          ciliTimePeriods: [
            {
              startTime: 0,
              endTime: 480,
            },
          ],
          ciloTimePeriods: [],
          coliTimePeriods: [],
          coloTimePeriods: [
            {
              startTime: 480,
              endTime: 2879,
            },
          ],
          approver01Name:
            'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
          isSummaryLocked: false,
          isLeaveOfAbsence: false,
          insufficientRestTime: 0,
        },
        {
          id: 'a0D2v000018UKrmEAG',
          recordDate: '2019-08-06',
          dayType: 'Workday',
          startTime: null,
          endTime: null,
          startStampTime: null,
          endStampTime: null,
          outStartTime: null,
          outEndTime: null,
          rest1StartTime: null,
          rest1EndTime: null,
          rest2StartTime: null,
          rest2EndTime: null,
          rest3StartTime: null,
          rest3EndTime: null,
          rest4StartTime: null,
          rest4EndTime: null,
          rest5StartTime: null,
          rest5EndTime: null,
          restHours: 60,
          remarks: null,
          requestTypeCodes: [],
          requestIds: [],
          contractedDetail: {
            workSystem: null,
            startTime: 660,
            rest5StartTime: null,
            rest5EndTime: null,
            rest4StartTime: null,
            rest4EndTime: null,
            rest3StartTime: null,
            rest3EndTime: null,
            rest2StartTime: null,
            rest2EndTime: null,
            rest1StartTime: null,
            rest1EndTime: null,
            requireOvertimeWorkApplyAfter: null,
            requireEarlyStartWorkApplyBefore: null,
            holidayWorkConfig: null,
            flexStartTime: null,
            flexEndTime: null,
            endTime: 960,
            directApplyStartTime: null,
            directApplyRest5StartTime: null,
            directApplyRest5EndTime: null,
            directApplyRest4StartTime: null,
            directApplyRest4EndTime: null,
            directApplyRest3StartTime: null,
            directApplyRest3EndTime: null,
            directApplyRest2StartTime: null,
            directApplyRest2EndTime: null,
            directApplyRest1StartTime: null,
            directApplyRest1EndTime: null,
            directApplyEndTime: null,
            allowToChangeApproverSelf: null,
          },
          ciliTimePeriods: [],
          ciloTimePeriods: [],
          coliTimePeriods: [],
          coloTimePeriods: [],
          approver01Name:
            'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
          isSummaryLocked: false,
          isLeaveOfAbsence: false,
          insufficientRestTime: 0,
        },
        {
          id: 'a0D2v000018UKrnEAG',
          recordDate: '2019-08-07',
          dayType: 'Workday',
          startTime: null,
          endTime: null,
          startStampTime: null,
          endStampTime: null,
          outStartTime: null,
          outEndTime: null,
          rest1StartTime: null,
          rest1EndTime: null,
          rest2StartTime: null,
          rest2EndTime: null,
          rest3StartTime: null,
          rest3EndTime: null,
          rest4StartTime: null,
          rest4EndTime: null,
          rest5StartTime: null,
          rest5EndTime: null,
          restHours: null,
          remarks: null,
          requestTypeCodes: [],
          requestIds: [],
          contractedDetail: {
            workSystem: null,
            startTime: 660,
            rest5StartTime: null,
            rest5EndTime: null,
            rest4StartTime: null,
            rest4EndTime: null,
            rest3StartTime: null,
            rest3EndTime: null,
            rest2StartTime: null,
            rest2EndTime: null,
            rest1StartTime: null,
            rest1EndTime: null,
            requireOvertimeWorkApplyAfter: null,
            requireEarlyStartWorkApplyBefore: null,
            holidayWorkConfig: null,
            flexStartTime: null,
            flexEndTime: null,
            endTime: 960,
            directApplyStartTime: null,
            directApplyRest5StartTime: null,
            directApplyRest5EndTime: null,
            directApplyRest4StartTime: null,
            directApplyRest4EndTime: null,
            directApplyRest3StartTime: null,
            directApplyRest3EndTime: null,
            directApplyRest2StartTime: null,
            directApplyRest2EndTime: null,
            directApplyRest1StartTime: null,
            directApplyRest1EndTime: null,
            directApplyEndTime: null,
            allowToChangeApproverSelf: null,
          },
          ciliTimePeriods: [],
          ciloTimePeriods: [],
          coliTimePeriods: [],
          coloTimePeriods: [],
          approver01Name:
            'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
          isSummaryLocked: false,
          isLeaveOfAbsence: false,
          insufficientRestTime: 0,
        },
        {
          id: 'a0D2v000018UKroEAG',
          recordDate: '2019-08-08',
          dayType: 'Workday',
          startTime: null,
          endTime: null,
          startStampTime: null,
          endStampTime: null,
          outStartTime: null,
          outEndTime: null,
          rest1StartTime: null,
          rest1EndTime: null,
          rest2StartTime: null,
          rest2EndTime: null,
          rest3StartTime: null,
          rest3EndTime: null,
          rest4StartTime: null,
          rest4EndTime: null,
          rest5StartTime: null,
          rest5EndTime: null,
          restHours: null,
          remarks: null,
          requestTypeCodes: [],
          requestIds: [],
          contractedDetail: {
            workSystem: null,
            startTime: 660,
            rest5StartTime: null,
            rest5EndTime: null,
            rest4StartTime: null,
            rest4EndTime: null,
            rest3StartTime: null,
            rest3EndTime: null,
            rest2StartTime: null,
            rest2EndTime: null,
            rest1StartTime: null,
            rest1EndTime: null,
            requireOvertimeWorkApplyAfter: null,
            requireEarlyStartWorkApplyBefore: null,
            holidayWorkConfig: null,
            flexStartTime: null,
            flexEndTime: null,
            endTime: 960,
            directApplyStartTime: null,
            directApplyRest5StartTime: null,
            directApplyRest5EndTime: null,
            directApplyRest4StartTime: null,
            directApplyRest4EndTime: null,
            directApplyRest3StartTime: null,
            directApplyRest3EndTime: null,
            directApplyRest2StartTime: null,
            directApplyRest2EndTime: null,
            directApplyRest1StartTime: null,
            directApplyRest1EndTime: null,
            directApplyEndTime: null,
            allowToChangeApproverSelf: null,
          },
          ciliTimePeriods: [],
          ciloTimePeriods: [],
          coliTimePeriods: [],
          coloTimePeriods: [],
          approver01Name:
            'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
          isSummaryLocked: false,
          isLeaveOfAbsence: false,
          insufficientRestTime: 0,
        },
        {
          id: 'a0D2v000018UKrpEAG',
          recordDate: '2019-08-09',
          dayType: 'Workday',
          startTime: 240,
          endTime: 1140,
          startStampTime: null,
          endStampTime: 406,
          outStartTime: 240,
          outEndTime: 1140,
          rest1StartTime: null,
          rest1EndTime: null,
          rest2StartTime: null,
          rest2EndTime: null,
          rest3StartTime: null,
          rest3EndTime: null,
          rest4StartTime: null,
          rest4EndTime: null,
          rest5StartTime: null,
          rest5EndTime: null,
          restHours: 60,
          remarks: null,
          requestTypeCodes: [],
          requestIds: [],
          contractedDetail: {
            workSystem: null,
            startTime: 660,
            rest5StartTime: null,
            rest5EndTime: null,
            rest4StartTime: null,
            rest4EndTime: null,
            rest3StartTime: null,
            rest3EndTime: null,
            rest2StartTime: null,
            rest2EndTime: null,
            rest1StartTime: null,
            rest1EndTime: null,
            requireOvertimeWorkApplyAfter: null,
            requireEarlyStartWorkApplyBefore: null,
            holidayWorkConfig: null,
            flexStartTime: null,
            flexEndTime: null,
            endTime: 960,
            directApplyStartTime: null,
            directApplyRest5StartTime: null,
            directApplyRest5EndTime: null,
            directApplyRest4StartTime: null,
            directApplyRest4EndTime: null,
            directApplyRest3StartTime: null,
            directApplyRest3EndTime: null,
            directApplyRest2StartTime: null,
            directApplyRest2EndTime: null,
            directApplyRest1StartTime: null,
            directApplyRest1EndTime: null,
            directApplyEndTime: null,
            allowToChangeApproverSelf: null,
          },
          ciliTimePeriods: [
            {
              startTime: 240,
              endTime: 720,
            },
          ],
          ciloTimePeriods: [],
          coliTimePeriods: [],
          coloTimePeriods: [
            {
              startTime: 720,
              endTime: 1140,
            },
          ],
          approver01Name:
            'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
          isSummaryLocked: false,
          isLeaveOfAbsence: false,
          insufficientRestTime: 0,
        },
        {
          id: 'a0D2v000018UKrqEAG',
          recordDate: '2019-08-10',
          dayType: 'Holiday',
          startTime: null,
          endTime: null,
          startStampTime: null,
          endStampTime: null,
          outStartTime: null,
          outEndTime: null,
          rest1StartTime: null,
          rest1EndTime: null,
          rest2StartTime: null,
          rest2EndTime: null,
          rest3StartTime: null,
          rest3EndTime: null,
          rest4StartTime: null,
          rest4EndTime: null,
          rest5StartTime: null,
          rest5EndTime: null,
          restHours: null,
          remarks: null,
          requestTypeCodes: ['HolidayWork'],
          requestIds: [],
          contractedDetail: {
            workSystem: null,
            startTime: null,
            rest5StartTime: null,
            rest5EndTime: null,
            rest4StartTime: null,
            rest4EndTime: null,
            rest3StartTime: null,
            rest3EndTime: null,
            rest2StartTime: null,
            rest2EndTime: null,
            rest1StartTime: null,
            rest1EndTime: null,
            requireOvertimeWorkApplyAfter: null,
            requireEarlyStartWorkApplyBefore: null,
            holidayWorkConfig: null,
            flexStartTime: null,
            flexEndTime: null,
            endTime: null,
            directApplyStartTime: null,
            directApplyRest5StartTime: null,
            directApplyRest5EndTime: null,
            directApplyRest4StartTime: null,
            directApplyRest4EndTime: null,
            directApplyRest3StartTime: null,
            directApplyRest3EndTime: null,
            directApplyRest2StartTime: null,
            directApplyRest2EndTime: null,
            directApplyRest1StartTime: null,
            directApplyRest1EndTime: null,
            directApplyEndTime: null,
            allowToChangeApproverSelf: null,
          },
          ciliTimePeriods: [],
          ciloTimePeriods: [],
          coliTimePeriods: [],
          coloTimePeriods: [],
          approver01Name:
            'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
          isSummaryLocked: false,
          isLeaveOfAbsence: false,
          insufficientRestTime: 0,
        },
        {
          id: 'a0D2v000018UKrrEAG',
          recordDate: '2019-08-11',
          dayType: 'LegalHoliday',
          startTime: null,
          endTime: null,
          startStampTime: null,
          endStampTime: null,
          outStartTime: null,
          outEndTime: null,
          rest1StartTime: null,
          rest1EndTime: null,
          rest2StartTime: null,
          rest2EndTime: null,
          rest3StartTime: null,
          rest3EndTime: null,
          rest4StartTime: null,
          rest4EndTime: null,
          rest5StartTime: null,
          rest5EndTime: null,
          restHours: null,
          remarks: null,
          requestTypeCodes: ['HolidayWork'],
          requestIds: [],
          contractedDetail: {
            workSystem: null,
            startTime: null,
            rest5StartTime: null,
            rest5EndTime: null,
            rest4StartTime: null,
            rest4EndTime: null,
            rest3StartTime: null,
            rest3EndTime: null,
            rest2StartTime: null,
            rest2EndTime: null,
            rest1StartTime: null,
            rest1EndTime: null,
            requireOvertimeWorkApplyAfter: null,
            requireEarlyStartWorkApplyBefore: null,
            holidayWorkConfig: null,
            flexStartTime: null,
            flexEndTime: null,
            endTime: null,
            directApplyStartTime: null,
            directApplyRest5StartTime: null,
            directApplyRest5EndTime: null,
            directApplyRest4StartTime: null,
            directApplyRest4EndTime: null,
            directApplyRest3StartTime: null,
            directApplyRest3EndTime: null,
            directApplyRest2StartTime: null,
            directApplyRest2EndTime: null,
            directApplyRest1StartTime: null,
            directApplyRest1EndTime: null,
            directApplyEndTime: null,
            allowToChangeApproverSelf: null,
          },
          ciliTimePeriods: [],
          ciloTimePeriods: [],
          coliTimePeriods: [],
          coloTimePeriods: [],
          approver01Name:
            'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
          isSummaryLocked: false,
          isLeaveOfAbsence: false,
          insufficientRestTime: 0,
        },
        {
          id: 'a0D2v000018UKrsEAG',
          recordDate: '2019-08-12',
          dayType: 'Holiday',
          startTime: null,
          endTime: null,
          startStampTime: null,
          endStampTime: null,
          outStartTime: null,
          outEndTime: null,
          rest1StartTime: null,
          rest1EndTime: null,
          rest2StartTime: null,
          rest2EndTime: null,
          rest3StartTime: null,
          rest3EndTime: null,
          rest4StartTime: null,
          rest4EndTime: null,
          rest5StartTime: null,
          rest5EndTime: null,
          restHours: null,
          remarks: null,
          requestTypeCodes: ['HolidayWork'],
          requestIds: [],
          contractedDetail: {
            workSystem: null,
            startTime: null,
            rest5StartTime: null,
            rest5EndTime: null,
            rest4StartTime: null,
            rest4EndTime: null,
            rest3StartTime: null,
            rest3EndTime: null,
            rest2StartTime: null,
            rest2EndTime: null,
            rest1StartTime: null,
            rest1EndTime: null,
            requireOvertimeWorkApplyAfter: null,
            requireEarlyStartWorkApplyBefore: null,
            holidayWorkConfig: null,
            flexStartTime: null,
            flexEndTime: null,
            endTime: null,
            directApplyStartTime: null,
            directApplyRest5StartTime: null,
            directApplyRest5EndTime: null,
            directApplyRest4StartTime: null,
            directApplyRest4EndTime: null,
            directApplyRest3StartTime: null,
            directApplyRest3EndTime: null,
            directApplyRest2StartTime: null,
            directApplyRest2EndTime: null,
            directApplyRest1StartTime: null,
            directApplyRest1EndTime: null,
            directApplyEndTime: null,
            allowToChangeApproverSelf: null,
          },
          ciliTimePeriods: [],
          ciloTimePeriods: [],
          coliTimePeriods: [],
          coloTimePeriods: [],
          approver01Name:
            'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
          isSummaryLocked: false,
          isLeaveOfAbsence: false,
          insufficientRestTime: 0,
        },
        {
          id: 'a0D2v000018UKrtEAG',
          recordDate: '2019-08-13',
          dayType: 'Workday',
          startTime: 420,
          endTime: 862,
          startStampTime: null,
          endStampTime: 862,
          outStartTime: 420,
          outEndTime: 862,
          rest1StartTime: null,
          rest1EndTime: null,
          rest2StartTime: null,
          rest2EndTime: null,
          rest3StartTime: null,
          rest3EndTime: null,
          rest4StartTime: null,
          rest4EndTime: null,
          rest5StartTime: null,
          rest5EndTime: null,
          restHours: 45,
          remarks: null,
          requestTypeCodes: [],
          requestIds: [],
          contractedDetail: {
            workSystem: null,
            startTime: 660,
            rest5StartTime: null,
            rest5EndTime: null,
            rest4StartTime: null,
            rest4EndTime: null,
            rest3StartTime: null,
            rest3EndTime: null,
            rest2StartTime: null,
            rest2EndTime: null,
            rest1StartTime: null,
            rest1EndTime: null,
            requireOvertimeWorkApplyAfter: null,
            requireEarlyStartWorkApplyBefore: null,
            holidayWorkConfig: null,
            flexStartTime: null,
            flexEndTime: null,
            endTime: 960,
            directApplyStartTime: null,
            directApplyRest5StartTime: null,
            directApplyRest5EndTime: null,
            directApplyRest4StartTime: null,
            directApplyRest4EndTime: null,
            directApplyRest3StartTime: null,
            directApplyRest3EndTime: null,
            directApplyRest2StartTime: null,
            directApplyRest2EndTime: null,
            directApplyRest1StartTime: null,
            directApplyRest1EndTime: null,
            directApplyEndTime: null,
            allowToChangeApproverSelf: null,
          },
          ciliTimePeriods: [
            {
              startTime: 420,
              endTime: 862,
            },
          ],
          ciloTimePeriods: [],
          coliTimePeriods: [],
          coloTimePeriods: [],
          approver01Name:
            'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
          isSummaryLocked: false,
          isLeaveOfAbsence: false,
          insufficientRestTime: 0,
        },
        {
          id: 'a0D2v000018UKruEAG',
          recordDate: '2019-08-14',
          dayType: 'Workday',
          startTime: null,
          endTime: null,
          startStampTime: null,
          endStampTime: null,
          outStartTime: null,
          outEndTime: null,
          rest1StartTime: null,
          rest1EndTime: null,
          rest2StartTime: null,
          rest2EndTime: null,
          rest3StartTime: null,
          rest3EndTime: null,
          rest4StartTime: null,
          rest4EndTime: null,
          rest5StartTime: null,
          rest5EndTime: null,
          restHours: null,
          remarks: null,
          requestTypeCodes: [],
          requestIds: [],
          contractedDetail: {
            workSystem: null,
            startTime: 660,
            rest5StartTime: null,
            rest5EndTime: null,
            rest4StartTime: null,
            rest4EndTime: null,
            rest3StartTime: null,
            rest3EndTime: null,
            rest2StartTime: null,
            rest2EndTime: null,
            rest1StartTime: null,
            rest1EndTime: null,
            requireOvertimeWorkApplyAfter: null,
            requireEarlyStartWorkApplyBefore: null,
            holidayWorkConfig: null,
            flexStartTime: null,
            flexEndTime: null,
            endTime: 960,
            directApplyStartTime: null,
            directApplyRest5StartTime: null,
            directApplyRest5EndTime: null,
            directApplyRest4StartTime: null,
            directApplyRest4EndTime: null,
            directApplyRest3StartTime: null,
            directApplyRest3EndTime: null,
            directApplyRest2StartTime: null,
            directApplyRest2EndTime: null,
            directApplyRest1StartTime: null,
            directApplyRest1EndTime: null,
            directApplyEndTime: null,
            allowToChangeApproverSelf: null,
          },
          ciliTimePeriods: [],
          ciloTimePeriods: [],
          coliTimePeriods: [],
          coloTimePeriods: [],
          approver01Name:
            'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
          isSummaryLocked: false,
          isLeaveOfAbsence: false,
          insufficientRestTime: 0,
        },
        {
          id: 'a0D2v000018UKrvEAG',
          recordDate: '2019-08-15',
          dayType: 'Workday',
          startTime: 540,
          endTime: 1140,
          startStampTime: null,
          endStampTime: null,
          outStartTime: 540,
          outEndTime: 1140,
          rest1StartTime: null,
          rest1EndTime: null,
          rest2StartTime: null,
          rest2EndTime: null,
          rest3StartTime: null,
          rest3EndTime: null,
          rest4StartTime: null,
          rest4EndTime: null,
          rest5StartTime: null,
          rest5EndTime: null,
          restHours: 60,
          remarks: null,
          requestTypeCodes: [],
          requestIds: [],
          contractedDetail: {
            workSystem: null,
            startTime: 660,
            rest5StartTime: null,
            rest5EndTime: null,
            rest4StartTime: null,
            rest4EndTime: null,
            rest3StartTime: null,
            rest3EndTime: null,
            rest2StartTime: null,
            rest2EndTime: null,
            rest1StartTime: null,
            rest1EndTime: null,
            requireOvertimeWorkApplyAfter: null,
            requireEarlyStartWorkApplyBefore: null,
            holidayWorkConfig: null,
            flexStartTime: null,
            flexEndTime: null,
            endTime: 960,
            directApplyStartTime: null,
            directApplyRest5StartTime: null,
            directApplyRest5EndTime: null,
            directApplyRest4StartTime: null,
            directApplyRest4EndTime: null,
            directApplyRest3StartTime: null,
            directApplyRest3EndTime: null,
            directApplyRest2StartTime: null,
            directApplyRest2EndTime: null,
            directApplyRest1StartTime: null,
            directApplyRest1EndTime: null,
            directApplyEndTime: null,
            allowToChangeApproverSelf: null,
          },
          ciliTimePeriods: [
            {
              startTime: 540,
              endTime: 1020,
            },
          ],
          ciloTimePeriods: [],
          coliTimePeriods: [],
          coloTimePeriods: [
            {
              startTime: 1020,
              endTime: 1140,
            },
          ],
          approver01Name:
            'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
          isSummaryLocked: false,
          isLeaveOfAbsence: false,
          insufficientRestTime: 0,
        },
        {
          id: 'a0D2v000018UKrwEAG',
          recordDate: '2019-08-16',
          dayType: 'Workday',
          startTime: null,
          endTime: null,
          startStampTime: null,
          endStampTime: null,
          outStartTime: null,
          outEndTime: null,
          rest1StartTime: null,
          rest1EndTime: null,
          rest2StartTime: null,
          rest2EndTime: null,
          rest3StartTime: null,
          rest3EndTime: null,
          rest4StartTime: null,
          rest4EndTime: null,
          rest5StartTime: null,
          rest5EndTime: null,
          restHours: null,
          remarks: null,
          requestTypeCodes: [],
          requestIds: [],
          contractedDetail: {
            workSystem: null,
            startTime: 660,
            rest5StartTime: null,
            rest5EndTime: null,
            rest4StartTime: null,
            rest4EndTime: null,
            rest3StartTime: null,
            rest3EndTime: null,
            rest2StartTime: null,
            rest2EndTime: null,
            rest1StartTime: null,
            rest1EndTime: null,
            requireOvertimeWorkApplyAfter: null,
            requireEarlyStartWorkApplyBefore: null,
            holidayWorkConfig: null,
            flexStartTime: null,
            flexEndTime: null,
            endTime: 960,
            directApplyStartTime: null,
            directApplyRest5StartTime: null,
            directApplyRest5EndTime: null,
            directApplyRest4StartTime: null,
            directApplyRest4EndTime: null,
            directApplyRest3StartTime: null,
            directApplyRest3EndTime: null,
            directApplyRest2StartTime: null,
            directApplyRest2EndTime: null,
            directApplyRest1StartTime: null,
            directApplyRest1EndTime: null,
            directApplyEndTime: null,
            allowToChangeApproverSelf: null,
          },
          ciliTimePeriods: [],
          ciloTimePeriods: [],
          coliTimePeriods: [],
          coloTimePeriods: [],
          approver01Name:
            'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
          isSummaryLocked: false,
          isLeaveOfAbsence: false,
          insufficientRestTime: 0,
        },
        {
          id: 'a0D2v000018UKrxEAG',
          recordDate: '2019-08-17',
          dayType: 'Holiday',
          startTime: null,
          endTime: null,
          startStampTime: null,
          endStampTime: null,
          outStartTime: null,
          outEndTime: null,
          rest1StartTime: null,
          rest1EndTime: null,
          rest2StartTime: null,
          rest2EndTime: null,
          rest3StartTime: null,
          rest3EndTime: null,
          rest4StartTime: null,
          rest4EndTime: null,
          rest5StartTime: null,
          rest5EndTime: null,
          restHours: null,
          remarks: null,
          requestTypeCodes: ['HolidayWork'],
          requestIds: [],
          contractedDetail: {
            workSystem: null,
            startTime: null,
            rest5StartTime: null,
            rest5EndTime: null,
            rest4StartTime: null,
            rest4EndTime: null,
            rest3StartTime: null,
            rest3EndTime: null,
            rest2StartTime: null,
            rest2EndTime: null,
            rest1StartTime: null,
            rest1EndTime: null,
            requireOvertimeWorkApplyAfter: null,
            requireEarlyStartWorkApplyBefore: null,
            holidayWorkConfig: null,
            flexStartTime: null,
            flexEndTime: null,
            endTime: null,
            directApplyStartTime: null,
            directApplyRest5StartTime: null,
            directApplyRest5EndTime: null,
            directApplyRest4StartTime: null,
            directApplyRest4EndTime: null,
            directApplyRest3StartTime: null,
            directApplyRest3EndTime: null,
            directApplyRest2StartTime: null,
            directApplyRest2EndTime: null,
            directApplyRest1StartTime: null,
            directApplyRest1EndTime: null,
            directApplyEndTime: null,
            allowToChangeApproverSelf: null,
          },
          ciliTimePeriods: [],
          ciloTimePeriods: [],
          coliTimePeriods: [],
          coloTimePeriods: [],
          approver01Name:
            'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
          isSummaryLocked: false,
          isLeaveOfAbsence: false,
          insufficientRestTime: 0,
        },
        {
          id: 'a0D2v000018UKryEAG',
          recordDate: '2019-08-18',
          dayType: 'LegalHoliday',
          startTime: null,
          endTime: null,
          startStampTime: null,
          endStampTime: null,
          outStartTime: null,
          outEndTime: null,
          rest1StartTime: null,
          rest1EndTime: null,
          rest2StartTime: null,
          rest2EndTime: null,
          rest3StartTime: null,
          rest3EndTime: null,
          rest4StartTime: null,
          rest4EndTime: null,
          rest5StartTime: null,
          rest5EndTime: null,
          restHours: null,
          remarks: null,
          requestTypeCodes: ['HolidayWork'],
          requestIds: [],
          contractedDetail: {
            workSystem: null,
            startTime: null,
            rest5StartTime: null,
            rest5EndTime: null,
            rest4StartTime: null,
            rest4EndTime: null,
            rest3StartTime: null,
            rest3EndTime: null,
            rest2StartTime: null,
            rest2EndTime: null,
            rest1StartTime: null,
            rest1EndTime: null,
            requireOvertimeWorkApplyAfter: null,
            requireEarlyStartWorkApplyBefore: null,
            holidayWorkConfig: null,
            flexStartTime: null,
            flexEndTime: null,
            endTime: null,
            directApplyStartTime: null,
            directApplyRest5StartTime: null,
            directApplyRest5EndTime: null,
            directApplyRest4StartTime: null,
            directApplyRest4EndTime: null,
            directApplyRest3StartTime: null,
            directApplyRest3EndTime: null,
            directApplyRest2StartTime: null,
            directApplyRest2EndTime: null,
            directApplyRest1StartTime: null,
            directApplyRest1EndTime: null,
            directApplyEndTime: null,
            allowToChangeApproverSelf: null,
          },
          ciliTimePeriods: [],
          ciloTimePeriods: [],
          coliTimePeriods: [],
          coloTimePeriods: [],
          approver01Name:
            'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
          isSummaryLocked: false,
          isLeaveOfAbsence: false,
          insufficientRestTime: 0,
        },
        {
          id: 'a0D2v000018UKrzEAG',
          recordDate: '2019-08-19',
          dayType: 'Workday',
          startTime: null,
          endTime: null,
          startStampTime: null,
          endStampTime: null,
          outStartTime: null,
          outEndTime: null,
          rest1StartTime: null,
          rest1EndTime: null,
          rest2StartTime: null,
          rest2EndTime: null,
          rest3StartTime: null,
          rest3EndTime: null,
          rest4StartTime: null,
          rest4EndTime: null,
          rest5StartTime: null,
          rest5EndTime: null,
          restHours: null,
          remarks: null,
          requestTypeCodes: [],
          requestIds: [],
          contractedDetail: {
            workSystem: null,
            startTime: 660,
            rest5StartTime: null,
            rest5EndTime: null,
            rest4StartTime: null,
            rest4EndTime: null,
            rest3StartTime: null,
            rest3EndTime: null,
            rest2StartTime: null,
            rest2EndTime: null,
            rest1StartTime: null,
            rest1EndTime: null,
            requireOvertimeWorkApplyAfter: null,
            requireEarlyStartWorkApplyBefore: null,
            holidayWorkConfig: null,
            flexStartTime: null,
            flexEndTime: null,
            endTime: 960,
            directApplyStartTime: null,
            directApplyRest5StartTime: null,
            directApplyRest5EndTime: null,
            directApplyRest4StartTime: null,
            directApplyRest4EndTime: null,
            directApplyRest3StartTime: null,
            directApplyRest3EndTime: null,
            directApplyRest2StartTime: null,
            directApplyRest2EndTime: null,
            directApplyRest1StartTime: null,
            directApplyRest1EndTime: null,
            directApplyEndTime: null,
            allowToChangeApproverSelf: null,
          },
          ciliTimePeriods: [],
          ciloTimePeriods: [],
          coliTimePeriods: [],
          coloTimePeriods: [],
          approver01Name:
            'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
          isSummaryLocked: false,
          isLeaveOfAbsence: false,
          insufficientRestTime: 0,
        },
        {
          id: 'a0D2v000018UKs0EAG',
          recordDate: '2019-08-20',
          dayType: 'Workday',
          startTime: 753,
          endTime: null,
          startStampTime: 753,
          endStampTime: 1018,
          outStartTime: null,
          outEndTime: null,
          rest1StartTime: 696,
          rest1EndTime: 699,
          rest2StartTime: null,
          rest2EndTime: null,
          rest3StartTime: null,
          rest3EndTime: null,
          rest4StartTime: null,
          rest4EndTime: null,
          rest5StartTime: null,
          rest5EndTime: null,
          restHours: null,
          remarks: null,
          requestTypeCodes: [],
          requestIds: [],
          contractedDetail: {
            workSystem: null,
            startTime: 660,
            rest5StartTime: null,
            rest5EndTime: null,
            rest4StartTime: null,
            rest4EndTime: null,
            rest3StartTime: null,
            rest3EndTime: null,
            rest2StartTime: null,
            rest2EndTime: null,
            rest1StartTime: null,
            rest1EndTime: null,
            requireOvertimeWorkApplyAfter: null,
            requireEarlyStartWorkApplyBefore: null,
            holidayWorkConfig: null,
            flexStartTime: null,
            flexEndTime: null,
            endTime: 960,
            directApplyStartTime: null,
            directApplyRest5StartTime: null,
            directApplyRest5EndTime: null,
            directApplyRest4StartTime: null,
            directApplyRest4EndTime: null,
            directApplyRest3StartTime: null,
            directApplyRest3EndTime: null,
            directApplyRest2StartTime: null,
            directApplyRest2EndTime: null,
            directApplyRest1StartTime: null,
            directApplyRest1EndTime: null,
            directApplyEndTime: null,
            allowToChangeApproverSelf: null,
          },
          ciliTimePeriods: [],
          ciloTimePeriods: [],
          coliTimePeriods: [],
          coloTimePeriods: [],
          approver01Name:
            'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
          isSummaryLocked: false,
          isLeaveOfAbsence: false,
          insufficientRestTime: 0,
        },
        {
          id: 'a0D2v000018UKs1EAG',
          recordDate: '2019-08-21',
          dayType: 'Workday',
          startTime: null,
          endTime: null,
          startStampTime: null,
          endStampTime: null,
          outStartTime: null,
          outEndTime: null,
          rest1StartTime: null,
          rest1EndTime: null,
          rest2StartTime: null,
          rest2EndTime: null,
          rest3StartTime: null,
          rest3EndTime: null,
          rest4StartTime: null,
          rest4EndTime: null,
          rest5StartTime: null,
          rest5EndTime: null,
          restHours: null,
          remarks: null,
          requestTypeCodes: [],
          requestIds: [],
          contractedDetail: {
            workSystem: null,
            startTime: 660,
            rest5StartTime: null,
            rest5EndTime: null,
            rest4StartTime: null,
            rest4EndTime: null,
            rest3StartTime: null,
            rest3EndTime: null,
            rest2StartTime: null,
            rest2EndTime: null,
            rest1StartTime: null,
            rest1EndTime: null,
            requireOvertimeWorkApplyAfter: null,
            requireEarlyStartWorkApplyBefore: null,
            holidayWorkConfig: null,
            flexStartTime: null,
            flexEndTime: null,
            endTime: 960,
            directApplyStartTime: null,
            directApplyRest5StartTime: null,
            directApplyRest5EndTime: null,
            directApplyRest4StartTime: null,
            directApplyRest4EndTime: null,
            directApplyRest3StartTime: null,
            directApplyRest3EndTime: null,
            directApplyRest2StartTime: null,
            directApplyRest2EndTime: null,
            directApplyRest1StartTime: null,
            directApplyRest1EndTime: null,
            directApplyEndTime: null,
            allowToChangeApproverSelf: null,
          },
          ciliTimePeriods: [],
          ciloTimePeriods: [],
          coliTimePeriods: [],
          coloTimePeriods: [],
          approver01Name:
            'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
          isSummaryLocked: false,
          isLeaveOfAbsence: false,
          insufficientRestTime: 0,
        },
        {
          id: 'a0D2v000018UKs2EAG',
          recordDate: '2019-08-22',
          dayType: 'Workday',
          startTime: null,
          endTime: null,
          startStampTime: null,
          endStampTime: null,
          outStartTime: null,
          outEndTime: null,
          rest1StartTime: null,
          rest1EndTime: null,
          rest2StartTime: null,
          rest2EndTime: null,
          rest3StartTime: null,
          rest3EndTime: null,
          rest4StartTime: null,
          rest4EndTime: null,
          rest5StartTime: null,
          rest5EndTime: null,
          restHours: null,
          remarks: null,
          requestTypeCodes: [],
          requestIds: [],
          contractedDetail: {
            workSystem: null,
            startTime: 660,
            rest5StartTime: null,
            rest5EndTime: null,
            rest4StartTime: null,
            rest4EndTime: null,
            rest3StartTime: null,
            rest3EndTime: null,
            rest2StartTime: null,
            rest2EndTime: null,
            rest1StartTime: null,
            rest1EndTime: null,
            requireOvertimeWorkApplyAfter: null,
            requireEarlyStartWorkApplyBefore: null,
            holidayWorkConfig: null,
            flexStartTime: null,
            flexEndTime: null,
            endTime: 960,
            directApplyStartTime: null,
            directApplyRest5StartTime: null,
            directApplyRest5EndTime: null,
            directApplyRest4StartTime: null,
            directApplyRest4EndTime: null,
            directApplyRest3StartTime: null,
            directApplyRest3EndTime: null,
            directApplyRest2StartTime: null,
            directApplyRest2EndTime: null,
            directApplyRest1StartTime: null,
            directApplyRest1EndTime: null,
            directApplyEndTime: null,
            allowToChangeApproverSelf: null,
          },
          ciliTimePeriods: [],
          ciloTimePeriods: [],
          coliTimePeriods: [],
          coloTimePeriods: [],
          approver01Name:
            'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
          isSummaryLocked: false,
          isLeaveOfAbsence: false,
          insufficientRestTime: 0,
        },
        {
          id: 'a0D2v000018UKs3EAG',
          recordDate: '2019-08-23',
          dayType: 'Workday',
          startTime: null,
          endTime: null,
          startStampTime: null,
          endStampTime: null,
          outStartTime: null,
          outEndTime: null,
          rest1StartTime: null,
          rest1EndTime: null,
          rest2StartTime: null,
          rest2EndTime: null,
          rest3StartTime: null,
          rest3EndTime: null,
          rest4StartTime: null,
          rest4EndTime: null,
          rest5StartTime: null,
          rest5EndTime: null,
          restHours: null,
          remarks: null,
          requestTypeCodes: [],
          requestIds: [],
          contractedDetail: {
            workSystem: null,
            startTime: 660,
            rest5StartTime: null,
            rest5EndTime: null,
            rest4StartTime: null,
            rest4EndTime: null,
            rest3StartTime: null,
            rest3EndTime: null,
            rest2StartTime: null,
            rest2EndTime: null,
            rest1StartTime: null,
            rest1EndTime: null,
            requireOvertimeWorkApplyAfter: null,
            requireEarlyStartWorkApplyBefore: null,
            holidayWorkConfig: null,
            flexStartTime: null,
            flexEndTime: null,
            endTime: 960,
            directApplyStartTime: null,
            directApplyRest5StartTime: null,
            directApplyRest5EndTime: null,
            directApplyRest4StartTime: null,
            directApplyRest4EndTime: null,
            directApplyRest3StartTime: null,
            directApplyRest3EndTime: null,
            directApplyRest2StartTime: null,
            directApplyRest2EndTime: null,
            directApplyRest1StartTime: null,
            directApplyRest1EndTime: null,
            directApplyEndTime: null,
            allowToChangeApproverSelf: null,
          },
          ciliTimePeriods: [],
          ciloTimePeriods: [],
          coliTimePeriods: [],
          coloTimePeriods: [],
          approver01Name:
            'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
          isSummaryLocked: false,
          isLeaveOfAbsence: false,
          insufficientRestTime: 0,
        },
        {
          id: 'a0D2v000018UKs4EAG',
          recordDate: '2019-08-24',
          dayType: 'Holiday',
          startTime: null,
          endTime: null,
          startStampTime: null,
          endStampTime: null,
          outStartTime: null,
          outEndTime: null,
          rest1StartTime: null,
          rest1EndTime: null,
          rest2StartTime: null,
          rest2EndTime: null,
          rest3StartTime: null,
          rest3EndTime: null,
          rest4StartTime: null,
          rest4EndTime: null,
          rest5StartTime: null,
          rest5EndTime: null,
          restHours: null,
          remarks: null,
          requestTypeCodes: ['HolidayWork'],
          requestIds: [],
          contractedDetail: {
            workSystem: null,
            startTime: null,
            rest5StartTime: null,
            rest5EndTime: null,
            rest4StartTime: null,
            rest4EndTime: null,
            rest3StartTime: null,
            rest3EndTime: null,
            rest2StartTime: null,
            rest2EndTime: null,
            rest1StartTime: null,
            rest1EndTime: null,
            requireOvertimeWorkApplyAfter: null,
            requireEarlyStartWorkApplyBefore: null,
            holidayWorkConfig: null,
            flexStartTime: null,
            flexEndTime: null,
            endTime: null,
            directApplyStartTime: null,
            directApplyRest5StartTime: null,
            directApplyRest5EndTime: null,
            directApplyRest4StartTime: null,
            directApplyRest4EndTime: null,
            directApplyRest3StartTime: null,
            directApplyRest3EndTime: null,
            directApplyRest2StartTime: null,
            directApplyRest2EndTime: null,
            directApplyRest1StartTime: null,
            directApplyRest1EndTime: null,
            directApplyEndTime: null,
            allowToChangeApproverSelf: null,
          },
          ciliTimePeriods: [],
          ciloTimePeriods: [],
          coliTimePeriods: [],
          coloTimePeriods: [],
          approver01Name:
            'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
          isSummaryLocked: false,
          isLeaveOfAbsence: false,
          insufficientRestTime: 0,
        },
        {
          id: 'a0D2v000018UKs5EAG',
          recordDate: '2019-08-25',
          dayType: 'LegalHoliday',
          startTime: null,
          endTime: null,
          startStampTime: null,
          endStampTime: null,
          outStartTime: null,
          outEndTime: null,
          rest1StartTime: null,
          rest1EndTime: null,
          rest2StartTime: null,
          rest2EndTime: null,
          rest3StartTime: null,
          rest3EndTime: null,
          rest4StartTime: null,
          rest4EndTime: null,
          rest5StartTime: null,
          rest5EndTime: null,
          restHours: null,
          remarks: null,
          requestTypeCodes: ['HolidayWork'],
          requestIds: [],
          contractedDetail: {
            workSystem: null,
            startTime: null,
            rest5StartTime: null,
            rest5EndTime: null,
            rest4StartTime: null,
            rest4EndTime: null,
            rest3StartTime: null,
            rest3EndTime: null,
            rest2StartTime: null,
            rest2EndTime: null,
            rest1StartTime: null,
            rest1EndTime: null,
            requireOvertimeWorkApplyAfter: null,
            requireEarlyStartWorkApplyBefore: null,
            holidayWorkConfig: null,
            flexStartTime: null,
            flexEndTime: null,
            endTime: null,
            directApplyStartTime: null,
            directApplyRest5StartTime: null,
            directApplyRest5EndTime: null,
            directApplyRest4StartTime: null,
            directApplyRest4EndTime: null,
            directApplyRest3StartTime: null,
            directApplyRest3EndTime: null,
            directApplyRest2StartTime: null,
            directApplyRest2EndTime: null,
            directApplyRest1StartTime: null,
            directApplyRest1EndTime: null,
            directApplyEndTime: null,
            allowToChangeApproverSelf: null,
          },
          ciliTimePeriods: [],
          ciloTimePeriods: [],
          coliTimePeriods: [],
          coloTimePeriods: [],
          approver01Name:
            'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
          isSummaryLocked: false,
          isLeaveOfAbsence: false,
          insufficientRestTime: 0,
        },
        {
          id: 'a0D2v000018UKs6EAG',
          recordDate: '2019-08-26',
          dayType: 'Workday',
          startTime: null,
          endTime: null,
          startStampTime: null,
          endStampTime: null,
          outStartTime: null,
          outEndTime: null,
          rest1StartTime: null,
          rest1EndTime: null,
          rest2StartTime: null,
          rest2EndTime: null,
          rest3StartTime: null,
          rest3EndTime: null,
          rest4StartTime: null,
          rest4EndTime: null,
          rest5StartTime: null,
          rest5EndTime: null,
          restHours: null,
          remarks:
            'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis,',
          requestTypeCodes: [],
          requestIds: [],
          contractedDetail: {
            workSystem: null,
            startTime: 660,
            rest5StartTime: null,
            rest5EndTime: null,
            rest4StartTime: null,
            rest4EndTime: null,
            rest3StartTime: null,
            rest3EndTime: null,
            rest2StartTime: null,
            rest2EndTime: null,
            rest1StartTime: null,
            rest1EndTime: null,
            requireOvertimeWorkApplyAfter: null,
            requireEarlyStartWorkApplyBefore: null,
            holidayWorkConfig: null,
            flexStartTime: null,
            flexEndTime: null,
            endTime: 960,
            directApplyStartTime: null,
            directApplyRest5StartTime: null,
            directApplyRest5EndTime: null,
            directApplyRest4StartTime: null,
            directApplyRest4EndTime: null,
            directApplyRest3StartTime: null,
            directApplyRest3EndTime: null,
            directApplyRest2StartTime: null,
            directApplyRest2EndTime: null,
            directApplyRest1StartTime: null,
            directApplyRest1EndTime: null,
            directApplyEndTime: null,
            allowToChangeApproverSelf: null,
          },
          ciliTimePeriods: [],
          ciloTimePeriods: [],
          coliTimePeriods: [],
          coloTimePeriods: [],
          approver01Name:
            'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
          isSummaryLocked: false,
          isLeaveOfAbsence: false,
          insufficientRestTime: 0,
        },
        {
          id: 'a0D2v000018UKs7EAG',
          recordDate: '2019-08-27',
          dayType: 'Workday',
          startTime: 600,
          endTime: 999,
          startStampTime: null,
          endStampTime: 999,
          outStartTime: 600,
          outEndTime: 999,
          rest1StartTime: null,
          rest1EndTime: null,
          rest2StartTime: null,
          rest2EndTime: null,
          rest3StartTime: null,
          rest3EndTime: null,
          rest4StartTime: null,
          rest4EndTime: null,
          rest5StartTime: null,
          rest5EndTime: null,
          restHours: 45,
          remarks: null,
          requestTypeCodes: [],
          requestIds: [],
          contractedDetail: {
            workSystem: null,
            startTime: 660,
            rest5StartTime: null,
            rest5EndTime: null,
            rest4StartTime: null,
            rest4EndTime: null,
            rest3StartTime: null,
            rest3EndTime: null,
            rest2StartTime: null,
            rest2EndTime: null,
            rest1StartTime: null,
            rest1EndTime: null,
            requireOvertimeWorkApplyAfter: null,
            requireEarlyStartWorkApplyBefore: null,
            holidayWorkConfig: null,
            flexStartTime: null,
            flexEndTime: null,
            endTime: 960,
            directApplyStartTime: null,
            directApplyRest5StartTime: null,
            directApplyRest5EndTime: null,
            directApplyRest4StartTime: null,
            directApplyRest4EndTime: null,
            directApplyRest3StartTime: null,
            directApplyRest3EndTime: null,
            directApplyRest2StartTime: null,
            directApplyRest2EndTime: null,
            directApplyRest1StartTime: null,
            directApplyRest1EndTime: null,
            directApplyEndTime: null,
            allowToChangeApproverSelf: null,
          },
          ciliTimePeriods: [
            {
              startTime: 600,
              endTime: 999,
            },
          ],
          ciloTimePeriods: [],
          coliTimePeriods: [],
          coloTimePeriods: [],
          approver01Name:
            'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
          isSummaryLocked: false,
          isLeaveOfAbsence: false,
          insufficientRestTime: 0,
        },
        {
          id: 'a0D2v000018UKs8EAG',
          recordDate: '2019-08-28',
          dayType: 'Workday',
          startTime: null,
          endTime: null,
          startStampTime: null,
          endStampTime: null,
          outStartTime: null,
          outEndTime: null,
          rest1StartTime: null,
          rest1EndTime: null,
          rest2StartTime: null,
          rest2EndTime: null,
          rest3StartTime: null,
          rest3EndTime: null,
          rest4StartTime: null,
          rest4EndTime: null,
          rest5StartTime: null,
          rest5EndTime: null,
          restHours: null,
          remarks: null,
          requestTypeCodes: [],
          requestIds: [],
          contractedDetail: {
            workSystem: null,
            startTime: 660,
            rest5StartTime: null,
            rest5EndTime: null,
            rest4StartTime: null,
            rest4EndTime: null,
            rest3StartTime: null,
            rest3EndTime: null,
            rest2StartTime: null,
            rest2EndTime: null,
            rest1StartTime: null,
            rest1EndTime: null,
            requireOvertimeWorkApplyAfter: null,
            requireEarlyStartWorkApplyBefore: null,
            holidayWorkConfig: null,
            flexStartTime: null,
            flexEndTime: null,
            endTime: 960,
            directApplyStartTime: null,
            directApplyRest5StartTime: null,
            directApplyRest5EndTime: null,
            directApplyRest4StartTime: null,
            directApplyRest4EndTime: null,
            directApplyRest3StartTime: null,
            directApplyRest3EndTime: null,
            directApplyRest2StartTime: null,
            directApplyRest2EndTime: null,
            directApplyRest1StartTime: null,
            directApplyRest1EndTime: null,
            directApplyEndTime: null,
            allowToChangeApproverSelf: null,
          },
          ciliTimePeriods: [],
          ciloTimePeriods: [],
          coliTimePeriods: [],
          coloTimePeriods: [],
          approver01Name:
            'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
          isSummaryLocked: false,
          isLeaveOfAbsence: false,
          insufficientRestTime: 0,
        },
        {
          id: 'a0D2v000018UKs9EAG',
          recordDate: '2019-08-29',
          dayType: 'Workday',
          startTime: null,
          endTime: null,
          startStampTime: null,
          endStampTime: null,
          outStartTime: null,
          outEndTime: null,
          rest1StartTime: null,
          rest1EndTime: null,
          rest2StartTime: null,
          rest2EndTime: null,
          rest3StartTime: null,
          rest3EndTime: null,
          rest4StartTime: null,
          rest4EndTime: null,
          rest5StartTime: null,
          rest5EndTime: null,
          restHours: null,
          remarks: null,
          requestTypeCodes: [],
          requestIds: [],
          contractedDetail: {
            workSystem: null,
            startTime: 660,
            rest5StartTime: null,
            rest5EndTime: null,
            rest4StartTime: null,
            rest4EndTime: null,
            rest3StartTime: null,
            rest3EndTime: null,
            rest2StartTime: null,
            rest2EndTime: null,
            rest1StartTime: null,
            rest1EndTime: null,
            requireOvertimeWorkApplyAfter: null,
            requireEarlyStartWorkApplyBefore: null,
            holidayWorkConfig: null,
            flexStartTime: null,
            flexEndTime: null,
            endTime: 960,
            directApplyStartTime: null,
            directApplyRest5StartTime: null,
            directApplyRest5EndTime: null,
            directApplyRest4StartTime: null,
            directApplyRest4EndTime: null,
            directApplyRest3StartTime: null,
            directApplyRest3EndTime: null,
            directApplyRest2StartTime: null,
            directApplyRest2EndTime: null,
            directApplyRest1StartTime: null,
            directApplyRest1EndTime: null,
            directApplyEndTime: null,
            allowToChangeApproverSelf: null,
          },
          ciliTimePeriods: [],
          ciloTimePeriods: [],
          coliTimePeriods: [],
          coloTimePeriods: [],
          approver01Name:
            'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
          isSummaryLocked: false,
          isLeaveOfAbsence: false,
          insufficientRestTime: 0,
        },
        {
          id: 'a0D2v000018UKsAEAW',
          recordDate: '2019-08-30',
          dayType: 'Workday',
          startTime: null,
          endTime: null,
          startStampTime: null,
          endStampTime: null,
          outStartTime: null,
          outEndTime: null,
          rest1StartTime: null,
          rest1EndTime: null,
          rest2StartTime: null,
          rest2EndTime: null,
          rest3StartTime: null,
          rest3EndTime: null,
          rest4StartTime: null,
          rest4EndTime: null,
          rest5StartTime: null,
          rest5EndTime: null,
          restHours: null,
          remarks: null,
          requestTypeCodes: [],
          requestIds: [],
          contractedDetail: {
            workSystem: null,
            startTime: 660,
            rest5StartTime: null,
            rest5EndTime: null,
            rest4StartTime: null,
            rest4EndTime: null,
            rest3StartTime: null,
            rest3EndTime: null,
            rest2StartTime: null,
            rest2EndTime: null,
            rest1StartTime: null,
            rest1EndTime: null,
            requireOvertimeWorkApplyAfter: null,
            requireEarlyStartWorkApplyBefore: null,
            holidayWorkConfig: null,
            flexStartTime: null,
            flexEndTime: null,
            endTime: 960,
            directApplyStartTime: null,
            directApplyRest5StartTime: null,
            directApplyRest5EndTime: null,
            directApplyRest4StartTime: null,
            directApplyRest4EndTime: null,
            directApplyRest3StartTime: null,
            directApplyRest3EndTime: null,
            directApplyRest2StartTime: null,
            directApplyRest2EndTime: null,
            directApplyRest1StartTime: null,
            directApplyRest1EndTime: null,
            directApplyEndTime: null,
            allowToChangeApproverSelf: null,
          },
          ciliTimePeriods: [],
          ciloTimePeriods: [],
          coliTimePeriods: [],
          coloTimePeriods: [],
          approver01Name:
            'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
          isSummaryLocked: false,
          isLeaveOfAbsence: false,
          insufficientRestTime: 0,
        },
        {
          id: 'a0D2v000018UKsBEAW',
          recordDate: '2019-08-31',
          dayType: 'Holiday',
          startTime: null,
          endTime: null,
          startStampTime: null,
          endStampTime: null,
          outStartTime: null,
          outEndTime: null,
          rest1StartTime: null,
          rest1EndTime: null,
          rest2StartTime: null,
          rest2EndTime: null,
          rest3StartTime: null,
          rest3EndTime: null,
          rest4StartTime: null,
          rest4EndTime: null,
          rest5StartTime: null,
          rest5EndTime: null,
          restHours: null,
          remarks: null,
          requestTypeCodes: ['HolidayWork'],
          requestIds: [],
          contractedDetail: {
            workSystem: null,
            startTime: null,
            rest5StartTime: null,
            rest5EndTime: null,
            rest4StartTime: null,
            rest4EndTime: null,
            rest3StartTime: null,
            rest3EndTime: null,
            rest2StartTime: null,
            rest2EndTime: null,
            rest1StartTime: null,
            rest1EndTime: null,
            requireOvertimeWorkApplyAfter: null,
            requireEarlyStartWorkApplyBefore: null,
            holidayWorkConfig: null,
            flexStartTime: null,
            flexEndTime: null,
            endTime: null,
            directApplyStartTime: null,
            directApplyRest5StartTime: null,
            directApplyRest5EndTime: null,
            directApplyRest4StartTime: null,
            directApplyRest4EndTime: null,
            directApplyRest3StartTime: null,
            directApplyRest3EndTime: null,
            directApplyRest2StartTime: null,
            directApplyRest2EndTime: null,
            directApplyRest1StartTime: null,
            directApplyRest1EndTime: null,
            directApplyEndTime: null,
            allowToChangeApproverSelf: null,
          },
          ciliTimePeriods: [],
          ciloTimePeriods: [],
          coliTimePeriods: [],
          coloTimePeriods: [],
          approver01Name:
            'One morning, when Gregor Samsa woke from troubled dreams, he found himself trans The quick, brown fox jumps over a lazy d',
          isSummaryLocked: false,
          isLeaveOfAbsence: false,
          insufficientRestTime: 0,
        },
      ],
      attSummary: {
        id: 'a0H2v00000ZF3esEAD',
        requestId: null,
        status: 'NotRequested',
        approver01Name: null,
        isLocked: false,
        performableActionForFix: 'Submit',
      },
    },
    timeTrackAlert: {},
  },
  client: {
    selectedPeriodStartDate: '2019-08-01',
  },
  ui: {
    approvalHistory: {
      isOpen: false,
    },
    dailyAttentions: {
      messages: [],
    },
    dailyRequest: {
      targetDate: null,
      editing: {
        id: null,
        requestTypeCode: null,
        editAction: 'None',
        disableAction: 'None',
        isEditing: false,
      },
      requests: {
        absenceRequest: {
          request: null,
          hasRange: false,
        },
        directRequest: {
          request: null,
          hasRange: false,
        },
        earlyStartWorkRequest: {
          request: null,
        },
        holidayWorkRequest: {
          request: null,
          substituteLeaveTypeList: [],
        },
        leaveRequest: {
          request: null,
          hasRange: false,
          attLeaveList: [],
          selectedAttLeave: null,
        },
        overtimeWorkRequest: {
          request: null,
        },
        patternRequest: {
          request: null,
          attPatternList: [],
          selectedAttPattern: null,
          hasRange: false,
        },
      },
    },
    editingDailyAttTime: null,
    editingDailyRemarks: null,
    editingFixSummaryRequest: null,
    stampWidget: {
      isOpened: true,
    },
    timesheet: {
      isManHoursGraphOpened: false,
    },
  },
  widgets: {
    PersonalMenuPopover: {
      ui: {
        visible: false,
      },
    },
    ApprovalHistoryDialog: {
      entities: {
        historyList: {
          byId: {},
          allIds: [],
        },
      },
    },
    ProxyEmployeeSelectDialog: {
      entities: {
        employees: {
          allIds: [],
          byId: {},
        },
      },
      ui: {
        isVisible: false,
        searchStrategy: 1,
        isSearchByQueriesExecuted: false,
        departmentCodeQuery: '',
        departmentNameQuery: '',
        employeeCodeQuery: '',
        employeeNameQuery: '',
        titleQuery: '',
        selectedEmployeeId: null,
      },
    },
  },
};
