const suggestionStatus = {
  INITIAL: 'INITIAL',
  SEARCH_STATION_SUCCESS: 'SUCCESS',
  SEARCH_STATION_NO_RESULT: 'SEARCH_STATION_NO_RESULT',
  EMPTY_SEARCH_STRING: 'EMPTY_SEARCH_STRING',
  SEARCH_STATION_ERROR: 'SEARCH_STATION_ERROR',
  SELECTED_SUGGESTION_ITEM: 'SELECTED_SUGGESTION_ITEM',
};

export default suggestionStatus;
