const classData = {
  result: {
    isSuccess: true,
  },
  data: {
    route: {
      storeData:
        '!15bc-SU5GTwAAABABM8ZLA#6-CA#7-TU9ZTwAAAtA#3bf-BNT1lPAAAC0AABA#3bc-E5PREUAAAAUAAIAAE4tACkAAYa5Ti0ACQABh3VQVEUyAAABSA#4-IAAQAAAAGGqAANAAIBDQAYA#8f-LQA#5-UgA#26-wA#4-Bh3UABwAJABAAAwA#8e-C0A#5-lIA#26-MAAABQVEUyAAAB6AABAAMAAQAEAAGGtQBQAEgA8AARA#8f-LQA#5-UgA#26-wA#4-BhqQAEgAOAEUACwA#8e-C0A#5-FIA#26-MA#5-Yd1AAcACQAQAAMA#8f-tA#5-JSA#26-DAAAAUFRFMgAAAegAAgADAAEAAQABh6IAHwAAAOoAFQA#8e-C0A#5-VIA#26-MA#5-YeEAA0ACgAkAAYA#8f-tA#5-JSA#26-DA#5-GHdQAHAAkAEAADA#8f-LQA#4-CUgA#26-wAAAFBURTIAAAFIAAMAAgABAAIAAYa2ACIAFwENACUA#8f-tA#5-BSA#26-DA#5-GHdQAHAAkAEAADA#8f-LQA#4-CUgA#26-wAAAFBURTIAAAFIAAQAAgABAAMAAYesACMADwDyABsA#8f-tA#5-FSA#26-DA#5-GHdQAAAAkATwAQA#8f-LQA#4-CUgA#26-wAAAFBURTIAAAKIAAUABAABAAUAAYesACMAGwBqAA0A#8f-tA#5-FSA#26-DA#5-GHsAAMAAAAdwAQA#8f-LQA#4-BUgA#26-wA#4-Bh4A#4-FADkACwA#8e-C0A#5-lIA#26-MA#5-Yd1AAUACQAgAAcA#8f-tA#5-JSA#26-DAAAARU5ERA#5-=,',
      routeNumber: 6,
      routeList: [
        {
          key: '1',
          transferNumber: 1,
          status: {
            isMinTransfer: true,
            isEarliest: true,
            isCheapest: false,
          },
          returnCost: 1280,
          requiredTime: 33,
          pathNumber: 2,
          pathList: [
            {
              transfer: false,
              toName: '新橋',
              seatName: '',
              seatList: [
                {
                  name: '普通車',
                  code: '#1',
                  airLineFare: '',
                  airLine: '',
                },
                {
                  name: 'グリーン席',
                  code: '#2',
                  airLineFare: '',
                  airLine: '',
                },
              ],
              seatCode: '',
              requiredTime: 24,
              lineType: '0',
              lineName: '東海道本線（東日本）',
              key: '1',
              fromName: '横浜',
              fareKey: '1',
              expressKey: 'TK-0',
              distance: 26.9,
              airLine: '',
            },
            {
              transfer: true,
              toName: '京橋（東京）',
              seatName: '',
              seatList: [],
              seatCode: '',
              requiredTime: 3,
              lineType: '2',
              lineName: '東京メトロ銀座線',
              key: '2',
              fromName: '新橋',
              fareKey: '2',
              expressKey: 'TK-0',
              distance: 1.6,
              airLine: '',
            },
          ],
          fareMap: {
            1: {
              returnFare: 940,
              isRoundDiscount: false,
              isIcFare: false,
              key: '1',
              fare: 470,
              exceptCommuterRoute: false,
            },
            2: {
              returnFare: 340,
              isRoundDiscount: false,
              isIcFare: false,
              key: '2',
              fare: 170,
              exceptCommuterRoute: false,
            },
          },
          expressMap: {
            'TK-0': {
              sleeping: 0,
              season: -1,
              returnSleeping: 0,
              returnFee: 0,
              reternGreen: 0,
              isConnectionDiscount: false,
              key: '0',
              green: 0,
              fee: 0,
            },
          },
          existsIcCost: false,
          distance: 28.5,
          cost: 640,
        },
        {
          key: '2',
          transferNumber: 2,
          status: {
            isMinTransfer: false,
            isEarliest: false,
            isCheapest: false,
          },
          returnCost: 1280,
          requiredTime: 41,
          pathNumber: 3,
          pathList: [
            {
              key: '1',
              transfer: false,
              toName: '大崎',
              seatName: '',
              seatList: [
                {
                  name: '普通車',
                  code: '#1',
                  airLineFare: '',
                  airLine: '',
                },
                {
                  name: 'グリーン席',
                  code: '#2',
                  airLineFare: '',
                  airLine: '',
                },
              ],
              seatCode: '',
              requiredTime: 17,
              lineType: '0',
              lineName: '湘南新宿ライン',
              fromName: '横浜',
              fareKey: '9',
              expressKey: '0',
              distance: 24,
              airLine: '',
            },
            {
              key: '2',
              transfer: true,
              toName: '新橋',
              seatName: '',
              seatList: [],
              seatCode: '',
              requiredTime: 11,
              lineType: '0',
              lineName: '山手線',
              fromName: '大崎',
              fareKey: '9',
              expressKey: '0',
              distance: 6.9,
              airLine: '',
            },
            {
              key: '3',
              transfer: true,
              toName: '京橋（東京）',
              seatName: '',
              seatList: [],
              seatCode: '',
              requiredTime: 3,
              lineType: '2',
              lineName: '東京メトロ銀座線',
              fromName: '新橋',
              fareKey: '10',
              expressKey: '0',
              distance: 1.6,
              airLine: '',
            },
          ],
          fareMap: {
            9: {
              returnFare: 940,
              isRoundDiscount: false,
              isIcFare: false,
              key: 9,
              fare: 470,
              exceptCommuterRoute: false,
            },
            10: {
              returnFare: 340,
              isRoundDiscount: false,
              isIcFare: false,
              key: 10,
              fare: 170,
              exceptCommuterRoute: false,
            },
          },
          expressMap: {
            0: {
              sleeping: 0,
              season: -1,
              returnSleeping: 0,
              returnFee: 0,
              reternGreen: 0,
              isConnectionDiscount: false,
              key: 'TK-1',
              green: 0,
              fee: 0,
            },
          },
          existsIcCost: false,
          distance: 32.5,
          cost: 640,
        },
      ],
    },
  },
};

export default classData;
