import moment from 'moment';

export default {
  common: {
    app: {
      loadingDepth: 0,
      error: null,
      unexpectedError: null,
      confirmDialog: null,
    },
    accessControl: {
      permission: {
        viewAttTimeSheetByDelegate: false,
        editAttTimeSheetByDelegate: false,
        editTimeTrackByDelegate: false,
        viewTimeTrackByDelegate: false,
        submitAttDailyRequestByDelegate: false,
        cancelAttDailyRequestByDelegate: false,
        approveSelfAttDailyRequestByEmployee: false,
        approveAttDailyRequestByDelegate: false,
        cancelAttDailyApprovalByEmployee: false,
        cancelAttDailyApprovalByDelegate: false,
        approveSelfAttRequestByEmployee: false,
        submitAttRequestByDelegate: false,
        cancelAttRequestByDelegate: false,
        approveAttRequestByDelegate: false,
        cancelAttApprovalByEmployee: false,
        cancelAttApprovalByDelegate: false,
        manageOverallSetting: false,
        switchCompany: false,
        manageDepartment: false,
        manageEmployee: false,
        manageCalendar: false,
        manageJobType: false,
        manageJob: false,
        manageMobileSetting: false,
        managePermission: false,
        managePlannerSetting: false,
        manageAttLeave: false,
        manageAttShortTimeWorkSetting: false,
        manageAttLeaveOfAbsence: false,
        manageAttWorkingType: false,
        manageAttPattern: false,
        manageAttAgreementAlertSetting: false,
        manageAttLeaveGrant: false,
        manageAttShortTimeWorkSettingApply: false,
        manageAttLeaveOfAbsenceApply: false,
        manageAttPatternApply: false,
        manageTimeSetting: false,
        manageTimeWorkCategory: false,
        manageExpTypeGroup: false,
        manageExpenseType: false,
        manageTaxType: false,
        manageExpSetting: false,
        manageExchangeRate: false,
        manageAccountingPeriod: false,
        manageReportType: false,
        manageCostCenter: false,
        manageVendor: false,
        manageExtendedItem: false,
        manageEmployeeGroup: false,
        manageExpCreditCard: false,
        manageExpCustomHint: false,
        managePsaSetting: false,
        managePsaJobGrade: false,
        managePsaSkillset: false,
      },
    },
    dialog: {
      show: false,
    },
    delegateApprovalDialog: {
      isNewAssignment: false,
    },
    empInfo: {
      isFetching: false,
      didInvalidate: false,
      record: {},
      startDayOfTheWeek: 0,
    },
    proxyEmployeeInfo: {
      isProxyMode: false,
      id: '',
      employeeCode: '',
      employeeName: '',
      employeePhotoUrl: '',
      departmentCode: '',
      departmentName: '',
      title: '',
      managerName: '',
    },
    targetEmpId: '',
    approverEmployeeSetting: {
      entities: {
        id: '',
        employeeName: '',
      },
      ui: {
        dialog: {
          isOpen: false,
          type: '',
        },
        status: {
          isReadOnly: true,
          targetDate: '',
        },
      },
    },
    approverEmployeeSearch: {
      ui: {
        dialog: {
          isOpen: false,
          type: '',
        },
        operation: {
          searchStrategy: 1,
          isSearchByQueriesExecuted: false,
          departmentCode: '',
          departmentName: '',
          employeeCode: '',
          employeeName: '',
          title: '',
          targetDate: '',
          selectedEmployeeId: '',
          isOverLimit: false,
        },
      },
      entities: {
        allIds: [],
        byId: {},
      },
    },
    approvalHistoryList: [],
    jobList: [],
    expTypeList: [],
    expTaxTypeList: [],
    costCenterList: [],
    selectedTab: 'NONE',
    currencyList: [],
    suggestInput: {
      origin: {
        selectSuggestion: {},
        suggestions: [],
        status: 'INITIAL',
        value: '',
      },
      arrival: {
        selectSuggestion: {},
        suggestions: [],
        status: 'INITIAL',
        value: '',
      },
      via1: {
        selectSuggestion: {},
        suggestions: [],
        status: 'INITIAL',
        value: '',
      },
      via2: {
        selectSuggestion: {},
        suggestions: [],
        status: 'INITIAL',
        value: '',
      },
      via3: {
        selectSuggestion: {},
        suggestions: [],
        status: 'INITIAL',
        value: '',
      },
      via4: {
        selectSuggestion: {},
        suggestions: [],
        status: 'INITIAL',
        value: '',
      },
    },
    searchedRoute: {},
    standaloneMode: {
      enabled: false,
    },
    stationHistoryList: [],
    userSetting: {
      id: '',
      name: '',
      userName: '',
      photoUrl: '',
      language: '',
      managerName: '',
      companyId: '',
      companyName: '',
      costCenterHistoryId: '',
      costCenterCode: '',
      costCenterName: '',
      departmentId: '',
      departmentCode: '',
      departmentName: '',
      employeeId: '',
      employeeCode: '',
      employeeName: '',
      allowToChangeApproverSelf: false,
      allowTaxAmountChange: false,
      approver01Name: '',
      currencySymbol: '',
      currencyDecimalPlaces: 0,
      expRoundingSetting: '',
      useExpense: false,
      useExpenseRequest: false,
      useAttendance: false,
      usePlanner: false,
      usePsa: false,
      useWorkTime: false,
      currencyId: '',
      currencyCode: '',
      useMasterCardImport: false,
    },
    personalSetting: {
      searchConditionList: [],
      plannerDefaultView: 'Weekly',
    },
    personalSettingDialog: {
      isVisible: false,
      selectedGroup: 'TIME_TRACKING',
      newPersonalSetting: {
        plannerDefaultView: 'Weekly',
      },
    },
    jobSelectDialog: {
      isVisible: false,
    },
    toast: {
      isShow: false,
      message: '',
    },
  },
  entities: {
    events: {
      targetDate: '2020-02-05',
      records: [
        {
          id: 'a182v00000HUNAUAA5',
          title: 'Sprint 1st',
          start: moment('2020-02-02T15:00:00.000Z'),
          end: moment('2020-02-13T15:00:00.000Z'),
          isAllDay: true,
          isOrganizer: true,
          isOuting: false,
          location: '',
          remarks: '',
          createdServiceBy: 'teamspirit',
          externalEventId: null,
          job: {
            id: '',
            name: '',
            code: '',
          },
          workCategoryId: '',
          workCategoryName: '',
          layout: {
            containsAllDay: true,
            startMinutesOfDay: 0,
            endMinutesOfDay: 0,
          },
        },
        {
          id: 'a182v00000HUNAjAAP',
          title: 'インサイダー取引研修〆切',
          start: moment('2020-02-02T15:00:00.000Z'),
          end: moment('2020-02-03T15:00:00.000Z'),
          isAllDay: true,
          isOrganizer: true,
          isOuting: false,
          location: '',
          remarks: '',
          createdServiceBy: 'teamspirit',
          externalEventId: null,
          job: {
            id: '',
            name: '',
            code: '',
          },
          workCategoryId: '',
          workCategoryName: '',
          layout: {
            containsAllDay: true,
            startMinutesOfDay: 0,
            endMinutesOfDay: 0,
          },
        },
        {
          id: 'a182v00000HUNAPAA5',
          title: '在宅勤務',
          start: moment('2020-02-02T15:00:00.000Z'),
          end: moment('2020-02-03T15:00:00.000Z'),
          isAllDay: true,
          isOrganizer: true,
          isOuting: false,
          location: '',
          remarks: '',
          createdServiceBy: 'teamspirit',
          externalEventId: null,
          job: {
            id: '',
            name: '',
            code: '',
          },
          workCategoryId: '',
          workCategoryName: '',
          layout: {
            containsAllDay: true,
            startMinutesOfDay: 0,
            endMinutesOfDay: 0,
          },
        },
        {
          id: 'a182v00000HUNAZAA5',
          title: '開発依頼〆切',
          start: moment('2020-02-02T15:00:00.000Z'),
          end: moment('2020-02-03T15:00:00.000Z'),
          isAllDay: true,
          isOrganizer: true,
          isOuting: false,
          location: '',
          remarks: '',
          createdServiceBy: 'teamspirit',
          externalEventId: null,
          job: {
            id: '',
            name: '',
            code: '',
          },
          workCategoryId: '',
          workCategoryName: '',
          layout: {
            containsAllDay: true,
            startMinutesOfDay: 0,
            endMinutesOfDay: 0,
          },
        },
        {
          id: 'a182v00000HUNAoAAP',
          title: 'コーディング',
          start: moment('2020-02-03T00:00:00.000Z'),
          end: moment('2020-02-03T05:30:00.000Z'),
          isAllDay: false,
          isOrganizer: true,
          isOuting: false,
          location: '',
          remarks: '',
          createdServiceBy: 'teamspirit',
          externalEventId: null,
          job: {
            id: 'a0h2v00000ManntAAB',
            name: '開発',
            code: '1',
          },
          workCategoryId: 'a1G2v000003yt6oEAA',
          workCategoryName: 'コーディング',
          layout: {
            containsAllDay: false,
            startMinutesOfDay: 450,
            endMinutesOfDay: 725,
          },
          left: 0,
          width: 125,
        },
        {
          id: 'a182v00000HUNAyAAP',
          title: 'カジュアル面談',
          start: moment('2020-02-03T08:30:00.000Z'),
          end: moment('2020-02-03T09:30:00.000Z'),
          isAllDay: false,
          isOrganizer: true,
          isOuting: false,
          location: '',
          remarks: '',
          createdServiceBy: 'teamspirit',
          externalEventId: null,
          job: {
            id: 'a0h2v00000ManntAAB',
            name: '開発',
            code: '1',
          },
          workCategoryId: 'a1G2v000003yt78EAA',
          workCategoryName: 'リクルーティング',
          layout: {
            containsAllDay: false,
            startMinutesOfDay: 875,
            endMinutesOfDay: 925,
          },
          left: 0,
          width: 62.5,
        },
        {
          id: 'a182v00000HUNB3AAP',
          title: 'ディナー',
          start: moment('2020-02-03T09:00:00.000Z'),
          end: moment('2020-02-03T10:00:00.000Z'),
          isAllDay: false,
          isOrganizer: true,
          isOuting: false,
          location: '',
          remarks: '',
          createdServiceBy: 'teamspirit',
          externalEventId: null,
          job: {
            id: '',
            name: '',
            code: '',
          },
          workCategoryId: '',
          workCategoryName: '',
          layout: {
            containsAllDay: false,
            startMinutesOfDay: 900,
            endMinutesOfDay: 950,
          },
          left: 62.5,
          width: 62.5,
        },
      ],
    },
    jobs: [],
    user: {
      id: '',
      employeeCode: '',
      employeeName: '',
      employeePhotoUrl: '',
      departmentCode: '',
      departmentName: '',
      title: '',
      managerName: '',
      isDelegated: false,
    },
  },
  ui: {
    dailySummary: {
      targetDate: '2020-02-03',
      note: '',
      timestampComment: '',
      isEnableEndStamp: false,
      taskList: [
        {
          id: '344e3227-ff0d-45a0-89b4-93f796020fd6',
          jobId: 'a0h2v00000ManntAAB',
          jobCode: '1',
          jobName: '開発',
          hasJobType: true,
          isDirectCharged: false,
          workCategoryId: 'a1G2v000003yt6oEAA',
          workCategoryName: 'コーディング',
          workCategoryCode: '1',
          color: {
            base: '#0083b6',
            linked: '#00658c',
          },
          isDirectInput: true,
          volume: null,
          ratio: null,
          taskTime: 330,
          eventTaskTime: 330,
        },
        {
          id: '2d7593c5-9f38-4dc4-8d9b-dfa24ec3ea76',
          jobId: 'a0h2v00000ManntAAB',
          jobCode: '1',
          jobName: '開発',
          hasJobType: true,
          isDirectCharged: false,
          workCategoryId: 'a1G2v000003yt78EAA',
          workCategoryName: 'リクルーティング',
          workCategoryCode: '5',
          color: {
            base: '#00a3df',
            linked: '#007dab',
          },
          isDirectInput: true,
          volume: null,
          ratio: null,
          taskTime: 60,
          eventTaskTime: 60,
        },
        {
          id: '6c439377-d1bb-405b-84ce-937b4fbaf08f',
          jobId: 'a0h2v00000ManntAAB',
          jobCode: '1',
          jobName: '開発',
          hasJobType: true,
          isDirectCharged: false,
          workCategoryId: 'a1G2v000003yt73EAA',
          workCategoryName: '研修',
          workCategoryCode: '4',
          color: {
            base: '#6fbeda',
            linked: '#5592a8',
          },
          isDirectInput: true,
          volume: null,
          ratio: null,
          taskTime: 60,
          eventTaskTime: 0,
        },
        {
          id: 'ed5fd445-531e-4f60-818f-abfd7ecabd7a',
          jobId: 'a0h2v00000a4y34AAA',
          jobCode: '3',
          jobName: '1',
          hasJobType: true,
          isDirectCharged: true,
          workCategoryId: 'a1G2v000003z0jkEAA',
          workCategoryName: 'イベント',
          workCategoryCode: '7',
          color: {
            base: '#79cca6',
            linked: '#5d9d80',
          },
          isDirectInput: true,
          volume: null,
          ratio: null,
          taskTime: 0,
          eventTaskTime: 0,
        },
        {
          id: '6d9c0f34-38d4-424a-926e-a6cd98ae28af',
          jobId: 'a0h2v00000ManntAAB',
          jobCode: '1',
          jobName: '開発',
          hasJobType: true,
          isDirectCharged: false,
          workCategoryId: null,
          workCategoryName: null,
          workCategoryCode: null,
          color: {
            base: '#8bcd77',
            linked: '#6b9e5b',
          },
          isDirectInput: true,
          volume: null,
          ratio: null,
          taskTime: 0,
          eventTaskTime: 0,
        },
        {
          id: '01be1c41-9afd-4d13-b576-4fbb6933baeb',
          jobId: 'a0h2v00000cwWbdAAE',
          jobCode: '4',
          jobName: '外部活動',
          hasJobType: false,
          isDirectCharged: true,
          workCategoryId: null,
          workCategoryName: null,
          workCategoryCode: null,
          color: {
            base: '#cdc050',
            linked: '#9e943d',
          },
          isDirectInput: true,
          volume: null,
          ratio: null,
          taskTime: 0,
          eventTaskTime: 0,
        },
        {
          id: '737adc11-4df6-469c-8f6f-f5cce10b6399',
          jobId: 'a0h2v00000ManntAAB',
          jobCode: '1',
          jobName: '開発',
          hasJobType: true,
          isDirectCharged: false,
          workCategoryId: 'a1G2v000003z0C2EAI',
          workCategoryName: '検討',
          workCategoryCode: '6',
          color: {
            base: '#ce9a42',
            linked: '#9e7633',
          },
          isDirectInput: true,
          volume: null,
          ratio: null,
          taskTime: 0,
          eventTaskTime: 0,
        },
        {
          id: '2cca26e1-24a0-4898-9acd-74cc6bc6ccee',
          jobId: 'a0h2v00000ManntAAB',
          jobCode: '1',
          jobName: '開発',
          hasJobType: true,
          isDirectCharged: false,
          workCategoryId: 'a1G2v000004cm8PEAQ',
          workCategoryName:
            '長いジョブ長いジョブ長いジョブ長いジョブ長いジョブ長いジョブ長いジョブ長いジョブ長いジョブ長いジョブ長いジョブ長いジョブ',
          workCategoryCode: '8',
          color: {
            base: '#cd7a49',
            linked: '#9e5e38',
          },
          isDirectInput: true,
          volume: null,
          ratio: null,
          taskTime: 0,
          eventTaskTime: 0,
        },
        {
          id: '9b27e034-c916-4cbe-8e23-18d675013af6',
          jobId: 'a0h2v00000a4y2zAAA',
          jobCode: '2',
          jobName: 'その他',
          hasJobType: true,
          isDirectCharged: true,
          workCategoryId: null,
          workCategoryName: null,
          workCategoryCode: null,
          color: {
            base: '#d38078',
            linked: '#a2625c',
          },
          isDirectInput: true,
          volume: null,
          ratio: null,
          taskTime: 0,
          eventTaskTime: 0,
        },
      ],
      originalTaskList: [
        {
          id: '344e3227-ff0d-45a0-89b4-93f796020fd6',
          jobId: 'a0h2v00000ManntAAB',
          jobCode: '1',
          jobName: '開発',
          hasJobType: true,
          isDirectCharged: false,
          workCategoryId: 'a1G2v000003yt6oEAA',
          workCategoryName: 'コーディング',
          workCategoryCode: '1',
          color: {
            base: '#0083b6',
            linked: '#00658c',
          },
          isDirectInput: true,
          volume: null,
          ratio: null,
          taskTime: 330,
          eventTaskTime: 330,
        },
        {
          id: '2d7593c5-9f38-4dc4-8d9b-dfa24ec3ea76',
          jobId: 'a0h2v00000ManntAAB',
          jobCode: '1',
          jobName: '開発',
          hasJobType: true,
          isDirectCharged: false,
          workCategoryId: 'a1G2v000003yt78EAA',
          workCategoryName: 'リクルーティング',
          workCategoryCode: '5',
          color: {
            base: '#00a3df',
            linked: '#007dab',
          },
          isDirectInput: true,
          volume: null,
          ratio: null,
          taskTime: 60,
          eventTaskTime: 60,
        },
        {
          id: '6c439377-d1bb-405b-84ce-937b4fbaf08f',
          jobId: 'a0h2v00000ManntAAB',
          jobCode: '1',
          jobName: '開発',
          hasJobType: true,
          isDirectCharged: false,
          workCategoryId: 'a1G2v000003yt73EAA',
          workCategoryName: '研修',
          workCategoryCode: '4',
          color: {
            base: '#6fbeda',
            linked: '#5592a8',
          },
          isDirectInput: true,
          volume: null,
          ratio: null,
          taskTime: 60,
          eventTaskTime: 0,
        },
        {
          id: 'ed5fd445-531e-4f60-818f-abfd7ecabd7a',
          jobId: 'a0h2v00000a4y34AAA',
          jobCode: '3',
          jobName: '1',
          hasJobType: true,
          isDirectCharged: true,
          workCategoryId: 'a1G2v000003z0jkEAA',
          workCategoryName: 'イベント',
          workCategoryCode: '7',
          color: {
            base: '#79cca6',
            linked: '#5d9d80',
          },
          isDirectInput: true,
          volume: null,
          ratio: null,
          taskTime: 0,
          eventTaskTime: 0,
        },
        {
          id: '6d9c0f34-38d4-424a-926e-a6cd98ae28af',
          jobId: 'a0h2v00000ManntAAB',
          jobCode: '1',
          jobName: '開発',
          hasJobType: true,
          isDirectCharged: false,
          workCategoryId: null,
          workCategoryName: null,
          workCategoryCode: null,
          color: {
            base: '#8bcd77',
            linked: '#6b9e5b',
          },
          isDirectInput: true,
          volume: null,
          ratio: null,
          taskTime: 0,
          eventTaskTime: 0,
        },
        {
          id: '01be1c41-9afd-4d13-b576-4fbb6933baeb',
          jobId: 'a0h2v00000cwWbdAAE',
          jobCode: '4',
          jobName: '外部活動',
          hasJobType: false,
          isDirectCharged: true,
          workCategoryId: null,
          workCategoryName: null,
          workCategoryCode: null,
          color: {
            base: '#cdc050',
            linked: '#9e943d',
          },
          isDirectInput: true,
          volume: null,
          ratio: null,
          taskTime: 0,
          eventTaskTime: 0,
        },
        {
          id: '737adc11-4df6-469c-8f6f-f5cce10b6399',
          jobId: 'a0h2v00000ManntAAB',
          jobCode: '1',
          jobName: '開発',
          hasJobType: true,
          isDirectCharged: false,
          workCategoryId: 'a1G2v000003z0C2EAI',
          workCategoryName: '検討',
          workCategoryCode: '6',
          color: {
            base: '#ce9a42',
            linked: '#9e7633',
          },
          isDirectInput: true,
          volume: null,
          ratio: null,
          taskTime: 0,
          eventTaskTime: 0,
        },
        {
          id: '2cca26e1-24a0-4898-9acd-74cc6bc6ccee',
          jobId: 'a0h2v00000ManntAAB',
          jobCode: '1',
          jobName: '開発',
          hasJobType: true,
          isDirectCharged: false,
          workCategoryId: 'a1G2v000004cm8PEAQ',
          workCategoryName:
            '長いジョブ長いジョブ長いジョブ長いジョブ長いジョブ長いジョブ長いジョブ長いジョブ長いジョブ長いジョブ長いジョブ長いジョブ',
          workCategoryCode: '8',
          color: {
            base: '#cd7a49',
            linked: '#9e5e38',
          },
          isDirectInput: true,
          volume: null,
          ratio: null,
          taskTime: 0,
          eventTaskTime: 0,
        },
        {
          id: '9b27e034-c916-4cbe-8e23-18d675013af6',
          jobId: 'a0h2v00000a4y2zAAA',
          jobCode: '2',
          jobName: 'その他',
          hasJobType: true,
          isDirectCharged: true,
          workCategoryId: null,
          workCategoryName: null,
          workCategoryCode: null,
          color: {
            base: '#d38078',
            linked: '#a2625c',
          },
          isDirectInput: true,
          volume: null,
          ratio: null,
          taskTime: 0,
          eventTaskTime: 0,
        },
      ],
      realWorkTime: 540,
      isTemporaryWorkTime: false,
      isJobSelectDialogOpened: false,
    },
    eventListPopup: {
      isOpen: false,
      date: null,
      top: 0,
      left: 0,
    },
    blocking: {
      enabled: false,
    },
  },
  toast: {
    isShow: false,
    message: '',
  },
};
