export const SHOW_DIALOG = 'SHOW_DIALOG';
export const HIDE_DIALOG = 'HIDE_DIALOG';

export const DIALOG_TYPE = {
  ADD_RECORD: 'ADD_RECORD',
  APPROVAL_HISTORY: 'APPROVAL_HISTORY',
  APPROVAL_REQUEST: 'APPROVAL_REQUEST',
  COST_CENTER_FINDER: 'COST_CENTER_FINDER',
  EXP_TYPE_FINDER: 'EXP_TYPE_FINDER',
  JOB_FINDER: 'JOB_FINDER',
  PAYMENT_DATE_SETTING: 'PAYMENT_DATE_SETTING',
  PAY_METHOD_SETTING: 'PAY_METHOD_SETTING',
  SEARCH_EXP_REPORT: 'SEARCH_EXP_REPORT',
  ATTENDANCE_FIX_DAILY: 'ATTENDANCE_FIX_DAILY',
  ATTENDANCE_INPUT: 'ATTENDANCE_INPUT',
  ATTENDANCE_APPLICATION_VACATION: 'ATTENDANCE_APPLICATION_VACATION',
  APPROVAL_LIST: 'APPROVAL_LIST',
  TIME_TRACKING_CONTROL: 'TIME_TRACKING_CONTROL',
  ROUTE_SEARCH_RESULT: 'ROUTE_SEARCH_RESULT',
  ADMIN: 'ADMIN',
};

export function showDialog(type) {
  return {
    type: SHOW_DIALOG,
    payload: {
      show: true,
      type,
    },
  };
}

export function hideDialog() {
  return {
    type: HIDE_DIALOG,
  };
}
