export const CALENDAR_CREATED_SERVICE_BY_SALESFORCE = 'salesforce';
export const CALENDAR_CREATED_SERVICE_BY_MICROSOFT365 = 'microsoft365';
export const CALENDAR_CREATED_SERVICE_BY_GOOGLE = 'google';
export const CALENDAR_CREATED_SERVICE_BY_TEAMSPIRIT = 'teamspirit';

export const DATETIME_FORMAT_FOR_EVENT_DATA_KEY = 'YYYYMMDD';
