import React from 'react';
import { Provider } from 'react-redux';
import renderer from 'react-test-renderer';
import configureStore from 'redux-mock-store';
import thunk from 'redux-thunk';

import ScheduleDetailsContainer from '../ScheduleDetailsContainer';

const mockStore = configureStore([thunk]);

const state = {
  common: {
    app: {
      loadingDepth: 0,
      loadingHint: '',
      error: null,
      unexpectedError: null,
      confirmDialog: null,
      loadingAreas: [],
    },
    accessControl: {
      permission: {
        viewAttTimeSheetByDelegate: false,
        editAttTimeSheetByDelegate: false,
        viewTimeTrackByDelegate: false,
        editTimeTrackByDelegate: false,
        submitAttDailyRequestByDelegate: false,
        cancelAttDailyRequestByDelegate: false,
        approveSelfAttDailyRequestByEmployee: false,
        approveAttDailyRequestByDelegate: false,
        cancelAttDailyApprovalByEmployee: false,
        cancelAttDailyApprovalByDelegate: false,
        approveSelfAttRequestByEmployee: false,
        submitAttRequestByDelegate: false,
        cancelAttRequestByDelegate: false,
        approveAttRequestByDelegate: false,
        cancelAttApprovalByEmployee: false,
        cancelAttApprovalByDelegate: false,
        submitTimeRequestByDelegate: false,
        cancelTimeRequestByDelegate: false,
        cancelTimeApprovalByEmployee: false,
        cancelTimeApprovalByDelegate: false,
        manageOverallSetting: false,
        switchCompany: false,
        manageDepartment: false,
        manageEmployee: false,
        manageCalendar: false,
        manageJobType: false,
        manageJob: false,
        manageMobileSetting: false,
        managePermission: false,
        managePlannerSetting: false,
        manageAttLeave: false,
        manageAttShortTimeWorkSetting: false,
        manageAttLeaveOfAbsence: false,
        manageAttWorkingType: false,
        manageAttPattern: false,
        manageAttAgreementAlertSetting: false,
        manageAttLeaveGrant: false,
        manageAttShortTimeWorkSettingApply: false,
        manageAttLeaveOfAbsenceApply: false,
        manageAttPatternApply: false,
        manageAttShortTimeSettingApply: false,
        manageTimeSetting: false,
        manageTimeWorkCategory: false,
        managePosition: false,
        manageOrgHPattern: false,
        manageExpTypeGroup: false,
        manageExpenseType: false,
        manageTaxType: false,
        manageExpSetting: false,
        manageExchangeRate: false,
        manageAccountingPeriod: false,
        manageReportType: false,
        manageCostCenter: false,
        manageVendor: false,
        manageExtendedItem: false,
        manageEmployeeGroup: false,
        manageExpCustomHint: false,
        managePsaSetting: false,
        managePsaJobGrade: false,
        managePsaSkillset: false,
        managePsaExtendedItem: false,
        managePsaGroup: false,
        canBulkApproveAttRequest: false,
        canBulkApproveAttDailyRequest: false,
      },
    },
    dialog: {
      show: false,
    },
    delegateApprovalDialog: {
      isNewAssignment: false,
    },
    empInfo: {
      isFetching: false,
      didInvalidate: false,
      record: {},
      startDayOfTheWeek: 0,
    },
    proxyEmployeeInfo: {
      isProxyMode: false,
      id: '',
      employeeCode: '',
      employeeName: '',
      employeePhotoUrl: '',
      departmentCode: '',
      departmentName: '',
      title: '',
      managerName: '',
    },
    targetEmpId: '',
    approverEmployeeSetting: {
      entities: {
        id: '',
        employeeName: '',
      },
      ui: {
        dialog: {
          isOpen: false,
          type: '',
        },
        status: {
          isReadOnly: true,
          targetDate: '',
        },
      },
    },
    approverEmployeeSearch: {
      ui: {
        dialog: {
          isOpen: false,
          type: '',
        },
        operation: {
          searchStrategy: 1,
          isSearchByQueriesExecuted: false,
          departmentCode: '',
          departmentName: '',
          employeeCode: '',
          employeeName: '',
          title: '',
          targetDate: '',
          selectedEmployeeId: '',
          isOverLimit: false,
        },
      },
      entities: {
        allIds: [],
        byId: {},
      },
    },
    approvalHistoryList: [],
    jobList: [],
    expTypeList: [],
    expTaxTypeList: [],
    costCenterList: [],
    selectedTab: 'NONE',
    currencyList: [],
    suggestInput: {
      origin: {
        selectSuggestion: {},
        suggestions: [],
        status: 'INITIAL',
        value: '',
      },
      arrival: {
        selectSuggestion: {},
        suggestions: [],
        status: 'INITIAL',
        value: '',
      },
      via1: {
        selectSuggestion: {},
        suggestions: [],
        status: 'INITIAL',
        value: '',
      },
      via2: {
        selectSuggestion: {},
        suggestions: [],
        status: 'INITIAL',
        value: '',
      },
      via3: {
        selectSuggestion: {},
        suggestions: [],
        status: 'INITIAL',
        value: '',
      },
      via4: {
        selectSuggestion: {},
        suggestions: [],
        status: 'INITIAL',
        value: '',
      },
    },
    searchedRoute: {},
    standaloneMode: {
      enabled: false,
    },
    stationHistoryList: [],
    userSetting: {
      useWorkTime: true,
      useTransitManager: false,
      useTimeTrackingChargeTransfer: false,
      userName: 'test-sompbvpuqzpd@example.com',
      useReceiptScan: false,
      usePsa: true,
      usePlanner: true,
      usePersonalVendor: true,
      useMasterCardImport: false,
      useJobSearchAndSelect: false,
      useImageQualityCheck: false,
      useExpenseRequest: true,
      useExpense: true,
      useCompanyVendor: true,
      useAttendance: true,
      timeZone: 'Asia/Singapore',
      sfCompanyDefaultCurrencyCode: null,
      salesId: null,
      photoUrl:
        'https://nosoftware-drive-2817-dev-ed--c.documentforce.com/profilephoto/005/T',
      organizationSetting: {
        language2: null,
        language1: 'ja',
        language0: 'en_US',
      },
      organization: {
        isSandbox: true,
        id: '00DN0000000T2b5MAC',
        enableErrorTracking: false,
      },
      name: 'User User',
      managerName: 'Sista Aadmi',
      locale: 'en-SG',
      language: 'en-US',
      id: '005N000000Ax8CsIAJ',
      expTaxRoundingSetting: 'Round',
      expRoundingSetting: 'Round',
      expAttendanceValidation: true,
      employeeName: 'Sista Aadmi',
      employeeId: 'a0kN000000EeVq5IAF',
      employeeCode: 'TDEMP000',
      empHistoryValidTo: '2101-01-01',
      empHistoryValidFrom: '2021-12-01',
      empGroupId: null,
      departmentName: 'DEPARTMENT QA',
      departmentId: 'a0iN000000kVMYbIAO',
      departmentCode: 'DEP001',
      customerId: null,
      currencySymbol: '',
      currencyName: 'Japanese Yen',
      currencyId: 'a0dN000000HNDCzIAP',
      currencyDecimalPlaces: 0,
      currencyCode: 'JPY',
      costCenterName: null,
      costCenterHistoryId: null,
      costCenterCode: null,
      companyName: 'WSP AUTO API',
      companyId: 'a0YN000000CSVR2MAP',
      belongsToResourceGroup: true,
      approver01Name: null,
      allowToChangeApproverSelf: null,
      allowTaxExcludedAmountInput: false,
      allowTaxAmountChange: false,
      allowLinkedFileDelete: false,
      allowApproveExpInDiffCompany: null,
    },
    personalSetting: {
      plannerDefaultView: 'Weekly',
      isTimeTrackSummaryOpenByDefault: false,
    },
    personalSettingDialog: {
      isVisible: false,
      selectedGroup: 'TIME_TRACKING',
      newPersonalSetting: {
        plannerDefaultView: 'Weekly',
      },
    },
    jobSelectDialog: {
      isVisible: false,
    },
    stampWidget: {
      isEnableStartStamp: false,
      isEnableEndStamp: false,
      isEnableRestartStamp: false,
      mode: null,
      message: '',
    },
    toast: {
      isShow: false,
      message: '',
    },
  },
  userSetting: {
    useWorkTime: true,
    useTransitManager: false,
    useTimeTrackingChargeTransfer: false,
    userName: 'test-sompbvpuqzpd@example.com',
    useReceiptScan: false,
    usePsa: true,
    usePlanner: true,
    usePersonalVendor: true,
    useMasterCardImport: false,
    useJobSearchAndSelect: false,
    useImageQualityCheck: false,
    useExpenseRequest: true,
    useExpense: true,
    useCompanyVendor: true,
    useAttendance: true,
    timeZone: 'Asia/Singapore',
    sfCompanyDefaultCurrencyCode: null,
    salesId: null,
    photoUrl:
      'https://nosoftware-drive-2817-dev-ed--c.documentforce.com/profilephoto/005/T',
    organizationSetting: {
      language2: null,
      language1: 'ja',
      language0: 'en_US',
    },
    organization: {
      isSandbox: true,
      id: '00DN0000000T2b5MAC',
      enableErrorTracking: false,
    },
    name: 'User User',
    managerName: 'Sista Aadmi',
    locale: 'en-SG',
    language: 'en-US',
    id: '005N000000Ax8CsIAJ',
    expTaxRoundingSetting: 'Round',
    expRoundingSetting: 'Round',
    expAttendanceValidation: true,
    employeeName: 'Sista Aadmi',
    employeeId: 'a0kN000000EeVq5IAF',
    employeeCode: 'TDEMP000',
    empHistoryValidTo: '2101-01-01',
    empHistoryValidFrom: '2021-12-01',
    empGroupId: null,
    departmentName: 'DEPARTMENT QA',
    departmentId: 'a0iN000000kVMYbIAO',
    departmentCode: 'DEP001',
    customerId: null,
    currencySymbol: '',
    currencyName: 'Japanese Yen',
    currencyId: 'a0dN000000HNDCzIAP',
    currencyDecimalPlaces: 0,
    currencyCode: 'JPY',
    costCenterName: null,
    costCenterHistoryId: null,
    costCenterCode: null,
    companyName: 'WSP AUTO API',
    companyId: 'a0YN000000CSVR2MAP',
    belongsToResourceGroup: true,
    approver01Name: null,
    allowToChangeApproverSelf: null,
    allowTaxExcludedAmountInput: false,
    allowTaxAmountChange: false,
    allowLinkedFileDelete: false,
    allowApproveExpInDiffCompany: null,
  },
  ui: {
    siteRoute: 'RESOURCE_PLANNER',
    sidebar: 'ACTIVITY',
    mode: 'DIRECT_ASSIGNMENT',
    tab: 'Projects',
    filter: {
      project: {
        projectTitle: '',
        projectCode: '',
        projectManagerCode: '',
        clientName: '',
        jobId: '',
        deptName: '',
        requester: '',
        requesterCode: '',
        projectManager: 'Sista Aadmi',
        projectStartDate: ['', ''],
        projectEndDate: ['2022-02-20', ''],
        statusList: ['Planning', 'InProgress'],
      },
      viewAllResources: {
        startDate: '2022-02-01',
        endDate: '2023-02-28',
        code: '',
        departmentName: '',
        isDateFilterNotApplied: true,
        jobGradeIds: null,
        name: '',
        position: '',
        requiredTime: 0,
        resourceGroups: null,
        resourceManager: null,
        rmId: '',
        skills: [],
      },
      resourceSelection: {
        startDate: '2022-03-01',
        endDate: '2022-07-24',
        code: '',
        departmentName: '',
        isDateFilterNotApplied: true,
        jobGradeIds: [],
        name: '',
        position: '',
        requiredTime: 11040,
        resourceGroups: [
          {
            id: 'a1lN000000CFCbxIAH',
            name: 'TD Resource Group 01',
          },
        ],
        resourceManager: null,
        rmId: '',
        skills: [],
      },
      requestSelection: {
        assignmentDueDate: ['', ''],
        clientName: '',
        deptId: '',
        jobGradeIds: [],
        pmName: '',
        pmCode: '',
        projectCode: '',
        projectJobId: '',
        projectTitle: '',
        receivedDate: ['', ''],
        requestCode: '',
        requesterName: '',
        requesterCode: '',
        resourceGroup: '',
        rmName: '',
        roleStartDate: ['', ''],
        roleTitle: '',
        statusList: ['Requested', 'Scheduling'],
      },
      roleRequest: {
        assignmentDueDate: ['', ''],
        clientName: '',
        deptId: '',
        jobGradeIds: [],
        pmName: '',
        pmCode: '',
        projectCode: '',
        projectJobId: '',
        projectTitle: '',
        receivedDate: ['', ''],
        requestCode: '',
        requesterName: '',
        requesterCode: '',
        resourceGroup: '',
        rmName: '',
        roleStartDate: ['', ''],
        roleTitle: '',
        statusList: ['Requested', 'Scheduling'],
      },
    },
    dialog: {
      activeDialog: [],
    },
    resourceAvailability: {
      availableHours: [],
    },
    resourceAssignmentDetail: {
      bookedTimePerDay: [],
    },
    resourceSelection: {
      currentState: 'SELECT_STRATEGY',
      currentIndex: 0,
      currentStrategy: 'AdjustConsiderAvailability',
      currentWorkHoursPerDay: 8,
      currentWorkHoursPercentPerDay: 100,
      resource: {
        position: null,
        photoUrl:
          'https://nosoftware-drive-2817-dev-ed--c.documentforce.com/profilephoto/005/T',
        name: 'Sista Aadmi',
        matchedSkills: 0,
        jobGradeName: '',
        jobGradeCode: '',
        id: 'a0kN000000EeVq5IAF',
        historyId: 'a0lN0000003stjOIAQ',
        departmentName: 'DEPARTMENT QA',
        departmentCode: 'DEP001',
        code: 'TDEMP000',
        availableTime: 47040,
        availability: [
          480, 480, 480, 480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480,
          480, 480, 480, 0, 0, 0, 480, 480, 480, 480, 0, 0, 480, 480, 480, 480,
          480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480, 480, 480, 480, 0,
          0, 480, 480, 480, 480, 480, 0, 0, 480, 480, 480, 480, 0, 0, 0, 480, 0,
          0, 0, 480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480, 480, 480,
          480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480, 480, 480, 480, 0,
          0, 480, 480, 480, 480, 480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480,
          480, 480, 480, 480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480,
          480, 480, 480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 0, 480, 480, 480,
          480, 0, 0,
        ],
        hasAssignment: true,
      },
    },
    isLoading: false,
  },
  entities: {
    psa: {
      access: {
        canConfirmProjectRoles: true,
        canUploadProjectRoles: true,
      },
      psaGroup: {
        selectedGroup: {
          code: 'PSAG001',
          companyId: 'a0Y6D000001oEHEUA2',
          groupType: 'PsaGroup',
          id: 'a1l6D000001lgKtQAI',
          isOwned: null,
          name: 'PSA Group 1',
          name_L0: 'PSA Group 1',
          name_L1: 'PSA Group 1',
        },
      },
      activity: {
        activityList: [
          {
            title: 'TD QA Activity',
            status: 'InProgress',
            roles: [
              {
                status: 'Requested',
                startDate: '2022-01-25',
                roleTitle: 'Copy of Copy of role 1',
                roleId: 'a1cN000000355G8IAI',
                isDirectAssign: false,
                endDate: '2022-02-24',
                assignmentDueDate: '2022-01-25',
                requestNo: '0000000002',
                requesterPhotoUrl:
                  'https://nosoftware-drive-2817-dev-ed--c.documentforce.com/profilephoto/005/T',
                requesterName: 'Sista Aadmi',
                requesterId: 'a0kN000000EeVq5IAF',
                employeePhotoUrl: null,
                employeeName: null,
                employeeBaseId: null,
                assignmentId: null,
              },
              {
                status: 'Planning',
                startDate: '2022-02-04',
                roleTitle: 'Copy of role 1',
                roleId: 'a1cN000000356TzIAI',
                isDirectAssign: false,
                endDate: '2022-02-24',
                assignmentDueDate: '2022-02-04',
                requestNo: '0000000003',
                requesterPhotoUrl: null,
                requesterName: null,
                requesterId: null,
                employeePhotoUrl: null,
                employeeName: null,
                employeeBaseId: null,
                assignmentId: null,
              },
              {
                status: 'Planning',
                startDate: '2022-03-01',
                roleTitle: 'Copy of Role -2561Test-Original role',
                roleId: 'a1cN000000358zwIAA',
                isDirectAssign: false,
                endDate: '2022-03-31',
                assignmentDueDate: '2022-02-05',
                requestNo: '0000000016',
                requesterPhotoUrl: null,
                requesterName: null,
                requesterId: null,
                employeePhotoUrl: null,
                employeeName: null,
                employeeBaseId: null,
                assignmentId: null,
              },
              {
                status: 'Planning',
                startDate: '2022-01-25',
                roleTitle: 'role 1',
                roleId: 'a1cN000000355FyIAI',
                isDirectAssign: false,
                endDate: '2022-02-24',
                assignmentDueDate: '2022-01-25',
                requestNo: '0000000000',
                requesterPhotoUrl: null,
                requesterName: null,
                requesterId: null,
                employeePhotoUrl: null,
                employeeName: null,
                employeeBaseId: null,
                assignmentId: null,
              },
              {
                status: 'Planning',
                startDate: '2022-03-01',
                roleTitle: 'Copy of Copy of Role -2561Test-Original role',
                roleId: 'a1cN0000003590aIAA',
                isDirectAssign: false,
                endDate: '2022-03-31',
                assignmentDueDate: '2022-02-07',
                requestNo: '0000000018',
                requesterPhotoUrl: null,
                requesterName: null,
                requesterId: null,
                employeePhotoUrl: null,
                employeeName: null,
                employeeBaseId: null,
                assignmentId: null,
              },
              {
                status: 'Completed',
                startDate: '2022-02-07',
                roleTitle: 'AUT 07/02/2022-1644215371RM',
                roleId: 'a1cN0000003592wIAA',
                isDirectAssign: false,
                endDate: '2022-02-07',
                assignmentDueDate: '2022-02-07',
                requestNo: '0000000029',
                requesterPhotoUrl:
                  'https://nosoftware-drive-2817-dev-ed--c.documentforce.com/profilephoto/005/T',
                requesterName: 'Sista Aadmi',
                requesterId: 'a0kN000000EeVq5IAF',
                employeePhotoUrl:
                  'https://nosoftware-drive-2817-dev-ed--c.documentforce.com/profilephoto/005/T',
                employeeName: 'Sista Aadmi',
                employeeBaseId: 'a0kN000000EeVq5IAF',
                assignmentId: null,
              },
              {
                status: 'InProgress',
                startDate: '2022-02-07',
                roleTitle: 'Reverse 07/02/2022-1644216027',
                roleId: 'a1cN0000003593aIAA',
                isDirectAssign: false,
                endDate: '2022-02-07',
                assignmentDueDate: '2022-02-07',
                requestNo: '0000000037',
                requesterPhotoUrl:
                  'https://nosoftware-drive-2817-dev-ed--c.documentforce.com/profilephoto/005/T',
                requesterName: 'Sista Aadmi',
                requesterId: 'a0kN000000EeVq5IAF',
                employeePhotoUrl:
                  'https://nosoftware-drive-2817-dev-ed--c.documentforce.com/profilephoto/005/T',
                employeeName: 'Stan Usou',
                employeeBaseId: 'a0kN000000EeVqAIAV',
                assignmentId: null,
              },
              {
                status: 'Planning',
                startDate: '2022-02-04',
                roleTitle: 'Role -2561Test-Original role',
                roleId: 'a1cN000000356U4IAI',
                isDirectAssign: false,
                endDate: '2022-07-24',
                assignmentDueDate: '2022-02-02',
                requestNo: '0000000004',
                requesterPhotoUrl: null,
                requesterName: null,
                requesterId: null,
                employeePhotoUrl: null,
                employeeName: null,
                employeeBaseId: null,
                assignmentId: null,
              },
              {
                status: 'Cancelled',
                startDate: '2022-02-07',
                roleTitle: 'AUT 07/02/2022-1644215371Decline',
                roleId: 'a1cN0000003593GIAQ',
                isDirectAssign: false,
                endDate: '2022-06-07',
                assignmentDueDate: '2022-02-07',
                requestNo: '0000000033',
                requesterPhotoUrl:
                  'https://nosoftware-drive-2817-dev-ed--c.documentforce.com/profilephoto/005/T',
                requesterName: 'Sista Aadmi',
                requesterId: 'a0kN000000EeVq5IAF',
                employeePhotoUrl: null,
                employeeName: null,
                employeeBaseId: null,
                assignmentId: null,
              },
            ],
            projectId: 'a1uN0000002Wj84IAC',
            plannedStartDate: '2022-01-25',
            plannedEndDate: '2022-07-24',
            leadPhotoUrl: null,
            leadName: null,
            leadBaseId: null,
            activityId: 'a1dN0000006Uus5IAC',
          },
        ],
        activity: {
          title: 'TD QA Activity',
          status: 'InProgress',
          roles: [],
          projectId: 'a1uN0000002Wj84IAC',
          plannedStartDate: '2022-01-25',
          plannedEndDate: '2022-07-24',
          leadPhotoUrl: null,
          leadName: null,
          leadBaseId: null,
          activityId: 'a1dN0000006Uus5IAC',
          projectStatus: 'InProgress',
          projectStartDate: '2022-01-25',
          projectName: 'TD QA Project',
          projectEndDate: '2023-01-25',
          jobId: 'a0xN0000003qVKOIA2',
          jobCode: 'TDC_TDAC001',
          description: null,
          code: 'TDAC001',
          closeDate: null,
        },
      },
      assignment: {
        assignment: {
          activityId: '',
          assigneeBaseId: '',
          assigneeName: '',
          assigneePhotoUrl: '',
          assignmentId: '',
          description: '',
          endDate: '',
          eventId: '',
          numOfWorkDays: '0',
          projectId: '',
          role: '',
          startDate: '',
          totalWorkHours: '0',
          workTimePerDay: '0',
        },
      },
      capabilityInfo: {
        activitiesNum: 0,
        assignments: [],
        empCode: '',
        empDeptName: '',
        empEmail: '',
        empGrade: '',
        empHiredDate: '',
        empId: '',
        empName_L0: '',
        empName_L1: '',
        empNameL: '',
        empPhotoUrl: '',
        empPosition: '',
        id: '',
        links: [],
        personalInfoId: '',
        personalInfoUrl: '',
        projectNum: 0,
        remarks: '',
        skills: [],
      },
      project: {
        totalRecords: 32,
        totalPages: 4,
        pageSize: 10,
        pageNum: 1,
        pageData: [
          {
            workTimePerDay: 480,
            status: 'InProgress',
            startDate: '2022-01-25',
            projectJobCode: 'TDC',
            projectId: 'a1uN0000002Wj84IAC',
            pmName: 'Sista Aadmi',
            pmBaseId: 'a0kN000000EeVq5IAF',
            name: 'TD QA Project',
            endDate: '2023-01-25',
            deptName: null,
            currentDetailId: 'a1qN0000003cg3mIAA',
            companyId: 'a0YN000000CSVR2MAP',
            clientName: null,
            clientId: null,
          },
          {
            workTimePerDay: 480,
            status: 'InProgress',
            startDate: '2022-02-07',
            projectJobCode: 'TDC',
            projectId: 'a1uN0000002Wq3gIAC',
            pmName: 'Sista Aadmi',
            pmBaseId: 'a0kN000000EeVq5IAF',
            name: 'Auto Project 1644212831St',
            endDate: '2022-12-31',
            deptName: null,
            currentDetailId: 'a1qN0000003chZYIAY',
            companyId: 'a0YN000000CSVR2MAP',
            clientName: null,
            clientId: null,
          },
          {
            workTimePerDay: 600,
            status: 'InProgress',
            startDate: '2022-02-07',
            projectJobCode: 'TDC',
            projectId: 'a1uN0000002Wq4tIAC',
            pmName: 'Sista Aadmi',
            pmBaseId: 'a0kN000000EeVq5IAF',
            name: 'Auto Project 1644214630St',
            endDate: '2022-12-31',
            deptName: null,
            currentDetailId: 'a1qN0000003chbKIAQ',
            companyId: 'a0YN000000CSVR2MAP',
            clientName: null,
            clientId: null,
          },
          {
            workTimePerDay: 600,
            status: 'InProgress',
            startDate: '2022-02-07',
            projectJobCode: 'TDC',
            projectId: 'a1uN0000002Wq5XIAS',
            pmName: 'Sista Aadmi',
            pmBaseId: 'a0kN000000EeVq5IAF',
            name: 'Auto Project 1644215151St',
            endDate: '2022-12-31',
            deptName: null,
            currentDetailId: 'a1qN0000003chc3IAA',
            companyId: 'a0YN000000CSVR2MAP',
            clientName: null,
            clientId: null,
          },
          {
            workTimePerDay: 480,
            status: 'InProgress',
            startDate: '2022-02-04',
            projectJobCode: 'TDJOB001',
            projectId: 'a1uN0000002WpPFIA0',
            pmName: 'Sista Aadmi',
            pmBaseId: 'a0kN000000EeVq5IAF',
            name: 'Test -2561',
            endDate: '2022-02-28',
            deptName: null,
            currentDetailId: 'a1qN0000003chWkIAI',
            companyId: 'a0YN000000CSVR2MAP',
            clientName: null,
            clientId: null,
          },
          {
            workTimePerDay: 480,
            status: 'InProgress',
            startDate: '2022-02-07',
            projectJobCode: 'TDJOB001',
            projectId: 'a1uN0000002Wq3WIAS',
            pmName: 'Sista Aadmi',
            pmBaseId: 'a0kN000000EeVq5IAF',
            name: 'Project Activity1644212960',
            endDate: '2022-07-07',
            deptName: null,
            currentDetailId: 'a1qN0000003chZEIAY',
            companyId: 'a0YN000000CSVR2MAP',
            clientName: null,
            clientId: null,
          },
          {
            workTimePerDay: 480,
            status: 'InProgress',
            startDate: '2022-02-07',
            projectJobCode: 'TDJOB001',
            projectId: 'a1uN0000002Wq3lIAC',
            pmName: 'Sista Aadmi',
            pmBaseId: 'a0kN000000EeVq5IAF',
            name: 'Scheduling 1644212999',
            endDate: '2022-03-07',
            deptName: null,
            currentDetailId: 'a1qN0000003chZTIAY',
            companyId: 'a0YN000000CSVR2MAP',
            clientName: null,
            clientId: null,
          },
          {
            workTimePerDay: 480,
            status: 'InProgress',
            startDate: '2022-02-07',
            projectJobCode: 'TDJOB001',
            projectId: 'a1uN0000002Wq3qIAC',
            pmName: 'Sista Aadmi',
            pmBaseId: 'a0kN000000EeVq5IAF',
            name: 'Rescheduling 1644213008',
            endDate: '2022-12-31',
            deptName: null,
            currentDetailId: 'a1qN0000003chZdIAI',
            companyId: 'a0YN000000CSVR2MAP',
            clientName: null,
            clientId: null,
          },
          {
            workTimePerDay: 480,
            status: 'InProgress',
            startDate: '2022-02-07',
            projectJobCode: 'TDJOB001',
            projectId: 'a1uN0000002Wq40IAC',
            pmName: 'Sista Aadmi',
            pmBaseId: 'a0kN000000EeVq5IAF',
            name: 'COMMENT 1644213110',
            endDate: '2022-02-21',
            deptName: null,
            currentDetailId: 'a1qN0000003chZnIAI',
            companyId: 'a0YN000000CSVR2MAP',
            clientName: null,
            clientId: null,
          },
          {
            workTimePerDay: 600,
            status: 'InProgress',
            startDate: '2022-02-07',
            projectJobCode: 'TDJOB001',
            projectId: 'a1uN0000002Wq4KIAS',
            pmName: 'Sista Aadmi',
            pmBaseId: 'a0kN000000EeVq5IAF',
            name: 'Edit Schedule 1644213404',
            endDate: '2022-04-07',
            deptName: null,
            currentDetailId: 'a1qN0000003cha7IAA',
            companyId: 'a0YN000000CSVR2MAP',
            clientName: null,
            clientId: null,
          },
        ],
        project: {
          extendedItemValueId: null,
          extendedItems: [],
          companyId: 'a0YN000000CSVR2MAP',
          workTimePerDay: 480,
          workingDayWED: true,
          workingDayTUE: true,
          workingDayTHU: true,
          workingDaySUN: false,
          workingDaySAT: false,
          workingDayMON: true,
          workingDayFRI: true,
          status: 'InProgress',
          startDate: '2022-01-25',
          revisionComment: null,
          projectId: 'a1uN0000002Wj84IAC',
          pmName: 'Sista Aadmi',
          pmCode: 'TDEMP000',
          pmBaseId: 'a0kN000000EeVq5IAF',
          name: 'TD QA Project',
          jobId: 'a0xN0000003qVKJIA2',
          jobCode: 'TDC',
          groupName: 'TD Resource Group 01',
          groupId: 'a1lN000000CFCbxIAH',
          endDate: '2023-01-25',
          description: null,
          deptName: null,
          deptId: null,
          deptCode: null,
          currentDetailId: 'a1qN0000003cg3mIAA',
          code: 'TDC',
          closeDate: null,
          clientName: null,
          clientId: null,
          clientCode: null,
          calendarId: 'a0WN000000G6ncxMAB',
        },
        data: null,
      },
      projectManager: {
        projectManagerId: '',
      },
      projectUploadInfo: {
        jobId: '',
        allowUpload: false,
        uploadSuccess: false,
        errorLog: '',
      },
      psaExtendedItem: {
        project: [],
        role: [],
      },
      request: {
        totalRecords: 0,
        totalPages: 0,
        pageSize: 0,
        pageNum: 0,
        pageData: [],
        request: {
          assignmentDueDate: '',
          clientName: '',
          endDate: '',
          firstName: '',
          lastName: '',
          projectCode: '',
          projectJobCode: '',
          projectTitle: '',
          receivedDate: '',
          requestCode: '',
          roleId: '',
          roleTitle: '',
          startDate: '',
          status: '',
        },
      },
      resource: {
        resourceList: [
          {
            position: null,
            photoUrl:
              'https://nosoftware-drive-2817-dev-ed--c.documentforce.com/profilephoto/005/T',
            name: 'Sista Aadmi',
            matchedSkills: 0,
            jobGradeName: '',
            jobGradeCode: '',
            id: 'a0kN000000EeVq5IAF',
            historyId: 'a0lN0000003stjOIAQ',
            departmentName: 'DEPARTMENT QA',
            departmentCode: 'DEP001',
            code: 'TDEMP000',
            availableTime: 47040,
            availability: [
              480, 480, 480, 480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480,
              480, 480, 480, 0, 0, 0, 480, 480, 480, 480, 0, 0, 480, 480, 480,
              480, 480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480, 480, 480,
              480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480, 480, 480, 0,
              0, 0, 480, 0, 0, 0, 480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480,
              480, 480, 480, 480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480,
              480, 480, 480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480, 480,
              480, 480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480, 480, 480,
              480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480, 480, 480, 480,
              0, 0, 0, 480, 480, 480, 480, 0, 0,
            ],
            hasAssignment: true,
          },
          {
            position: null,
            photoUrl:
              'https://nosoftware-drive-2817-dev-ed--c.documentforce.com/profilephoto/005/T',
            name: 'Stan Usou',
            matchedSkills: 0,
            jobGradeName: '',
            jobGradeCode: '',
            id: 'a0kN000000EeVqAIAV',
            historyId: 'a0lN0000003stj4IAA',
            departmentName: 'DEPARTMENT QA',
            departmentCode: 'DEP001',
            code: 'TDEMP001',
            availableTime: 47040,
            availability: [
              480, 480, 480, 480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480,
              480, 480, 480, 0, 0, 0, 480, 480, 480, 480, 0, 0, 480, 480, 480,
              480, 480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480, 480, 480,
              480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480, 480, 480, 0,
              0, 0, 480, 0, 0, 0, 480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480,
              480, 480, 480, 480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480,
              480, 480, 480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480, 480,
              480, 480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480, 480, 480,
              480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480, 480, 480, 480,
              0, 0, 0, 480, 480, 480, 480, 0, 0,
            ],
            hasAssignment: true,
          },
          {
            position: null,
            photoUrl:
              'https://nosoftware-drive-2817-dev-ed--c.documentforce.com/profilephoto/005/T',
            name: 'Resou Maan',
            matchedSkills: 0,
            jobGradeName: '',
            jobGradeCode: '',
            id: 'a0kN000000EeVqFIAV',
            historyId: 'a0lN0000003stj9IAA',
            departmentName: 'DEPARTMENT QA',
            departmentCode: 'DEP001',
            code: 'TDEMP002',
            availableTime: 45864,
            availability: [
              468, 468, 468, 468, 0, 0, 468, 468, 468, 468, 468, 0, 0, 468, 468,
              468, 468, 468, 0, 0, -12, 468, 468, 468, 468, 0, 0, 468, 468, 468,
              468, 468, 0, 0, 468, 468, 468, 468, 468, 0, 0, 468, 468, 468, 468,
              468, 0, 0, 468, 468, 468, 468, 468, 0, 0, 468, 468, 468, 468, -12,
              0, 0, 468, -12, -12, -12, 468, 0, 0, 468, 468, 468, 468, 468, 0,
              0, 468, 468, 468, 468, 468, 0, 0, 468, 468, 468, 468, 468, 0, 0,
              468, 468, 468, 468, 468, 0, 0, 468, 468, 468, 468, 468, 0, 0, 468,
              468, 468, 468, 468, 0, 0, 468, 468, 468, 468, 468, 0, 0, 468, 468,
              468, 468, 468, 0, 0, 468, 468, 468, 468, 468, 0, 0, 468, 468, 468,
              468, 468, 0, 0, -12, 468, 468, 468, 468, 0, 0,
            ],
            hasAssignment: true,
          },
          {
            position: null,
            photoUrl:
              'https://nosoftware-drive-2817-dev-ed--c.documentforce.com/profilephoto/005/T',
            name: 'Produ Managi',
            matchedSkills: 0,
            jobGradeName: '',
            jobGradeCode: '',
            id: 'a0kN000000EeVqKIAV',
            historyId: 'a0lN0000003stjEIAQ',
            departmentName: 'DEPARTMENT QA',
            departmentCode: 'DEP001',
            code: 'TDEMP003',
            availableTime: 47040,
            availability: [
              480, 480, 480, 480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480,
              480, 480, 480, 0, 0, 0, 480, 480, 480, 480, 0, 0, 480, 480, 480,
              480, 480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480, 480, 480,
              480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480, 480, 480, 0,
              0, 0, 480, 0, 0, 0, 480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480,
              480, 480, 480, 480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480,
              480, 480, 480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480, 480,
              480, 480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480, 480, 480,
              480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480, 480, 480, 480,
              0, 0, 0, 480, 480, 480, 480, 0, 0,
            ],
            hasAssignment: true,
          },
          {
            position: null,
            photoUrl:
              'https://nosoftware-drive-2817-dev-ed--c.documentforce.com/profilephoto/005/T',
            name: 'Akou Cleri',
            matchedSkills: 0,
            jobGradeName: '',
            jobGradeCode: '',
            id: 'a0kN000000EeVqPIAV',
            historyId: 'a0lN0000003stjJIAQ',
            departmentName: 'DEPARTMENT QA',
            departmentCode: 'DEP001',
            code: 'TDEMP004',
            availableTime: 47040,
            availability: [
              480, 480, 480, 480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480,
              480, 480, 480, 0, 0, 0, 480, 480, 480, 480, 0, 0, 480, 480, 480,
              480, 480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480, 480, 480,
              480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480, 480, 480, 0,
              0, 0, 480, 0, 0, 0, 480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480,
              480, 480, 480, 480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480,
              480, 480, 480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480, 480,
              480, 480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480, 480, 480,
              480, 0, 0, 480, 480, 480, 480, 480, 0, 0, 480, 480, 480, 480, 480,
              0, 0, 0, 480, 480, 480, 480, 0, 0,
            ],
            hasAssignment: true,
          },
        ],
        resource: {
          availableTime: '',
          bookedTime: '',
          departmentName: '',
          name: '',
          position: '',
          totalCapacity: '',
        },
        viewAllResourceList: {
          pageData: [],
          pageNum: 0,
          pageSize: 0,
          totalPages: 0,
          totalRecords: 0,
        },
        resourceIdList: {
          totalRecords: 0,
          ids: [],
        },
        assignmentDetailList: {
          assignments: [],
          employeeBaseId: '',
        },
      },
      resourceGroup: {
        groups: [],
      },
      resourceManager: {
        resourceManagerList: [],
      },
      role: {
        role: {
          extendedItemValueId: null,
          extendedItems: [],
          companyId: null,
          workingDays: 23,
          useDefaultRate: false,
          status: 'Planning',
          startDate: '2022-03-01',
          roleTitle: 'Copy of Copy of Role -2561Test-Original role',
          roleId: 'a1cN0000003590aIAA',
          requiredTimePercentage: 100,
          requiredTime: 11040,
          remarks: null,
          maxWorkingTime: 11040,
          isDirectAssign: false,
          isActivityLead: false,
          groupId: 'a1lN000000CFCbxIAH',
          endDate: '2022-03-31',
          costRate: null,
          billRate: null,
          assignmentDueDate: '2022-02-07',
          activityId: 'a1dN0000006Uus5IAC',
          softBookDate: null,
          softBookBy: null,
          skills: [],
          requesterDeptName: null,
          requesterDeptCode: null,
          requestDateTime: null,
          requestCode: '0000000018',
          requestByCode: null,
          requestBy: null,
          projectJobCode: 'TDC',
          projectDept: null,
          projectCode: 'TDC',
          memo: {
            visibleForRM: true,
            visibleForManagers: true,
            memoForRM: null,
            memoForManagers: null,
            memoForAll: null,
            id: 'a1nN00000043vrZIAQ',
          },
          jobGrades: [],
          jobCode: 'TDC_TDAC001',
          groupName: 'TD Resource Group 01',
          confirmDate: null,
          confirmBy: null,
          commentsHistory: null,
          clientName: null,
          assignment: {
            bookedTimePerDay: '',
            startDate: '',
            strategy: {
              schedulingStrategy: '',
            },
          },
        },
      },
      setting: {
        useExistingJobCode: true,
        id: 'a1xN0000003H7EkIAK',
        defaultWorkTime: 9,
        defaultCalendarId: 'a0WN000000G6ncxMAB',
        companyId: null,
        allowCrossGroupSearch: true,
      },
    },
    employeeList: [
      {
        id: 'a0kN000000EeVq5IAF',
        displayName: 'Sista Aadmi',
        code: 'TDEMP000',
      },
    ],
    skillsetCategoryList: [
      {
        skillsets: [
          {
            ratingType: 'None',
            name: 'Salesforce Developer',
            id: 'a1zN0000002Spt1IAC',
            grades: null,
            code: 'TDSKI002',
          },
          {
            ratingType: 'None',
            name: 'Salesforce Admin',
            id: 'a1zN0000002SpswIAC',
            grades: null,
            code: 'TDSKI001',
          },
          {
            ratingType: 'None',
            name: 'Salesforce App Builder',
            id: 'a1zN0000002Spt6IAC',
            grades: null,
            code: 'TDSKI003',
          },
        ],
        name: 'TD Exams',
        id: 'a1yN0000003AVk2IAG',
      },
      {
        skillsets: [
          {
            ratingType: 'Score',
            name: 'Physical Exam',
            id: 'a1zN0000002SptBIAS',
            grades: null,
            code: 'TDSKI004',
          },
          {
            ratingType: 'Score',
            name: 'Awesomeness Exam',
            id: 'a1zN0000002SptGIAS',
            grades: null,
            code: 'TDSKI005',
          },
        ],
        name: 'TD Certifications',
        id: 'a1yN0000003AVk7IAG',
      },
    ],
    jobGradeList: [
      {
        name_L2: null,
        name_L1: 'TD Job Grade Level 4',
        name_L0: 'TD Job Grade Level 4',
        name: 'TD Job Grade Level 4',
        id: 'a1mN0000003wWqQIAU',
        grade: null,
        costRate: 4000,
        companyId: 'a0YN000000CSVR2MAP',
        code: 'TDJG004',
        billingRate: 8000,
      },
      {
        name_L2: null,
        name_L1: 'TD Job Grade Level 3',
        name_L0: 'TD Job Grade Level 3',
        name: 'TD Job Grade Level 3',
        id: 'a1mN0000003wWqLIAU',
        grade: null,
        costRate: 3000,
        companyId: 'a0YN000000CSVR2MAP',
        code: 'TDJG003',
        billingRate: 6000,
      },
      {
        name_L2: null,
        name_L1: 'TD Job Grade Level 5',
        name_L0: 'TD Job Grade Level 5',
        name: 'TD Job Grade Level 5',
        id: 'a1mN0000003wWqVIAU',
        grade: null,
        costRate: 5000,
        companyId: 'a0YN000000CSVR2MAP',
        code: 'TDJG005',
        billingRate: 10000,
      },
      {
        name_L2: null,
        name_L1: 'TD Job Grade Level 2',
        name_L0: 'TD Job Grade Level 2',
        name: 'TD Job Grade Level 2',
        id: 'a1mN0000003wWqGIAU',
        grade: null,
        costRate: 2000,
        companyId: 'a0YN000000CSVR2MAP',
        code: 'TDJG002',
        billingRate: 4000,
      },
      {
        name_L2: null,
        name_L1: 'TD Job Grade Level 1',
        name_L0: 'TD Job Grade Level 1',
        name: 'TD Job Grade Level 1',
        id: 'a1mN0000003wWqBIAU',
        grade: null,
        costRate: 1000,
        companyId: 'a0YN000000CSVR2MAP',
        code: 'TDJG001',
        billingRate: 2000,
      },
    ],
    calendarList: [
      {
        type: 'Attendance',
        remarks: null,
        name_L2: null,
        name_L1: '全社共通カレンダー',
        name_L0: 'Company Calendar',
        name: 'Company Calendar',
        isDefault: true,
        id: 'a0WN000000G6ncxMAB',
        companyId: 'a0YN000000CSVR2MAP',
        code: 'COM001',
      },
    ],
    resourceGroupList: [
      {
        parentId: null,
        name_L2: null,
        name_L1: null,
        name_L0: 'TD Resource Group 01',
        name: 'TD Resource Group 01',
        id: 'a1lN000000CFCbxIAH',
        groupType: 'ResourceGroup',
        companyId: 'a0YN000000CSVR2MAP',
        code: 'TDRG001',
        canUploadProjectRoles: false,
        canConfirmProjectRoles: false,
        parentName: null,
        isOwned: false,
      },
    ],
    resourceGroupDetail: [],
    departmentList: [
      {
        id: 'a0iN000000kVMYbIAO',
        code: 'DEP001',
        name: 'DEPARTMENT QA',
        displayName: 'a0iN000000kVMYbIAO - DEP001',
      },
    ],
  },
};

describe('ScheduleDetailsContainer Test', () => {
  let store;
  let component;
  beforeEach(async () => {
    store = mockStore(state);
    await renderer.act(() => {
      component = renderer.create(
        <Provider store={store}>
          <ScheduleDetailsContainer />
        </Provider>
      );
    });
  });

  it('it renders without crashing', () => {
    expect(component.toJSON()).toMatchSnapshot();
  });
});
