import '../../../../../../../commons/config/moment';

import AttRecord from '../../../../../models/AttRecord';
import STATUS from '@apps/domain/models/approval/request/Status';

const attRecords: AttRecord[] = [
  new AttRecord({
    id: 'a0D2v00001DGI98EAH',
    recordDate: '2020-02-01',
    dayType: 'Holiday',
    startTime: null,
    endTime: null,
    startStampTime: null,
    endStampTime: null,
    outStartTime: null,
    outEndTime: null,
    dailyRestList: [],
    restHours: null,
    otherRestReason: null,
    remarks: null,
    requestTypeCodes: ['HolidayWork'],
    requestIds: [],
    contractedDetail: {
      startTime: null,
      endTime: null,
      rest5StartTime: null,
      rest5EndTime: null,
      rest5Reason: null,
      rest4StartTime: null,
      rest4EndTime: null,
      rest4Reason: null,
      rest3StartTime: null,
      rest3EndTime: null,
      rest3Reason: null,
      rest2StartTime: null,
      rest2EndTime: null,
      rest2Reason: null,
      rest1StartTime: null,
      rest1EndTime: null,
      rest1Reason: null,
    },
    ciliTimePeriods: [],
    ciloTimePeriods: [],
    coliTimePeriods: [],
    coloTimePeriods: [],
    approver01Name: '渡邉 航',
    earlyLeaveEndTime: null,
    isSummaryLocked: false,
    isLeaveOfAbsence: false,
    insufficientRestTime: 0,
    outInsufficientMinimumWorkHours: 0,
    earlyStartWorkApplyDefaultEndTime: 540,
    overtimeWorkApplyDefaultStartTime: 1080,
    lateArrivalStartTime: null,
    commuteCount: {
      forwardCount: 0,
      backwardCount: 0,
    },
    realWorkTime: undefined,
    useManageLateArrivalPersonalReason: false,
    useManageEarlyLeavePersonalReason: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    fixDailyRequest: {
      id: undefined,
      status: STATUS.Approved,
      approver01Name: undefined,
      performableActionForFix: undefined,
    },
    requestDayType: 'Holiday',
    isDirectInputTimeRequest: false,
    isLocked: false,
    useFixDailyRequest: false,
    isHolLegalHoliday: false,
    isFlexWithoutCore: false,
    isFlexWithoutCoreRequireEarlyLeaveApply: false,
    personalReasonEarlyLeaveEndTime: null,
    objectiveReasonEarlyLeaveEndTime: null,
    lateArrivalEarlyLeaveReasonId: '',
  }),
  new AttRecord({
    id: 'a0D2v00001DGI99EAH',
    recordDate: '2020-02-02',
    dayType: 'Workday',
    startTime: 540,
    endTime: 1080,
    startStampTime: null,
    endStampTime: null,
    outStartTime: 540,
    outEndTime: 1080,
    dailyRestList: [],
    restHours: null,
    otherRestReason: null,
    remarks: null,
    requestTypeCodes: ['OvertimeWork', 'EarlyStartWork', 'Absence', 'Direct'],
    requestIds: ['a012v000033TVVjAAO'],
    contractedDetail: {
      startTime: null,
      rest5StartTime: null,
      rest5EndTime: null,
      rest5Reason: null,
      rest4StartTime: null,
      rest4EndTime: null,
      rest4Reason: null,
      rest3StartTime: null,
      rest3EndTime: null,
      rest3Reason: null,
      rest2StartTime: null,
      rest2EndTime: null,
      rest2Reason: null,
      rest1StartTime: null,
      rest1EndTime: null,
      rest1Reason: null,
      endTime: null,
    },
    ciliTimePeriods: [
      { startTime: 540, endTime: 720 },
      { startTime: 780, endTime: 1080 },
    ],
    ciloTimePeriods: [],
    coliTimePeriods: [],
    coloTimePeriods: [],
    approver01Name: '渡邉 航',
    earlyLeaveEndTime: null,
    isSummaryLocked: false,
    isLeaveOfAbsence: false,
    insufficientRestTime: 0,
    outInsufficientMinimumWorkHours: 0,
    earlyStartWorkApplyDefaultEndTime: 540,
    overtimeWorkApplyDefaultStartTime: 1080,
    realWorkTime: undefined,
    lateArrivalStartTime: 540,
    commuteCount: {
      forwardCount: 1,
      backwardCount: 0,
    },
    useManageLateArrivalPersonalReason: false,
    useManageEarlyLeavePersonalReason: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    fixDailyRequest: {
      id: undefined,
      status: STATUS.Approved,
      approver01Name: undefined,
      performableActionForFix: undefined,
    },
    requestDayType: 'Holiday',
    isDirectInputTimeRequest: false,
    isLocked: false,
    useFixDailyRequest: false,
    isHolLegalHoliday: false,
    isFlexWithoutCore: false,
    isFlexWithoutCoreRequireEarlyLeaveApply: false,
    personalReasonEarlyLeaveEndTime: null,
    objectiveReasonEarlyLeaveEndTime: null,
    lateArrivalEarlyLeaveReasonId: '',
  }),
  new AttRecord({
    realWorkTime: undefined,
    id: 'a0D2v00001DGI9AEAX',
    recordDate: '2020-02-03',
    dayType: 'Workday',
    startTime: 540,
    endTime: 1080,
    startStampTime: null,
    endStampTime: null,
    outStartTime: 540,
    outEndTime: 1080,
    dailyRestList: [],
    restHours: null,
    otherRestReason: null,
    remarks: null,
    requestTypeCodes: [
      'Leave',
      'OvertimeWork',
      'EarlyStartWork',
      'Absence',
      'Direct',
    ],
    requestIds: [],
    contractedDetail: {
      startTime: null,
      rest5StartTime: null,
      rest5EndTime: null,
      rest5Reason: null,
      rest4StartTime: null,
      rest4EndTime: null,
      rest4Reason: null,
      rest3StartTime: null,
      rest3EndTime: null,
      rest3Reason: null,
      rest2StartTime: null,
      rest2EndTime: null,
      rest2Reason: null,
      rest1StartTime: null,
      rest1EndTime: null,
      rest1Reason: null,
      endTime: null,
    },
    ciliTimePeriods: [
      { startTime: 540, endTime: 720 },
      { startTime: 780, endTime: 1080 },
    ],
    ciloTimePeriods: [],
    coliTimePeriods: [],
    coloTimePeriods: [],
    approver01Name: '渡邉 航',
    earlyLeaveEndTime: null,
    isSummaryLocked: false,
    isLeaveOfAbsence: false,
    insufficientRestTime: 0,
    outInsufficientMinimumWorkHours: 0,
    earlyStartWorkApplyDefaultEndTime: 540,
    overtimeWorkApplyDefaultStartTime: 1080,
    lateArrivalStartTime: 540,
    commuteCount: {
      forwardCount: 0,
      backwardCount: 1,
    },
    useManageLateArrivalPersonalReason: false,
    useManageEarlyLeavePersonalReason: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    fixDailyRequest: {
      id: undefined,
      status: STATUS.Pending,
      approver01Name: undefined,
      performableActionForFix: undefined,
    },
    requestDayType: 'Holiday',
    isDirectInputTimeRequest: false,
    isLocked: false,
    useFixDailyRequest: false,
    isHolLegalHoliday: false,
    isFlexWithoutCore: false,
    isFlexWithoutCoreRequireEarlyLeaveApply: false,
    personalReasonEarlyLeaveEndTime: null,
    objectiveReasonEarlyLeaveEndTime: null,
    lateArrivalEarlyLeaveReasonId: '',
  }),
  new AttRecord({
    id: 'a0D2v00001DGI9BEAX',
    recordDate: '2020-02-04',
    dayType: 'LegalHoliday',
    startTime: null,
    endTime: null,
    startStampTime: null,
    endStampTime: null,
    outStartTime: null,
    outEndTime: null,
    dailyRestList: [],
    restHours: null,
    otherRestReason: null,
    remarks: null,
    requestTypeCodes: [],
    requestIds: ['a012v000033TVVjAAO'],
    contractedDetail: {
      startTime: null,
      rest5StartTime: null,
      rest5EndTime: null,
      rest5Reason: null,
      rest4StartTime: null,
      rest4EndTime: null,
      rest4Reason: null,
      rest3StartTime: null,
      rest3EndTime: null,
      rest3Reason: null,
      rest2StartTime: null,
      rest2EndTime: null,
      rest2Reason: null,
      rest1StartTime: null,
      rest1EndTime: null,
      rest1Reason: null,
      endTime: null,
    },
    ciliTimePeriods: [],
    ciloTimePeriods: [],
    coliTimePeriods: [],
    coloTimePeriods: [],
    approver01Name: '渡邉 航',
    earlyLeaveEndTime: null,
    isSummaryLocked: false,
    isLeaveOfAbsence: false,
    insufficientRestTime: 0,
    outInsufficientMinimumWorkHours: 0,
    realWorkTime: undefined,
    earlyStartWorkApplyDefaultEndTime: 540,
    overtimeWorkApplyDefaultStartTime: 1080,
    lateArrivalStartTime: null,
    commuteCount: {
      forwardCount: 1,
      backwardCount: 1,
    },
    useManageLateArrivalPersonalReason: false,
    useManageEarlyLeavePersonalReason: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    fixDailyRequest: {
      id: undefined,
      status: STATUS.Canceled,
      approver01Name: undefined,
      performableActionForFix: undefined,
    },
    requestDayType: null,
    isDirectInputTimeRequest: false,
    isLocked: false,
    useFixDailyRequest: false,
    isHolLegalHoliday: false,
    isFlexWithoutCore: false,
    isFlexWithoutCoreRequireEarlyLeaveApply: false,
    personalReasonEarlyLeaveEndTime: null,
    objectiveReasonEarlyLeaveEndTime: null,
    lateArrivalEarlyLeaveReasonId: '',
  }),
  new AttRecord({
    realWorkTime: undefined,
    id: 'a0D2v00001DGI9CEAX',
    recordDate: '2020-02-05',
    dayType: 'Workday',
    startTime: 840,
    endTime: 900,
    startStampTime: null,
    endStampTime: null,
    outStartTime: 840,
    outEndTime: 900,
    dailyRestList: [],
    restHours: null,
    otherRestReason: null,
    remarks: null,
    requestTypeCodes: [
      'Leave',
      'OvertimeWork',
      'EarlyStartWork',
      'Absence',
      'Direct',
    ],
    requestIds: [],
    contractedDetail: {
      startTime: null,
      rest5StartTime: null,
      rest5EndTime: null,
      rest5Reason: null,
      rest4StartTime: null,
      rest4EndTime: null,
      rest4Reason: null,
      rest3StartTime: null,
      rest3EndTime: null,
      rest3Reason: null,
      rest2StartTime: null,
      rest2EndTime: null,
      rest2Reason: null,
      rest1StartTime: null,
      rest1EndTime: null,
      rest1Reason: null,
      endTime: null,
    },
    ciliTimePeriods: [{ startTime: 840, endTime: 900 }],
    ciloTimePeriods: [],
    coliTimePeriods: [],
    coloTimePeriods: [],
    approver01Name: '渡邉 航',
    earlyLeaveEndTime: null,
    isSummaryLocked: false,
    isLeaveOfAbsence: false,
    insufficientRestTime: 0,
    outInsufficientMinimumWorkHours: 0,
    earlyStartWorkApplyDefaultEndTime: 540,
    overtimeWorkApplyDefaultStartTime: 1080,
    lateArrivalStartTime: 540,
    commuteCount: {
      forwardCount: 0,
      backwardCount: 0,
    },
    useManageLateArrivalPersonalReason: false,
    useManageEarlyLeavePersonalReason: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    fixDailyRequest: {
      id: undefined,
      status: STATUS.NotRequested,
      approver01Name: undefined,
      performableActionForFix: undefined,
    },
    requestDayType: 'Holiday',
    isDirectInputTimeRequest: false,
    isLocked: false,
    useFixDailyRequest: false,
    isHolLegalHoliday: false,
    isFlexWithoutCore: false,
    isFlexWithoutCoreRequireEarlyLeaveApply: false,
    personalReasonEarlyLeaveEndTime: null,
    objectiveReasonEarlyLeaveEndTime: null,
    lateArrivalEarlyLeaveReasonId: '',
  }),
  new AttRecord({
    realWorkTime: undefined,
    id: 'a0D2v00001DGI9DEAX',
    recordDate: '2020-02-06',
    dayType: 'Workday',
    startTime: null,
    endTime: null,
    startStampTime: null,
    endStampTime: null,
    outStartTime: null,
    outEndTime: null,
    dailyRestList: [],
    restHours: null,
    otherRestReason: null,
    remarks: null,
    requestTypeCodes: [],
    requestIds: ['a012v000033TVRXAA4'],
    contractedDetail: {
      startTime: null,
      rest5StartTime: null,
      rest5EndTime: null,
      rest5Reason: null,
      rest4StartTime: null,
      rest4EndTime: null,
      rest4Reason: null,
      rest3StartTime: null,
      rest3EndTime: null,
      rest3Reason: null,
      rest2StartTime: null,
      rest2EndTime: null,
      rest2Reason: null,
      rest1StartTime: null,
      rest1EndTime: null,
      rest1Reason: null,
      endTime: null,
    },
    ciliTimePeriods: [],
    ciloTimePeriods: [],
    coliTimePeriods: [],
    coloTimePeriods: [],
    approver01Name: '渡邉 航',
    earlyLeaveEndTime: null,
    isSummaryLocked: false,
    isLeaveOfAbsence: false,
    insufficientRestTime: 0,
    outInsufficientMinimumWorkHours: 0,
    earlyStartWorkApplyDefaultEndTime: 540,
    overtimeWorkApplyDefaultStartTime: 1080,
    lateArrivalStartTime: null,
    commuteCount: {
      forwardCount: 1,
      backwardCount: 0,
    },
    useManageLateArrivalPersonalReason: false,
    useManageEarlyLeavePersonalReason: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    fixDailyRequest: {
      id: undefined,
      status: STATUS.Pending,
      approver01Name: undefined,
      performableActionForFix: undefined,
    },
    requestDayType: 'Holiday',
    isDirectInputTimeRequest: false,
    isLocked: false,
    useFixDailyRequest: false,
    isHolLegalHoliday: false,
    isFlexWithoutCore: false,
    isFlexWithoutCoreRequireEarlyLeaveApply: false,
    personalReasonEarlyLeaveEndTime: null,
    objectiveReasonEarlyLeaveEndTime: null,
    lateArrivalEarlyLeaveReasonId: '',
  }),
  new AttRecord({
    realWorkTime: undefined,
    id: 'a0D2v00001DGI9EEAX',
    recordDate: '2020-02-07',
    dayType: 'Workday',
    startTime: 120,
    endTime: 1200,
    startStampTime: null,
    endStampTime: null,
    outStartTime: 120,
    outEndTime: 1200,
    dailyRestList: [],
    restHours: null,
    otherRestReason: null,
    remarks: null,
    requestTypeCodes: [
      'Leave',
      'OvertimeWork',
      'EarlyStartWork',
      'Absence',
      'Direct',
    ],
    requestIds: [],
    contractedDetail: {
      startTime: null,
      rest5StartTime: null,
      rest5EndTime: null,
      rest5Reason: null,
      rest4StartTime: null,
      rest4EndTime: null,
      rest4Reason: null,
      rest3StartTime: null,
      rest3EndTime: null,
      rest3Reason: null,
      rest2StartTime: null,
      rest2EndTime: null,
      rest2Reason: null,
      rest1StartTime: null,
      rest1EndTime: null,
      rest1Reason: null,
      endTime: null,
    },
    ciliTimePeriods: [
      { startTime: 540, endTime: 720 },
      { startTime: 780, endTime: 1080 },
    ],
    ciloTimePeriods: [],
    coliTimePeriods: [],
    coloTimePeriods: [
      { startTime: 120, endTime: 540 },
      { startTime: 1080, endTime: 1200 },
    ],
    approver01Name: '渡邉 航',
    earlyLeaveEndTime: null,
    isSummaryLocked: false,
    isLeaveOfAbsence: false,
    insufficientRestTime: 0,
    outInsufficientMinimumWorkHours: 0,
    earlyStartWorkApplyDefaultEndTime: 540,
    overtimeWorkApplyDefaultStartTime: 1080,
    lateArrivalStartTime: 540,
    commuteCount: {
      forwardCount: 0,
      backwardCount: 1,
    },
    useManageLateArrivalPersonalReason: false,
    useManageEarlyLeavePersonalReason: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    fixDailyRequest: {
      id: undefined,
      status: STATUS.NotRequested,
      approver01Name: undefined,
      performableActionForFix: undefined,
    },
    requestDayType: 'Holiday',
    isDirectInputTimeRequest: false,
    isLocked: false,
    useFixDailyRequest: false,
    isHolLegalHoliday: false,
    isFlexWithoutCore: false,
    isFlexWithoutCoreRequireEarlyLeaveApply: false,
    personalReasonEarlyLeaveEndTime: null,
    objectiveReasonEarlyLeaveEndTime: null,
    lateArrivalEarlyLeaveReasonId: '',
  }),
  new AttRecord({
    id: 'a0D2v00001DGI9FEAX',
    recordDate: '2020-02-08',
    dayType: 'Holiday',
    startTime: null,
    endTime: null,
    startStampTime: null,
    endStampTime: null,
    outStartTime: null,
    outEndTime: null,
    dailyRestList: [],
    restHours: null,
    otherRestReason: null,
    remarks: null,
    requestTypeCodes: ['HolidayWork'],
    requestIds: [],
    contractedDetail: {
      startTime: null,
      rest5StartTime: null,
      rest5EndTime: null,
      rest5Reason: null,
      rest4StartTime: null,
      rest4EndTime: null,
      rest4Reason: null,
      rest3StartTime: null,
      rest3EndTime: null,
      rest3Reason: null,
      rest2StartTime: null,
      rest2EndTime: null,
      rest2Reason: null,
      rest1StartTime: null,
      rest1EndTime: null,
      rest1Reason: null,
      endTime: null,
    },
    ciliTimePeriods: [],
    ciloTimePeriods: [],
    coliTimePeriods: [],
    coloTimePeriods: [],
    approver01Name: '渡邉 航',
    earlyLeaveEndTime: null,
    isSummaryLocked: false,
    isLeaveOfAbsence: false,
    insufficientRestTime: 0,
    outInsufficientMinimumWorkHours: 0,
    earlyStartWorkApplyDefaultEndTime: 540,
    overtimeWorkApplyDefaultStartTime: 1080,
    realWorkTime: undefined,
    lateArrivalStartTime: null,
    commuteCount: {
      forwardCount: null,
      backwardCount: null,
    },
    useManageLateArrivalPersonalReason: false,
    useManageEarlyLeavePersonalReason: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    fixDailyRequest: {
      id: undefined,
      status: STATUS.NotRequested,
      approver01Name: undefined,
      performableActionForFix: undefined,
    },
    requestDayType: 'Holiday',
    isDirectInputTimeRequest: false,
    isLocked: false,
    useFixDailyRequest: false,
    isHolLegalHoliday: false,
    isFlexWithoutCore: false,
    isFlexWithoutCoreRequireEarlyLeaveApply: false,
    personalReasonEarlyLeaveEndTime: null,
    objectiveReasonEarlyLeaveEndTime: null,
    lateArrivalEarlyLeaveReasonId: '',
  }),
  new AttRecord({
    realWorkTime: undefined,
    id: 'a0D2v00001DGI9GEAX',
    recordDate: '2020-02-09',
    dayType: 'LegalHoliday',
    startTime: null,
    endTime: null,
    startStampTime: null,
    endStampTime: null,
    outStartTime: null,
    outEndTime: null,
    dailyRestList: [],
    restHours: null,
    otherRestReason: null,
    remarks: null,
    requestTypeCodes: ['HolidayWork'],
    requestIds: [],
    contractedDetail: {
      startTime: null,
      rest5StartTime: null,
      rest5EndTime: null,
      rest5Reason: null,
      rest4StartTime: null,
      rest4EndTime: null,
      rest4Reason: null,
      rest3StartTime: null,
      rest3EndTime: null,
      rest3Reason: null,
      rest2StartTime: null,
      rest2EndTime: null,
      rest2Reason: null,
      rest1StartTime: null,
      rest1EndTime: null,
      rest1Reason: null,
      endTime: null,
    },
    ciliTimePeriods: [],
    ciloTimePeriods: [],
    coliTimePeriods: [],
    coloTimePeriods: [],
    approver01Name: '渡邉 航',
    earlyLeaveEndTime: null,
    isSummaryLocked: false,
    isLeaveOfAbsence: false,
    insufficientRestTime: 0,
    outInsufficientMinimumWorkHours: 0,
    earlyStartWorkApplyDefaultEndTime: 540,
    overtimeWorkApplyDefaultStartTime: 1080,
    lateArrivalStartTime: null,
    commuteCount: {
      forwardCount: null,
      backwardCount: null,
    },
    useManageLateArrivalPersonalReason: false,
    useManageEarlyLeavePersonalReason: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    fixDailyRequest: {
      id: undefined,
      status: STATUS.NotRequested,
      approver01Name: undefined,
      performableActionForFix: undefined,
    },
    requestDayType: null,
    isDirectInputTimeRequest: false,
    isLocked: false,
    useFixDailyRequest: false,
    isHolLegalHoliday: false,
    isFlexWithoutCore: false,
    isFlexWithoutCoreRequireEarlyLeaveApply: false,
    personalReasonEarlyLeaveEndTime: null,
    objectiveReasonEarlyLeaveEndTime: null,
    lateArrivalEarlyLeaveReasonId: '',
  }),
  new AttRecord({
    realWorkTime: undefined,
    id: 'a0D2v00001DGI9HEAX',
    recordDate: '2020-02-10',
    dayType: 'Workday',
    startTime: 966,
    endTime: 1080,
    startStampTime: 966,
    endStampTime: null,
    outStartTime: 966,
    outEndTime: 1080,
    dailyRestList: [],
    restHours: null,
    otherRestReason: null,
    remarks: null,
    requestTypeCodes: [
      'Leave',
      'OvertimeWork',
      'EarlyStartWork',
      'Absence',
      'Direct',
    ],
    requestIds: [],
    contractedDetail: {
      startTime: null,
      rest5StartTime: null,
      rest5EndTime: null,
      rest5Reason: null,
      rest4StartTime: null,
      rest4EndTime: null,
      rest4Reason: null,
      rest3StartTime: null,
      rest3EndTime: null,
      rest3Reason: null,
      rest2StartTime: null,
      rest2EndTime: null,
      rest2Reason: null,
      rest1StartTime: null,
      rest1EndTime: null,
      rest1Reason: null,
      endTime: null,
    },
    ciliTimePeriods: [{ startTime: 966, endTime: 1080 }],
    ciloTimePeriods: [],
    coliTimePeriods: [],
    coloTimePeriods: [],
    approver01Name: '渡邉 航',
    earlyLeaveEndTime: null,
    isSummaryLocked: false,
    isLeaveOfAbsence: false,
    insufficientRestTime: 0,
    outInsufficientMinimumWorkHours: 0,
    earlyStartWorkApplyDefaultEndTime: 540,
    overtimeWorkApplyDefaultStartTime: 1080,
    lateArrivalStartTime: 540,
    commuteCount: {
      forwardCount: null,
      backwardCount: null,
    },
    useManageLateArrivalPersonalReason: false,
    useManageEarlyLeavePersonalReason: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    fixDailyRequest: {
      id: undefined,
      status: STATUS.NotRequested,
      approver01Name: undefined,
      performableActionForFix: undefined,
    },

    requestDayType: 'Holiday',
    isDirectInputTimeRequest: false,

    isLocked: false,
    useFixDailyRequest: false,
    isHolLegalHoliday: false,
    isFlexWithoutCore: false,
    isFlexWithoutCoreRequireEarlyLeaveApply: false,
    personalReasonEarlyLeaveEndTime: null,
    objectiveReasonEarlyLeaveEndTime: null,
    lateArrivalEarlyLeaveReasonId: '',
  }),
  new AttRecord({
    realWorkTime: undefined,
    id: 'a0D2v00001DGI9IEAX',
    recordDate: '2020-02-11',
    dayType: 'Holiday',
    startTime: null,
    endTime: null,
    startStampTime: null,
    endStampTime: null,
    outStartTime: null,
    outEndTime: null,
    dailyRestList: [],
    restHours: null,
    otherRestReason: null,
    remarks: null,
    requestTypeCodes: ['HolidayWork'],
    requestIds: [],
    contractedDetail: {
      startTime: null,
      rest5StartTime: null,
      rest5EndTime: null,
      rest5Reason: null,
      rest4StartTime: null,
      rest4EndTime: null,
      rest4Reason: null,
      rest3StartTime: null,
      rest3EndTime: null,
      rest3Reason: null,
      rest2StartTime: null,
      rest2EndTime: null,
      rest2Reason: null,
      rest1StartTime: null,
      rest1EndTime: null,
      rest1Reason: null,
      endTime: null,
    },
    ciliTimePeriods: [],
    ciloTimePeriods: [],
    coliTimePeriods: [],
    coloTimePeriods: [],
    approver01Name: '渡邉 航',
    earlyLeaveEndTime: null,
    isSummaryLocked: false,
    isLeaveOfAbsence: false,
    insufficientRestTime: 0,
    outInsufficientMinimumWorkHours: 0,
    earlyStartWorkApplyDefaultEndTime: 540,
    overtimeWorkApplyDefaultStartTime: 1080,
    lateArrivalStartTime: null,
    commuteCount: {
      forwardCount: 0,
      backwardCount: 1,
    },
    useManageLateArrivalPersonalReason: false,
    useManageEarlyLeavePersonalReason: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    fixDailyRequest: {
      id: undefined,
      status: STATUS.NotRequested,
      approver01Name: undefined,
      performableActionForFix: undefined,
    },

    requestDayType: 'Holiday',
    isDirectInputTimeRequest: false,

    isLocked: false,
    useFixDailyRequest: false,
    isHolLegalHoliday: false,
    isFlexWithoutCore: false,
    isFlexWithoutCoreRequireEarlyLeaveApply: false,
    personalReasonEarlyLeaveEndTime: null,
    objectiveReasonEarlyLeaveEndTime: null,
    lateArrivalEarlyLeaveReasonId: '',
  }),
  new AttRecord({
    realWorkTime: undefined,
    id: 'a0D2v00001DGI9JEAX',
    recordDate: '2020-02-12',
    dayType: 'Workday',
    startTime: 240,
    endTime: 1200,
    startStampTime: null,
    endStampTime: null,
    outStartTime: 240,
    outEndTime: 1200,
    dailyRestList: [],
    restHours: null,
    otherRestReason: null,
    remarks: '休憩してないです',
    requestTypeCodes: [
      'Leave',
      'OvertimeWork',
      'EarlyStartWork',
      'Absence',
      'Direct',
    ],
    requestIds: [],
    contractedDetail: {
      startTime: null,
      rest5StartTime: null,
      rest5EndTime: null,
      rest5Reason: null,
      rest4StartTime: null,
      rest4EndTime: null,
      rest4Reason: null,
      rest3StartTime: null,
      rest3EndTime: null,
      rest3Reason: null,
      rest2StartTime: null,
      rest2EndTime: null,
      rest2Reason: null,
      rest1StartTime: null,
      rest1EndTime: null,
      rest1Reason: null,
      endTime: null,
    },
    ciliTimePeriods: [{ startTime: 540, endTime: 1020 }],
    ciloTimePeriods: [],
    coliTimePeriods: [],
    coloTimePeriods: [
      { startTime: 240, endTime: 540 },
      { startTime: 1020, endTime: 1200 },
    ],
    approver01Name: '渡邉 航',
    earlyLeaveEndTime: null,
    isSummaryLocked: false,
    isLeaveOfAbsence: false,
    insufficientRestTime: 60,
    outInsufficientMinimumWorkHours: 0,
    earlyStartWorkApplyDefaultEndTime: 540,
    overtimeWorkApplyDefaultStartTime: 1080,
    lateArrivalStartTime: 540,
    commuteCount: {
      forwardCount: 1,
      backwardCount: 1,
    },
    useManageLateArrivalPersonalReason: false,
    useManageEarlyLeavePersonalReason: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    fixDailyRequest: {
      id: undefined,
      status: STATUS.NotRequested,
      approver01Name: undefined,
      performableActionForFix: undefined,
    },

    requestDayType: 'Holiday',
    isDirectInputTimeRequest: false,

    isLocked: false,
    useFixDailyRequest: false,
    isHolLegalHoliday: false,
    isFlexWithoutCore: false,
    isFlexWithoutCoreRequireEarlyLeaveApply: false,
    personalReasonEarlyLeaveEndTime: null,
    objectiveReasonEarlyLeaveEndTime: null,
    lateArrivalEarlyLeaveReasonId: '',
  }),
  new AttRecord({
    realWorkTime: undefined,
    id: 'a0D2v00001DGI9KEAX',
    recordDate: '2020-02-13',
    dayType: 'Workday',
    startTime: 240,
    endTime: 674,
    startStampTime: null,
    endStampTime: 674,
    outStartTime: 240,
    outEndTime: 674,
    dailyRestList: [],
    otherRestReason: null,
    restHours: 45,
    remarks: null,
    requestTypeCodes: [
      'Leave',
      'OvertimeWork',
      'EarlyStartWork',
      'Absence',
      'Direct',
    ],
    requestIds: [],
    contractedDetail: {
      startTime: null,
      rest5StartTime: null,
      rest5EndTime: null,
      rest5Reason: null,
      rest4StartTime: null,
      rest4EndTime: null,
      rest4Reason: null,
      rest3StartTime: null,
      rest3EndTime: null,
      rest3Reason: null,
      rest2StartTime: null,
      rest2EndTime: null,
      rest2Reason: null,
      rest1StartTime: null,
      rest1EndTime: null,
      rest1Reason: null,
      endTime: null,
    },
    ciliTimePeriods: [{ startTime: 540, endTime: 674 }],
    ciloTimePeriods: [],
    coliTimePeriods: [{ startTime: 240, endTime: 540 }],
    coloTimePeriods: [],
    approver01Name: '渡邉 航',
    earlyLeaveEndTime: null,
    isSummaryLocked: false,
    isLeaveOfAbsence: false,
    insufficientRestTime: 0,
    outInsufficientMinimumWorkHours: 0,
    earlyStartWorkApplyDefaultEndTime: 540,
    overtimeWorkApplyDefaultStartTime: 1080,
    lateArrivalStartTime: 540,
    commuteCount: {
      forwardCount: 0,
      backwardCount: 0,
    },
    useManageLateArrivalPersonalReason: false,
    useManageEarlyLeavePersonalReason: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    fixDailyRequest: {
      id: undefined,
      status: STATUS.NotRequested,
      approver01Name: undefined,
      performableActionForFix: undefined,
    },

    requestDayType: 'Holiday',
    isDirectInputTimeRequest: false,

    isLocked: false,
    useFixDailyRequest: false,
    isHolLegalHoliday: false,
    isFlexWithoutCore: false,
    isFlexWithoutCoreRequireEarlyLeaveApply: false,
    personalReasonEarlyLeaveEndTime: null,
    objectiveReasonEarlyLeaveEndTime: null,
    lateArrivalEarlyLeaveReasonId: '',
  }),
  new AttRecord({
    realWorkTime: undefined,
    id: 'a0D2v00001DGI9LEAX',
    recordDate: '2020-02-14',
    dayType: 'Workday',
    startTime: null,
    endTime: null,
    startStampTime: null,
    endStampTime: null,
    outStartTime: null,
    outEndTime: null,
    dailyRestList: [],
    restHours: null,
    otherRestReason: null,
    remarks: null,
    requestTypeCodes: [],
    requestIds: ['a012v000033TVVtAAO'],
    contractedDetail: {
      startTime: null,
      rest5StartTime: null,
      rest5EndTime: null,
      rest5Reason: null,
      rest4StartTime: null,
      rest4EndTime: null,
      rest4Reason: null,
      rest3StartTime: null,
      rest3EndTime: null,
      rest3Reason: null,
      rest2StartTime: null,
      rest2EndTime: null,
      rest2Reason: null,
      rest1StartTime: null,
      rest1EndTime: null,
      rest1Reason: null,
      endTime: null,
    },
    ciliTimePeriods: [],
    ciloTimePeriods: [],
    coliTimePeriods: [],
    coloTimePeriods: [],
    approver01Name: '渡邉 航',
    earlyLeaveEndTime: null,
    isSummaryLocked: false,
    isLeaveOfAbsence: false,
    insufficientRestTime: 0,
    outInsufficientMinimumWorkHours: 0,
    earlyStartWorkApplyDefaultEndTime: 540,
    overtimeWorkApplyDefaultStartTime: 1080,
    lateArrivalStartTime: 540,
    commuteCount: {
      forwardCount: 1,
      backwardCount: 0,
    },
    useManageLateArrivalPersonalReason: false,
    useManageEarlyLeavePersonalReason: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    fixDailyRequest: {
      id: undefined,
      status: STATUS.NotRequested,
      approver01Name: undefined,
      performableActionForFix: undefined,
    },

    requestDayType: 'Holiday',
    isDirectInputTimeRequest: false,

    isLocked: false,
    useFixDailyRequest: false,
    isHolLegalHoliday: false,
    isFlexWithoutCore: false,
    isFlexWithoutCoreRequireEarlyLeaveApply: false,
    personalReasonEarlyLeaveEndTime: null,
    objectiveReasonEarlyLeaveEndTime: null,
    lateArrivalEarlyLeaveReasonId: '',
  }),
  new AttRecord({
    realWorkTime: undefined,
    id: 'a0D2v00001DGI9MEAX',
    recordDate: '2020-02-15',
    dayType: 'Holiday',
    startTime: null,
    endTime: null,
    startStampTime: null,
    endStampTime: null,
    outStartTime: null,
    outEndTime: null,
    dailyRestList: [],
    restHours: null,
    otherRestReason: null,
    remarks: null,
    requestTypeCodes: ['HolidayWork'],
    requestIds: [],
    contractedDetail: {
      startTime: null,
      rest5StartTime: null,
      rest5EndTime: null,
      rest5Reason: null,
      rest4StartTime: null,
      rest4EndTime: null,
      rest4Reason: null,
      rest3StartTime: null,
      rest3EndTime: null,
      rest3Reason: null,
      rest2StartTime: null,
      rest2EndTime: null,
      rest2Reason: null,
      rest1StartTime: null,
      rest1EndTime: null,
      rest1Reason: null,
      endTime: null,
    },
    ciliTimePeriods: [],
    ciloTimePeriods: [],
    coliTimePeriods: [],
    coloTimePeriods: [],
    approver01Name: '渡邉 航',
    earlyLeaveEndTime: null,
    isSummaryLocked: false,
    isLeaveOfAbsence: false,
    insufficientRestTime: 0,
    outInsufficientMinimumWorkHours: 0,
    earlyStartWorkApplyDefaultEndTime: 540,
    overtimeWorkApplyDefaultStartTime: 1080,
    lateArrivalStartTime: null,
    commuteCount: {
      forwardCount: 0,
      backwardCount: 1,
    },
    useManageLateArrivalPersonalReason: false,
    useManageEarlyLeavePersonalReason: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    fixDailyRequest: {
      id: undefined,
      status: STATUS.NotRequested,
      approver01Name: undefined,
      performableActionForFix: undefined,
    },

    requestDayType: 'Holiday',
    isDirectInputTimeRequest: false,

    isLocked: false,
    useFixDailyRequest: false,
    isHolLegalHoliday: false,
    isFlexWithoutCore: false,
    isFlexWithoutCoreRequireEarlyLeaveApply: false,
    personalReasonEarlyLeaveEndTime: null,
    objectiveReasonEarlyLeaveEndTime: null,
    lateArrivalEarlyLeaveReasonId: '',
  }),
  new AttRecord({
    realWorkTime: undefined,
    id: 'a0D2v00001DGI9NEAX',
    recordDate: '2020-02-16',
    dayType: 'LegalHoliday',
    startTime: null,
    endTime: null,
    startStampTime: null,
    endStampTime: null,
    outStartTime: null,
    outEndTime: null,
    dailyRestList: [],
    restHours: null,
    otherRestReason: null,
    remarks: null,
    requestTypeCodes: ['HolidayWork'],
    requestIds: [],
    contractedDetail: {
      startTime: null,
      rest5StartTime: null,
      rest5EndTime: null,
      rest5Reason: null,
      rest4StartTime: null,
      rest4EndTime: null,
      rest4Reason: null,
      rest3StartTime: null,
      rest3EndTime: null,
      rest3Reason: null,
      rest2StartTime: null,
      rest2EndTime: null,
      rest2Reason: null,
      rest1StartTime: null,
      rest1EndTime: null,
      rest1Reason: null,
      endTime: null,
    },
    ciliTimePeriods: [],
    ciloTimePeriods: [],
    coliTimePeriods: [],
    coloTimePeriods: [],
    approver01Name: '渡邉 航',
    earlyLeaveEndTime: null,
    isSummaryLocked: false,
    isLeaveOfAbsence: false,
    insufficientRestTime: 0,
    outInsufficientMinimumWorkHours: 0,
    earlyStartWorkApplyDefaultEndTime: 540,
    overtimeWorkApplyDefaultStartTime: 1080,
    lateArrivalStartTime: null,
    commuteCount: {
      forwardCount: 1,
      backwardCount: 1,
    },
    useManageLateArrivalPersonalReason: false,
    useManageEarlyLeavePersonalReason: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    fixDailyRequest: {
      id: undefined,
      status: STATUS.NotRequested,
      approver01Name: undefined,
      performableActionForFix: undefined,
    },

    requestDayType: 'Holiday',
    isDirectInputTimeRequest: false,

    isLocked: false,
    useFixDailyRequest: false,
    isHolLegalHoliday: false,
    isFlexWithoutCore: false,
    isFlexWithoutCoreRequireEarlyLeaveApply: false,
    personalReasonEarlyLeaveEndTime: null,
    objectiveReasonEarlyLeaveEndTime: null,
    lateArrivalEarlyLeaveReasonId: '',
  }),
  new AttRecord({
    realWorkTime: undefined,
    id: 'a0D2v00001DGI9OEAX',
    recordDate: '2020-02-17',
    dayType: 'Workday',
    startTime: 540,
    endTime: 1080,
    startStampTime: null,
    endStampTime: null,
    outStartTime: 540,
    outEndTime: 1080,
    dailyRestList: [],
    restHours: null,
    otherRestReason: null,
    remarks: null,
    requestTypeCodes: [
      'Leave',
      'OvertimeWork',
      'EarlyStartWork',
      'Absence',
      'Direct',
    ],
    requestIds: [],
    contractedDetail: {
      startTime: null,
      rest5StartTime: null,
      rest5EndTime: null,
      rest5Reason: null,
      rest4StartTime: null,
      rest4EndTime: null,
      rest4Reason: null,
      rest3StartTime: null,
      rest3EndTime: null,
      rest3Reason: null,
      rest2StartTime: null,
      rest2EndTime: null,
      rest2Reason: null,
      rest1StartTime: null,
      rest1EndTime: null,
      rest1Reason: null,
      endTime: null,
    },
    ciliTimePeriods: [
      { startTime: 540, endTime: 720 },
      { startTime: 780, endTime: 1080 },
    ],
    ciloTimePeriods: [],
    coliTimePeriods: [],
    coloTimePeriods: [],
    approver01Name: '渡邉 航',
    earlyLeaveEndTime: null,
    isSummaryLocked: false,
    isLeaveOfAbsence: false,
    insufficientRestTime: 0,
    outInsufficientMinimumWorkHours: 0,
    earlyStartWorkApplyDefaultEndTime: 540,
    overtimeWorkApplyDefaultStartTime: 1080,
    lateArrivalStartTime: 540,
    commuteCount: {
      forwardCount: 0,
      backwardCount: 0,
    },
    useManageLateArrivalPersonalReason: false,
    useManageEarlyLeavePersonalReason: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    fixDailyRequest: {
      id: undefined,
      status: STATUS.NotRequested,
      approver01Name: undefined,
      performableActionForFix: undefined,
    },

    requestDayType: 'Holiday',
    isDirectInputTimeRequest: false,

    isLocked: false,
    useFixDailyRequest: false,
    isHolLegalHoliday: false,
    isFlexWithoutCore: false,
    isFlexWithoutCoreRequireEarlyLeaveApply: false,
    personalReasonEarlyLeaveEndTime: null,
    objectiveReasonEarlyLeaveEndTime: null,
    lateArrivalEarlyLeaveReasonId: '',
  }),
  new AttRecord({
    realWorkTime: undefined,
    id: 'a0D2v00001DGI9PEAX',
    recordDate: '2020-02-18',
    dayType: 'Workday',
    startTime: 480,
    endTime: 1200,
    startStampTime: null,
    endStampTime: null,
    outStartTime: 480,
    outEndTime: 1200,
    dailyRestList: [],
    restHours: null,
    otherRestReason: null,
    remarks: null,
    requestTypeCodes: [
      'Leave',
      'OvertimeWork',
      'EarlyStartWork',
      'Absence',
      'Direct',
    ],
    requestIds: [],
    contractedDetail: {
      startTime: null,
      rest5StartTime: null,
      rest5EndTime: null,
      rest5Reason: null,
      rest4StartTime: null,
      rest4EndTime: null,
      rest4Reason: null,
      rest3StartTime: null,
      rest3EndTime: null,
      rest3Reason: null,
      rest2StartTime: null,
      rest2EndTime: null,
      rest2Reason: null,
      rest1StartTime: null,
      rest1EndTime: null,
      rest1Reason: null,
      endTime: null,
    },
    ciliTimePeriods: [
      { startTime: 540, endTime: 720 },
      { startTime: 780, endTime: 1080 },
    ],
    ciloTimePeriods: [],
    coliTimePeriods: [],
    coloTimePeriods: [
      { startTime: 480, endTime: 540 },
      { startTime: 1080, endTime: 1200 },
    ],
    approver01Name: '渡邉 航',
    earlyLeaveEndTime: null,
    isSummaryLocked: false,
    isLeaveOfAbsence: false,
    insufficientRestTime: 0,
    outInsufficientMinimumWorkHours: 0,
    earlyStartWorkApplyDefaultEndTime: 540,
    overtimeWorkApplyDefaultStartTime: 1080,
    lateArrivalStartTime: 540,
    commuteCount: {
      forwardCount: 0,
      backwardCount: 1,
    },
    useManageLateArrivalPersonalReason: false,
    useManageEarlyLeavePersonalReason: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    fixDailyRequest: {
      id: undefined,
      status: STATUS.NotRequested,
      approver01Name: undefined,
      performableActionForFix: undefined,
    },

    requestDayType: 'Holiday',
    isDirectInputTimeRequest: false,

    isLocked: false,
    useFixDailyRequest: false,
    isHolLegalHoliday: false,
    isFlexWithoutCore: false,
    isFlexWithoutCoreRequireEarlyLeaveApply: false,
    personalReasonEarlyLeaveEndTime: null,
    objectiveReasonEarlyLeaveEndTime: null,
    lateArrivalEarlyLeaveReasonId: '',
  }),
  new AttRecord({
    realWorkTime: undefined,
    id: 'a0D2v00001DGI9QEAX',
    recordDate: '2020-02-19',
    dayType: 'Workday',
    startTime: 540,
    endTime: 960,
    startStampTime: null,
    endStampTime: null,
    outStartTime: 540,
    outEndTime: 960,
    dailyRestList: [],
    restHours: null,
    otherRestReason: null,
    remarks: null,
    requestTypeCodes: [
      'Leave',
      'OvertimeWork',
      'EarlyStartWork',
      'Absence',
      'Direct',
    ],
    requestIds: [],
    contractedDetail: {
      startTime: null,
      rest5StartTime: null,
      rest5EndTime: null,
      rest5Reason: null,
      rest4StartTime: null,
      rest4EndTime: null,
      rest4Reason: null,
      rest3StartTime: null,
      rest3EndTime: null,
      rest3Reason: null,
      rest2StartTime: null,
      rest2EndTime: null,
      rest2Reason: null,
      rest1StartTime: null,
      rest1EndTime: null,
      rest1Reason: null,
      endTime: null,
    },
    ciliTimePeriods: [
      { startTime: 540, endTime: 720 },
      { startTime: 780, endTime: 960 },
    ],
    ciloTimePeriods: [],
    coliTimePeriods: [],
    coloTimePeriods: [],
    approver01Name: '渡邉 航',
    earlyLeaveEndTime: null,
    isSummaryLocked: false,
    isLeaveOfAbsence: false,
    insufficientRestTime: 0,
    outInsufficientMinimumWorkHours: 0,
    earlyStartWorkApplyDefaultEndTime: 540,
    overtimeWorkApplyDefaultStartTime: 1080,
    lateArrivalStartTime: 540,
    commuteCount: {
      forwardCount: 1,
      backwardCount: 0,
    },
    useManageLateArrivalPersonalReason: false,
    useManageEarlyLeavePersonalReason: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    fixDailyRequest: {
      id: undefined,
      status: STATUS.NotRequested,
      approver01Name: undefined,
      performableActionForFix: undefined,
    },

    requestDayType: 'Holiday',
    isDirectInputTimeRequest: false,

    isLocked: false,
    useFixDailyRequest: false,
    isHolLegalHoliday: false,
    isFlexWithoutCore: false,
    isFlexWithoutCoreRequireEarlyLeaveApply: false,
    personalReasonEarlyLeaveEndTime: null,
    objectiveReasonEarlyLeaveEndTime: null,
    lateArrivalEarlyLeaveReasonId: '',
  }),
  new AttRecord({
    realWorkTime: undefined,
    id: 'a0D2v00001DGI9REAX',
    recordDate: '2020-02-20',
    dayType: 'Workday',
    startTime: null,
    endTime: null,
    startStampTime: null,
    endStampTime: null,
    outStartTime: null,
    outEndTime: null,
    dailyRestList: [],
    restHours: null,
    otherRestReason: null,
    remarks: null,
    requestTypeCodes: [],
    requestIds: ['a012v000033TVWcAAO'],
    contractedDetail: {
      startTime: null,
      rest5StartTime: null,
      rest5EndTime: null,
      rest5Reason: null,
      rest4StartTime: null,
      rest4EndTime: null,
      rest4Reason: null,
      rest3StartTime: null,
      rest3EndTime: null,
      rest3Reason: null,
      rest2StartTime: null,
      rest2EndTime: null,
      rest2Reason: null,
      rest1StartTime: null,
      rest1EndTime: null,
      rest1Reason: null,
      endTime: null,
    },
    ciliTimePeriods: [],
    ciloTimePeriods: [],
    coliTimePeriods: [],
    coloTimePeriods: [],
    approver01Name: '渡邉 航',
    earlyLeaveEndTime: null,
    isSummaryLocked: false,
    isLeaveOfAbsence: false,
    insufficientRestTime: 0,
    outInsufficientMinimumWorkHours: 0,
    earlyStartWorkApplyDefaultEndTime: 540,
    overtimeWorkApplyDefaultStartTime: 1080,
    lateArrivalStartTime: 540,
    commuteCount: {
      forwardCount: 1,
      backwardCount: 1,
    },
    useManageLateArrivalPersonalReason: false,
    useManageEarlyLeavePersonalReason: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    fixDailyRequest: {
      id: undefined,
      status: STATUS.NotRequested,
      approver01Name: undefined,
      performableActionForFix: undefined,
    },

    requestDayType: 'Holiday',
    isDirectInputTimeRequest: false,

    isLocked: false,
    useFixDailyRequest: false,
    isHolLegalHoliday: false,
    isFlexWithoutCore: false,
    isFlexWithoutCoreRequireEarlyLeaveApply: false,
    personalReasonEarlyLeaveEndTime: null,
    objectiveReasonEarlyLeaveEndTime: null,
    lateArrivalEarlyLeaveReasonId: '',
  }),
  new AttRecord({
    realWorkTime: undefined,
    id: 'a0D2v00001DGI9SEAX',
    recordDate: '2020-02-21',
    dayType: 'Workday',
    startTime: null,
    endTime: null,
    startStampTime: null,
    endStampTime: null,
    outStartTime: null,
    outEndTime: null,
    dailyRestList: [],
    restHours: null,
    otherRestReason: null,
    remarks: null,
    requestTypeCodes: [],
    requestIds: ['a012v000033TVWcAAO'],
    contractedDetail: {
      startTime: null,
      rest5StartTime: null,
      rest5EndTime: null,
      rest5Reason: null,
      rest4StartTime: null,
      rest4EndTime: null,
      rest4Reason: null,
      rest3StartTime: null,
      rest3EndTime: null,
      rest3Reason: null,
      rest2StartTime: null,
      rest2EndTime: null,
      rest2Reason: null,
      rest1StartTime: null,
      rest1EndTime: null,
      rest1Reason: null,
      endTime: null,
    },
    ciliTimePeriods: [],
    ciloTimePeriods: [],
    coliTimePeriods: [],
    coloTimePeriods: [],
    approver01Name: '渡邉 航',
    earlyLeaveEndTime: null,
    isSummaryLocked: false,
    isLeaveOfAbsence: false,
    insufficientRestTime: 0,
    outInsufficientMinimumWorkHours: 0,
    earlyStartWorkApplyDefaultEndTime: 540,
    overtimeWorkApplyDefaultStartTime: 1080,
    lateArrivalStartTime: 540,
    commuteCount: {
      forwardCount: 0,
      backwardCount: 0,
    },
    useManageLateArrivalPersonalReason: false,
    useManageEarlyLeavePersonalReason: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    fixDailyRequest: {
      id: undefined,
      status: STATUS.NotRequested,
      approver01Name: undefined,
      performableActionForFix: undefined,
    },

    requestDayType: 'Holiday',
    isDirectInputTimeRequest: false,

    isLocked: false,
    useFixDailyRequest: false,
    isHolLegalHoliday: false,
    isFlexWithoutCore: false,
    isFlexWithoutCoreRequireEarlyLeaveApply: false,
    personalReasonEarlyLeaveEndTime: null,
    objectiveReasonEarlyLeaveEndTime: null,
    lateArrivalEarlyLeaveReasonId: '',
  }),
  new AttRecord({
    realWorkTime: undefined,
    id: 'a0D2v00001DGI9TEAX',
    recordDate: '2020-02-22',
    dayType: 'Holiday',
    startTime: null,
    endTime: null,
    startStampTime: null,
    endStampTime: null,
    outStartTime: null,
    outEndTime: null,
    dailyRestList: [],
    restHours: null,
    otherRestReason: null,
    remarks: null,
    requestTypeCodes: ['HolidayWork'],
    requestIds: [],
    contractedDetail: {
      startTime: null,
      rest5StartTime: null,
      rest5EndTime: null,
      rest5Reason: null,
      rest4StartTime: null,
      rest4EndTime: null,
      rest4Reason: null,
      rest3StartTime: null,
      rest3EndTime: null,
      rest3Reason: null,
      rest2StartTime: null,
      rest2EndTime: null,
      rest2Reason: null,
      rest1StartTime: null,
      rest1EndTime: null,
      rest1Reason: null,
      endTime: null,
    },
    ciliTimePeriods: [],
    ciloTimePeriods: [],
    coliTimePeriods: [],
    coloTimePeriods: [],
    approver01Name: '渡邉 航',
    earlyLeaveEndTime: null,
    isSummaryLocked: false,
    isLeaveOfAbsence: false,
    insufficientRestTime: 0,
    outInsufficientMinimumWorkHours: 0,
    earlyStartWorkApplyDefaultEndTime: 540,
    overtimeWorkApplyDefaultStartTime: 1080,
    lateArrivalStartTime: null,
    commuteCount: {
      forwardCount: 1,
      backwardCount: 0,
    },
    useManageLateArrivalPersonalReason: false,
    useManageEarlyLeavePersonalReason: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    fixDailyRequest: {
      id: undefined,
      status: STATUS.NotRequested,
      approver01Name: undefined,
      performableActionForFix: undefined,
    },

    requestDayType: 'Holiday',
    isDirectInputTimeRequest: false,

    isLocked: false,
    useFixDailyRequest: false,
    isHolLegalHoliday: false,
    isFlexWithoutCore: false,
    isFlexWithoutCoreRequireEarlyLeaveApply: false,
    personalReasonEarlyLeaveEndTime: null,
    objectiveReasonEarlyLeaveEndTime: null,
    lateArrivalEarlyLeaveReasonId: '',
  }),
  new AttRecord({
    realWorkTime: undefined,
    id: 'a0D2v00001DGI9UEAX',
    recordDate: '2020-02-23',
    dayType: 'LegalHoliday',
    startTime: null,
    endTime: null,
    startStampTime: null,
    endStampTime: null,
    outStartTime: null,
    outEndTime: null,
    dailyRestList: [],
    restHours: null,
    otherRestReason: null,
    remarks: null,
    requestTypeCodes: ['HolidayWork'],
    requestIds: [],
    contractedDetail: {
      startTime: null,
      rest5StartTime: null,
      rest5EndTime: null,
      rest5Reason: null,
      rest4StartTime: null,
      rest4EndTime: null,
      rest4Reason: null,
      rest3StartTime: null,
      rest3EndTime: null,
      rest3Reason: null,
      rest2StartTime: null,
      rest2EndTime: null,
      rest2Reason: null,
      rest1StartTime: null,
      rest1EndTime: null,
      rest1Reason: null,
      endTime: null,
    },
    ciliTimePeriods: [],
    ciloTimePeriods: [],
    coliTimePeriods: [],
    coloTimePeriods: [],
    approver01Name: '渡邉 航',
    earlyLeaveEndTime: null,
    isSummaryLocked: false,
    isLeaveOfAbsence: false,
    insufficientRestTime: 0,
    outInsufficientMinimumWorkHours: 0,
    earlyStartWorkApplyDefaultEndTime: 540,
    overtimeWorkApplyDefaultStartTime: 1080,
    lateArrivalStartTime: null,
    commuteCount: {
      forwardCount: 0,
      backwardCount: 1,
    },
    useManageLateArrivalPersonalReason: false,
    useManageEarlyLeavePersonalReason: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    fixDailyRequest: {
      id: undefined,
      status: STATUS.NotRequested,
      approver01Name: undefined,
      performableActionForFix: undefined,
    },

    requestDayType: null,
    isDirectInputTimeRequest: false,

    isLocked: false,
    useFixDailyRequest: false,
    isHolLegalHoliday: false,
    isFlexWithoutCore: false,
    isFlexWithoutCoreRequireEarlyLeaveApply: false,
    personalReasonEarlyLeaveEndTime: null,
    objectiveReasonEarlyLeaveEndTime: null,
    lateArrivalEarlyLeaveReasonId: '',
  }),
  new AttRecord({
    id: 'a0D2v00001DGI9VEAX',
    recordDate: '2020-02-24',
    dayType: 'Holiday',
    startTime: null,
    endTime: null,
    startStampTime: null,
    endStampTime: null,
    realWorkTime: undefined,
    outStartTime: null,
    outEndTime: null,
    dailyRestList: [],
    restHours: null,
    otherRestReason: null,
    remarks: null,
    requestTypeCodes: ['HolidayWork'],
    requestIds: [],
    contractedDetail: {
      startTime: null,
      rest5StartTime: null,
      rest5EndTime: null,
      rest5Reason: null,
      rest4StartTime: null,
      rest4EndTime: null,
      rest4Reason: null,
      rest3StartTime: null,
      rest3EndTime: null,
      rest3Reason: null,
      rest2StartTime: null,
      rest2EndTime: null,
      rest2Reason: null,
      rest1StartTime: null,
      rest1EndTime: null,
      rest1Reason: null,
      endTime: null,
    },
    ciliTimePeriods: [],
    ciloTimePeriods: [],
    coliTimePeriods: [],
    coloTimePeriods: [],
    approver01Name: '渡邉 航',
    earlyLeaveEndTime: null,
    isSummaryLocked: false,
    isLeaveOfAbsence: false,
    insufficientRestTime: 0,
    outInsufficientMinimumWorkHours: 0,
    earlyStartWorkApplyDefaultEndTime: 540,
    overtimeWorkApplyDefaultStartTime: 1080,
    lateArrivalStartTime: null,
    commuteCount: {
      forwardCount: 1,
      backwardCount: 1,
    },
    useManageLateArrivalPersonalReason: false,
    useManageEarlyLeavePersonalReason: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    fixDailyRequest: {
      id: undefined,
      status: STATUS.NotRequested,
      approver01Name: undefined,
      performableActionForFix: undefined,
    },

    requestDayType: 'Holiday',
    isDirectInputTimeRequest: false,

    isLocked: false,
    useFixDailyRequest: false,
    isHolLegalHoliday: false,
    isFlexWithoutCore: false,
    isFlexWithoutCoreRequireEarlyLeaveApply: false,
    personalReasonEarlyLeaveEndTime: null,
    objectiveReasonEarlyLeaveEndTime: null,
    lateArrivalEarlyLeaveReasonId: '',
  }),
  new AttRecord({
    realWorkTime: undefined,
    id: 'a0D2v00001DGI9WEAX',
    recordDate: '2020-02-25',
    dayType: 'Workday',
    startTime: null,
    endTime: null,
    startStampTime: null,
    endStampTime: null,
    outStartTime: null,
    outEndTime: null,
    dailyRestList: [],
    restHours: null,
    otherRestReason: null,
    remarks: null,
    requestTypeCodes: [],
    requestIds: ['a012v000033TVWcAAO'],
    contractedDetail: {
      startTime: null,
      rest5StartTime: null,
      rest5EndTime: null,
      rest5Reason: null,
      rest4StartTime: null,
      rest4EndTime: null,
      rest4Reason: null,
      rest3StartTime: null,
      rest3EndTime: null,
      rest3Reason: null,
      rest2StartTime: null,
      rest2EndTime: null,
      rest2Reason: null,
      rest1StartTime: null,
      rest1EndTime: null,
      rest1Reason: null,
      endTime: null,
    },
    ciliTimePeriods: [],
    ciloTimePeriods: [],
    coliTimePeriods: [],
    coloTimePeriods: [],
    approver01Name: '渡邉 航',
    earlyLeaveEndTime: null,
    isSummaryLocked: false,
    isLeaveOfAbsence: false,
    insufficientRestTime: 0,
    outInsufficientMinimumWorkHours: 0,
    earlyStartWorkApplyDefaultEndTime: 540,
    overtimeWorkApplyDefaultStartTime: 1080,
    lateArrivalStartTime: 540,
    commuteCount: {
      forwardCount: 0,
      backwardCount: 0,
    },
    useManageLateArrivalPersonalReason: false,
    useManageEarlyLeavePersonalReason: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    fixDailyRequest: {
      id: undefined,
      status: STATUS.NotRequested,
      approver01Name: undefined,
      performableActionForFix: undefined,
    },

    requestDayType: 'Holiday',
    isDirectInputTimeRequest: false,

    isLocked: false,
    useFixDailyRequest: false,
    isHolLegalHoliday: false,
    isFlexWithoutCore: false,
    isFlexWithoutCoreRequireEarlyLeaveApply: false,
    personalReasonEarlyLeaveEndTime: null,
    objectiveReasonEarlyLeaveEndTime: null,
    lateArrivalEarlyLeaveReasonId: '',
  }),
  new AttRecord({
    realWorkTime: undefined,
    id: 'a0D2v00001DGI9XEAX',
    recordDate: '2020-02-26',
    dayType: 'Workday',
    startTime: null,
    endTime: null,
    startStampTime: null,
    endStampTime: null,
    outStartTime: null,
    outEndTime: null,
    dailyRestList: [],
    restHours: null,
    otherRestReason: null,
    remarks: null,
    requestTypeCodes: [],
    requestIds: ['a012v000033TVWcAAO'],
    contractedDetail: {
      startTime: null,
      rest5StartTime: null,
      rest5EndTime: null,
      rest5Reason: null,
      rest4StartTime: null,
      rest4EndTime: null,
      rest4Reason: null,
      rest3StartTime: null,
      rest3EndTime: null,
      rest3Reason: null,
      rest2StartTime: null,
      rest2EndTime: null,
      rest2Reason: null,
      rest1StartTime: null,
      rest1EndTime: null,
      rest1Reason: null,
      endTime: null,
    },
    ciliTimePeriods: [],
    ciloTimePeriods: [],
    coliTimePeriods: [],
    coloTimePeriods: [],
    approver01Name: '渡邉 航',
    earlyLeaveEndTime: null,
    isSummaryLocked: false,
    isLeaveOfAbsence: false,
    insufficientRestTime: 0,
    outInsufficientMinimumWorkHours: 0,
    earlyStartWorkApplyDefaultEndTime: 540,
    overtimeWorkApplyDefaultStartTime: 1080,
    lateArrivalStartTime: 540,
    commuteCount: {
      forwardCount: 1,
      backwardCount: 0,
    },
    useManageLateArrivalPersonalReason: false,
    useManageEarlyLeavePersonalReason: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    fixDailyRequest: {
      id: undefined,
      status: STATUS.NotRequested,
      approver01Name: undefined,
      performableActionForFix: undefined,
    },

    requestDayType: 'Holiday',
    isDirectInputTimeRequest: false,

    isLocked: false,
    useFixDailyRequest: false,
    isHolLegalHoliday: false,
    isFlexWithoutCore: false,
    isFlexWithoutCoreRequireEarlyLeaveApply: false,
    personalReasonEarlyLeaveEndTime: null,
    objectiveReasonEarlyLeaveEndTime: null,
    lateArrivalEarlyLeaveReasonId: '',
  }),
  new AttRecord({
    realWorkTime: undefined,
    id: 'a0D2v00001DGI9YEAX',
    recordDate: '2020-02-27',
    dayType: 'Workday',
    startTime: null,
    endTime: null,
    startStampTime: null,
    endStampTime: null,
    outStartTime: null,
    outEndTime: null,
    dailyRestList: [],
    restHours: null,
    otherRestReason: null,
    remarks: null,
    requestTypeCodes: [],
    requestIds: ['a012v000033TVWcAAO'],
    contractedDetail: {
      startTime: null,
      rest5StartTime: null,
      rest5EndTime: null,
      rest5Reason: null,
      rest4StartTime: null,
      rest4EndTime: null,
      rest4Reason: null,
      rest3StartTime: null,
      rest3EndTime: null,
      rest3Reason: null,
      rest2StartTime: null,
      rest2EndTime: null,
      rest2Reason: null,
      rest1StartTime: null,
      rest1EndTime: null,
      rest1Reason: null,
      endTime: null,
    },
    ciliTimePeriods: [],
    ciloTimePeriods: [],
    coliTimePeriods: [],
    coloTimePeriods: [],
    approver01Name: '渡邉 航',
    earlyLeaveEndTime: null,
    isSummaryLocked: false,
    isLeaveOfAbsence: false,
    insufficientRestTime: 0,
    outInsufficientMinimumWorkHours: 0,
    earlyStartWorkApplyDefaultEndTime: 540,
    overtimeWorkApplyDefaultStartTime: 1080,
    lateArrivalStartTime: 540,
    commuteCount: {
      forwardCount: 0,
      backwardCount: 1,
    },
    useManageLateArrivalPersonalReason: false,
    useManageEarlyLeavePersonalReason: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    fixDailyRequest: {
      id: undefined,
      status: STATUS.NotRequested,
      approver01Name: undefined,
      performableActionForFix: undefined,
    },

    requestDayType: 'Holiday',
    isDirectInputTimeRequest: false,

    isLocked: false,
    useFixDailyRequest: false,
    isHolLegalHoliday: false,
    isFlexWithoutCore: false,
    isFlexWithoutCoreRequireEarlyLeaveApply: false,
    personalReasonEarlyLeaveEndTime: null,
    objectiveReasonEarlyLeaveEndTime: null,
    lateArrivalEarlyLeaveReasonId: '',
  }),
  new AttRecord({
    realWorkTime: undefined,
    id: 'a0D2v00001DGI9ZEAX',
    recordDate: '2020-02-28',
    dayType: 'Workday',
    startTime: null,
    endTime: null,
    startStampTime: null,
    endStampTime: null,
    outStartTime: null,
    outEndTime: null,
    dailyRestList: [],
    restHours: null,
    otherRestReason: null,
    remarks: null,
    requestTypeCodes: [],
    requestIds: ['a012v000033TVWcAAO'],
    contractedDetail: {
      startTime: null,
      rest5StartTime: null,
      rest5EndTime: null,
      rest5Reason: null,
      rest4StartTime: null,
      rest4EndTime: null,
      rest4Reason: null,
      rest3StartTime: null,
      rest3EndTime: null,
      rest3Reason: null,
      rest2StartTime: null,
      rest2EndTime: null,
      rest2Reason: null,
      rest1StartTime: null,
      rest1EndTime: null,
      rest1Reason: null,
      endTime: null,
    },
    ciliTimePeriods: [],
    ciloTimePeriods: [],
    coliTimePeriods: [],
    coloTimePeriods: [],
    approver01Name: '渡邉 航',
    earlyLeaveEndTime: null,
    isSummaryLocked: false,
    isLeaveOfAbsence: false,
    insufficientRestTime: 0,
    outInsufficientMinimumWorkHours: 0,
    earlyStartWorkApplyDefaultEndTime: 540,
    overtimeWorkApplyDefaultStartTime: 1080,
    lateArrivalStartTime: 540,
    commuteCount: {
      forwardCount: 1,
      backwardCount: 1,
    },
    useManageLateArrivalPersonalReason: false,
    useManageEarlyLeavePersonalReason: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    fixDailyRequest: {
      id: undefined,
      status: STATUS.NotRequested,
      approver01Name: undefined,
      performableActionForFix: undefined,
    },

    requestDayType: 'Holiday',
    isDirectInputTimeRequest: false,
    isLocked: false,
    useFixDailyRequest: false,
    isHolLegalHoliday: false,
    isFlexWithoutCore: false,
    isFlexWithoutCoreRequireEarlyLeaveApply: false,
    personalReasonEarlyLeaveEndTime: null,
    objectiveReasonEarlyLeaveEndTime: null,
    lateArrivalEarlyLeaveReasonId: '',
  }),
  new AttRecord({
    realWorkTime: undefined,
    id: 'a0D2v00001DGI9aEAH',
    recordDate: '2020-02-29',
    dayType: 'Holiday',
    startTime: null,
    endTime: null,
    startStampTime: null,
    endStampTime: null,
    outStartTime: null,
    outEndTime: null,
    dailyRestList: [],
    restHours: null,
    otherRestReason: null,
    remarks: null,
    requestTypeCodes: ['HolidayWork'],
    requestIds: [],
    contractedDetail: {
      startTime: null,
      rest5StartTime: null,
      rest5EndTime: null,
      rest5Reason: null,
      rest4StartTime: null,
      rest4EndTime: null,
      rest4Reason: null,
      rest3StartTime: null,
      rest3EndTime: null,
      rest3Reason: null,
      rest2StartTime: null,
      rest2EndTime: null,
      rest2Reason: null,
      rest1StartTime: null,
      rest1EndTime: null,
      rest1Reason: null,
      endTime: null,
    },
    ciliTimePeriods: [],
    ciloTimePeriods: [],
    coliTimePeriods: [],
    coloTimePeriods: [],
    approver01Name: '渡邉 航',
    earlyLeaveEndTime: null,
    isSummaryLocked: false,
    isLeaveOfAbsence: false,
    insufficientRestTime: 0,
    outInsufficientMinimumWorkHours: 0,
    earlyStartWorkApplyDefaultEndTime: 540,
    overtimeWorkApplyDefaultStartTime: 1080,
    lateArrivalStartTime: null,
    commuteCount: {
      forwardCount: 0,
      backwardCount: 0,
    },
    useManageLateArrivalPersonalReason: false,
    useManageEarlyLeavePersonalReason: false,
    workSystem: null,
    flexStartTime: null,
    flexEndTime: null,
    withoutCoreTime: false,
    fixDailyRequest: {
      id: undefined,
      status: STATUS.NotRequested,
      approver01Name: undefined,
      performableActionForFix: undefined,
    },

    requestDayType: 'Holiday',
    isDirectInputTimeRequest: false,
    isLocked: false,
    useFixDailyRequest: false,
    isHolLegalHoliday: false,
    isFlexWithoutCore: false,
    isFlexWithoutCoreRequireEarlyLeaveApply: false,
    personalReasonEarlyLeaveEndTime: null,
    objectiveReasonEarlyLeaveEndTime: null,
    lateArrivalEarlyLeaveReasonId: '',
  }),
];
export default attRecords;
