import { Event } from '../../../domain/models/time-management/Event';

export default [
  {
    workCategoryCode: null,
    workCategoryName: null,
    workCategoryId: null,
    title: '7',
    startDateTime: '2018-12-15T15:00:00.000Z',
    ownerId: '0052v00000WnC8VAAV',
    location: null,
    jobName: null,
    jobId: null,
    jobCode: null,
    isOuting: false,
    calculateCapacity: false,
    isOrganizer: true,
    isAllDay: true,
    id: 'a182v00000HHo7GAAT',
    externalEventId: null,
    endDateTime: '2018-12-17T15:00:00.000Z',
    description: null,
    createdServiceBy: 'teamspirit',
    contactName: null,
    contactId: null,
  },
  {
    workCategoryCode: null,
    workCategoryName: null,
    workCategoryId: null,
    title: '4',
    startDateTime: '2018-12-15T15:00:00.000Z',
    ownerId: '0052v00000WnC8VAAV',
    location: null,
    jobName: null,
    jobId: null,
    jobCode: null,
    isOuting: false,
    calculateCapacity: false,
    isOrganizer: true,
    isAllDay: true,
    id: 'a182v00000HHo7QAAT',
    externalEventId: null,
    endDateTime: '2018-12-15T15:00:00.000Z',
    description: null,
    createdServiceBy: 'teamspirit',
    contactName: null,
    contactId: null,
  },
  {
    workCategoryCode: null,
    workCategoryName: null,
    workCategoryId: null,
    title: '1',
    startDateTime: '2018-12-15T15:00:00.000Z',
    ownerId: '0052v00000WnC8VAAV',
    location: null,
    jobName: null,
    jobId: null,
    jobCode: null,
    isOuting: false,
    calculateCapacity: false,
    isOrganizer: true,
    isAllDay: true,
    id: 'a182v00000HHo6rAAD',
    externalEventId: null,
    endDateTime: '2018-12-18T15:00:00.000Z',
    description: null,
    createdServiceBy: 'teamspirit',
    contactName: null,
    contactId: null,
  },
  {
    workCategoryCode: null,
    workCategoryName: null,
    workCategoryId: null,
    title: 'others2',
    startDateTime: '2018-12-15T15:00:00.000Z',
    ownerId: '0052v00000WnC8VAAV',
    location: null,
    jobName: null,
    jobId: null,
    jobCode: null,
    isOuting: false,
    calculateCapacity: false,
    isOrganizer: true,
    isAllDay: true,
    id: 'a182v00000HHo7pAAD',
    externalEventId: null,
    endDateTime: '2018-12-15T15:00:00.000Z',
    description: null,
    createdServiceBy: 'teamspirit',
    contactName: null,
    contactId: null,
  },
  {
    workCategoryCode: null,
    workCategoryName: null,
    workCategoryId: null,
    title: 'others1',
    startDateTime: '2018-12-15T15:00:00.000Z',
    ownerId: '0052v00000WnC8VAAV',
    location: null,
    jobName: null,
    jobId: null,
    jobCode: null,
    isOuting: false,
    calculateCapacity: false,
    isOrganizer: true,
    isAllDay: true,
    id: 'a182v00000HHo7kAAD',
    externalEventId: null,
    endDateTime: '2018-12-15T15:00:00.000Z',
    description: null,
    createdServiceBy: 'teamspirit',
    contactName: null,
    contactId: null,
  },
  {
    workCategoryCode: null,
    workCategoryName: null,
    workCategoryId: null,
    title: 'othrers3',
    startDateTime: '2018-12-15T15:00:00.000Z',
    ownerId: '0052v00000WnC8VAAV',
    location: null,
    jobName: null,
    jobId: null,
    jobCode: null,
    isOuting: false,
    calculateCapacity: false,
    isOrganizer: true,
    isAllDay: true,
    id: 'a182v00000HHo7uAAD',
    externalEventId: null,
    endDateTime: '2018-12-15T15:00:00.000Z',
    description: null,
    createdServiceBy: 'teamspirit',
    contactName: null,
    contactId: null,
  },
  {
    workCategoryCode: null,
    workCategoryName: null,
    workCategoryId: null,
    title: '5',
    startDateTime: '2018-12-16T15:00:00.000Z',
    ownerId: '0052v00000WnC8VAAV',
    location: null,
    jobName: null,
    jobId: null,
    jobCode: null,
    isOuting: false,
    calculateCapacity: false,
    isOrganizer: true,
    isAllDay: true,
    id: 'a182v00000HHo7BAAT',
    externalEventId: null,
    endDateTime: '2018-12-19T15:00:00.000Z',
    description: null,
    createdServiceBy: 'teamspirit',
    contactName: null,
    contactId: null,
  },
  {
    workCategoryCode: null,
    workCategoryName: null,
    workCategoryId: null,
    title: 'others1',
    startDateTime: '2018-12-16T15:00:00.000Z',
    ownerId: '0052v00000WnC8VAAV',
    location: null,
    jobName: null,
    jobId: null,
    jobCode: null,
    isOuting: false,
    calculateCapacity: false,
    isOrganizer: true,
    isAllDay: true,
    id: 'a182v00000HHo81AAD',
    externalEventId: null,
    endDateTime: '2018-12-18T15:00:00.000Z',
    description: null,
    createdServiceBy: 'teamspirit',
    contactName: null,
    contactId: null,
  },
  {
    workCategoryCode: null,
    workCategoryName: 'ミーティング',
    workCategoryId: 'a1G2v000003yt6tEAA',
    title: 'Daily Meeting',
    startDateTime: '2018-12-16T23:00:00.000Z',
    ownerId: '0052v00000WnC8VAAV',
    location: null,
    jobName: '開発',
    jobId: 'a0h2v00000ManntAAB',
    jobCode: '1',
    isOuting: false,
    calculateCapacity: false,
    isOrganizer: true,
    isAllDay: false,
    id: 'a182v00000HHoPyAAL',
    externalEventId: null,
    endDateTime: '2018-12-17T01:00:00.000Z',
    description: null,
    createdServiceBy: 'teamspirit',
    contactName: null,
    contactId: null,
  },
  {
    workCategoryCode: null,
    workCategoryName: null,
    workCategoryId: null,
    title: 'UI/UX Lunch',
    startDateTime: '2018-12-17T03:00:00.000Z',
    ownerId: '0052v00000WnC8VAAV',
    location: null,
    jobName: null,
    jobId: null,
    jobCode: null,
    isOuting: false,
    calculateCapacity: false,
    isOrganizer: true,
    isAllDay: false,
    id: 'a182v00000HHoQ8AAL',
    externalEventId: null,
    endDateTime: '2018-12-17T04:00:00.000Z',
    description: null,
    createdServiceBy: 'teamspirit',
    contactName: null,
    contactId: null,
  },
  {
    workCategoryCode: null,
    workCategoryName: null,
    workCategoryId: null,
    title: 'Lunch with PM',
    startDateTime: '2018-12-18T03:00:00.000Z',
    ownerId: '0052v00000WnC8VAAV',
    location: null,
    jobName: null,
    jobId: null,
    jobCode: null,
    isOuting: false,
    calculateCapacity: false,
    isOrganizer: true,
    isAllDay: false,
    id: 'a182v00000HHoQDAA1',
    externalEventId: null,
    endDateTime: '2018-12-18T04:00:00.000Z',
    description: null,
    createdServiceBy: 'teamspirit',
    contactName: null,
    contactId: null,
  },
  {
    workCategoryCode: null,
    workCategoryName: 'コーディング',
    workCategoryId: 'a1G2v000003yt6oEAA',
    title: 'Development/Planner',
    startDateTime: '2018-12-18T05:00:00.000Z',
    ownerId: '0052v00000WnC8VAAV',
    location: null,
    jobName: '開発',
    jobId: 'a0h2v00000ManntAAB',
    jobCode: '1',
    isOuting: false,
    calculateCapacity: false,
    isOrganizer: true,
    isAllDay: false,
    id: 'a182v00000HHoVEAA1',
    externalEventId: null,
    endDateTime: '2018-12-18T09:00:00.000Z',
    description: null,
    createdServiceBy: 'teamspirit',
    contactName: null,
    contactId: null,
  },
  {
    workCategoryCode: null,
    workCategoryName: 'ミーティング',
    workCategoryId: 'a1G2v000003yt6tEAA',
    title: 'Backlog Grooming',
    startDateTime: '2018-12-18T05:00:00.000Z',
    ownerId: '0052v00000WnC8VAAV',
    location: null,
    jobName: '開発',
    jobId: 'a0h2v00000ManntAAB',
    jobCode: '1',
    isOuting: false,
    calculateCapacity: false,
    isOrganizer: true,
    isAllDay: false,
    id: 'a182v00000HHoVdAAL',
    externalEventId: null,
    endDateTime: '2018-12-18T06:00:00.000Z',
    description: null,
    createdServiceBy: 'teamspirit',
    contactName: null,
    contactId: null,
  },
  {
    workCategoryCode: null,
    workCategoryName: null,
    workCategoryId: null,
    title: 'Input',
    startDateTime: '2018-12-19T03:00:00.000Z',
    ownerId: '0052v00000WnC8VAAV',
    location: null,
    jobName: null,
    jobId: null,
    jobCode: null,
    isOuting: false,
    calculateCapacity: false,
    isOrganizer: true,
    isAllDay: false,
    id: 'a182v00000HHppyAAD',
    externalEventId: null,
    endDateTime: '2018-12-19T03:05:00.000Z',
    description: null,
    createdServiceBy: 'teamspirit',
    contactName: null,
    contactId: null,
  },
  {
    workCategoryCode: null,
    workCategoryName: null,
    workCategoryId: null,
    title: 'Notice',
    startDateTime: '2018-12-19T03:15:00.000Z',
    ownerId: '0052v00000WnC8VAAV',
    location: null,
    jobName: null,
    jobId: null,
    jobCode: null,
    isOuting: false,
    calculateCapacity: false,
    isOrganizer: true,
    isAllDay: false,
    id: 'a182v00000HHoWqAAL',
    externalEventId: null,
    endDateTime: '2018-12-19T03:30:00.000Z',
    description: null,
    createdServiceBy: 'teamspirit',
    contactName: null,
    contactId: null,
  },
  {
    workCategoryCode: null,
    workCategoryName: null,
    workCategoryId: null,
    title: 'Lunch at Ginza',
    startDateTime: '2018-12-19T03:30:00.000Z',
    ownerId: '0052v00000WnC8VAAV',
    location: null,
    jobName: null,
    jobId: null,
    jobCode: null,
    isOuting: false,
    calculateCapacity: false,
    isOrganizer: true,
    isAllDay: false,
    id: 'a182v00000HHoUfAAL',
    externalEventId: null,
    endDateTime: '2018-12-19T04:30:00.000Z',
    description: null,
    createdServiceBy: 'teamspirit',
    contactName: null,
    contactId: null,
  },
  {
    workCategoryCode: null,
    workCategoryName: null,
    workCategoryId: null,
    title: '1on1 with PM',
    startDateTime: '2018-12-19T08:00:00.000Z',
    ownerId: '0052v00000WnC8VAAV',
    location: null,
    jobName: 'その他',
    jobId: 'a0h2v00000a4y2zAAA',
    jobCode: '2',
    isOuting: false,
    calculateCapacity: false,
    isOrganizer: true,
    isAllDay: false,
    id: 'a182v00000HHoViAAL',
    externalEventId: null,
    endDateTime: '2018-12-19T09:00:00.000Z',
    description: null,
    createdServiceBy: 'teamspirit',
    contactName: null,
    contactId: null,
  },
  {
    workCategoryCode: null,
    workCategoryName: null,
    workCategoryId: null,
    title: '8',
    startDateTime: '2018-12-19T15:00:00.000Z',
    ownerId: '0052v00000WnC8VAAV',
    location: null,
    jobName: null,
    jobId: null,
    jobCode: null,
    isOuting: false,
    calculateCapacity: false,
    isOrganizer: true,
    isAllDay: true,
    id: 'a182v00000HHo7LAAT',
    externalEventId: null,
    endDateTime: '2018-12-19T15:00:00.000Z',
    description: null,
    createdServiceBy: 'teamspirit',
    contactName: null,
    contactId: null,
  },
  {
    workCategoryCode: null,
    workCategoryName: null,
    workCategoryId: null,
    title: '2',
    startDateTime: '2018-12-19T15:00:00.000Z',
    ownerId: '0052v00000WnC8VAAV',
    location: null,
    jobName: null,
    jobId: null,
    jobCode: null,
    isOuting: false,
    calculateCapacity: false,
    isOrganizer: true,
    isAllDay: true,
    id: 'a182v00000HHo71AAD',
    externalEventId: null,
    endDateTime: '2018-12-19T15:00:00.000Z',
    description: null,
    createdServiceBy: 'teamspirit',
    contactName: null,
    contactId: null,
  },
  {
    workCategoryCode: null,
    workCategoryName: 'コーディング',
    workCategoryId: 'a1G2v000003yt6oEAA',
    title: 'Meeting',
    startDateTime: '2018-12-20T01:00:00.000Z',
    ownerId: '0052v00000WnC8VAAV',
    location: null,
    jobName: '開発',
    jobId: 'a0h2v00000ManntAAB',
    jobCode: '1',
    isOuting: false,
    calculateCapacity: false,
    isOrganizer: true,
    isAllDay: false,
    id: 'a182v00000HHpjlAAD',
    externalEventId: null,
    endDateTime: '2018-12-20T02:00:00.000Z',
    description: null,
    createdServiceBy: 'teamspirit',
    contactName: null,
    contactId: null,
  },
  {
    workCategoryCode: null,
    workCategoryName: null,
    workCategoryId: null,
    title: 'Party',
    startDateTime: '2018-12-20T01:00:00.000Z',
    ownerId: '0052v00000WnC8VAAV',
    location: null,
    jobName: null,
    jobId: null,
    jobCode: null,
    isOuting: false,
    calculateCapacity: false,
    isOrganizer: true,
    isAllDay: false,
    id: 'a182v00000HHpjMAAT',
    externalEventId: null,
    endDateTime: '2018-12-20T06:00:00.000Z',
    description: null,
    createdServiceBy: 'teamspirit',
    contactName: null,
    contactId: null,
  },
  {
    workCategoryCode: null,
    workCategoryName: null,
    workCategoryId: null,
    title: 'Input',
    startDateTime: '2018-12-20T01:00:00.000Z',
    ownerId: '0052v00000WnC8VAAV',
    location: null,
    jobName: null,
    jobId: null,
    jobCode: null,
    isOuting: false,
    calculateCapacity: false,
    isOrganizer: true,
    isAllDay: false,
    id: 'a182v00000HHpl8AAD',
    externalEventId: null,
    endDateTime: '2018-12-20T01:30:00.000Z',
    description: null,
    createdServiceBy: 'teamspirit',
    contactName: null,
    contactId: null,
  },
  {
    workCategoryCode: null,
    workCategoryName: 'レビュー',
    workCategoryId: 'a1G2v000003yt6yEAA',
    title: 'Review',
    startDateTime: '2018-12-20T04:00:00.000Z',
    ownerId: '0052v00000WnC8VAAV',
    location: null,
    jobName: '開発',
    jobId: 'a0h2v00000ManntAAB',
    jobCode: '1',
    isOuting: false,
    calculateCapacity: false,
    isOrganizer: true,
    isAllDay: false,
    id: 'a182v00000HHpkPAAT',
    externalEventId: null,
    endDateTime: '2018-12-20T05:00:00.000Z',
    description: null,
    createdServiceBy: 'teamspirit',
    contactName: null,
    contactId: null,
  },
  {
    workCategoryCode: null,
    workCategoryName: null,
    workCategoryId: null,
    title: 'All Night Conference',
    startDateTime: '2018-12-20T10:00:00.000Z',
    ownerId: '0052v00000WnC8VAAV',
    location: null,
    jobName: null,
    jobId: null,
    jobCode: null,
    isOuting: false,
    calculateCapacity: false,
    isOrganizer: true,
    isAllDay: false,
    id: 'a182v00000HHoUuAAL',
    externalEventId: null,
    endDateTime: '2018-12-20T22:00:00.000Z',
    description: null,
    createdServiceBy: 'teamspirit',
    contactName: null,
    contactId: null,
  },
  {
    workCategoryCode: null,
    workCategoryName: null,
    workCategoryId: null,
    title: 'CW1',
    startDateTime: '2018-12-20T15:00:00.000Z',
    ownerId: '0052v00000WnC8VAAV',
    location: null,
    jobName: null,
    jobId: null,
    jobCode: null,
    isOuting: false,
    calculateCapacity: false,
    isOrganizer: true,
    isAllDay: false,
    id: 'a182v00000HHoP0AAL',
    externalEventId: null,
    endDateTime: '2018-12-21T15:00:00.000Z',
    description: null,
    createdServiceBy: 'teamspirit',
    contactName: null,
    contactId: null,
  },
  {
    workCategoryCode: null,
    workCategoryName: null,
    workCategoryId: null,
    title: '3',
    startDateTime: '2018-12-20T15:00:00.000Z',
    ownerId: '0052v00000WnC8VAAV',
    location: null,
    jobName: null,
    jobId: null,
    jobCode: null,
    isOuting: false,
    calculateCapacity: false,
    isOrganizer: true,
    isAllDay: true,
    id: 'a182v00000HHo7aAAD',
    externalEventId: null,
    endDateTime: '2018-12-21T15:00:00.000Z',
    description: null,
    createdServiceBy: 'teamspirit',
    contactName: null,
    contactId: null,
  },
  {
    workCategoryCode: null,
    workCategoryName: null,
    workCategoryId: null,
    title: 'Study English',
    startDateTime: '2018-12-21T10:00:00.000Z',
    ownerId: '0052v00000WnC8VAAV',
    location: null,
    jobName: null,
    jobId: null,
    jobCode: null,
    isOuting: false,
    calculateCapacity: false,
    isOrganizer: true,
    isAllDay: false,
    id: 'a182v00000HHoWRAA1',
    externalEventId: null,
    endDateTime: '2018-12-21T11:00:00.000Z',
    description: null,
    createdServiceBy: 'teamspirit',
    contactName: null,
    contactId: null,
  },
  {
    workCategoryCode: null,
    workCategoryName: null,
    workCategoryId: null,
    title: '6',
    startDateTime: '2018-12-21T15:00:00.000Z',
    ownerId: '0052v00000WnC8VAAV',
    location: null,
    jobName: null,
    jobId: null,
    jobCode: null,
    isOuting: false,
    isOrganizer: true,
    isAllDay: true,
    id: 'a182v00000HHo76AAD',
    externalEventId: null,
    endDateTime: '2018-12-21T15:00:00.000Z',
    description: null,
    createdServiceBy: 'teamspirit',
    contactName: null,
    contactId: null,
  },
] as Event[];
