// eslint-disable-next-line import/prefer-default-export
export const snapshot = {
  '2019-05-01': {
    status: null,
    recordDate: '2019-05-01',
    output: null,
    note: null,
    dailyRecordItemList: [],
    targetDate: '2019-05-01',
    time: null,
    realWorkTime: null,
    totalTaskTime: null,
  },
  '2019-05-02': {
    status: null,
    recordDate: '2019-05-02',
    output: null,
    note: null,
    dailyRecordItemList: [],
    targetDate: '2019-05-02',
    time: null,
    realWorkTime: null,
    totalTaskTime: null,
  },
  '2019-05-03': {
    status: null,
    recordDate: '2019-05-03',
    output: null,
    note: null,
    dailyRecordItemList: [],
    targetDate: '2019-05-03',
    time: null,
    realWorkTime: null,
    totalTaskTime: null,
  },
  '2019-05-04': {
    status: null,
    recordDate: '2019-05-04',
    output: null,
    note: null,
    dailyRecordItemList: [],
    targetDate: '2019-05-04',
    time: null,
    realWorkTime: null,
    totalTaskTime: null,
  },
  '2019-05-05': {
    status: null,
    recordDate: '2019-05-05',
    output: null,
    note: null,
    dailyRecordItemList: [],
    targetDate: '2019-05-05',
    time: null,
    realWorkTime: null,
    totalTaskTime: null,
  },
  '2019-05-06': {
    status: null,
    recordDate: '2019-05-06',
    output: null,
    note: null,
    dailyRecordItemList: [
      {
        workCategoryName: '',
        workCategoryId: null,
        workCategoryCode: null,
        taskTime: null,
        taskNote: null,
        ratio: 100,
        jobName: '002 - お寿司の醤油のキャップをしめる仕事',
        jobId: 'a0V6F00000yJp0aUAC',
        jobCode: '002',
      },
      {
        workCategoryName: 'テストD',
        workCategoryId: 'a0o6F00000ZxCBiQAN',
        workCategoryCode: 'E010',
        taskTime: 310,
        taskNote: null,
        ratio: null,
        jobName: '004 - 自宅の警備員の仕事',
        jobId: 'a0V6F00000yJsUuUAK',
        jobCode: '004',
      },
    ],
    targetDate: '2019-05-06',
    time: 310,
    realWorkTime: null,
    totalTaskTime: 310,
  },
  '2019-05-07': {
    status: null,
    recordDate: '2019-05-07',
    output: null,
    note: null,
    dailyRecordItemList: [
      {
        workCategoryName: '',
        workCategoryId: null,
        workCategoryCode: null,
        taskTime: 600,
        taskNote: null,
        ratio: 0,
        jobName: '004 - 自宅の警備員の仕事',
        jobId: 'a0V6F00000yJsUuUAK',
        jobCode: '004',
      },
      {
        workCategoryName: '',
        workCategoryId: null,
        workCategoryCode: null,
        taskTime: null,
        taskNote: null,
        ratio: 100,
        jobName:
          '001 - 刺身の上にタンポポを置く仕事 -----------------------------------------------------------',
        jobId: 'a0V6F00000yJp06UAC',
        jobCode: '001',
      },
    ],
    targetDate: '2019-05-07',
    time: 600,
    realWorkTime: 60,
    totalTaskTime: 600,
  },
  '2019-05-08': {
    status: null,
    recordDate: '2019-05-08',
    output: null,
    note: null,
    dailyRecordItemList: [
      {
        workCategoryName: '',
        workCategoryId: null,
        workCategoryCode: null,
        taskTime: null,
        taskNote: null,
        ratio: 100,
        jobName:
          '001 - 刺身の上にタンポポを置く仕事 -----------------------------------------------------------',
        jobId: 'a0V6F00000yJp06UAC',
        jobCode: '001',
      },
      {
        workCategoryName: '',
        workCategoryId: null,
        workCategoryCode: null,
        taskTime: 255,
        taskNote: null,
        ratio: null,
        jobName: '003 - そうめんに２〜３本だけ黄色や赤色や緑色の麺を混ぜる仕事',
        jobId: 'a0V6F00000yJp0uUAC',
        jobCode: '003',
      },
      {
        workCategoryName: '',
        workCategoryId: null,
        workCategoryCode: null,
        taskTime: 380,
        taskNote: null,
        ratio: null,
        jobName: '002 - お寿司の醤油のキャップをしめる仕事',
        jobId: 'a0V6F00000yJp0aUAC',
        jobCode: '002',
      },
      {
        workCategoryName: '',
        workCategoryId: null,
        workCategoryCode: null,
        taskTime: 155,
        taskNote: null,
        ratio: null,
        jobName: '004 - 自宅の警備員の仕事',
        jobId: 'a0V6F00000yJsUuUAK',
        jobCode: '004',
      },
    ],
    targetDate: '2019-05-08',
    time: 790,
    realWorkTime: null,
    totalTaskTime: 790,
  },
  '2019-05-09': {
    status: null,
    recordDate: '2019-05-09',
    output: null,
    note: null,
    dailyRecordItemList: [
      {
        workCategoryName: '',
        workCategoryId: null,
        workCategoryCode: null,
        taskTime: null,
        taskNote: null,
        ratio: 100,
        jobName:
          '001 - 刺身の上にタンポポを置く仕事 -----------------------------------------------------------',
        jobId: 'a0V6F00000yJp06UAC',
        jobCode: '001',
      },
      {
        workCategoryName: 'テストA',
        workCategoryId: 'a0o6F00000ZxCBTQA3',
        workCategoryCode: 'B010',
        taskTime: 330,
        taskNote: null,
        ratio: null,
        jobName:
          '001 - 刺身の上にタンポポを置く仕事 -----------------------------------------------------------',
        jobId: 'a0V6F00000yJp06UAC',
        jobCode: '001',
      },
    ],
    targetDate: '2019-05-09',
    time: 330,
    realWorkTime: null,
    totalTaskTime: 330,
  },
  '2019-05-10': {
    status: null,
    recordDate: '2019-05-10',
    output: null,
    note: null,
    dailyRecordItemList: [],
    targetDate: '2019-05-10',
    time: null,
    realWorkTime: 60,
    totalTaskTime: null,
  },
  '2019-05-11': {
    status: null,
    recordDate: '2019-05-11',
    output: null,
    note: null,
    dailyRecordItemList: [],
    targetDate: '2019-05-11',
    time: null,
    realWorkTime: null,
    totalTaskTime: null,
  },
  '2019-05-12': {
    status: null,
    recordDate: '2019-05-12',
    output: null,
    note: null,
    dailyRecordItemList: [],
    targetDate: '2019-05-12',
    time: null,
    realWorkTime: null,
    totalTaskTime: null,
  },
  '2019-05-13': {
    status: null,
    recordDate: '2019-05-13',
    output: null,
    note: null,
    dailyRecordItemList: [],
    targetDate: '2019-05-13',
    time: null,
    realWorkTime: null,
    totalTaskTime: null,
  },
  '2019-05-14': {
    status: null,
    recordDate: '2019-05-14',
    output: null,
    note: null,
    dailyRecordItemList: [
      {
        workCategoryName: '',
        workCategoryId: null,
        workCategoryCode: null,
        taskTime: null,
        taskNote: null,
        ratio: 100,
        jobName: '002 - お寿司の醤油のキャップをしめる仕事',
        jobId: 'a0V6F00000yJp0aUAC',
        jobCode: '002',
      },
      {
        workCategoryName: '',
        workCategoryId: null,
        workCategoryCode: null,
        taskTime: 80,
        taskNote: null,
        ratio: null,
        jobName:
          '001 - 刺身の上にタンポポを置く仕事 -----------------------------------------------------------',
        jobId: 'a0V6F00000yJp06UAC',
        jobCode: '001',
      },
      {
        workCategoryName:
          '親譲りの無鉄砲で小供の時から損ばかりしている。小学校に居る時分学校の二階から飛び降りて一週間ほど腰を抜かした事がある。なぜそんな無闇をしたと聞く人があるかも知れ',
        workCategoryId: 'a0o6F00000Zw4X1QAJ',
        workCategoryCode: 'A010',
        taskTime: 365,
        taskNote: null,
        ratio: null,
        jobName: '004 - 自宅の警備員の仕事',
        jobId: 'a0V6F00000yJsUuUAK',
        jobCode: '004',
      },
    ],
    targetDate: '2019-05-14',
    time: 445,
    realWorkTime: 362,
    totalTaskTime: 445,
  },
  '2019-05-15': {
    status: null,
    recordDate: '2019-05-15',
    output: null,
    note: null,
    dailyRecordItemList: [
      {
        workCategoryName: '',
        workCategoryId: null,
        workCategoryCode: null,
        taskTime: 390,
        taskNote: null,
        ratio: null,
        jobName:
          '001 - 刺身の上にタンポポを置く仕事 -----------------------------------------------------------',
        jobId: 'a0V6F00000yJp06UAC',
        jobCode: '001',
      },
      {
        workCategoryName:
          '親譲りの無鉄砲で小供の時から損ばかりしている。小学校に居る時分学校の二階から飛び降りて一週間ほど腰を抜かした事がある。なぜそんな無闇をしたと聞く人があるかも知れ',
        workCategoryId: 'a0o6F00000Zw4X1QAJ',
        workCategoryCode: 'A010',
        taskTime: 185,
        taskNote: null,
        ratio: null,
        jobName: '004 - 自宅の警備員の仕事',
        jobId: 'a0V6F00000yJsUuUAK',
        jobCode: '004',
      },
    ],
    targetDate: '2019-05-15',
    time: 575,
    realWorkTime: null,
    totalTaskTime: 575,
  },
  '2019-05-16': {
    status: null,
    recordDate: '2019-05-16',
    output: null,
    note: null,
    dailyRecordItemList: [],
    targetDate: '2019-05-16',
    time: null,
    realWorkTime: null,
    totalTaskTime: null,
  },
  '2019-05-17': {
    status: null,
    recordDate: '2019-05-17',
    output: null,
    note: null,
    dailyRecordItemList: [],
    targetDate: '2019-05-17',
    time: null,
    realWorkTime: null,
    totalTaskTime: null,
  },
  '2019-05-18': {
    status: null,
    recordDate: '2019-05-18',
    output: null,
    note: null,
    dailyRecordItemList: [],
    targetDate: '2019-05-18',
    time: null,
    realWorkTime: null,
    totalTaskTime: null,
  },
  '2019-05-19': {
    status: null,
    recordDate: '2019-05-19',
    output: null,
    note: null,
    dailyRecordItemList: [],
    targetDate: '2019-05-19',
    time: null,
    realWorkTime: null,
    totalTaskTime: null,
  },
  '2019-05-20': {
    status: null,
    recordDate: '2019-05-20',
    output: null,
    note: null,
    dailyRecordItemList: [],
    targetDate: '2019-05-20',
    time: null,
    realWorkTime: null,
    totalTaskTime: null,
  },
  '2019-05-21': {
    status: null,
    recordDate: '2019-05-21',
    output: null,
    note: null,
    dailyRecordItemList: [],
    targetDate: '2019-05-21',
    time: null,
    realWorkTime: null,
    totalTaskTime: null,
  },
  '2019-05-22': {
    status: null,
    recordDate: '2019-05-22',
    output: null,
    note: null,
    dailyRecordItemList: [],
    targetDate: '2019-05-22',
    time: null,
    realWorkTime: null,
    totalTaskTime: null,
  },
  '2019-05-23': {
    status: null,
    recordDate: '2019-05-23',
    output: null,
    note: null,
    dailyRecordItemList: [],
    targetDate: '2019-05-23',
    time: null,
    realWorkTime: null,
    totalTaskTime: null,
  },
  '2019-05-24': {
    status: null,
    recordDate: '2019-05-24',
    output: null,
    note: null,
    dailyRecordItemList: [],
    targetDate: '2019-05-24',
    time: null,
    realWorkTime: null,
    totalTaskTime: null,
  },
  '2019-05-25': {
    status: null,
    recordDate: '2019-05-25',
    output: null,
    note: null,
    dailyRecordItemList: [],
    targetDate: '2019-05-25',
    time: null,
    realWorkTime: null,
    totalTaskTime: null,
  },
  '2019-05-26': {
    status: null,
    recordDate: '2019-05-26',
    output: null,
    note: null,
    dailyRecordItemList: [],
    targetDate: '2019-05-26',
    time: null,
    realWorkTime: null,
    totalTaskTime: null,
  },
  '2019-05-27': {
    status: null,
    recordDate: '2019-05-27',
    output: null,
    note: null,
    dailyRecordItemList: [],
    targetDate: '2019-05-27',
    time: null,
    realWorkTime: null,
    totalTaskTime: null,
  },
  '2019-05-28': {
    status: null,
    recordDate: '2019-05-28',
    output: null,
    note: null,
    dailyRecordItemList: [],
    targetDate: '2019-05-28',
    time: null,
    realWorkTime: null,
    totalTaskTime: null,
  },
  '2019-05-29': {
    status: null,
    recordDate: '2019-05-29',
    output: null,
    note: null,
    dailyRecordItemList: [],
    targetDate: '2019-05-29',
    time: null,
    realWorkTime: null,
    totalTaskTime: null,
  },
  '2019-05-30': {
    status: null,
    recordDate: '2019-05-30',
    output: null,
    note: null,
    dailyRecordItemList: [],
    targetDate: '2019-05-30',
    time: null,
    realWorkTime: null,
    totalTaskTime: null,
  },
  '2019-05-31': {
    status: null,
    recordDate: '2019-05-31',
    output: null,
    note: null,
    dailyRecordItemList: [],
    targetDate: '2019-05-31',
    time: null,
    realWorkTime: null,
    totalTaskTime: null,
  },
};
