if(typeof(teasp) == 'object' && !teasp.resolved['8302'] && teasp.dialog && teasp.dialog.EmpApply){
teasp.dialog.EmpApply.prototype.createHolidayWorkForm=function(e,t,a,o,s){var i=!1,n=null,r=!1,l=this.pouch.isUseDaiqManage(),p=3;
this.dayWrap.getExplicDayType()!=teasp.constant.DAY_TYPE_LEGAL_HOLIDAY||this.pouch.isUseDaiqLegalHoliday()?this.dayWrap.isPlannedHoliday()?(r=!0,this.pouch.isUseDaiqManage()&&!o&&(n=teasp.message.getLabel("tm10003840")),l=!1):this.pouch.isNoDaiqExchanged()&&this.dayWrap.isExchangedEdge()&&(o||(n=teasp.message.getLabel("tm10003960")),l=!1):(this.pouch.isUseDaiqManage()&&!o&&(n=teasp.message.getLabel("tm10003770")),l=!1);
var d=o&&teasp.constant.STATUS_FIX.contains(o.status)||this.isReadOnly(),c=this.getInputClass(d,o),m=dojo.create("div",null,t);if(this.holidayWorkRests=this.dayWrap.getPattern().restTimes||[],(this.pouch.isHolidayWorkRestChangeable()||d)&&o&&o.timeTable&&(this.holidayWorkRests=teasp.util.extractTimes(o.timeTable)),this.holidayWorkRestChangeable=!1,!d&&!this.pouch.isHideTimeGraphPopup()){var h=dojo.create("div",{id:"dialogApplyZangyoRow"+a,
className:"empApply2Div"},m);dojo.create("div",{className:"empApply2CL",innerHTML:teasp.message.getLabel("zangyoOfMonth_label")},h),dojo.create("div",{className:"empApply2VL",innerHTML:this.pouch.getMonthSubTimeByKey("workLegalOutOverTime"),id:"dialogApplyZangyo"+a,style:"margin:0px 4px;"},h)}var u=function(){var e=teasp.util.time.clock2minutes(dojo.byId("dialogApplyStartTime"+a).value),t=teasp.util.time.clock2minutes(dojo.byId("dialogApplyEndTime"+a).value),o=0,s=0,i=this.holidayWorkRests;
if("number"==typeof e&&"number"==typeof t&&e<t){s=teasp.util.time.rangeTime({from:e,to:t},i),o=t-e-s;for(var n=this.pouch.getRestTimeCheck(),r=0,l=0;l<n.length;l++){var p=n[l];if(p.check&&p.push&&o>p.workTime&&s<p.restTime){var d=p.restTime-s;r<d&&(r=d)}}o-=r,s=t-e-o}return{workTime:o,restTime:s}},g=function(){for(var e=this.pouch.getRestTimeCheck(),t=[],a=0;a<e.length;a++){var o=e[a];o.check&&o.push&&t.push(teasp.message.getLabel("tf10007290",teasp.util.time.timeValue(o.workTime),teasp.util.time.timeValue(o.restTime)));
}return t.length>0?teasp.message.getLabel("tf10007300",t.join(teasp.message.getLabel("tm10001560"))):null},y=function(){if(this.holidayWorkRestChangeable){for(var e=this.holidayWorkRests||[],t=[],a=0;a<e.length;a++){for(var o=e[a],s=""+o.from,i=""+o.to,n=""+o.type;s.length<4;)s="0"+s;for(;i.length<4;)i="0"+i;for(;n.length<2;)n="0"+n;t.push(s+i+n)}return t.join(":")+":"}return null},f=null,b=null,v=function(e){var t=u.apply(this),o=dojo.byId("dialogApplyTimeRest"+a);
if(o&&(o.innerHTML=teasp.util.time.timeValue(t.restTime)),l){var s=this.pouch.getDaiqAllBorderTime(),i=this.pouch.isUseHalfDaiq()?this.pouch.getDaiqHalfBorderTime():-1;p=0,i>=0&&t.workTime>=i&&(p=1),t.workTime>=s&&(p|=2),console.log("o.workTime="+t.workTime+" ("+teasp.util.time.timeValue(t.workTime)+"), daiqFlag="+p),b&&b.apply(this),f&&f.apply(this,[null,e])}};if(this.createTimeParts(e,m,a,o,this.pouch.isUseRegulateHoliday()||r,v),
this.pouch.isHolidayWorkRestChangeable()||d&&o&&o.timeTable){this.holidayWorkRestChangeable=!0;var _=dojo.byId("dialogApplyTimeNote"+a),h=dojo.create("tr",null,dojo.create("tbody",null,dojo.create("table",{className:"pane_table horizon"},_,"before"))),T=dojo.create("td",{style:{paddingTop:"1px"}},h);dojo.create("div",{style:"margin:5px 6px 5px 2px;font-weight:bold;float:left;",innerHTML:teasp.message.getLabel("restTime_label")
},T),dojo.create("div",{id:"dialogApplyTimeRest"+a,style:"margin:5px;float:left;",innerHTML:"0:00"},T);var j=dojo.create("button",{id:"dialogApplyTimeRestChange"+a,className:"std-button2",style:"margin:0px 8px 0px 0px;"},T);dojo.create("div",{style:"margin:2px 6px;float:left;",innerHTML:teasp.message.getLabel(d?"setting_btn_title":"change_btn_title")},j),this.eventHandles.push(dojo.connect(j,"onclick",this,function(){
teasp.manager.dialogOpen("RestInput",{rests:this.holidayWorkRests,fxtimes:this.dayWrap.getFixTimeNums(),note:g.apply(this),fix:d},this.pouch,this,function(e){this.holidayWorkRests=e,v.apply(this,[!0])})}))}if(this.pouch.isUseDirectApply()||d&&o&&(o.directFlag||o.travelTime)){var h=dojo.create("div",{className:"empApply2Div"},m);dojo.create("div",{className:"empApply2CL",innerHTML:teasp.message.getLabel("tk10004670")},h);
var T=dojo.create("div",{className:"empApply2VL",style:"padding:0px;"},h),E=dojo.create("tbody",null,dojo.create("table",{className:"pane_table"},T)),L=dojo.create("tr",null,E),k=dojo.create("td",{style:{paddingTop:"1px"}},L),D=dojo.create("div",{style:{margin:"2px 4px 2px 0px","float":"left"}},k),I=dojo.create("label",null,D),A=dojo.create("input",{type:"checkbox",style:{margin:"2px"},id:"dialogApplyDirectIn"+a},I);dojo.create("span",{
innerHTML:teasp.message.getLabel("tk10004680"),style:{margin:"2px"}},I),D=dojo.create("div",{style:{margin:"2px 4px 2px 0px","float":"left"}},k),I=dojo.create("label",null,D);var x=dojo.create("input",{type:"checkbox",style:{margin:"2px"},id:"dialogApplyDirectOut"+a},I);dojo.create("span",{innerHTML:teasp.message.getLabel("tk10004690"),style:{margin:"2px"}},I),o&&(A.checked=0!=(1&o.directFlag),x.checked=0!=(2&o.directFlag)),
A.disabled=o&&(teasp.constant.STATUS_FIX.contains(o.status)||!o.active),x.disabled=o&&(teasp.constant.STATUS_FIX.contains(o.status)||!o.active),teasp.isNarrow()&&(h=dojo.create("div",{className:"empApply2Div"},m)),dojo.create("div",{className:"empApply2CL",style:teasp.isNarrow()?"":"min-width:100px;margin-left:20px;",innerHTML:teasp.message.getLabel("tk10004710")},h);var S=dojo.create("input",{type:"text",id:"dialogApplyTravelTime"+a,
style:"margin:2px;",className:"inputime "+c},dojo.create("div",{className:"empApply2VL"},h));o&&("number"==typeof o.travelTime&&(S.value=teasp.util.time.timeValue(o.travelTime)),this.changeInputAreaView(S,o,d)),d?S.readOnly="readOnly":(this.eventHandles.push(dojo.connect(S,"blur",this,teasp.util.time.onblurTime)),this.eventHandles.push(dojo.connect(S,"onkeypress",this,teasp.util.time.onkeypressTime)))}if(this.pouch.isUseDirectApply()||d&&o&&o.workType){
var h=dojo.create("div",{className:"empApply2Div"},m);if(dojo.create("div",{className:"empApply2CL",innerHTML:teasp.message.getLabel("tk10004700")},h),!o||!d&&o.active){var w=dojo.create("select",{id:"dialogApplyWorkType"+a,className:c,style:"width:100%;margin:2px;"},dojo.create("div",{className:"empApply2VL",style:dojo.string.substitute("width:${0};",[this.valueWidth])},h)),M=this.pouch.getWorkTypeList()||[];dojo.create("option",{
value:"",innerHTML:""},w);for(var O=0;O<M.length;O++)dojo.create("option",{value:M[O],innerHTML:M[O]},w);h.style.display=M.length>0?"":"none"}else{var N=o.workType||"";dojo.create("div",{className:"empApply2VL",innerHTML:N,style:"margin:2px;"},h),h.style.display=N?"":"none"}}if(this.createNoteParts(e,m,a,o),l&&this.pouch.isUseDaiqReserve()||o&&o.daiqReserve&&o.daiqDate1){i=this.pouch.isUseHalfDaiq()||o&&o.daiqDate2;var h=dojo.create("div",{
className:"empApply2Div",id:"dialogApplyDaiqResvRow"+a},m);dojo.create("div",{className:"empApply2CL",innerHTML:teasp.message.getLabel("daiqReserve_label")},h),dojo.create("input",{type:"checkbox",checked:!0,id:"dialogApplyDaiqResv"+a},dojo.create("div",{className:"empApply2VL"},h));var h=dojo.create("div",{className:"empApply2Div",id:"dialogApplyDaiq1DateRow"+a},m);dojo.create("div",{className:"empApply2CL",innerHTML:teasp.message.getLabel(i?"daiqDate1_label":"daiqDate_label")
},h);var R=dojo.create("tr",null,dojo.create("tbody",null,dojo.create("table",{className:"pane_table"},dojo.create("div",{className:"empApply2VL"},h))));dojo.create("input",{type:"text",id:"dialogApplyDaiq1Date"+a,style:{margin:"2px"},className:"inpudate "+c},dojo.create("td",null,R));var H=d?null:dojo.create("input",{type:"button",id:"dialogApplyDaiq1DateCal"+a,style:{margin:"2px"},className:"pp_base pp_btn_cal_dis"},dojo.create("td",null,R)),C=dojo.create("td",{
className:"daiq1-option"},R);b=function(e){var t=e||dojo.query("#dialogApplyDaiq1DateRow"+a+" td.daiq1-option")[0];if(t){var s="1",i=dojo.byId("dialogApplyDaiq1Option"+a);i?s=i.value:i=dojo.create("select",{id:"dialogApplyDaiq1Option"+a,style:"margin-left:4px;",className:"inputran"},t),dojo.empty(i),dojo.create("option",{value:"0",innerHTML:""},i),2&p?dojo.create("option",{value:"1",innerHTML:teasp.message.getLabel("holidayDay_label")
},i):"1"==s&&(s="0"),this.pouch.isUseHalfDaiq()||d&&o&&o.daiqReserve&&"1"!=(o.daiqDate1Range||"1")?(dojo.create("option",{value:"2",innerHTML:teasp.message.getLabel("holidayAm_label")},i),dojo.create("option",{value:"3",innerHTML:teasp.message.getLabel("holidayPm_label")},i)):this.pouch.isUseHalfDaiq()||dojo.style(t,"display","none"),i.value=s}},b.apply(this,[C]);var h=dojo.create("div",{className:"empApply2Div",id:"dialogApplyDaiq2DateRow"+a
},m);dojo.create("div",{className:"empApply2CL",innerHTML:teasp.message.getLabel("daiqDate2_label")},h),R=dojo.create("tr",null,dojo.create("tbody",null,dojo.create("table",{className:"pane_table"},dojo.create("div",{className:"empApply2VL"},h)))),dojo.create("input",{type:"text",id:"dialogApplyDaiq2Date"+a,style:{margin:"2px"},className:"inpudate "+c},dojo.create("td",null,R));var P=d?null:dojo.create("input",{type:"button",
id:"dialogApplyDaiq2DateCal"+a,style:{margin:"2px"},className:"pp_base pp_btn_cal_dis"},dojo.create("td",null,R));w=dojo.create("select",{id:"dialogApplyDaiq2Option"+a,style:"margin-left:4px;",className:"inputran"},dojo.create("td",null,R)),dojo.create("option",{value:"0",innerHTML:""},w),dojo.create("option",{value:"2",innerHTML:teasp.message.getLabel("holidayAm_label")},w),dojo.create("option",{value:"3",innerHTML:teasp.message.getLabel("holidayPm_label")
},w),w.value="0",i||dojo.style(h,"display","none"),o?(dojo.byId("dialogApplyDaiqResv"+a).checked=o.daiqReserve,dojo.byId("dialogApplyDaiq1Date"+a).value=teasp.util.date.formatDate(o.daiqDate1,"SLA"),H&&(H.className="pp_base pp_btn_cal"),dojo.byId("dialogApplyDaiq1Option"+a).value=o.daiqDate1Range||"1","1"==o.daiqDate1Range?(dojo.byId("dialogApplyDaiq2Date"+a).value="",P&&(P.className="pp_base pp_btn_cal_dis"),dojo.byId("dialogApplyDaiq2Option"+a).value="0"):(dojo.byId("dialogApplyDaiq2Date"+a).value=teasp.util.date.formatDate(o.daiqDate2,"SLA"),
P&&(P.className="pp_base pp_btn_cal"),dojo.byId("dialogApplyDaiq2Option"+a).value=o.daiqDate2Range||"0"),d&&(dojo.byId("dialogApplyDaiqResv"+a).disabled=!0,dojo.byId("dialogApplyDaiq1Date"+a).disabled=!0,dojo.byId("dialogApplyDaiq2Date"+a).disabled=!0,dojo.toggleClass(dojo.byId("dialogApplyDaiq1Option"+a),"inputro",!0),dojo.toggleClass(dojo.byId("dialogApplyDaiq2Option"+a),"inputro",!0))):(dojo.byId("dialogApplyDaiq1Date"+a).value="",
H&&(H.className="pp_base pp_btn_cal"),dojo.byId("dialogApplyDaiq1Option"+a).value="1",dojo.byId("dialogApplyDaiq2Date"+a).value="",P&&(P.className="pp_base pp_btn_cal_dis"),dojo.byId("dialogApplyDaiq2Option"+a).value="0",dojo.byId("dialogApplyDaiq2Date"+a).disabled=!0,dojo.byId("dialogApplyDaiq2Option"+a).disabled=!0,dojo.toggleClass(dojo.byId("dialogApplyDaiq2Option"+a),"inputro",!0));var F=dojo.hitch(this,function(e){
var t=e;return dojo.hitch(this,function(e){if(!dojo.byId(t).disabled){var a=teasp.util.date.parseDate(dojo.byId(t).value);a||(a=teasp.util.date.parseDate(this.args.date)),teasp.manager.dialogOpen("Calendar",{date:a,isDisabledDateFunc:dojo.hitch(this,function(e){var t=teasp.util.date.formatDate(e);return 0!=teasp.util.date.compareDate(e,a)&&!this.daiqableMap[t]})},null,this,function(e){dojo.byId(t).value=teasp.util.date.formatDate(e,"SLA");
})}})});d||(this.eventHandles.push(dojo.connect(H,"onclick",this,F("dialogApplyDaiq1Date"+a))),i&&this.eventHandles.push(dojo.connect(P,"onclick",this,F("dialogApplyDaiq2Date"+a)))),f=function(e,t){e||p||t||(dojo.byId("dialogApplyDaiqResv"+a).checked=!1);var o=dojo.byId("dialogApplyDaiqResv"+a).checked,s=d||!o||!p;dojo.byId("dialogApplyDaiq1Date"+a).disabled=s,H&&(H.className="pp_base "+(s?"pp_btn_cal_dis":"pp_btn_cal")),
dojo.byId("dialogApplyDaiq1Option"+a).disabled=s,dojo.toggleClass(dojo.byId("dialogApplyDaiq1Option"+a),"inputro",s);var i=dojo.byId("dialogApplyDaiq1Option"+a).value,n=d||!o||!(2&p)||"1"==i||"0"==i;dojo.byId("dialogApplyDaiq2Date"+a).disabled=n,P&&(P.className="pp_base "+(n?"pp_btn_cal_dis":"pp_btn_cal")),dojo.byId("dialogApplyDaiq2Option"+a).disabled=n,dojo.toggleClass(dojo.byId("dialogApplyDaiq2Option"+a),"inputro",n);
},this.eventHandles.push(dojo.connect(dojo.byId("dialogApplyDaiqResv"+a),"onclick",this,f)),i&&this.eventHandles.push(dojo.connect(dojo.byId("dialogApplyDaiq1Option"+a),"onchange",this,function(e){var t=dojo.byId("dialogApplyDaiq1Option"+a).value,o=!(2&p)||"1"==t||"0"==t;dojo.byId("dialogApplyDaiq2Date"+a).disabled=o,P&&(P.className="pp_base "+(o?"pp_btn_cal_dis":"pp_btn_cal")),dojo.byId("dialogApplyDaiq2Option"+a).disabled=o,
dojo.toggleClass(dojo.byId("dialogApplyDaiq2Option"+a),"inputro",o)}))}if(n){var h=dojo.create("div",{className:"empApply2Div"},m);dojo.create("div",{className:"empApply2CL"},h),dojo.create("div",{className:"empApply2VL",innerHTML:n},h)}this.createApplySetParts(e,m,a,o),this.createApplyTimeParts(e,m,a,o),this.createStatusParts(e,m,a,o),this.createAnnotateParts(e,m,a),this.createErrorParts(e,m,a),s&&dojo.place(s,m);var Y=dojo.byId("dialogApplyTimeNote"+a),W=!1;
if(o)this.displayOnOff("dialogApplyAnnotateRow"+a,!0),this.daiqZan.applys[o.id]&&(dojo.byId("dialogApplyAnnotate"+a).innerHTML=this.daiqZan.applys[o.id].status),W=o.afterFlag;else{var q=this.dayWrap.getDefaultZangyoRange(!0);dojo.byId("dialogApplyStartTime"+a).value=teasp.util.time.timeValue(q.from,this.timeForm),dojo.byId("dialogApplyEndTime"+a).value=teasp.util.time.timeValue(q.to,this.timeForm),this.displayOnOff("dialogApplyAnnotateRow"+a,!1);
var C=teasp.util.date.getToday(),B=teasp.util.date.compareDate(this.args.date,C);W=B<0}W&&this.pouch.isClarifyAfterApply()&&(Y.innerHTML=teasp.message.getLabel("tm10001680",teasp.message.getLabel("tk10004030")),Y.style.color="black"),v.apply(this,[!0]),this.drawLast(o,t);var V=dojo.byId("empApplyDone"+a);V&&this.eventHandles.push(dojo.connect(V,"onclick",this,function(e){var t=dojo.byId("dialogApplyDaiqResv"+a),s=2&p?1:1&p?.5:0,n=t?t.checked:this.pouch.isUseDaiqManage()&&l,d={
empId:this.pouch.getEmpId(),month:this.pouch.getYearMonth(),startDate:this.pouch.getStartDate(),lastModifiedDate:this.pouch.getLastModifiedDate(),date:this.args.date,apply:{id:o?o.id:null,applyType:teasp.constant.APPLY_TYPE_KYUSHTU,patternId:null,holidayId:null,status:null,startDate:this.args.date,endDate:this.args.date,exchangeDate:null,startTime:teasp.util.time.clock2minutes(dojo.byId("dialogApplyStartTime"+a).value),
endTime:teasp.util.time.clock2minutes(dojo.byId("dialogApplyEndTime"+a).value),note:dojo.byId("dialogApplyNote"+a).value||null,contact:null,daiqReserve:n,daiqProvide:s,daiqDate1:null,daiqDate1Range:null,daiqDate2:null,daiqDate2Range:null,useRegulateHoliday:n&&this.pouch.isUseRegulateHoliday()||r,afterFlag:!1,directFlag:0,workType:null,travelTime:null,timeTable:y.apply(this)}};if(void 0===d.apply.startTime||void 0===d.apply.endTime)return void teasp.dialog.EmpApply.showError(a,teasp.message.getLabel("tm10003100"));
if(d.apply.startTime>=d.apply.endTime)return void teasp.dialog.EmpApply.showError(a,teasp.message.getLabel("tm10003110"));if(d.apply.startTime>=1440)return void teasp.dialog.EmpApply.showError(a,teasp.message.getLabel("tm10002030"));if(d.apply.endTime>2880)return void teasp.dialog.EmpApply.showError(a,teasp.message.getLabel("tm10003120"));if(t&&d.apply.daiqReserve){var c=teasp.util.strToDate(dojo.byId("dialogApplyDaiq1Date"+a).value);
if(c.failed>1)return void teasp.dialog.EmpApply.showError(a,dojo.replace(c.tmpl,[teasp.message.getLabel(i?"daiqDate1_label":"daiqDate_label")]));var m=dojo.byId("dialogApplyDaiq1Option"+a).value;if(0==c.failed&&this.pouch.isUseHalfDaiq()){if("0"==m||!m)return void teasp.dialog.EmpApply.showError(a,teasp.message.getLabel("tm10003232"))}else m="1";var h=dojo.byId("dialogApplyDaiq2Date"+a),u=null,g=null;if(h){if(u=teasp.util.strToDate(h.value),
u.failed>1)return void teasp.dialog.EmpApply.showError(a,dojo.replace(u.tmpl,[teasp.message.getLabel("daiqDate2_label")]));if(g=dojo.byId("dialogApplyDaiq2Option"+a).value,1==c.failed&&0==u.failed)return void teasp.dialog.EmpApply.showError(a,teasp.message.getLabel("tm10003220"));if("1"!=m&&0==u.failed&&"0"==g)return void teasp.dialog.EmpApply.showError(a,teasp.message.getLabel("tm10003230"));if(c.datef==u.datef&&m==g)return void teasp.dialog.EmpApply.showError(a,teasp.message.getLabel("tm10003231"));
}if(0==c.failed){if(!this.daiqableMap[c.datef])return void teasp.dialog.EmpApply.showError(a,teasp.message.getLabel("tf10007940",teasp.message.getLabel("daiqDate1_label")));d.apply.daiqDate1=c.datef,d.apply.daiqDate1Range=m;var f=this.getRangeApplys(d.apply.daiqDate1),b={cnt:0},v=this.conflictHoliday(f[d.apply.daiqDate1],{range:m},{msge1:teasp.message.getLabel("tk10005200"),msge2:teasp.message.getLabel("tk10005200")},b);
if(v)return void teasp.dialog.EmpApply.showError(a,v);if(b.cnt)return void teasp.dialog.EmpApply.showError(a,teasp.message.getLabel("tk10005230",teasp.message.getLabel("tk10005200"),teasp.dialog.EmpApply.getApplyTypesName(b)));if("1"!=m&&u&&0==u.failed){if(!this.daiqableMap[u.datef])return void teasp.dialog.EmpApply.showError(a,teasp.message.getLabel("tf10007940",teasp.message.getLabel("daiqDate2_label")));if(d.apply.daiqDate2=u.datef,
d.apply.daiqDate2Range=g,f=this.getRangeApplys(d.apply.daiqDate2),b={cnt:0},v=this.conflictHoliday(f[d.apply.daiqDate2],{range:g},{msge1:teasp.message.getLabel("tk10005200"),msge2:teasp.message.getLabel("tk10005200")},b))return void teasp.dialog.EmpApply.showError(a,v);if(b.cnt)return void teasp.dialog.EmpApply.showError(a,teasp.message.getLabel("tk10005230",teasp.message.getLabel("tk10005200"),teasp.dialog.EmpApply.getApplyTypesName(b)));
}}}if(this.pouch.isRequireNote(teasp.constant.APPLY_KEY_KYUSHTU)&&!d.apply.note)return void teasp.dialog.EmpApply.showError(a,teasp.message.getLabel("tm10003680"));if(d.apply.afterFlag=this.getAfterFlag(teasp.constant.APPLY_KEY_KYUSHTU,d.apply.startDate,d.apply.startTime,d.apply.endTime),teasp.dialog.EmpApply.showError(a,null),this.pouch.isUseDirectApply()){dojo.byId("dialogApplyDirectIn"+a).checked&&(d.apply.directFlag|=1),
dojo.byId("dialogApplyDirectOut"+a).checked&&(d.apply.directFlag|=2),d.apply.workType=dojo.byId("dialogApplyWorkType"+a).value||null;var _=teasp.util.time.clock2minutes(dojo.byId("dialogApplyTravelTime"+a).value);d.apply.travelTime="number"==typeof _?_:null,this.requestDirectApply(a,d)}else this.requestSend(a,d)}))};
}
