if(typeof(teasp) == 'object' && (!teasp.resolved || !teasp.resolved['4599']) && teasp.data && teasp.data.Pouch){
teasp.data.Pouch.getDaiqZan=function(e,t,a,o){var s="代休",i=[],n={},r=0;"object"==typeof t&&(t=teasp.util.date.formatDate(t)),"object"==typeof a&&(a=teasp.util.date.formatDate(a)),"object"==typeof o&&(o=teasp.util.date.formatDate(o));for(var l=0;l<e.length;l++)if(e[l].type==s){var p=e[l];if(i.push(p),p.days<0)continue;
teasp.util.date.compareDate(p.startDate,t)<=0&&teasp.util.date.compareDate(p.limitDate,t)>0&&(r+=p.remainDays||0),p.zans=p.days||0;for(var d=0;d<p.consumers.length;d++){var c=p.consumers[d],m=n[c.consumedByStockId];m||(m=n[c.consumedByStockId]=c,m.parents=[],m.parentMap={},i.push({id:c.consumedByStockId,parent:p})),m.parentMap[p.id]||(m.parents.push(p),m.parentMap[p.id]={cdays:c.cdays})}}var h=0;if(s==teasp.constant.STOCK_DAIQ){
for(var l=0;l<i.length;l++){var p=i[l];(!o||p.date<=o)&&!p.parent&&p.days<0&&!n[p.id]&&(r+=p.days||0)}r<0&&(h=r)}for(var u=[],g={},y={},f=0,l=0;l<i.length;l++){var p=i[l],b=[],v="";if(!y[p.id])if(y[p.id]=1,p.parent){for(var c=n[p.id],_=0,d=0;d<c.parents.length;d++){var T=c.parents[d];p.parent.type==teasp.constant.STOCK_DAIQ&&T.apply?b.push(teasp.message.getLabel("tm10003720",teasp.util.date.formatDate(T.date,"+M/d"))):b.push(teasp.message.getLabel("tm10003723",teasp.util.date.formatDate(T.date,"+M/d"),T.name)),
_+=T.days}_<Math.abs(c.days)&&b.push("???"),v=c.empApplyId?c.holidayName:c.name;var m={date:teasp.util.date.formatDate(c.date?c.date:c.startDate,"SLA"),subject:v,plus:"-",minus:teasp.message.getLabel("tk10005151",Math.abs(c.days)),startDate:"-",limitDate:"-",status:b.join(teasp.message.getLabel("tm10001540")),seq:++f,applyStartDate:c.applyStartDate,applyEndDate:c.applyEndDate};u.push(m),c.empApplyId&&(g[c.empApplyId]=m);
}else{var m={},j=p.days;if(p.type==teasp.constant.STOCK_DAIQ){if(v=p.apply?p.days>=0?teasp.message.getLabel("tm10001390")+("number"==typeof p.workRealTime&&p.workRealTime>=0?" ("+teasp.util.time.timeValue(p.workRealTime)+")":""):p.apply.holiday?p.apply.holiday.name:"???":p.name,0==p.days)b.push(teasp.message.getLabel("tm10003752"));else if(p.days>0){var E=[];for(var L in n)if(n.hasOwnProperty(L)&&n[L].parentMap[p.id]){
var c=n[L];E.push(teasp.util.date.formatDate(c.date,"+M/d"))}E.length>0&&b.push(teasp.message.getLabel("tm10003730",E.join(", "))),p.remainDays>0&&p.limitDate<=t&&b.push(teasp.message.getLabel("tm10010710"))}else n[p.id]&&(j=0,delete y[p.id]);!p.apply&&j>0?(b.push(teasp.message.getLabel("tm10003722",teasp.util.date.formatDate(p.date,"SLA"))),m.date=teasp.util.date.formatDate(p.startDate,"SLA")):m.date=teasp.util.date.formatDate(p.date,"SLA");
}else v=p.days>=0?p.name:p.apply&&p.apply.holiday?p.apply.holiday.name:p.name,b.push(teasp.message.getLabel("tm10003722",teasp.util.date.formatDate(p.date,"SLA"))),p.remainDays>0&&p.limitDate<=t?b.push(teasp.message.getLabel("tm10010710")):p.days<0&&n[p.id]&&(j=0,delete y[p.id]),m.date=teasp.util.date.formatDate(p.startDate,"SLA");0!=j&&(m.subject=v,m.plus=j<0?"-":teasp.message.getLabel("tk10005151",p.days),m.minus=j<0?teasp.message.getLabel("tk10005151",Math.abs(p.days)):"-",
m.startDate=j<0?"-":teasp.util.date.formatDate(p.startDate,"SLA"),m.limitDate=j<0?"-":"2999-12-31"==p.limitDate?teasp.message.getLabel("infinite_date"):teasp.util.date.formatDate(p.limitDate,"SLA"),m.status=j<0?"???":b.join(teasp.message.getLabel("tm10001540")),m.seq=++f,u.push(m),p.apply&&(g[p.apply.id]=m))}}u=u.sort(function(e,t){return e.date==t.date?e.seq-t.seq:e.date<t.date?-1:e.date>t.date?1:0});for(var L in n)if(n.hasOwnProperty(L)){
var c=n[L];c.parents&&delete c.parents,c.parentMap&&delete c.parentMap}return{zan:r,overSpend:h,stocks:i,consumers:n,history:u,applys:g}};
}
