import { createFromParam } from '../../../../../domain/models/attendance/DailyAttTime';
import AttRecord from '../../../../models/AttRecord';

export default createFromParam(
  new AttRecord({
    approver01Name: '',
    ciliTimePeriods: [],
    ciloTimePeriods: [],
    coliTimePeriods: [],
    coloTimePeriods: [],
    contractedDetail: undefined,
    earlyLeaveEndTime: undefined,
    earlyStartWorkApplyDefaultEndTime: undefined,
    id: '',
    insufficientRestTime: undefined,
    isLeaveOfAbsence: false,
    isSummaryLocked: false,
    lateArrivalStartTime: undefined,
    outEndTime: undefined,
    outStartTime: undefined,
    overtimeWorkApplyDefaultStartTime: undefined,
    realWorkTime: undefined,
    remarks: undefined,
    requestIds: [],
    requestTypeCodes: [],
    rest5EndTime: undefined,
    rest5StartTime: undefined,
    restHours: undefined,
    recordDate: '2017-08-01',
    dayType: AttRecord.DAY_TYPE.WORKDAY,
    startTime: 540,
    endTime: 1080,
    startStampTime: 520,
    endStampTime: 1090,
    rest1StartTime: 781,
    rest1EndTime: 841,
    rest2StartTime: 782,
    rest2EndTime: 842,
    rest3StartTime: 783,
    rest3EndTime: 843,
    rest4StartTime: 784,
    rest4EndTime: 844,
    // rest5StartTime: 785,
    // rest5EndTime: 845,
    commuteForwardCount: null,
    commuteBackwardCount: null,
  })
);
