if(typeof(teasp) == 'object' && !teasp.resolved['MBJS3'] && teasp.dialog && teasp.dialog.EmpApply){
teasp.dialog.EmpApply.prototype.createLateStartForm=function(e,t,a,o,s){var i=o&&teasp.constant.STATUS_FIX.contains(o.status)||this.isReadOnly(),n=this.getInputClass(i,o),r=dojo.create("div",null,t),l=dojo.create("div",{id:"dialogApplyTimeRow"+a,className:"empApply2Div"},r);dojo.create("div",{className:"empApply2CL",innerHTML:teasp.message.getLabel("startTime_label")
},l);var p=dojo.create("input",{type:"text",id:"dialogApplyTime"+a,style:{margin:"2px"},className:"inputime "+n},dojo.create("div",{className:"empApply2VL"},l));if(o)p.value=teasp.util.time.timeValue(o.endTime,this.timeForm),(teasp.constant.STATUS_FIX.contains(o.status)||this.isReadOnly())&&(p.readOnly="readOnly"),this.changeInputAreaView(p,o,i);else{var d=this.dayWrap.getStartTime(!0,null,teasp.constant.C_REAL);d&&(p.value=teasp.util.time.timeValue(d,this.timeForm));
}this.createNoteParts(e,r,a,o,teasp.message.getLabel("reason_label")),(i&&o&&o.treatDeduct||this.pouch.isUseOwnReasonLateStart())&&(l=dojo.create("div",{id:"dialogApplyLateEscapeRow"+a,className:"empApply2Div"},r),dojo.create("div",{className:"empApply2CL"},l),i&&o?dojo.create("div",{innerHTML:o.ownReason?"自己都合による":"会社都合による(電車遅延・バス遅延を含む)",style:"border:1px solid #808080;padding:2px 8px;"},dojo.create("div",{className:"empApply2VL",
style:"padding:0px 2px;"},l)):(p=dojo.create("select",{id:"dialogApplyLateEscape"+a},dojo.create("div",{className:"empApply2VL",style:"padding:0px 2px;"},l)),dojo.create("option",{innerHTML:"自己都合による",value:"1"},p),dojo.create("option",{innerHTML:"会社都合による(電車遅延・バス遅延を含む)",value:"0"},p),p.value=o?o.ownReason?"1":"0":"1")),this.createApplySetParts(e,r,a,o),this.createApplyTimeParts(e,r,a,o),this.createStatusParts(e,r,a,o),this.createErrorParts(e,r,a),
s&&dojo.place(s,r),dojo.query(".inputime",dojo.byId("dialogApplyTimeRow"+a)).forEach(function(e){this.eventHandles.push(dojo.connect(e,"blur",this,teasp.util.time.onblurTime)),this.eventHandles.push(dojo.connect(e,"onkeypress",this,teasp.util.time.onkeypressTime))},this),this.drawLast(o,t);var c=dojo.byId("empApplyDone"+a);c&&this.eventHandles.push(dojo.connect(c,"onclick",this,function(e){var t=teasp.util.time.clock2minutes(dojo.byId("dialogApplyTime"+a).value);
if(void 0===t)return void teasp.dialog.EmpApply.showError(a,teasp.message.getLabel("tm10003350"));var s=this.dayWrap.getBorderTime().st;if(s<0||s>=t)return void teasp.dialog.EmpApply.showError(a,teasp.message.getLabel("tm10003360",teasp.util.time.timeValue(s,this.timeForm)));var i=dojo.byId("dialogApplyLateEscape"+a),n={empId:this.pouch.getEmpId(),month:this.pouch.getYearMonth(),startDate:this.pouch.getStartDate(),lastModifiedDate:this.pouch.getLastModifiedDate(),
date:this.args.date,apply:{id:o?o.id:null,applyType:teasp.constant.APPLY_TYPE_LATESTART,patternId:null,holidayId:null,status:null,startDate:this.args.date,endDate:this.args.date,exchangeDate:null,startTime:s,endTime:t,note:dojo.byId("dialogApplyNote"+a).value||null,contact:null,ownReason:!(!i||"1"!=i.value),treatDeduct:this.pouch.getTreatLateStart()}};return this.pouch.isRequireNote(teasp.constant.APPLY_KEY_LATESTART)&&!n.apply.note?void teasp.dialog.EmpApply.showError(a,teasp.message.getLabel("tm10003690")):void(this.dayWrap.getInputLimit().flag?this.requestDirectApply(a,n,!0):this.requestSend(a,n));
}))};
teasp.dialog.EmpApply.prototype.createEarlyEndForm=function(e,t,a,o,s){var i=o&&teasp.constant.STATUS_FIX.contains(o.status)||this.isReadOnly(),n=this.getInputClass(i,o),r=dojo.create("div",null,t),l=dojo.create("div",{id:"dialogApplyTimeRow"+a,className:"empApply2Div"},r);dojo.create("div",{className:"empApply2CL",innerHTML:teasp.message.getLabel("endTime_label")},l);var p=dojo.create("input",{type:"text",id:"dialogApplyTime"+a,
style:"margin:2px;",className:"inputime "+n},dojo.create("div",{className:"empApply2VL"},l));if(o)p.value=teasp.util.time.timeValue(o.startTime,this.timeForm),(teasp.constant.STATUS_FIX.contains(o.status)||this.isReadOnly())&&(p.readOnly="readOnly"),this.changeInputAreaView(p,o,i);else{var d=this.dayWrap.getEndTime(!0,null,teasp.constant.C_REAL);d&&(p.value=teasp.util.time.timeValue(d,this.timeForm))}this.createNoteParts(e,r,a,o,teasp.message.getLabel("reason_label")),
(i&&o&&o.treatDeduct||this.pouch.isUseOwnReasonEarlyEnd())&&(l=dojo.create("div",{id:"dialogApplyEarlyEscapeRow"+a,className:"empApply2Div"},r),dojo.create("div",{className:"empApply2CL"},l),i&&o?dojo.create("div",{innerHTML:o.ownReason?"自己都合による":"会社都合による",style:"border:1px solid #808080;padding:2px 8px;"},dojo.create("div",{className:"empApply2VL",style:"padding:0px 2px;"},l)):(p=dojo.create("select",{id:"dialogApplyEarlyEscape"+a
},dojo.create("div",{className:"empApply2VL",style:"padding:0px 2px;"},l)),dojo.create("option",{innerHTML:"自己都合による",value:"1"},p),dojo.create("option",{innerHTML:"会社都合による",value:"0"},p),p.value=o?o.ownReason?"1":"0":"1")),this.createApplySetParts(e,r,a,o),this.createApplyTimeParts(e,r,a,o),this.createStatusParts(e,r,a,o),this.createErrorParts(e,r,a),s&&dojo.place(s,r),dojo.query(".inputime",dojo.byId("dialogApplyTimeRow"+a)).forEach(function(e){
this.eventHandles.push(dojo.connect(e,"blur",this,teasp.util.time.onblurTime)),this.eventHandles.push(dojo.connect(e,"onkeypress",this,teasp.util.time.onkeypressTime))},this),this.drawLast(o,t);var c=dojo.byId("empApplyDone"+a);c&&this.eventHandles.push(dojo.connect(c,"onclick",this,function(e){var t=teasp.util.time.clock2minutes(dojo.byId("dialogApplyTime"+a).value);if(void 0===t)return void teasp.dialog.EmpApply.showError(a,teasp.message.getLabel("tm10003350"));
var s=this.dayWrap.getBorderTime().et;if(s<0||s<=t)return void teasp.dialog.EmpApply.showError(a,teasp.message.getLabel("tm10003370",teasp.util.time.timeValue(s,this.timeForm)));var i=dojo.byId("dialogApplyEarlyEscape"+a),n={empId:this.pouch.getEmpId(),month:this.pouch.getYearMonth(),startDate:this.pouch.getStartDate(),lastModifiedDate:this.pouch.getLastModifiedDate(),date:this.args.date,apply:{id:o?o.id:null,applyType:teasp.constant.APPLY_TYPE_EARLYEND,
patternId:null,holidayId:null,status:null,startDate:this.args.date,endDate:this.args.date,exchangeDate:null,startTime:t,endTime:s,note:dojo.byId("dialogApplyNote"+a).value||null,contact:null,ownReason:!(!i||"1"!=i.value),treatDeduct:this.pouch.getTreatEarlyEnd()}};return this.pouch.isRequireNote(teasp.constant.APPLY_KEY_EARLYEND)&&!n.apply.note?void teasp.dialog.EmpApply.showError(a,teasp.message.getLabel("tm10003690")):void(this.dayWrap.getInputLimit().flag?this.requestDirectApply(a,n,!0):this.requestSend(a,n));
}))};
}
