// eslint-disable-next-line import/prefer-default-export
export const events = {
  '20190827': [
    {
      id: 'a172v00000dXbGSAA0',
      title: '08/27-09/01 All Day',
      start: '2019-08-26T15:00:00.000Z',
      end: '2019-08-31T15:00:00.000Z',
      isAllDay: false,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: 'a0h2v00000Xa3gtAAB',
        name: '9',
        code: '9',
      },
      workCategoryId: 'a1F2v00000CwPQEEA3',
      workCategoryName:
        '親譲りの無鉄砲で小供の時から損ばかりしている。小学校に居る時分学校の二階から飛び降りて一週間ほど腰を抜かした事がある。なぜそんな無闇をしたと聞く人があるかも知れ',
      layout: {
        colSpan: 5,
        colIndex: 2,
        startMinutesOfDay: 0,
        endMinutesOfDay: 30,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
  ],
  '20190901': [
    {
      id: 'a172v00000dXbGSAA0',
      title: '08/27-09/01 All Day',
      start: '2019-08-26T15:00:00.000Z',
      end: '2019-08-31T15:00:00.000Z',
      isAllDay: false,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: 'a0h2v00000Xa3gtAAB',
        name: '9',
        code: '9',
      },
      workCategoryId: 'a1F2v00000CwPQEEA3',
      workCategoryName:
        '親譲りの無鉄砲で小供の時から損ばかりしている。小学校に居る時分学校の二階から飛び降りて一週間ほど腰を抜かした事がある。なぜそんな無闇をしたと聞く人があるかも知れ',
      layout: {
        colSpan: 1,
        colIndex: 0,
        startMinutesOfDay: 0,
        endMinutesOfDay: 30,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
    {
      id: 'a172v00000dXTBaAAO',
      title: '',
      start: '2019-08-31T15:00:00.000Z',
      end: '2019-08-31T15:00:00.000Z',
      isAllDay: true,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 1,
        colIndex: 0,
        startMinutesOfDay: 0,
        endMinutesOfDay: 0,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
    {
      id: 'a172v00000dXTB7AAO',
      title: '',
      start: '2019-08-31T15:00:00.000Z',
      end: '2019-08-31T15:00:00.000Z',
      isAllDay: true,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 1,
        colIndex: 0,
        startMinutesOfDay: 0,
        endMinutesOfDay: 0,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
    {
      id: 'a172v00000dXTBVAA4',
      title: '',
      start: '2019-08-31T15:00:00.000Z',
      end: '2019-08-31T15:00:00.000Z',
      isAllDay: true,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 1,
        colIndex: 0,
        startMinutesOfDay: 0,
        endMinutesOfDay: 0,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
    {
      id: 'a172v00000dXTBLAA4',
      title: '',
      start: '2019-08-31T15:00:00.000Z',
      end: '2019-08-31T15:00:00.000Z',
      isAllDay: true,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 1,
        colIndex: 0,
        startMinutesOfDay: 0,
        endMinutesOfDay: 0,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
    {
      id: 'a172v00000dXTBQAA4',
      title: '',
      start: '2019-08-31T15:00:00.000Z',
      end: '2019-08-31T15:00:00.000Z',
      isAllDay: true,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 1,
        colIndex: 0,
        startMinutesOfDay: 0,
        endMinutesOfDay: 0,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
  ],
  '20190902': [
    {
      id: 'a172v00000dXTBfAAO',
      title: '',
      start: '2019-09-01T15:00:00.000Z',
      end: '2019-09-09T15:00:00.000Z',
      isAllDay: false,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: 'a0h2v00000Xa3gtAAB',
        name: '9',
        code: '9',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 6,
        colIndex: 1,
        startMinutesOfDay: 0,
        endMinutesOfDay: 30,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
    {
      id: 'a172v00000dXTCEAA4',
      title: '',
      start: '2019-09-01T15:00:00.000Z',
      end: '2019-09-01T15:00:00.000Z',
      isAllDay: true,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 1,
        colIndex: 1,
        startMinutesOfDay: 0,
        endMinutesOfDay: 0,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
    {
      id: 'a172v00000dXTC4AAO',
      title: '',
      start: '2019-09-01T15:00:00.000Z',
      end: '2019-09-01T15:00:00.000Z',
      isAllDay: true,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 1,
        colIndex: 1,
        startMinutesOfDay: 0,
        endMinutesOfDay: 0,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
    {
      id: 'a172v00000dWRPqAAO',
      title: '1日',
      start: '2019-09-01T15:00:00.000Z',
      end: '2019-09-02T15:00:00.000Z',
      isAllDay: false,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 1,
        colIndex: 1,
        startMinutesOfDay: 0,
        endMinutesOfDay: 30,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
    {
      id: 'a172v00000dWRPvAAO',
      title: '終日 1日',
      start: '2019-09-01T15:00:00.000Z',
      end: '2019-09-01T15:00:00.000Z',
      isAllDay: true,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 1,
        colIndex: 1,
        startMinutesOfDay: 0,
        endMinutesOfDay: 0,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
  ],
  '20190903': [
    {
      id: 'a172v00000deJKoAAM',
      title: 'ららららららららららアイウエオかきくけこvvvvvvvvvvvvvvvvvvvvvvv',
      start: '2019-09-02T15:00:00.000Z',
      end: '2019-09-02T15:00:00.000Z',
      isAllDay: true,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 1,
        colIndex: 2,
        startMinutesOfDay: 0,
        endMinutesOfDay: 0,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
  ],
  '20190904': [
    {
      id: 'a172v00000dWRPlAAO',
      title: '4日〜6日',
      start: '2019-09-03T15:00:00.000Z',
      end: '2019-09-06T15:00:00.000Z',
      isAllDay: false,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 3,
        colIndex: 3,
        startMinutesOfDay: 0,
        endMinutesOfDay: 30,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
  ],
  '20190908': [
    {
      id: 'a172v00000dXTBfAAO',
      title: '',
      start: '2019-09-01T15:00:00.000Z',
      end: '2019-09-09T15:00:00.000Z',
      isAllDay: false,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: 'a0h2v00000Xa3gtAAB',
        name: '9',
        code: '9',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 2,
        colIndex: 0,
        startMinutesOfDay: 0,
        endMinutesOfDay: 30,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
  ],
  '20190909': [
    {
      id: 'a172v00000dWSNDAA4',
      title: 'error',
      start: '2019-09-08T15:00:00.000Z',
      end: '2019-09-08T15:00:00.000Z',
      isAllDay: false,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 1,
        colIndex: 1,
        startMinutesOfDay: 0,
        endMinutesOfDay: 30,
        visibleInMonthlyView: true,
        containsAllDay: false,
      },
      left: 0,
      width: 222.71428571428572,
    },
  ],
  '20190910': [
    {
      id: 'a172v00000deHmWAAU',
      title: 'dfgsdfgdddddsdfg',
      start: '2019-09-09T15:00:00.000Z',
      end: '2019-09-11T15:00:00.000Z',
      isAllDay: true,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 2,
        colIndex: 2,
        startMinutesOfDay: 0,
        endMinutesOfDay: 0,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
    {
      id: 'a172v00000dWT3nAAG',
      title: 'abbbb',
      start: '2019-09-09T15:00:00.000Z',
      end: '2019-09-10T15:00:00.000Z',
      isAllDay: true,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 1,
        colIndex: 2,
        startMinutesOfDay: 0,
        endMinutesOfDay: 0,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
  ],
  '20190912': [
    {
      id: 'a172v00000deMkSAAU',
      title: '',
      start: '2019-09-11T15:00:00.000Z',
      end: '2019-09-11T15:00:00.000Z',
      isAllDay: true,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 1,
        colIndex: 4,
        startMinutesOfDay: 0,
        endMinutesOfDay: 0,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
    {
      id: 'a172v00000deMkhAAE',
      title: '',
      start: '2019-09-11T15:00:00.000Z',
      end: '2019-09-11T15:00:00.000Z',
      isAllDay: true,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 1,
        colIndex: 4,
        startMinutesOfDay: 0,
        endMinutesOfDay: 0,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
    {
      id: 'a172v00000deMkXAAU',
      title: '',
      start: '2019-09-11T15:00:00.000Z',
      end: '2019-09-11T15:00:00.000Z',
      isAllDay: true,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 1,
        colIndex: 4,
        startMinutesOfDay: 0,
        endMinutesOfDay: 0,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
  ],
  '20190913': [
    {
      id: 'a172v00000deRLLAA2',
      title: 'aaaaaa',
      start: '2019-09-12T15:00:00.000Z',
      end: '2019-09-16T15:00:00.000Z',
      isAllDay: false,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 2,
        colIndex: 5,
        startMinutesOfDay: 0,
        endMinutesOfDay: 30,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
    {
      id: 'a172v00000deRGfAAM',
      title: 'テスト',
      start: '2019-09-12T15:00:00.000Z',
      end: '2019-09-13T15:00:00.000Z',
      isAllDay: false,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 1,
        colIndex: 5,
        startMinutesOfDay: 0,
        endMinutesOfDay: 30,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
  ],
  '20190914': [
    {
      id: 'a172v00000deRRVAA2',
      title: '',
      start: '2019-09-13T15:00:00.000Z',
      end: '2019-09-13T15:00:00.000Z',
      isAllDay: false,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 1,
        colIndex: 6,
        startMinutesOfDay: 0,
        endMinutesOfDay: 30,
        visibleInMonthlyView: true,
        containsAllDay: false,
      },
      left: 0,
      width: 222.71428571428572,
    },
  ],
  '20190915': [
    {
      id: 'a172v00000deRLLAA2',
      title: 'aaaaaa',
      start: '2019-09-12T15:00:00.000Z',
      end: '2019-09-16T15:00:00.000Z',
      isAllDay: false,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 2,
        colIndex: 0,
        startMinutesOfDay: 0,
        endMinutesOfDay: 30,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
    {
      id: 'a172v00000deRLkAAM',
      title: '',
      start: '2019-09-14T15:00:00.000Z',
      end: '2019-09-17T15:00:00.000Z',
      isAllDay: true,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 3,
        colIndex: 0,
        startMinutesOfDay: 0,
        endMinutesOfDay: 0,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
  ],
  '20190918': [
    {
      id: 'a172v00000dWP7gAAG',
      title: 'hhhhh',
      start: '2019-09-17T15:00:00.000Z',
      end: '2019-09-24T15:00:00.000Z',
      isAllDay: true,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 4,
        colIndex: 3,
        startMinutesOfDay: 0,
        endMinutesOfDay: 0,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
  ],
  '20190922': [
    {
      id: 'a172v00000dWP7gAAG',
      title: 'hhhhh',
      start: '2019-09-17T15:00:00.000Z',
      end: '2019-09-24T15:00:00.000Z',
      isAllDay: true,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 3,
        colIndex: 0,
        startMinutesOfDay: 0,
        endMinutesOfDay: 0,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
  ],
  '20190929': [
    {
      id: 'a172v00000ddrWEAAY',
      title: 'TEST',
      start: '2019-09-28T15:00:00.000Z',
      end: '2019-09-29T15:00:00.000Z',
      isAllDay: true,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 1,
        colIndex: 0,
        startMinutesOfDay: 0,
        endMinutesOfDay: 0,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
    {
      id: 'a172v00000ddrWTAAY',
      title: 'TEST',
      start: '2019-09-28T15:00:00.000Z',
      end: '2019-09-29T15:00:00.000Z',
      isAllDay: false,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 1,
        colIndex: 0,
        startMinutesOfDay: 0,
        endMinutesOfDay: 30,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
    {
      id: 'a172v00000ddrWOAAY',
      title: 'dddd',
      start: '2019-09-28T15:00:00.000Z',
      end: '2019-09-28T15:00:00.000Z',
      isAllDay: true,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 1,
        colIndex: 0,
        startMinutesOfDay: 0,
        endMinutesOfDay: 0,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
    {
      id: 'a172v00000ddrWdAAI',
      title: '',
      start: '2019-09-28T15:00:00.000Z',
      end: '2019-09-29T14:30:00.000Z',
      isAllDay: false,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 1,
        colIndex: 0,
        startMinutesOfDay: 0,
        endMinutesOfDay: 1410,
        visibleInMonthlyView: true,
        containsAllDay: false,
      },
      left: 0,
      width: 222.71428571428572,
    },
  ],
  '20190930': [
    {
      id: 'a172v00000deOySAAU',
      title: '',
      start: '2019-09-29T15:00:00.000Z',
      end: '2019-10-02T15:00:00.000Z',
      isAllDay: true,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 3,
        colIndex: 1,
        startMinutesOfDay: 0,
        endMinutesOfDay: 0,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
    {
      id: 'a172v00000deHfjAAE',
      title: '',
      start: '2019-09-29T15:00:00.000Z',
      end: '2019-09-29T15:00:00.000Z',
      isAllDay: true,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 1,
        colIndex: 1,
        startMinutesOfDay: 0,
        endMinutesOfDay: 0,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
    {
      id: 'a172v00000deOzfAAE',
      title: '',
      start: '2019-09-29T15:00:00.000Z',
      end: '2019-09-29T15:00:00.000Z',
      isAllDay: true,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 1,
        colIndex: 1,
        startMinutesOfDay: 0,
        endMinutesOfDay: 0,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
    {
      id: 'a172v00000deOyXAAU',
      title: '',
      start: '2019-09-29T15:00:00.000Z',
      end: '2019-09-29T15:00:00.000Z',
      isAllDay: true,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 1,
        colIndex: 1,
        startMinutesOfDay: 0,
        endMinutesOfDay: 0,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
  ],
  '20191001': [
    {
      id: 'a172v00000ddrVkAAI',
      title: '',
      start: '2019-09-30T15:00:00.000Z',
      end: '2019-10-04T15:00:00.000Z',
      isAllDay: true,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 4,
        colIndex: 2,
        startMinutesOfDay: 0,
        endMinutesOfDay: 0,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
  ],
  '20191005': [
    {
      id: 'a172v00000dWTIyAAO',
      title: 'イベント',
      start: '2019-10-04T15:00:00.000Z',
      end: '2019-10-04T15:00:00.000Z',
      isAllDay: true,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 1,
        colIndex: 6,
        startMinutesOfDay: 0,
        endMinutesOfDay: 0,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
    {
      id: 'a172v00000ddrWJAAY',
      title: 'テスト',
      start: '2019-10-04T15:00:00.000Z',
      end: '2019-10-04T15:00:00.000Z',
      isAllDay: true,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 1,
        colIndex: 6,
        startMinutesOfDay: 0,
        endMinutesOfDay: 0,
        visibleInMonthlyView: true,
        containsAllDay: true,
      },
    },
  ],
  '20191006': [
    {
      id: 'a172v00000deHn0AAE',
      title: '',
      start: '2019-10-05T15:00:00.000Z',
      end: '2019-10-06T03:00:00.000Z',
      isAllDay: false,
      isOrganizer: true,
      isOuting: false,
      calculateCapacity: false,
      location: '',
      remarks: '',
      createdServiceBy: 'teamspirit',
      externalEventId: null,
      job: {
        id: '',
        name: '',
        code: '',
      },
      workCategoryId: '',
      workCategoryName: '',
      layout: {
        colSpan: 1,
        colIndex: 0,
        startMinutesOfDay: 0,
        endMinutesOfDay: 720,
        visibleInMonthlyView: true,
        containsAllDay: false,
      },
      left: 0,
      width: 222.71428571428572,
    },
  ],
};
