import * as base from '@admin-pc/actions/base';

const FUNC_NAME = 'org-hierarchy-pattern';
const FUNC_NAME_HIERARCHY = 'department/hierarchy';
const FUNC_NAME_HIERARCHY_PARENT = 'parent';
export const SEARCH_ORGANIZATION_HIERARCHY = 'SEARCH_ORGANIZATION_HIERARCHY';
export const CREATE_ORGANIZATION_HIERARCHY = 'CREATE_ORGANIZATION_HIERARCHY';
export const DELETE_ORGANIZATION_HIERARCHY = 'DELETE_ORGANIZATION_HIERARCHY';
export const UPDATE_ORGANIZATION_HIERARCHY = 'UPDATE_ORGANIZATION_HIERARCHY';
export const ADD_ORGANIZATION_HIERARCHY_CHILD =
  'ADD_ORGANIZATION_HIERARCHY_CHILD';
export const REMOVE_ORGANIZATION_HIERARCHY_CHILD =
  'REMOVE_ORGANIZATION_HIERARCHY_CHILD';

export const GET_CONSTANTS_ORGANIZATION_HIERARCHY =
  'GET_CONSTANTS_ORGANIZATION_HIERARCHY';

export const SEARCH_ORGANIZATION_HIERARCHY_ERROR =
  'SEARCH_ORGANIZATION_HIERARCHY_ERROR';
export const CREATE_ORGANIZATION_HIERARCHY_ERROR =
  'CREATE_ORGANIZATION_HIERARCHY_ERROR';
export const DELETE_ORGANIZATION_HIERARCHY_ERROR =
  'DELETE_ORGANIZATION_HIERARCHY_ERROR';
export const UPDATE_ORGANIZATION_HIERARCHY_ERROR =
  'UPDATE_ORGANIZATION_HIERARCHY_ERROR';
export const ADD_ORGANIZATION_HIERARCHY_CHILD_ERROR =
  'ADD_ORGANIZATION_HIERARCHY_CHILD_ERROR';
export const REMOVE_ORGANIZATION_HIERARCHY_CHILD_ERROR =
  'REMOVE_ORGANIZATION_HIERARCHY_CHILD_ERROR';

export const SEARCH_ORGANIZATION_HIERARCHY_PARENT =
  'SEARCH_ORGANIZATION_HIERARCHY_PARENT';
export const SEARCH_ORGANIZATION_HIERARCHY_PARENT_ERROR =
  'SEARCH_ORGANIZATION_HIERARCHY_PARENT_ERROR';

export const searchOrganizationHierarchy = (param = {}) => {
  return base.search(
    FUNC_NAME,
    param,
    SEARCH_ORGANIZATION_HIERARCHY,
    SEARCH_ORGANIZATION_HIERARCHY_ERROR
  );
};

export const createOrganizationHierarchy = (param) => {
  return base.create(
    FUNC_NAME,
    param,
    CREATE_ORGANIZATION_HIERARCHY,
    CREATE_ORGANIZATION_HIERARCHY_ERROR
  );
};

export const deleteOrganizationHierarchy = (param) => {
  return base.del(
    FUNC_NAME,
    param,
    DELETE_ORGANIZATION_HIERARCHY,
    DELETE_ORGANIZATION_HIERARCHY_ERROR
  );
};

export const updateOrganizationHierarchy = (param) => {
  return base.update(
    FUNC_NAME,
    param,
    UPDATE_ORGANIZATION_HIERARCHY,
    UPDATE_ORGANIZATION_HIERARCHY_ERROR
  );
};

export const getConstantsOrganizationHierarchy = () => ({
  type: GET_CONSTANTS_ORGANIZATION_HIERARCHY,
});

export const addDepartment = (param) => {
  return base.save(
    FUNC_NAME_HIERARCHY,
    param,
    ADD_ORGANIZATION_HIERARCHY_CHILD,
    ADD_ORGANIZATION_HIERARCHY_CHILD_ERROR
  );
};

export const removeDepartment = (param) => {
  return base.del(
    FUNC_NAME_HIERARCHY,
    param,
    REMOVE_ORGANIZATION_HIERARCHY_CHILD,
    REMOVE_ORGANIZATION_HIERARCHY_CHILD_ERROR
  );
};
export const searchDepartmentHierarchyParent = (param) => {
  return base.search(
    `${FUNC_NAME_HIERARCHY}/${FUNC_NAME_HIERARCHY_PARENT}`,
    param,
    SEARCH_ORGANIZATION_HIERARCHY_PARENT,
    SEARCH_ORGANIZATION_HIERARCHY_PARENT_ERROR
  );
};
