if(typeof(teasp) == 'object' && !teasp.resolved['7674'] && teasp.view && teasp.view.Shift){
teasp.dialog.EmpDay.prototype.createContent=function(){var e,t,a;for(e=dojo.byId("EmpDayTbody");e.firstChild;)dojo.destroy(e.firstChild);
var s=this.emp.days[this.dkey],o=this.emp.DeptId__r?this.emp.DeptId__r.DeptCode__c+"-"+this.emp.DeptId__r.Name:null;o&&(t=dojo.create("tr",null,e),dojo.create("div",{innerHTML:o},dojo.create("td",null,t))),t=dojo.create("tr",null,e),dojo.create("div",{innerHTML:(this.emp.EmpCode__c||"")+"  "+this.emp.Name},dojo.create("td",null,t)),t=dojo.create("tr",null,e),dojo.create("div",{innerHTML:teasp.util.date.formatDate(this.dkey,"JP1")
},dojo.create("td",null,t));var i=[],n=null,r=!1;if(s.dayType==teasp.constant.DAY_TYPE_NORMAL_HOLIDAY?i.push("所定休日"):s.dayType==teasp.constant.DAY_TYPE_PUBLIC_HOLIDAY?i.push("祝日"):s.dayType==teasp.constant.DAY_TYPE_LEGAL_HOLIDAY?i.push("法定休日"):!s.plannedHoliday||s.applys.kyushtu&&s.applys.kyushtu.length?s.applys.holidayAll?i.push(s.applys.holidayAll.HolidayId__r.Name+" (終日)"):(i.push("勤務日"),r=!0,n=s.pattern,s.applys.holidayAm&&i.push(s.applys.holidayAm.HolidayId__r.Name+" (午前休)"),
s.applys.holidayPm&&i.push(s.applys.holidayPm.HolidayId__r.Name+" (午後休)")):i.push("有休計画付与日"),t=dojo.create("tr",null,e),dojo.create("div",{innerHTML:i.join(", ")},dojo.create("td",null,t)),r&&(n||(n=this.emp.empType.days[this.dkey].config,n.Name=" 通常勤務",n.Symbol__c=this.normalPatternSymbol)),n){if(t=dojo.create("tr",null,e),a=dojo.create("td",null,t),s.pattern){var l=n.Symbol__c||n.Name.substring(0,1);dojo.create("div",{
className:"pattern dayDiv",style:{"float":"left"},innerHTML:l},a)}dojo.create("div",{innerHTML:n.Name},a),t=dojo.create("tr",null,e);var p=teasp.util.time.timeValue(s.startTime)+"～"+teasp.util.time.timeValue(s.endTime);dojo.create("div",{innerHTML:p},dojo.create("td",null,t)),t=dojo.create("tr",null,e);for(var d=n.RestTimes__c&&n.RestTimes__c.length>0?n.RestTimes__c.split(/,/):[],c=[],m=0;m<d.length;m++){var h=/(\d+)\-(\d+)/.exec(d[m]);
h&&c.push(teasp.util.time.timeValue(h[1])+"～"+teasp.util.time.timeValue(h[2]))}dojo.create("div",{innerHTML:"(休憩："+(c.length>0?c.join(", "):"なし")+")"},dojo.create("td",null,t)),n.UseDiscretionary__c&&(t=dojo.create("tr",null,e),dojo.create("div",{innerHTML:"裁量"},dojo.create("td",null,t)))}if(s.workPlace&&s.workPlace.Id!=this.emp.DeptId__c){var l=s.workPlace.Symbol__c||s.workPlace.Name.substring(0,1);t=dojo.create("tr",null,e),
a=dojo.create("td",null,t),dojo.create("div",{innerHTML:"主管部署：",style:{"float":"left"}},a),dojo.create("div",{className:"workPlace dayDiv",style:{"float":"left",marginRight:"2px"},innerHTML:l},a),dojo.create("div",{innerHTML:" "+s.workPlace.Name},a)}for(var u in s.applys)if(s.applys.hasOwnProperty(u))for(var g=is_array(s.applys[u])?s.applys[u]:[s.applys[u]],y=0;y<g.length;y++){var f=g[y];t=dojo.create("tr",null,e),a=dojo.create("td",null,t),
dojo.create("div",{className:"pp_base pp_ap_"+teasp.view.Shift.getApplyStyleKey(u)+teasp.constant.getStatusStyleSuffix(s.applys[u].Status__c),style:{"float":"left",marginTop:"2px",marginRight:"2px"}},a);var p=f.ApplyType__c;f.ApplyType__c==teasp.constant.APPLY_TYPE_HOLIDAY?p+=f.HolidayId__r.Range__c==teasp.constant.RANGE_TIME?"("+f.HolidayId__r.Name+"/"+teasp.util.time.timeValue(f.StartTime__c)+"-"+teasp.util.time.timeValue(f.EndTime__c)+")":"("+f.HolidayId__r.Name+")":f.ApplyType__c==teasp.constant.APPLY_TYPE_PATTERNS||f.ApplyType__c==teasp.constant.APPLY_TYPE_PATTERNL?p+="("+(f.PatternId__r?f.PatternId__r.Name:this.getDisplayDayType(f.DayType__c))+")":f.ApplyType__c==teasp.constant.APPLY_TYPE_EXCHANGE&&(p+="("+teasp.util.date.formatDate(f.StartDate__c,"M/d")+"⇔"+teasp.util.date.formatDate(f.ExchangeDate__c,"M/d")+")"),
p+="("+f.Status__c+")",dojo.create("div",{innerHTML:p},a)}s.memo&&(t=dojo.create("tr",null,e),dojo.create("div",{innerHTML:teasp.util.entitize(s.memo).replace(/\n/g,"<br/>")},dojo.create("td",null,t)))};

teasp.dialog.ShiftSetting.prototype.changedPattern=function(){for(var e=dojo.byId("shiftSettingPatterns").value,t=this.pouch.allPatterns,a=null,s=0;s<t.length;s++)if(t[s].Id==e){
a=t[s];break}dojo.attr("shiftSettingSt","readOnly",!1),dojo.attr("shiftSettingEt","readOnly",!1),dojo.attr("shiftSettingSt","disabled",!("-"!=e&&"*"!=e&&a&&!a.UseDiscretionary__c)),dojo.attr("shiftSettingEt","disabled",!("-"!=e&&"*"!=e&&a&&!a.UseDiscretionary__c));var o=dojo.byId("shiftSettingPatternIcon");if(dojo.empty(o),"-"!=e&&"*"!=e)if(a){var i=a.Symbol__c||a.Name.substring(0,1);dojo.create("div",{className:"pattern dayDiv",
style:{marginLeft:"auto",marginRight:"auto"},innerHTML:i},o),dojo.byId("shiftSettingSt").value=teasp.util.time.timeValue(a.StdStartTime__c),dojo.byId("shiftSettingEt").value=teasp.util.time.timeValue(a.StdEndTime__c)}else dojo.byId("shiftSettingSt").value="",dojo.byId("shiftSettingEt").value="";else{var n="-"==e?this.defaultVals.normalSEList:this.defaultVals.currentSEList;if(1==n.length){var r=n[0];dojo.byId("shiftSettingSt").value=teasp.util.time.timeValue(r.st),
dojo.byId("shiftSettingEt").value=teasp.util.time.timeValue(r.et)}else dojo.byId("shiftSettingSt").value="",dojo.byId("shiftSettingEt").value=""}if(1==this.defaultVals.memoList.length)this.getNoteDisNode().checked=!1,dojo.style("shiftSettingNoteDis","display","none"),dojo.byId("shiftSettingNote").disabled=!1,dojo.byId("shiftSettingNote").value=this.defaultVals.memoList[0];else{var l=this.defaultVals.memoList.length;this.getNoteDisNode().checked=l>1,
dojo.style("shiftSettingNoteDis","display",l>1?"":"none"),dojo.byId("shiftSettingNote").disabled=l>1,dojo.byId("shiftSettingNote").value=""}};

teasp.dialog.ShiftSetting.prototype.ok=function(){var e=dojo.byId("shiftSettingDepts").value,t=dojo.byId("shiftSettingPatterns").value,a="*"==dojo.byId("shiftSettingDayType").value?null:dojo.byId("shiftSettingDayType").value,s=dojo.byId("shiftSettingNote").value;"1"==a&&dojo.byId("shiftSettingDayTypeLegalHoliday").checked&&(a="2");var o=teasp.util.time.clock2minutes(dojo.byId("shiftSettingSt").value),i=teasp.util.time.clock2minutes(dojo.byId("shiftSettingEt").value);
o="number"==typeof o?o:null,i="number"==typeof i?i:null;var n=this.args.target;for(var r in n)if(n.hasOwnProperty(r)){for(var l={},p=0;p<n[r].dateList.length;p++){var d=n[r].dateList[p];l[d]={dayType:a,workPlaceId:"*"==e?null:e||null,deptId:this.getDeptIdByEmpId(r),patternId:t,note:this.getNoteDisNode().checked?this.getOrgMemo(r,d):s,startTime:o,endTime:i}}n[r]=l}this.onfinishfunc({target:n},"shiftSettingErrorRow",function(e){
this.hide()},this)};

teasp.dialog.EmpShift.prototype.changedPattern=function(){
for(var e=dojo.byId("empShiftPatterns").value,t=this.pouch.allPatterns,a=null,s=0;s<t.length;s++)if(t[s].Id==e){a=t[s];break}dojo.attr("empShiftSt","disabled",!0),dojo.attr("empShiftEt","disabled",!0);var o=dojo.byId("empShiftPatternIcon");if(dojo.empty(o),"-"!=e&&"*"!=e)if(a){var i=a.Symbol__c||a.Name.substring(0,1);dojo.create("div",{className:"pattern dayDiv",style:{marginLeft:"auto",marginRight:"auto"},innerHTML:i
},o),dojo.byId("empShiftSt").value=teasp.util.time.timeValue(a.StdStartTime__c),dojo.byId("empShiftEt").value=teasp.util.time.timeValue(a.StdEndTime__c)}else dojo.byId("empShiftSt").value="",dojo.byId("empShiftEt").value="";else dojo.byId("empShiftSt").value="",dojo.byId("empShiftEt").value=""};

teasp.view.Shift.prototype.collectData=function(e){this.localObj.param=e.param,this.localObj.emps=[],this.localObj.dateList=[],this.localObj.patterns=[],this.localObj.holidays=[],this.localObj.allPatterns=[],this.localObj.empIdIndex={},this.localObj.deptMap={},
this.localObj.events={},this.localObj.pubEvents={},this.localObj.deptEvents={},this.localObj.notes={},this.localObj.countDays={},this.startCell=null,this.temporaryShiftId=[],this.sumColumns=dojo.clone(this.sumColumnsFix);var t,a,s,o=teasp.util.date.getDateList(e.param.startDate,e.param.endDate),i={},n={},r={},l={},p={common:{}},d={},c={},m={},h={},u={};for(t=0;t<e.empApplys.length;t++){var g=e.empApplys[t];g.startDate=teasp.logic.convert.valDate(g.StartDate__c),
g.endDate=teasp.logic.convert.valDate(g.EndDate__c),g.exchangeDate=teasp.logic.convert.valDate(g.ExchangeDate__c),g.originalStartDate=teasp.logic.convert.valDate(g.OriginalStartDate__c),m[g.EmpId__c]||(m[g.EmpId__c]=[]),m[g.EmpId__c].push(g),o.contains(g.startDate)||(u[g.startDate]=1),o.contains(g.endDate)||(u[g.endDate]=1),g.exchangeDate&&!o.contains(g.exchangeDate)&&(u[g.exchangeDate]=1),g.originalStartDate&&!o.contains(g.originalStartDate)&&(u[g.originalStartDate]=1),
g.HolidayId__r&&(r[g.HolidayId__r.Id]=g.HolidayId__r)}var y=[].concat(o);for(var f in u)u.hasOwnProperty(f)&&y.push(f);y=y.sort(function(e,t){return e<t?-1:e>t?1:0});var b=y[0],v=y[y.length-1],_=this.getPermission();for(t=0;t<e.configs.length;t++){var T=e.configs[t];i[T.ConfigBaseId__c]||(i[T.ConfigBaseId__c]=[]),T.validStartDate=T.ValidStartDate__c?teasp.logic.convert.valDate(T.ValidStartDate__c):null,T.validEndDate=T.ValidEndDate__c?teasp.logic.convert.valDate(T.ValidEndDate__c):null;
var j=T.Holidays__c||"0000000",E=[],L=[];for(a=0;a<j.length;a++){var k=j.substring(a,a+1);"0"!=k&&E.push(a),"2"==k&&L.push(a)}T.fixHolys=getHolidays(teasp.util.date.parseDate(T.validStartDate?T.validStartDate<=b?b:T.validStartDate:b),teasp.util.date.parseDate(T.validEndDate?T.validEndDate>=v?v:T.validEndDate:v),E,!1);for(var D in T.fixHolys)if(T.fixHolys.hasOwnProperty(D)){var I=T.fixHolys[D];L.contains(I.dayOfWeek)?I.dayType=teasp.constant.DAY_TYPE_LEGAL_HOLIDAY:E.contains(I.dayOfWeek)?I.dayType=teasp.constant.DAY_TYPE_NORMAL_HOLIDAY:T.NonPublicHoliday__c?I.dayType=teasp.constant.DAY_TYPE_NORMAL:I.dayType=teasp.constant.DAY_TYPE_PUBLIC_HOLIDAY;
}i[T.ConfigBaseId__c].push(T)}for(t=0;t<e.calendars.length;t++){var A=e.calendars[t],D=teasp.logic.convert.valDate(A.Date__c);if(A.DeptId__c){var f=A.DeptId__c;d[f]||(d[f]={}),d[f][D]=A}else{var f=A.EmpTypeId__c?A.EmpTypeId__c:"common";p[f]||(p[f]={}),p[f][D]=A}}for(t=0;t<e.patterns.length;t++){var x=e.patterns[t];n[x.Id]=x}for(t=0;t<e.empTypePatterns.length;t++){var S=e.empTypePatterns[t];S.pattern=n[S.PatternId__c],
l[S.EmpTypeId__c]||(l[S.EmpTypeId__c]=[]),l[S.EmpTypeId__c].push(S)}for(t=0;t<e.empMonths.length;t++){var w=e.empMonths[t];w.startDate=teasp.logic.convert.valDate(w.StartDate__c),w.endDate=teasp.logic.convert.valDate(w.EndDate__c),h[w.EmpId__c]||(h[w.EmpId__c]=[]),h[w.EmpId__c].push(w)}for(t=0;t<e.empTypes.length;t++){var M=e.empTypes[t];c[M.Id]=M,M.patterns=(l[M.Id]||[]).sort(function(e,t){return e.Order__c-t.Order__c;
}),M.days={};var O=i[M.ConfigBaseId__c];for(a=0;a<y.length;a++){var D=y[a],N=M.days[D]={date:teasp.util.date.parseDate(D)};if(1==O.length)N.config=O[0];else for(s=0;s<O.length;s++){var T=O[s];if((!T.validStartDate||T.validStartDate<=D)&&(!T.validEndDate||T.validEndDate>=D)){N.config=T;break}}N.layer1=function(){var e={},t=N.config.fixHolys[D];e.dayType=t?t.dayType:teasp.constant.DAY_TYPE_NORMAL,e.event=t&&t.title||null;
var a=teasp.view.Shift.getPatternByDate(M.patterns,N.date);return e.pattern=a&&a.pattern||null,e}(),N.layer2=function(e,t){if(!e&&!t)return{};var a={},s=function(e){switch(e){case"1":return teasp.constant.DAY_TYPE_NORMAL_HOLIDAY;case"2":return teasp.constant.DAY_TYPE_LEGAL_HOLIDAY;case"3":return teasp.constant.DAY_TYPE_PUBLIC_HOLIDAY;default:return teasp.constant.DAY_TYPE_NORMAL}};return e&&(e.Type__c&&(a.dayType=s(e.Type__c),
a.plannedHoliday=e.PlannedHoliday__c||!1,a.commonPriority="1"==e.Priority__c),e.Event__c&&e.Event__c.length>0&&(a.commonEvent=e.Event__c),e.Note__c&&e.Note__c.length>0&&(a.commonNote=e.Note__c)),t&&(t.Type__c&&!a.commonPriority&&(a.dayType=s(t.Type__c),a.plannedHoliday=t.PlannedHoliday__c||!1),t.Event__c&&t.Event__c.length>0&&(a.event=t.Event__c),t.Note__c&&t.Note__c.length>0&&(a.note=t.Note__c),a.pattern=t.PatternId__r||null),
a}(p.common[D]||null,(p[M.Id]||{})[D]||null),N.dayType="number"==typeof N.layer2.dayType?N.layer2.dayType:N.layer1.dayType,N.plannedHoliday=N.dayType==teasp.constant.DAY_TYPE_NORMAL&&N.layer2.plannedHoliday||!1,N.pattern=N.layer2.pattern?N.layer2.pattern:N.layer1.pattern;var R=[];N.layer1.event&&R.push(N.layer1.event),N.layer2.commonEvent&&R.push(N.layer2.commonEvent),N.layer2.event&&R.push(N.layer2.event),N.event=R.length>0?R.join(teasp.message.getLabel("tm10001470")):null,
N.note=N.layer2.note,this.localObj.pubEvents[D]=N.layer1.event,this.localObj.events[D]=N.layer2.commonEvent}}for(t=0;t<this.localObj.depts.length;t++){var H=this.localObj.depts[t];for(this.localObj.deptEvents[H.Id]={days:{}},a=0;a<y.length;a++){var D=y[a],N=this.localObj.deptEvents[H.Id].days[D]={},C=(d[H.Id]||{})[D];C&&(N.event=C.Event__c,N.note=C.Note__c)}}n={},r={};var P=0;for(e.emps=e.emps.sort(function(e,t){return e.Title__c==t.Title__c?e.EmpCode__c==t.EmpCode__c?e.Name<t.Name?-1:1:!e.EmpCode__c&&t.EmpCode__c?1:e.EmpCode__c&&!t.EmpCode__c?-1:e.EmpCode__c<t.EmpCode__c?-1:1:!e.Title__c&&t.Title__c?1:e.Title__c&&!t.Title__c?-1:e.Title__c<t.Title__c?-1:1;
}),t=0;t<e.emps.length;t++){var F=e.emps[t];F.empType=c[F.EmpTypeId__c];var Y=F.DeptId__c||"(null)";this.localObj.deptMap[Y]||(this.localObj.deptMap[Y]=[]),this.localObj.deptMap[Y].push(F),F.days={},F.countDays={workDays:0,holiDays:0,offDays:0};var W=this.isEditable(F,_);for(a=0;a<o.length;a++){var D=o[a],N=F.days[D]={};if(h[F.Id]){var q=h[F.Id];for(s=0;s<q.length;s++){var B=q[s];if(B.startDate<=D&&D<=B.endDate){N.monthStatus=B.EmpApplyId__r?B.EmpApplyId__r.Status__c:null;
break}}}var V=[];if(m[F.Id]){var q=m[F.Id];for(s=0;s<q.length;s++){var K=q[s];(K.startDate<=D&&D<=K.endDate||K.ApplyType__c==teasp.constant.APPLY_TYPE_EXCHANGE&&D==K.exchangeDate)&&V.push(K)}}var J={},U={};for(s=0;s<V.length;s++){var K=V[s];teasp.view.Shift.setApplyToDayObj(K.Decree__c?U:J,teasp.view.Shift.getApplyKey(K,D),K)}N.applys=teasp.view.Shift.getValidApplys(J),N.decrees=teasp.view.Shift.getValidApplys(U),N.dayType=F.empType.days[D].dayType,
N.plannedHoliday=F.empType.days[D].plannedHoliday,N.pattern=F.empType.days[D].pattern,N.pattern?(N.startTime=N.pattern.StdStartTime__c,N.endTime=N.pattern.StdEndTime__c,N.restTimes=N.pattern.RestTimes__c):(N.startTime=F.empType.days[D].config.StdStartTime__c,N.endTime=F.empType.days[D].config.StdEndTime__c,N.restTimes=F.empType.days[D].config.RestTimes__c),N.orgDayType=N.dayType;var G=N.decrees.patternS||N.decrees.patternL;
if(G&&(G.Removed__c||("string"==typeof G.DayType__c&&(N.dayType=parseInt(G.DayType__c,10)),N.pattern=G.PatternId__r||null,N.workPlace=G.WorkPlaceId__r||null,N.startTime=G.StartTime__c,N.endTime=G.EndTime__c,G.PatternId__r&&(N.restTimes=G.PatternId__r.RestTimes__c)),N.temporary=G.TempFlag__c,N.memo=G.Content__c||null,N.temporary&&(this.temporaryShiftId.push(G.Id),N.decrees.patternS.orgs&&N.decrees.patternS.orgs.length>0)))for(s=0;s<N.decrees.patternS.orgs.length;s++)this.temporaryShiftId.push(N.decrees.patternS.orgs[s].Id);
var z=N.applys.patternS||N.applys.patternL;if(z&&("string"==typeof z.DayType__c&&(N.dayType=parseInt(z.DayType__c,10)),N.pattern=z.PatternId__r||null,N.startTime=z.StartTime__c,N.endTime=z.EndTime__c,z.PatternId__r&&(N.restTimes=z.PatternId__r.RestTimes__c)),N.applys.exchangeS?N.dayType=F.empType.days[N.applys.exchangeS.exchangeDate].dayType:!N.applys.exchangeS&&N.applys.exchangeE&&(N.dayType=F.empType.days[N.applys.exchangeE.originalStartDate].dayType),
N.pattern){var X=n[N.pattern.Id];X?X.cnt++:n[N.pattern.Id]={cnt:1,pattern:N.pattern}}if(N.applys.holidayAll){var Q=r[N.applys.holidayAll.HolidayId__r.Id];Q?Q.cnt++:r[N.applys.holidayAll.HolidayId__r.Id]={cnt:1,holiday:N.applys.holidayAll.HolidayId__r}}if(N.applys.holidayAm){var Q=r[N.applys.holidayAm.HolidayId__r.Id];Q?Q.cnt++:r[N.applys.holidayAm.HolidayId__r.Id]={cnt:1,holiday:N.applys.holidayAm.HolidayId__r}}if(N.applys.holidayPm){
var Q=r[N.applys.holidayPm.HolidayId__r.Id];Q?Q.cnt++:r[N.applys.holidayPm.HolidayId__r.Id]={cnt:1,holiday:N.applys.holidayPm.HolidayId__r}}if(N.fix=teasp.constant.STATUS_FIX.contains(N.monthStatus)||N.applys.dailyFix,N.editable=W,N.dayType==teasp.constant.DAY_TYPE_NORMAL){if(N.plannedHoliday&&!N.applys.kyushtu&&(F.countDays.offDays++,P++),N.applys.holidayAll&&(F.countDays[N.applys.holidayAll.HolidayId__r.Id]?F.countDays[N.applys.holidayAll.HolidayId__r.Id]++:F.countDays[N.applys.holidayAll.HolidayId__r.Id]=1),
N.applys.holidayAm&&(F.countDays[N.applys.holidayAm.HolidayId__r.Id]?F.countDays[N.applys.holidayAm.HolidayId__r.Id]++:F.countDays[N.applys.holidayAm.HolidayId__r.Id]=1),N.applys.holidayPm&&(F.countDays[N.applys.holidayPm.HolidayId__r.Id]?F.countDays[N.applys.holidayPm.HolidayId__r.Id]++:F.countDays[N.applys.holidayPm.HolidayId__r.Id]=1),!(N.applys.holidayAll||N.applys.holidayAm&&N.applys.holidayPm)){F.countDays.workDays++;
var Z=N.pattern?N.pattern.Id:"(null)",$=N.workPlace?N.workPlace.Id:F.DeptId__c?F.DeptId__c:"(null)";F.countDays[Z]?F.countDays[Z]++:F.countDays[Z]=1,this.localObj.countDays[$]||(this.localObj.countDays[$]={}),this.localObj.countDays[$][D]||(this.localObj.countDays[$][D]={}),this.localObj.countDays[$][D][Z]?this.localObj.countDays[$][D][Z]++:this.localObj.countDays[$][D][Z]=1}}else F.countDays.holiDays++}}this.localObj.emps=e.emps,
this.localObj.dateList=o;for(var f in n)n.hasOwnProperty(f)&&this.localObj.patterns.push(n[f]);this.localObj.patterns=this.localObj.patterns.sort(function(e,t){return t.cnt-e.cnt}),this.localObj.patterns.unshift({}),this.localObj.allPatterns=e.patterns,console.log(this.localObj.emps);for(var f in r)r.hasOwnProperty(f)&&this.localObj.holidays.push(r[f]);for(this.localObj.holidays=this.localObj.holidays.sort(function(e,t){
return t.cnt-e.cnt}),P<=0&&this.sumColumns.splice(2,1),t=0;t<this.localObj.holidays.length;t++){var k=this.localObj.holidays[t].holiday;this.sumColumns.push({name:k.Name,headId:k.Id,headClassName:"sumHoriz1Cell",holiday:k})}this.deptKeys=[];for(var f in this.localObj.deptMap)this.localObj.deptMap.hasOwnProperty(f)&&this.deptKeys.push(f);var ee=this.localObj.param.deptId;this.deptKeys=this.deptKeys.sort(function(e,t){return"-1"==ee?"(null)"==e?-1:"(null)"==t?1:0:e==ee?-1:t==ee?1:0;
})};

teasp.view.Shift.prototype.createTable=function(){var e,t,a,s,o,i,n={},r=this;this.normalPatternSymbol=null;var l=!!dojo.byId("displayTime")&&dojo.byId("displayTime").checked;this.localObj.param.rangeType?dojo.byId("searchCondRange").innerHTML=teasp.util.date.formatDate(this.localObj.param.startDate,"SLA")+"～"+teasp.util.date.formatDate(this.localObj.param.endDate,"SLA"):dojo.byId("searchCondRange").innerHTML=Math.floor(this.localObj.param.month/100)+"年"+this.localObj.param.month%100+"月度 （ "+teasp.util.date.formatDate(this.localObj.param.startDate,"SLA")+"～"+teasp.util.date.formatDate(this.localObj.param.endDate,"SLA")+" ）";
var p="";"-1"==this.localObj.param.deptId?dojo.byId("searchCondDept").innerHTML=p="（部署未設定）":dojo.byId("searchCondDept").innerHTML=p=this.localObj.param.deptName||"",this.localObj.param.empIdList.length>0?(dojo.style("searchCondEmpRow","display",""),dojo.byId("searchCondEmp").innerHTML=this.getSearchEmpName(this.localObj.param.empIdList,this.printFlag).truncateTailInWidth(300,dojo.byId("ruler1"))):dojo.style("searchCondEmpRow","display","none"),
this.printFlag||(dojo.style("searchCancel","display",""),dojo.style("inputCondition","display","none"),dojo.style("searchCondition","display",""));for(var d in this.eventDayCells)this.eventDayCells.hasOwnProperty(d)&&(dojo.disconnect(this.eventDayCells[d]),delete this.eventDayCells[d]);for(var c=dojo.byId("baseDiv");c.firstChild;)dojo.destroy(c.firstChild);var m=this.deptKeys.length>0?this.deptKeys[0]:null,h=m&&this.localObj.deptMap[m].length>0?this.localObj.deptMap[m][0]:null,u=this.localObj.param.deptId||"(null)",g=0,y=this.localObj.param.deptId;
y&&"-"!=y&&"-1"!=y||(y=this.deptKeys[0]),e=dojo.create("tbody",null,dojo.create("table",{className:"shiftTable",id:"shiftTable"},c)),t=dojo.create("tr",null,e);var f=(h&&h.DeptId__r&&h.DeptId__r.Name||"")==p?p:"";this.localObj.param.deptId&&"-1"!=this.localObj.param.deptId||!h||!h.DeptId__r||(f=h.DeptId__r.Name),dojo.create("div",{innerHTML:f,style:{width:"100px",fontSize:"0.9em"}},dojo.create("td",{rowSpan:3,style:{verticalAlign:"bottom"
}},t));var b=null;for(i=0;i<this.localObj.dateList.length;i++){var v=this.localObj.dateList[i],_=teasp.util.date.parseDate(v);o=b&&b.getMonth()==_.getMonth()?_.getDate():_.getMonth()+1+"/"+_.getDate(),b=_,a=dojo.create("td",{id:"dd"+v,className:"dayCell "+(i%2==0?"even":"odd"),style:{height:"15px"}},t),dojo.create("div",{innerHTML:o},a)}for(i=0;i<this.sumColumns.length;i++){var T=this.sumColumns[i];if(a=dojo.create("td",{
id:T.headId,rowSpan:3,className:T.headClassName,style:{textAlign:"center",verticalAlign:"top"}},t),T.holiday){var j=T.holiday.Symbol__c||T.holiday.Name.substring(0,1);dojo.create("div",{className:"holyIcon dayDiv",style:{marginLeft:"auto",marginRight:"auto"},innerHTML:j},a)}dojo.create("div",{innerHTML:T.name,style:{width:"20px",margin:"2px auto"}},a)}for(i=0;i<this.localObj.patterns.length;i++){var E=this.localObj.patterns[i].pattern;
if(E){a=dojo.create("td",{rowSpan:3,className:"sumHoriz2Cell",style:{textAlign:"center",verticalAlign:"top"}},t);var j=E.Symbol__c||E.Name.substring(0,1);dojo.create("div",{className:"pattern dayDiv",style:{marginLeft:"auto",marginRight:"auto"},innerHTML:j},a),dojo.create("div",{innerHTML:E.Name,style:{width:"20px",margin:"2px auto"}},a)}else a=dojo.create("td",{rowSpan:3,className:"sumHoriz2Cell",style:{textAlign:"center",
verticalAlign:"top"}},t),this.normalPatternSymbol&&dojo.create("div",{className:"pattern dayDiv",style:{marginLeft:"auto",marginRight:"auto"},innerHTML:this.normalPatternSymbol},a),dojo.create("div",{innerHTML:"通常勤務",style:{width:"20px",margin:"2px auto"}},a)}for(t=dojo.create("tr",null,e),i=0;i<this.localObj.dateList.length;i++){var v=this.localObj.dateList[i];a=dojo.create("td",{id:"wd"+v,className:"dayCell "+(i%2==0?"even":"odd"),
style:{height:"15px"}},t);var L=teasp.util.date.parseDate(v),k={};0==L.getDay()?k.color="red":6==L.getDay()&&(k.color="blue"),dojo.create("div",{innerHTML:teasp.util.date.formatDate(v,"JPW"),style:k},a)}for(t=dojo.create("tr",null,e),i=0;i<this.localObj.dateList.length;i++){var v=this.localObj.dateList[i],D=[],I=[];if(this.localObj.events[v]&&(D.push('<span style="color:#8b0000;">'+this.localObj.events[v]+"</span>"),I.push(this.localObj.events[v])),
this.localObj.deptEvents[u]&&this.localObj.deptEvents[u].days[v]&&this.localObj.deptEvents[u].days[v].event&&(D.push('<span style="color:#2e8b57;">'+this.localObj.deptEvents[u].days[v].event+"</span>"),I.push(this.localObj.deptEvents[u].days[v].event)),this.localObj.deptEvents[u]&&this.localObj.deptEvents[u].days[v]&&this.localObj.deptEvents[u].days[v].note&&(D.push('<span style="color:#00008b;">'+this.localObj.deptEvents[u].days[v].note+"</span>"),
I.push(this.localObj.deptEvents[u].days[v].note)),a=dojo.create("td",{id:"vd"+v,className:"dayCell "+(i%2==0?"even":"odd"),style:{fontSize:"0.9em",verticalAlign:"top"}},t),dojo.byId("displayEvent").checked){this.localObj.pubEvents[v]&&D.unshift(this.localObj.pubEvents[v]);var A=D.join(teasp.message.getLabel("tm10001470")),x=I.join(teasp.message.getLabel("tm10001470")+"\n");dojo.create("div",{style:{height:"10px",verticalAlign:"top",
display:"table",wordBreak:"break-all"},innerHTML:A,title:x},a)}else{var A=D.join(teasp.message.getLabel("tm10001470")),x=I.join(teasp.message.getLabel("tm10001470")+"\n");this.localObj.pubEvents[v]&&dojo.create("div",{className:"pp_base pp_btn_naholy",style:{margin:"1px auto"},title:this.localObj.pubEvents[v]},a),A&&dojo.create("div",{className:"pp_base pp_shift_event",style:{margin:"1px auto"},title:x},a)}}for(var S=0;S<this.deptKeys.length;S++){
m=this.deptKeys[S];var w=this.localObj.deptMap[m];if(m!=y){for(t=dojo.create("tr",null,e),dojo.create("div",{innerHTML:w[0].DeptId__r&&w[0].DeptId__r.Name||"",style:{width:"100px",fontSize:"0.9em"}},dojo.create("td",{style:{verticalAlign:"bottom"}},t)),i=0;i<this.localObj.dateList.length;i++){var v=this.localObj.dateList[i];a=dojo.create("td",{id:"xd"+v,className:"dayCell "+(i%2==0?"even":"odd"),style:{borderLeft:"1px dashed #6393B7",
borderRight:"1px dashed #6393B7"}},t),dojo.create("div",{style:{width:"34px",height:"40px"}},a)}for(i=0;i<this.sumColumns.length;i++)dojo.create("div",{style:{width:"24px",height:"40px"}},dojo.create("td",{className:"cell",style:{borderLeft:"1px dashed #6393B7",borderRight:"1px dashed #6393B7"}},t));for(i=0;i<this.localObj.patterns.length;i++)dojo.create("div",{style:{width:"24px",height:"40px"}},dojo.create("td",{className:"cell",
style:{borderLeft:"1px dashed #6393B7",borderRight:"1px dashed #6393B7"}},t))}for(s=0;s<w.length;s++){for(h=w[s],this.localObj.empIdIndex[h.Id]=g++,t=dojo.create("tr",null,e),a=dojo.create("td",{id:"emp"+h.Id,className:"name empCell"},t),h.UserId__r&&h.UserId__r.SmallPhotoUrl&&dojo.create("img",{src:h.UserId__r.SmallPhotoUrl,style:{"float":"left",margin:"1px"},className:"dayDiv",width:"30px",height:"30px"},a),dojo.create("div",{
innerHTML:h.Title__c||"",className:"dayDiv empTitle",style:{margin:"1px",whiteSpace:"nowrap",fontSize:"0.8em"}},a),dojo.create("div",{innerHTML:h.EmpCode__c||"",className:"dayDiv",style:{margin:"1px",whiteSpace:"nowrap",fontSize:"0.8em"}},a),dojo.create("div",{innerHTML:h.Name,className:"dayDiv",style:{margin:"2px 4px"}},a),i=0;i<this.localObj.dateList.length;i++){var v=this.localObj.dateList[i],_=h.days[v],E=null;if(a=dojo.create("td",{
id:(_.fix||!_.editable?"xd":"ed")+v+h.Id,className:"dayCell "+(!_.fix&&_.editable||this.printFlag?"":"disableCell ")+(i%2==0?"even":"odd"),style:{width:"30px",height:"30px",verticalAlign:"top"}},t),this.eventDayCells[v+h.Id]=dojo.connect(a,"ondblclick",this,function(){var e=a,t=h,s=v;return function(){r.empDayDialog.setEmpDay(t,s,this.normalPatternSymbol),dijit.popup.open({popup:r.empDayDialog.getDialog(),around:e})}}()),
_.decrees.patternS&&!this.printFlag){a.style.textAlign="center";var M=dojo.create("div",{style:{marginLeft:"auto",marginRight:"auto",display:"table"}},a);_.decrees.patternS.Removed__c||dojo.create("div",{className:"pp_base pp_shift_done",style:{margin:"1px auto","float":_.temporary?"left":"none"}},M),_.temporary&&dojo.create("div",{className:"pp_base pp_shift_temp_pin",style:{margin:"1px","float":"left"},title:_.Removed__c?"仮削除状態":"仮登録状態"
},M)}if(!this.printFlag)for(var d in _.applys)_.applys.hasOwnProperty(d)&&!_.applys[d].Decree__c&&dojo.create("div",{className:"pp_base pp_ap_"+teasp.view.Shift.getApplyStyleKey(d)+teasp.constant.getStatusStyleSuffix(_.applys[d].Status__c),style:{"float":"left"}},a);if(_.dayType==teasp.constant.DAY_TYPE_NORMAL_HOLIDAY||_.dayType==teasp.constant.DAY_TYPE_PUBLIC_HOLIDAY)a.style.backgroundColor=teasp.constant.NORMAL_HOLIDAY_COLOR,
this.printFlag&&dojo.create("div",{className:"printDayType",style:{"float":"left",color:"blue"},innerHTML:_.dayType==teasp.constant.DAY_TYPE_PUBLIC_HOLIDAY?"(祝日)":"(所休)"},a);else if(_.dayType==teasp.constant.DAY_TYPE_LEGAL_HOLIDAY)a.style.backgroundColor=teasp.constant.LEGAL_HOLIDAY_COLOR,this.printFlag&&dojo.create("div",{className:"printDayType",style:{"float":"left",color:"red"},innerHTML:"(法休)"},a);else{var O=_.applys.holidayAll||_.applys.holidayAm&&_.applys.holidayPm;
if(_.plannedHoliday&&!_.applys.kyushtu)a.style.backgroundColor=teasp.constant.PRIVATE_HOLIDAY_COLOR,this.printFlag&&dojo.create("div",{className:"printDayType",style:{"float":"left"},innerHTML:"[休暇]"},a);else if(O)if(a.style.backgroundColor=teasp.constant.PRIVATE_HOLIDAY_COLOR,this.printFlag&&dojo.create("div",{className:"printDayType",style:{"float":"left"},innerHTML:"[休暇]"},a),_.applys.holidayAll){var j=_.applys.holidayAll.HolidayId__r.Symbol__c||_.applys.holidayAll.HolidayId__r.Name.substring(0,1);
dojo.create("div",{className:"holyIcon dayDiv",style:{"float":"left"},innerHTML:j},a)}else{var j=_.applys.holidayAm.HolidayId__r.Symbol__c||_.applys.holidayAm.HolidayId__r.Name.substring(0,1);dojo.create("div",{className:"holyIcon dayDiv",style:{"float":"left"},innerHTML:j},a),j=_.applys.holidayPm.HolidayId__r.Symbol__c||_.applys.holidayPm.HolidayId__r.Name.substring(0,1),dojo.create("div",{className:"holyIcon dayDiv",
style:{"float":"left"},innerHTML:j},a)}else{if(this.printFlag&&(_.applys.holidayAm?dojo.create("div",{className:"printDayType",style:{"float":"left"},innerHTML:"[午前休]"},a):_.applys.holidayPm&&dojo.create("div",{className:"printDayType",style:{"float":"left"},innerHTML:"[午後休]"},a)),_.applys.holidayAm){var j=_.applys.holidayAm.HolidayId__r.Symbol__c||_.applys.holidayAm.HolidayId__r.Name.substring(0,1);dojo.create("div",{
className:"holyIcon dayDiv",style:{"float":"left"},innerHTML:j},a)}else if(_.applys.holidayPm){var j=_.applys.holidayPm.HolidayId__r.Symbol__c||_.applys.holidayPm.HolidayId__r.Name.substring(0,1);dojo.create("div",{className:"holyIcon dayDiv",style:{"float":"left"},innerHTML:j},a)}if(_.pattern){E=_.pattern;var j=_.pattern.Symbol__c||_.pattern.Name.substring(0,1);dojo.create("div",{className:"pattern dayDiv",style:{"float":"left"
},innerHTML:j},a)}else E=h.empType.days[v].config,this.normalPatternSymbol&&dojo.create("div",{className:"pattern dayDiv",style:{"float":"left"},innerHTML:this.normalPatternSymbol},a);if(_.workPlace&&_.workPlace.Id!=h.DeptId__c){var j=_.workPlace.Symbol__c||_.workPlace.Name.substring(0,1);dojo.create("div",{className:"workPlace dayDiv",style:{"float":"left"},innerHTML:j},a),n[_.workPlace.Id]=_.workPlace}}}if(E){dojo.create("div",{
style:{clear:"left"}},a);var N=teasp.util.time.timeValue(_.startTime)+" -<br/>"+teasp.util.time.timeValue(_.endTime),M=dojo.create("div",{innerHTML:N,className:"dayTime",style:{whiteSpace:"nowrap",fontSize:"10px",fontFamily:"sans-serif",margin:"1px"}},a);dojo.style(M,"display",l?"":"none")}}for(i=0;i<this.sumColumns.length;i++){var T=this.sumColumns[i];dojo.create("div",{innerHTML:h.countDays[T.headId]||"",style:{whiteSpace:"nowrap",
marginRight:"2px"}},dojo.create("td",{className:"cell",style:{width:"24px",textAlign:"center",verticalAlign:"middle"}},t))}for(i=0;i<this.localObj.patterns.length;i++){var E=this.localObj.patterns[i].pattern;a=dojo.create("td",{className:"cell",style:{width:"24px",textAlign:"center",verticalAlign:"middle"}},t);var R=h.countDays[E?E.Id:"(null)"];dojo.create("div",{innerHTML:""+(R||""),style:{whiteSpace:"nowrap",marginRight:"2px",
wordBreak:"break-all"}},a)}}}if(this.localObj.param.deptId){for(t=dojo.create("tr",null,e),dojo.create("div",{innerHTML:("-1"==this.localObj.param.deptId?"（部署未設定）":this.localObj.param.deptName||"")+"集計",style:{width:"100px",fontSize:"0.9em"}},dojo.create("td",{style:{verticalAlign:"bottom"}},t)),i=0;i<this.localObj.dateList.length;i++)a=dojo.create("td",{style:{borderLeft:"1px dashed #6393B7",borderRight:"1px dashed #6393B7",
height:"50px"}},t);for(i=0;i<this.sumColumns.length;i++)dojo.create("td",null,t);for(i=0;i<this.localObj.patterns.length;i++)dojo.create("td",null,t);for(s=0;s<this.localObj.patterns.length;s++){var E=this.localObj.patterns[s].pattern;if(t=dojo.create("tr",null,e),a=dojo.create("td",{className:"sumHoriz2Cell",style:{textAlign:"left",verticalAlign:"middle"}},t),E){var j=E.Symbol__c||E.Name.substring(0,1);dojo.create("div",{
className:"pattern",style:{"float":"left"},innerHTML:j},a),dojo.create("div",{innerHTML:E.Name,style:{"float":"left",margin:"2px"}},a)}else this.normalPatternSymbol&&dojo.create("div",{className:"pattern",style:{"float":"left"},innerHTML:this.normalPatternSymbol},a),dojo.create("div",{innerHTML:"通常勤務",style:{"float":"left",margin:"2px"}},a);var H=this.localObj.countDays[this.localObj.param.deptId||"(null)"]||{};for(i=0;i<this.localObj.dateList.length;i++){
var v=this.localObj.dateList[i];a=dojo.create("td",{id:"bd"+v,className:"dayCell "+(i%2==0?"even":"odd"),style:{border:"1px solid #6393B7",width:"30px",height:"16px",textAlign:"center",verticalAlign:"middle"}},t);var R=(H[v]||{})[E?E.Id:"(null)"];dojo.create("div",{innerHTML:""+(R||""),style:{whiteSpace:"nowrap",marginRight:"2px"}},a)}for(i=0;i<this.sumColumns.length;i++)dojo.create("td",null,t)}}this.createExplanation(c,n),
this.printFlag||(dojo.byId("shiftTable").onmouseup=function(e){return r.mouseUp(this,e),!1},dojo.query(".dayCell").forEach(function(e){e.onmousedown=function(e){return r.mouseDown(this,e),!1},e.onmousemove=function(e){return r.mouseMoveCell(this,e),!1}}),dojo.query(".empCell").forEach(function(e){e.onmousedown=function(e){return r.mouseDown(this,e),!1},e.onmousemove=function(e){return r.mouseMoveCell(this,e),!1}}),dojo.query(".dayDiv").forEach(function(e){
e.onmousedown=function(e){return r.mouseDown(this,e),!1},e.onmousemove=function(e){return r.mouseMoveCell(this,e),!1}}),dijit.popup.close(this.empSelectDialog.getDialog()),dojo.style("changeRealSave","display",this.temporaryShiftId.length>0?"":"none"))};

teasp.view.Shift.prototype.getCsvValue1=function(e){for(var t='"部署コード","部署名","役職","社員コード","社員名"',a=teasp.util.date.getDateList(this.localObj.param.startDate,this.localObj.param.endDate),s=this.localObj.param.deptId||"(null)",o=0;o<a.length;o++)t+=',"'+teasp.util.date.formatDate(a[o],"SLA")+'"';
for(var i='"","","",""',o=0;o<a.length;o++){var n=a[o],r=[];this.localObj.pubEvents[n]&&r.push(this.localObj.pubEvents[n]),this.localObj.events[n]&&r.push(this.localObj.events[n]),i+=',"'+r.join(teasp.message.getLabel("tm10001470"))+'"'}i+='\n"","","",""';for(var o=0;o<a.length;o++){var n=a[o];i+=',"'+(this.localObj.deptEvents[s]&&this.localObj.deptEvents[s].days[n]&&this.localObj.deptEvents[s].days[n].event||"")+'"'}
i+='\n"","","",""';for(var o=0;o<a.length;o++){var n=a[o];i+=',"'+(this.localObj.deptEvents[s]&&this.localObj.deptEvents[s].days[n]&&this.localObj.deptEvents[s].days[n].note||"")+'"'}for(var l=0;l<this.deptKeys.length;l++)for(var p=this.deptKeys[l],d=this.localObj.deptMap[p],c=0;c<d.length;c++){var m=d[c];i+='\n"'+(m.DeptId__r&&m.DeptId__r.DeptCode__c||"")+'","'+(m.DeptId__r&&m.DeptId__r.Name||"")+'","'+(m.Title__c||"")+'","'+(m.EmpCode__c||"")+'","'+m.Name+'"';
for(var o=0;o<a.length;o++){var n=a[o],h=m.days[n],u=null,g="";if(h.dayType==teasp.constant.DAY_TYPE_NORMAL_HOLIDAY)g="(所定休日)";else if(h.dayType==teasp.constant.DAY_TYPE_PUBLIC_HOLIDAY)g="(祝日)";else if(h.dayType==teasp.constant.DAY_TYPE_LEGAL_HOLIDAY)g="(法定休日)";else{var y=h.applys.holidayAll||h.applys.holidayAm&&h.applys.holidayPm;if(h.plannedHoliday&&!h.applys.kyushtu)g="[休暇](計画)";else if(y)g=h.applys.holidayAll?"[休暇]("+this.getHolidayName(h.applys.holidayAll.HolidayId__r,e.holidayFull)+")":"[休暇]("+this.getHolidayName(h.applys.holidayAm.HolidayId__r,e.holidayFull)+","+this.getHolidayName(h.applys.holidayPm.HolidayId__r,e.holidayFull)+")";else{
if(h.applys.holidayAm?g="[午前休]("+this.getHolidayName(h.applys.holidayAm.HolidayId__r,e.holidayFull)+")":h.applys.holidayPm&&(g="[午後休]("+this.getHolidayName(h.applys.holidayPm.HolidayId__r,e.holidayFull)+")"),h.pattern)if(u=h.pattern,e.patternFull)g+=(g?"\n":"")+h.pattern.Name;else{var f=h.pattern.Symbol__c||h.pattern.Name.substring(0,1);g+=(g?"\n":"")+f}else u=m.empType.days[n].config,e.patternFull&&(g+=(g?"\n":"")+"(通常勤務)");
h.workPlace&&h.workPlace.Id!=m.DeptId__c&&(g+=(g?"\n":"")+"主管部署:"+h.workPlace.Name)}}u&&e.timeIn&&(g+=(g?"\n":"")+teasp.util.time.timeValue(h.startTime)+" -"+teasp.util.time.timeValue(h.endTime)),h.temporary&&(g+=(g?"\n":"")+"(仮)"),i+=',"'+g+'"'}}return{head:t,value:i}};

teasp.view.Shift.prototype.getCsvValue2=function(e){var t='"部署コード","部署名","役職","社員コード","社員名","日付","曜日","設定","勤務パターン"';e.timeIn&&(t+=',"始業時刻","終業時刻"'),t+=',"主管部署","メモ","共通のイベント","部署のイベント","備考"';
for(var a=teasp.util.date.getDateList(this.localObj.param.startDate,this.localObj.param.endDate),s=this.localObj.param.deptId||"(null)",o="",i={},n=0;n<a.length;n++){var r=a[n];i[r]={},i[r].date=teasp.util.date.formatDate(r,"SLA"),i[r].week=teasp.util.date.formatDate(r,"JPW");var l=[];this.localObj.pubEvents[r]&&l.push(this.localObj.pubEvents[r]),this.localObj.events[r]&&l.push(this.localObj.events[r]),i[r].pubEvent=l.join(teasp.message.getLabel("tm10001470")),
i[r].event=this.localObj.deptEvents[s]&&this.localObj.deptEvents[s].days[r]&&this.localObj.deptEvents[s].days[r].event||"",i[r].note=this.localObj.deptEvents[s]&&this.localObj.deptEvents[s].days[r]&&this.localObj.deptEvents[s].days[r].note||""}for(var p=0;p<this.deptKeys.length;p++)for(var d=this.deptKeys[p],c=this.localObj.deptMap[d],m=0;m<c.length;m++)for(var h=c[m],n=0;n<a.length;n++){var r=a[n],u=i[r],g=h.days[r],y=null,f="",b="",v="",_="",T="";
if(g.dayType==teasp.constant.DAY_TYPE_NORMAL_HOLIDAY)f="(所定休日)";else if(g.dayType==teasp.constant.DAY_TYPE_PUBLIC_HOLIDAY)f="(祝日)";else if(g.dayType==teasp.constant.DAY_TYPE_LEGAL_HOLIDAY)f="(法定休日)";else{var j=g.applys.holidayAll||g.applys.holidayAm&&g.applys.holidayPm;g.plannedHoliday&&!g.applys.kyushtu?f="[休暇](計画)":j?f=g.applys.holidayAll?"[休暇]("+this.getHolidayName(g.applys.holidayAll.HolidayId__r,e.holidayFull)+")":"[休暇]("+this.getHolidayName(g.applys.holidayAm.HolidayId__r,e.holidayFull)+","+this.getHolidayName(g.applys.holidayPm.HolidayId__r,e.holidayFull)+")":(g.applys.holidayAm?f="[午前休]("+this.getHolidayName(g.applys.holidayAm.HolidayId__r,e.holidayFull)+")":g.applys.holidayPm&&(f="[午後休]("+this.getHolidayName(g.applys.holidayPm.HolidayId__r,e.holidayFull)+")"),
g.pattern?(y=g.pattern,b=e.patternFull?g.pattern.Name:g.pattern.Symbol__c||g.pattern.Name.substring(0,1)):(y=h.empType.days[r].config,b=e.patternFull?"(通常勤務)":""),g.workPlace&&g.workPlace.Id!=h.DeptId__c&&(v=g.workPlace.Name))}y&&(_=teasp.util.time.timeValue(g.startTime),T=teasp.util.time.timeValue(g.endTime)),o+='"'+(h.DeptId__r&&h.DeptId__r.DeptCode__c||""),o+='","'+(h.DeptId__r&&h.DeptId__r.Name||""),o+='","'+(h.Title__c||""),
o+='","'+(h.EmpCode__c||""),o+='","'+h.Name,o+='","'+u.date,o+='","'+u.week,o+='","'+f+(g.temporary?"(仮)":""),o+='","'+b,e.timeIn&&(o+='","'+_,o+='","'+T),o+='","'+v,o+='","'+(g.memo||""),o+='","'+u.pubEvent,o+='","'+u.event,o+='","'+u.note,o+='"\n'}return{head:t,value:o}};
}
